<?php
/**
 * Roundcube Plus AI plugin.
 *
 * Copyright 2023, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'مساعد الذكاء الاصطناعي';
$labels['ai_assistant'] = 'مساعد الذكاء الاصطناعي';
$labels['ai_assistant_settings'] = 'إعدادات مساعد الذكاء الاصطناعي';

// compose page
$labels['compose_dialog_button_text'] = 'الذكاء الاصطناعي';
$labels['compose_dialog_button_title'] = 'اكتب رسالة بالذكاء الاصطناعي';

$labels['compose_label_to'] = 'اسم المستلم';
$labels['compose_label_from'] = 'اسم المرسل';
$labels['compose_label_style'] = 'الطراز';
$labels['compose_label_length'] = 'الطول';
$labels['compose_label_language'] = 'اللغة';
$labels['compose_label_creativity'] = 'الإبداع';
$labels['compose_label_instructions'] = 'التعليمات';
$labels['compose_no_change'] = 'لا يوجد تغيير';
$labels['compose_instructions_placeholder'] = 'مثال: اطلب تغيير الموعد للأسبوع القادم';

$labels['compose_style_assertive'] = 'التوكيد';
$labels['compose_style_casual'] = 'عادي';
$labels['compose_style_enthusiastic'] = 'متحمس';
$labels['compose_style_funny'] = 'مضحك';
$labels['compose_style_informational'] = 'إعلامي';
$labels['compose_style_professional'] = 'محترف';
$labels['compose_style_urgent'] = 'عاجل';
$labels['compose_style_witty'] = 'بارع';

$labels['compose_length_short'] = 'قصير';
$labels['compose_length_medium'] = 'متوسط';
$labels['compose_length_long'] = 'طويل';

$labels['compose_creativity_low'] = 'منخفضة';
$labels['compose_creativity_medium'] = 'متوسط';
$labels['compose_creativity_high'] = 'عالية';

$labels['compose_insert_email'] = 'إدراج البريد الإلكتروني';
$labels['compose_generate_email'] = 'إنشاء بريد إلكتروني';
$labels['compose_generate_again'] = 'توليد مرة أخرى';
$labels['compose_stop_generating'] = 'إيقاف التوليد';
$labels['compose_error_help_button'] = 'المساعدة';

$labels['compose_no_instructions'] = 'اكتب التعليمات.';
$labels['compose_instructions_too_long'] = 'تعليماتك طويلة جدًا؛ يمكن أن تكون على الأكثر $ن حرفًا.';
$labels['compose_empty_response'] = 'قام الخادم بإرجاع استجابة فارغة.';

$labels['compose_tip_to'] = 'اسم مستلم البريد الإلكتروني الجديد. يمكنك تحديد أكثر من اسم، أو استخدام سلاسل مثل "الجميع"، "الفريق"، إلخ.';
$labels['compose_tip_from'] = 'سيتم توقيع البريد الإلكتروني الجديد بهذا الاسم.';
$labels['compose_tip_style'] = 'أسلوب الكتابة المفضل للبريد الإلكتروني الجديد.';
$labels['compose_tip_length'] = 'الطول المفضل للبريد الإلكتروني الجديد.';
$labels['compose_tip_language'] = 'اللغة التي يجب كتابة البريد الإلكتروني الجديد بها. حدد "لا تغيير" للكتابة باللغة التي يتم بها إعطاء التعليمات.';
$labels['compose_tip_creativity'] = 'سيؤدي الإبداع العالي إلى توليد رسائل بريد إلكتروني أكثر تنوعًا وغير متوقعة؛ بينما سيؤدي الإبداع المنخفض إلى توليد رسائل بريد إلكتروني أكثر واقعية وفي صلب الموضوع.';
$labels['compose_tip_instructions'] = 'تعليمات حول ما يجب تضمينه في البريد الإلكتروني الجديد. انقر على زر أمثلة التعليمات لمشاهدة بعض الأمثلة.';

$labels['compose_help_button_show'] = 'أمثلة على التعليمات';
$labels['compose_help_button_hide'] = 'رجوع';
$labels['compose_help_title'] = 'المساعدة والأمثلة';
$labels['compose_help_info'] = 'أخبر الذكاء الاصطناعي عن البريد الإلكتروني الذي ترغب في كتابته. قم بتضمين التفاصيل، مثل الأسماء والتواريخ والمواقع والأسباب وما إلى ذلك. يمكنك أيضًا طلب أفكار أو تفسيرات إبداعية. بعد إنشاء البريد الإلكتروني، ستتمكن من تعديله وإدراجه في صفحة الإنشاء. إليك بعض نماذج التعليمات لتبدأ بها:';

$labels['compose_help_example_1'] = 'قل مرحباً';
$labels['compose_help_example_2'] = 'تم إلغاء اجتماع اليوم';
$labels['compose_help_example_3'] = 'لقد حددت اجتماعًا مع مارجي يوم الأربعاء الساعة الثالثة عصرًا، وأعددت عرضًا تقديميًا حول مزايا استخدام الذكاء الاصطناعي في حملاتنا التسويقية لإقناعها';
$labels['compose_help_example_4'] = 'قررنا إضافة دعم للمحتوى الذي تم إنشاؤه بالذكاء الاصطناعي، اشرح باختصار ما هو';
$labels['compose_help_example_5'] = 'متابعة مهمة العمل من الأسبوع الماضي، أحتاجها غدًا';
$labels['compose_help_example_6'] = 'أطلب زيادة في الراتب، لم أحصل على واحدة منذ أكثر من عام';
$labels['compose_help_example_7'] = 'ذكّر بتقديم التقرير غداً وإلا سيقع الفريق في مشكلة مع مارجي التي تعاني من التوتر';
$labels['compose_help_example_8'] = 'اكتب للعملاء عن خصم 20% على جميع المنتجات حتى يوم الثلاثاء، نبيع الملابس';
$labels['compose_help_example_9'] = 'اطلب كتابة رسالة إلى لورا وأخبرها أن تنظم لقاءً بمناسبة عيد ميلاد كيفن في نهاية هذا الأسبوع';
$labels['compose_help_example_10'] = 'اسأل عن التقدم المحرز في الموقع الإلكتروني الجديد، بما في ذلك 5 أفكار لشعارات تسويقية للصفحة الأولى، نحن نقوم بإصلاح السيارات';
$labels['compose_help_example_11'] = 'نشرة إخبارية حول ميزات vpn الجديدة التي أضفناها: بروتوكول wireguard، وإعادة توجيه المنفذ، ومفتاح الإيقاف، وعنوان IP المخصص؛ اشرح ما هي';
$labels['compose_help_example_12'] = 'نشرة إخبارية عن برنامج ولاء جديد، التكلفة الأولية 10 دولارات للبطاقة ثم خصومات تصل إلى 20% على معظم المنتجات لمدة عام';
$labels['compose_help_example_13'] = 'بريد إلكتروني للتواصل مع شخص معجب به وأريد التواصل معه مهنياً';
$labels['compose_help_example_14'] = 'شكرًا احترافيًا على المساعدة في المشروع بالأمس';
$labels['compose_help_example_15'] = 'الخروج بعشر أفكار لاستراتيجيات لصياغة عرض ترويجي فعال عبر البريد الإلكتروني للمستثمرين، ستعمل عليها غدًا';
$labels['compose_help_example_16'] = 'رسالة استقالة مهنية عبر البريد الإلكتروني، مع إعطاء إشعار لمدة شهر واحد وفقًا للعقد، وتسمى الشركة ACME';
$labels['compose_help_example_17'] = 'رسالة بريد إلكتروني مُلزمة لطلب ترقية، ملمحًا إلى أنني قد أستقيل إذا لم أحصل عليها لأن هناك فرصًا أخرى';
$labels['compose_help_example_18'] = 'كان من الجيد أن ألتقي بك في المؤتمر بالأمس، لقد استمتعت بمحادثتنا، لنبقى على اتصال';

$labels['compose_help_use_example'] = '(استخدم هذا)';

// summaries
$labels['creating_summary'] = 'إنشاء ملخص...';
$labels['show_summary'] = 'عرض الملخص';
$labels['hide_summary'] = 'إخفاء الملخص';
$labels['recreate_summary'] = 'إعادة إنشاء الملخص';
$labels['email_has_no_text'] = 'هذا البريد الإلكتروني لا يحتوي على نص.';

// settings
$labels['setting_compose_style'] = 'الطراز';
$labels['setting_compose_length'] = 'الطول';
$labels['setting_compose_language'] = 'اللغة';
$labels['setting_compose_creativity'] = 'الإبداع';
$labels['setting_language'] = 'اللغة';

$labels['summarizing_messages'] = 'تلخيص الرسائل';
$labels['setting_show_summary_on_mail_view'] = 'إظهار ملخصات الذكاء الاصطناعي عند عرض رسائل البريد الإلكتروني';
$labels['setting_show_summary_on_list_hover'] = 'إظهار ملخصات الذكاء الاصطناعي عند التمرير فوق قائمة البريد الإلكتروني';
$labels['setting_list_summary_placement'] = 'وضع قائمة ملخص القائمة المنبثقة';

$labels['above'] = 'أعلاه';
$labels['below'] = 'أدناه';
$labels['left'] = 'يسار';
$labels['right'] = 'صحيح';

$labels['ai_disclaimer'] = 'قد تكون مخرجات الذكاء الاصطناعي في بعض الأحيان غير مكتملة أو غير صحيحة. تحقق دائمًا من المعلومات الأساسية مرة أخرى.';

// errors
$labels['api_error'] = 'حدث خطأ أثناء الاتصال بخادم الذكاء الاصطناعي. يرجى الاتصال بالمسؤول.';
