<?php
/**
 * Roundcube Plus AI plugin.
 *
 * Copyright 2023, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Pomočnik z umetno inteligenco';
$labels['ai_assistant'] = 'Pomočnik z umetno inteligenco';
$labels['ai_assistant_settings'] = 'Nastavitve pomočnika AI';

// compose page
$labels['compose_dialog_button_text'] = 'AI';
$labels['compose_dialog_button_title'] = 'Sestavite sporočilo z umetno inteligenco';

$labels['compose_label_to'] = 'Ime prejemnika';
$labels['compose_label_from'] = 'Ime pošiljatelja';
$labels['compose_label_style'] = 'Slog';
$labels['compose_label_length'] = 'Dolžina';
$labels['compose_label_language'] = 'Jezik';
$labels['compose_label_creativity'] = 'Ustvarjalnost';
$labels['compose_label_instructions'] = 'Navodila';
$labels['compose_no_change'] = 'Brez sprememb';
$labels['compose_instructions_placeholder'] = 'Primer: prosite za spremembo termina za naslednji teden.';

$labels['compose_style_assertive'] = 'Asertivni';
$labels['compose_style_casual'] = 'Priložnostno';
$labels['compose_style_enthusiastic'] = 'Navdušen';
$labels['compose_style_funny'] = 'Smešno';
$labels['compose_style_informational'] = 'Informativni';
$labels['compose_style_professional'] = 'Strokovno';
$labels['compose_style_urgent'] = 'Nujno';
$labels['compose_style_witty'] = 'Witty';

$labels['compose_length_short'] = 'Kratek';
$labels['compose_length_medium'] = 'Srednja';
$labels['compose_length_long'] = 'Dolga';

$labels['compose_creativity_low'] = 'Nizka';
$labels['compose_creativity_medium'] = 'Srednja';
$labels['compose_creativity_high'] = 'Visoka';

$labels['compose_insert_email'] = 'Vstavite e-pošto';
$labels['compose_generate_email'] = 'Ustvarjanje e-pošte';
$labels['compose_generate_again'] = 'Ponovno ustvarjanje';
$labels['compose_stop_generating'] = 'Prenehajte ustvarjati';
$labels['compose_error_help_button'] = 'Pomoč';

$labels['compose_no_instructions'] = 'Vnesite navodila.';
$labels['compose_instructions_too_long'] = 'Vaša navodila so predolga; obsegajo lahko največ $n znakov.';
$labels['compose_empty_response'] = 'Strežnik je vrnil prazen odgovor.';

$labels['compose_tip_to'] = 'Ime prejemnika novega e-poštnega sporočila. Navedete lahko več kot eno ime ali uporabite nize, kot so "vsi", "ekipa" itd.';
$labels['compose_tip_from'] = 'Novo e-poštno sporočilo bo podpisano s tem imenom.';
$labels['compose_tip_style'] = 'Najprimernejši slog pisanja za novo e-pošto.';
$labels['compose_tip_length'] = 'Prednostna dolžina novega e-poštnega sporočila.';
$labels['compose_tip_language'] = 'Jezik, v katerem mora biti napisano novo e-poštno sporočilo. Določite "Brez sprememb", če želite pisati v jeziku, v katerem so podana navodila.';
$labels['compose_tip_creativity'] = 'Večja kreativnost bo ustvarila bolj nepredvidljiva in raznolika e-poštna sporočila, manjša kreativnost pa bolj stvarna in jedrnata e-poštna sporočila.';
$labels['compose_tip_instructions'] = 'Navodila o tem, kaj vključiti v novo e-poštno sporočilo. Kliknite gumb Primeri navodil, da si ogledate nekaj primerov.';

$labels['compose_help_button_show'] = 'Primeri navodil';
$labels['compose_help_button_hide'] = 'Nazaj';
$labels['compose_help_title'] = 'Pomoč in primeri';
$labels['compose_help_info'] = 'Umetni inteligenci povejte, kakšno e-poštno sporočilo želite napisati. Vključite podrobnosti, kot so imena, datumi, lokacije, razlogi itd. Prosite lahko tudi za ustvarjalne zamisli ali pojasnila. Ko bo e-poštno sporočilo ustvarjeno, ga boste lahko prilagodili in vstavili na stran za sestavljanje. Tukaj je nekaj vzorčnih navodil, ki vam bodo pomagala začeti:';

$labels['compose_help_example_1'] = 'Pozdravite se';
$labels['compose_help_example_2'] = 'današnji sestanek je bil odpovedan.';
$labels['compose_help_example_3'] = 'V sredo ob 15. uri sem se dogovoril za sestanek z Margy, pripravil predstavitev prednosti uporabe umetne inteligence v naših marketinških kampanjah, da bi jo prepričal.';
$labels['compose_help_example_4'] = 'smo se odločili dodati podporo za vsebino, ustvarjeno z umetno inteligenco, na kratko pojasnite, kaj je to';
$labels['compose_help_example_5'] = 'nadaljevanje delovne naloge iz prejšnjega tedna, potrebujem jo jutri';
$labels['compose_help_example_6'] = 'prosim za povišico, več kot leto dni je nisem dobil.';
$labels['compose_help_example_7'] = 'opomni, da je treba poročilo predložiti jutri, sicer bo imela ekipa težave z Margyjem, ki je pod stresom.';
$labels['compose_help_example_8'] = 'pišite strankam o 20-odstotnem popustu na vse izdelke do torka, prodajamo oblačila';
$labels['compose_help_example_9'] = 'prosim, da pišeš Lauri in ji poveš, naj organizira srečanje za Kevinov rojstni dan ta konec tedna.';
$labels['compose_help_example_10'] = 'vprašajte o napredku pri novi spletni strani, vključite 5 idej za marketinške slogane za prvo stran, popravljamo avtomobile';
$labels['compose_help_example_11'] = 'novice o novih funkcijah VPN, ki smo jih dodali: protokol wireguard, posredovanje vrat, ubijalsko stikalo, namenski IP; razložite, kaj so';
$labels['compose_help_example_12'] = 'novice o novem programu zvestobe, začetni strošek je 10 USD za kartico, nato pa do 20 % popustov na večino izdelkov za eno leto.';
$labels['compose_help_example_13'] = 'e-poštno sporočilo za mreženje nekomu, ki ga občudujem in se želim z njim poklicno povezati.';
$labels['compose_help_example_14'] = 'strokovna zahvala za pomoč pri včerajšnjem projektu';
$labels['compose_help_example_15'] = 'pripravila je 10 idej o strategijah za pripravo učinkovitega elektronskega sporočila za vlagatelje, ki ga bo pripravila jutri.';
$labels['compose_help_example_16'] = 'profesionalno elektronsko sporočilo o odstopu z enomesečnim odpovednim rokom v skladu s pogodbo, podjetje se imenuje ACME.';
$labels['compose_help_example_17'] = 'prepričljivo elektronsko sporočilo, v katerem zahtevam napredovanje in namigujem, da bom morda odstopil, če ga ne bom dobil, ker obstajajo druge priložnosti.';
$labels['compose_help_example_18'] = 'Lepo te je bilo spoznati na včerajšnji konferenci, uživala sem v najinem klepetu, ostanimo v stiku';

$labels['compose_help_use_example'] = '(Uporabite to)';

// summaries
$labels['creating_summary'] = 'Ustvarjanje povzetka...';
$labels['show_summary'] = 'Prikaži povzetek';
$labels['hide_summary'] = 'Skrij povzetek';
$labels['recreate_summary'] = 'Ponovna izdelava povzetka';
$labels['email_has_no_text'] = 'To e-poštno sporočilo nima besedila.';

// settings
$labels['setting_compose_style'] = 'Slog';
$labels['setting_compose_length'] = 'Dolžina';
$labels['setting_compose_language'] = 'Jezik';
$labels['setting_compose_creativity'] = 'Ustvarjalnost';
$labels['setting_language'] = 'Jezik';

$labels['summarizing_messages'] = 'Povzemanje sporočil';
$labels['setting_show_summary_on_mail_view'] = 'Prikaz povzetkov AI pri pregledovanju e-poštnih sporočil';
$labels['setting_show_summary_on_list_hover'] = 'Prikaz povzetkov umetne inteligence, ko se pomaknete nad seznam e-pošte';
$labels['setting_list_summary_placement'] = 'Postavitev pojavnega okna s povzetkom seznama';

$labels['above'] = 'Nad';
$labels['below'] = 'Pod';
$labels['left'] = 'Leva stran';
$labels['right'] = 'Desno';

$labels['ai_disclaimer'] = 'Izpis umetne inteligence je lahko včasih nepopoln ali nepravilen. Vedno dvakrat preverite bistvene informacije.';

// errors
$labels['api_error'] = 'Med povezovanjem s strežnikom AI je prišlo do napake. Obrnite se na skrbnika.';
