<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Přihlášení k $p';
$labels['all_files'] = 'Všechny soubory';
$labels['shared_files'] = 'Sdílené soubory';
$labels['select_files'] = 'Výběr souborů';
$labels['save_file'] = 'Uložit soubor:';
$labels['folder_empty'] = 'Tato složka je prázdná.';
$labels['no_shares'] = 'Neexistují žádné sdílené soubory.';
$labels['cannot_find_directory'] = 'Nelze najít adresář.';
$labels['cannot_connect_to_server'] = 'Nelze se připojit k serveru.';
$labels['cannot_save_attachment'] = 'Nelze uložit přílohu.';
$labels['invalid_login_credentials'] = 'Neplatné uživatelské jméno nebo heslo.';
$labels['file_saved'] = 'Soubor byl úspěšně uložen.';
$labels['button_insert_link'] = 'Vložit odkaz';
$labels['incorrect_stored_credentials'] = 'Nelze se přihlásit k serveru, protože uložené přihlašovací údaje jsou nesprávné. Klikněte na tlačítko Odhlásit a zadejte nové uživatelské jméno a heslo.';

// settings
$labels['setting_provider'] = 'Poskytovatel';
$labels['setting_auth'] = 'Typ ověření';
$labels['setting_url'] = 'Adresa URL WebDAV';
$labels['setting_shared_url'] = 'Sdílená adresa URL WebDAV';
$labels['settings_shared_url_link'] = 'Vytvořit z adresy URL WebDAV';
$labels['specify_webdav_url'] = 'Pro vytvoření sdílené adresy URL je nutné zadat adresu URL WebDAV.';
