<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'ウェブダブリュー';
$labels['webdav'] = 'ウェブダブリュー';
$labels['login_to_provider'] = 'pにログイン';
$labels['all_files'] = 'すべてのファイル';
$labels['shared_files'] = '共有ファイル';
$labels['select_files'] = 'ファイルを選択';
$labels['save_file'] = 'ファイルを保存する：';
$labels['folder_empty'] = 'このフォルダは空です。';
$labels['no_shares'] = '共有ファイルはない。';
$labels['cannot_find_directory'] = 'ディレクトリが見つかりません。';
$labels['cannot_connect_to_server'] = 'サーバーに接続できません。';
$labels['cannot_save_attachment'] = '添付ファイルを保存できません。';
$labels['invalid_login_credentials'] = 'ユーザー名またはパスワードが無効です。';
$labels['file_saved'] = 'ファイルは正常に保存されました。';
$labels['button_insert_link'] = 'リンク挿入';
$labels['incorrect_stored_credentials'] = '保存されているログイン認証情報が正しくないため、サーバーにログインできません。ログアウト］をクリックし、新しいユーザー名とパスワードを入力します。';

// settings
$labels['setting_provider'] = 'プロバイダー';
$labels['setting_auth'] = '認証タイプ';
$labels['setting_url'] = 'WebDAV URL';
$labels['setting_shared_url'] = 'WebDAV共有URL';
$labels['settings_shared_url_link'] = 'WebDAV URLから作成';
$labels['specify_webdav_url'] = '共有URLを作成するには、WebDAV URLを指定する必要があります。';
