<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Zaloguj się do $p';
$labels['all_files'] = 'Wszystkie pliki';
$labels['shared_files'] = 'Pliki udostępnione';
$labels['select_files'] = 'Wybierz pliki';
$labels['save_file'] = 'Zapisz plik:';
$labels['folder_empty'] = 'Ten folder jest pusty.';
$labels['no_shares'] = 'Nie ma żadnych udostępnionych plików.';
$labels['cannot_find_directory'] = 'Nie można znaleźć katalogu.';
$labels['cannot_connect_to_server'] = 'Nie można połączyć się z serwerem.';
$labels['cannot_save_attachment'] = 'Nie można zapisać załącznika.';
$labels['invalid_login_credentials'] = 'Nieprawidłowa nazwa użytkownika lub hasło.';
$labels['file_saved'] = 'Plik został zapisany pomyślnie.';
$labels['button_insert_link'] = 'Wstawić link';
$labels['incorrect_stored_credentials'] = 'Nie można zalogować się do serwera, ponieważ zapisane poświadczenia logowania są nieprawidłowe. Kliknij Wyloguj i wprowadź nową nazwę użytkownika i hasło.';

// settings
$labels['setting_provider'] = 'Dostawca';
$labels['setting_auth'] = 'Typ uwierzytelniania';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'Współdzielony adres URL WebDAV';
$labels['settings_shared_url_link'] = 'Tworzenie z adresu WebDAV';
$labels['specify_webdav_url'] = 'Aby utworzyć współdzielony adres URL musisz określić adres URL WebDAV.';
