<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Logga in på $p';
$labels['all_files'] = 'Alla filer';
$labels['shared_files'] = 'Delade filer';
$labels['select_files'] = 'Välj filer';
$labels['save_file'] = 'Spara filen:';
$labels['folder_empty'] = 'Den här mappen är tom.';
$labels['no_shares'] = 'Det finns inga delade filer.';
$labels['cannot_find_directory'] = 'Kan inte hitta katalogen.';
$labels['cannot_connect_to_server'] = 'Det går inte att ansluta till servern.';
$labels['cannot_save_attachment'] = 'Det går inte att spara bilagan.';
$labels['invalid_login_credentials'] = 'Ogiltigt användarnamn eller lösenord.';
$labels['file_saved'] = 'Filen sparades framgångsrikt.';
$labels['button_insert_link'] = 'Infoga länk';
$labels['incorrect_stored_credentials'] = 'Det går inte att logga in på servern eftersom de lagrade inloggningsuppgifterna är felaktiga. Klicka på Logga ut och ange ett nytt användarnamn och lösenord.';

// settings
$labels['setting_provider'] = 'Leverantör';
$labels['setting_auth'] = 'Typ av autentisering';
$labels['setting_url'] = 'WebDAV-URL';
$labels['setting_shared_url'] = 'WebDAV delad URL';
$labels['settings_shared_url_link'] = 'Skapa från WebDAV URL';
$labels['specify_webdav_url'] = 'För att kunna skapa den delade URL:en måste du ange WebDAV-URL:en.';
