<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'p adresine giriş yapın';
$labels['all_files'] = 'Tüm dosyalar';
$labels['shared_files'] = 'Paylaşılan dosyalar';
$labels['select_files'] = 'Dosyaları seçin';
$labels['save_file'] = 'Dosyayı kaydet:';
$labels['folder_empty'] = 'Bu klasör boş.';
$labels['no_shares'] = 'Paylaşılan dosya yoktur.';
$labels['cannot_find_directory'] = 'Dizin bulunamıyor.';
$labels['cannot_connect_to_server'] = 'Sunucuya bağlanılamıyor.';
$labels['cannot_save_attachment'] = 'Ek kaydedilemiyor.';
$labels['invalid_login_credentials'] = 'Geçersiz kullanıcı adı veya şifre.';
$labels['file_saved'] = 'Dosya başarıyla kaydedildi.';
$labels['button_insert_link'] = 'Bağlantı ekle';
$labels['incorrect_stored_credentials'] = 'Saklanan oturum açma kimlik bilgileri yanlış olduğu için sunucuda oturum açılamıyor. Oturumu Kapat\'a tıklayın ve yeni bir kullanıcı adı ve parola girin.';

// settings
$labels['setting_provider'] = 'Sağlayıcı';
$labels['setting_auth'] = 'Kimlik doğrulama türü';
$labels['setting_url'] = 'WebDAV URL\'si';
$labels['setting_shared_url'] = 'WebDAV paylaşılan URL';
$labels['settings_shared_url_link'] = 'WebDAV URL\'sinden oluştur';
$labels['specify_webdav_url'] = 'Paylaşılan URL\'yi oluşturmak için WebDAV URL\'sini belirtmeniz gerekir.';
