<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = '登入 $p';
$labels['all_files'] = '所有檔案';
$labels['shared_files'] = '共用檔案';
$labels['select_files'] = '選擇檔案';
$labels['save_file'] = '儲存檔案：';
$labels['folder_empty'] = '此資料夾為空。';
$labels['no_shares'] = '沒有共用檔案。';
$labels['cannot_find_directory'] = '無法找到目錄。';
$labels['cannot_connect_to_server'] = '無法連線至伺服器。';
$labels['cannot_save_attachment'] = '無法儲存附件。';
$labels['invalid_login_credentials'] = '無效的使用者名稱或密碼。';
$labels['file_saved'] = '檔案已成功儲存。';
$labels['button_insert_link'] = '插入連結';
$labels['incorrect_stored_credentials'] = '無法登入伺服器，因為儲存的登入憑證不正確。按一下登出，然後輸入新的使用者名稱和密碼。';

// settings
$labels['setting_provider'] = '供應商';
$labels['setting_auth'] = '驗證類型';
$labels['setting_url'] = 'WebDAV URL';
$labels['setting_shared_url'] = 'WebDAV 共用 URL';
$labels['settings_shared_url_link'] = '從 WebDAV URL 建立';
$labels['specify_webdav_url'] = '為了建立共用 URL，您必須指定 WebDAV URL。';
