<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Новинарски поток';
$labels['news_feed'] = 'Новинарски поток';
$labels['preview'] = 'Преглед';
$labels['test_settings'] = 'Тестване на настройките на новинарския поток';
$labels['feed_error'] = 'Не мога да заредя новинарска емисия.';
$labels['feed_error_url'] = 'Грешка: Не може да се зареди новинарска емисия от посочения URL адрес.';
$labels['feed_error_content'] = 'Грешка: Съдържанието, заредено от посочения URL адрес, е празно.';
$labels['setting_show_xnews_feed'] = 'Показване на емисията новини';
$labels['setting_predefined'] = 'Предварително зададени емисии';
$labels['setting_title'] = 'Заглавие';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Елементи за показване';
