<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Nyhedsfeed';
$labels['news_feed'] = 'Nyheder';
$labels['preview'] = 'Forhåndsvisning';
$labels['test_settings'] = 'Test indstillinger for nyhedsfeed';
$labels['feed_error'] = 'Kan ikke indlæse nyhedsfeed.';
$labels['feed_error_url'] = 'Fejl: Kan ikke indlæse nyhedsfeed fra den angivne URL.';
$labels['feed_error_content'] = 'Fejl: Indholdet, der er indlæst fra den angivne URL, er tomt.';
$labels['setting_show_xnews_feed'] = 'Vis nyhedsstrøm';
$labels['setting_predefined'] = 'Foruddefinerede feeds';
$labels['setting_title'] = 'Titel';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Elementer, der skal vises';
