<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'News Feed';
$labels['news_feed'] = 'News Feed';
$labels['preview'] = 'Vorschau';
$labels['test_settings'] = 'Einstellungen für den Newsfeed testen';
$labels['feed_error'] = 'Nachrichten-Feed kann nicht geladen werden.';
$labels['feed_error_url'] = 'Fehler: Der Newsfeed kann nicht von der angegebenen URL geladen werden.';
$labels['feed_error_content'] = 'Fehler: Der von der angegebenen URL geladene Inhalt ist leer.';
$labels['setting_show_xnews_feed'] = 'News Feed anzeigen';
$labels['setting_predefined'] = 'Vordefinierte Feeds';
$labels['setting_title'] = 'Titel';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Zu zeigende Artikel';
