<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Uutissyöte';
$labels['news_feed'] = 'Uutissyöte';
$labels['preview'] = 'Esikatselu';
$labels['test_settings'] = 'Testaa uutissyötteen asetuksia';
$labels['feed_error'] = 'Uutissyötettä ei voi ladata.';
$labels['feed_error_url'] = 'Virhe: URL-osoitteesta.';
$labels['feed_error_content'] = 'Virhe: URL-osoitteesta ladattu sisältö on tyhjä.';
$labels['setting_show_xnews_feed'] = 'Näytä uutisvirta';
$labels['setting_predefined'] = 'Ennalta määritellyt syötteet';
$labels['setting_title'] = 'Otsikko';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Näytettävät kohteet';
