<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Fil d\'actualité';
$labels['news_feed'] = 'Fil d\'actualité';
$labels['preview'] = 'Aperçu';
$labels['test_settings'] = 'Tester les paramètres du fil d\'actualité';
$labels['feed_error'] = 'Impossible de charger le fil d\'actualité.';
$labels['feed_error_url'] = 'Erreur : Impossible de charger le fil d\'actualités à partir de l\'URL spécifié.';
$labels['feed_error_content'] = 'Erreur : Le contenu chargé à partir de l\'URL spécifié est vide.';
$labels['setting_show_xnews_feed'] = 'Afficher le fil d\'actualité';
$labels['setting_predefined'] = 'Flux prédéfinis';
$labels['setting_title'] = 'Titre';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Nombre d\'items à afficher';
