<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Hírfolyam';
$labels['news_feed'] = 'Hírfolyam';
$labels['preview'] = 'Előnézet';
$labels['test_settings'] = 'Hírfolyam beállítások tesztelése';
$labels['feed_error'] = 'Nem lehet betölteni a hírfolyamot.';
$labels['feed_error_url'] = 'Hiba: A megadott URL-címről nem lehet betölteni a hírfolyamot.';
$labels['feed_error_content'] = 'Hiba: A megadott URL-címről betöltött tartalom üres.';
$labels['setting_show_xnews_feed'] = 'Hírfolyam megjelenítése';
$labels['setting_predefined'] = 'Előre meghatározott tápok';
$labels['setting_title'] = 'Cím';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Megmutatandó elemek';
