<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'ニュースフィード';
$labels['news_feed'] = 'ニュースフィード';
$labels['preview'] = 'プレビュー';
$labels['test_settings'] = 'ニュースフィードの設定をテストする';
$labels['feed_error'] = 'ニュースフィードを読み込めません。';
$labels['feed_error_url'] = 'エラー：指定されたURLからニュースフィードをロードできません。';
$labels['feed_error_content'] = 'エラー：指定された URL から読み込まれたコンテンツは空です。';
$labels['setting_show_xnews_feed'] = 'ニュースフィードを表示';
$labels['setting_predefined'] = '定義済みフィード';
$labels['setting_title'] = 'タイトル';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = '表示項目';
