<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Nieuws';
$labels['news_feed'] = 'Nieuws';
$labels['preview'] = 'Voorbeeld';
$labels['test_settings'] = 'Test nieuwsfeed-instellingen';
$labels['feed_error'] = 'Kan nieuwsfeed niet laden.';
$labels['feed_error_url'] = 'Fout: Kan nieuwsfeed niet laden van de opgegeven URL.';
$labels['feed_error_content'] = 'Fout: De inhoud van de opgegeven URL is leeg.';
$labels['setting_show_xnews_feed'] = 'Toon Nieuwsfeed';
$labels['setting_predefined'] = 'Voorgedefinieerde feeds';
$labels['setting_title'] = 'Titel';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Te tonen items';
