<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Feed de notícias';
$labels['news_feed'] = 'Feed de notícias';
$labels['preview'] = 'Pré-visualização';
$labels['test_settings'] = 'Testar definições do feed de notícias';
$labels['feed_error'] = 'Não é possível carregar o feed de notícias.';
$labels['feed_error_url'] = 'Erro: Não é possível carregar o feed de notícias a partir do URL especificado.';
$labels['feed_error_content'] = 'Erro: O conteúdo carregado a partir do URL especificado está vazio.';
$labels['setting_show_xnews_feed'] = 'Mostrar feed de notícias';
$labels['setting_predefined'] = 'Feeds predefinidos';
$labels['setting_title'] = 'Título';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Itens a mostrar';
