<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Новостная лента';
$labels['news_feed'] = 'Новостная лента';
$labels['preview'] = 'Предварительный просмотр';
$labels['test_settings'] = 'Проверить настройки ленты новостей';
$labels['feed_error'] = 'Не удается загрузить новостную ленту.';
$labels['feed_error_url'] = 'Ошибка: Невозможно загрузить новостную ленту с указанного URL.';
$labels['feed_error_content'] = 'Ошибка: Содержимое, загруженное с указанного URL, пусто.';
$labels['setting_show_xnews_feed'] = 'Показать новостную ленту';
$labels['setting_predefined'] = 'Предопределенные каналы';
$labels['setting_title'] = 'Заглавие';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Предметы для показа';
