<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Novice';
$labels['news_feed'] = 'Novice';
$labels['preview'] = 'Predogled';
$labels['test_settings'] = 'Preizkusite nastavitve podajanja novic';
$labels['feed_error'] = 'Ni mogoče naložiti novice.';
$labels['feed_error_url'] = 'Napaka: Ne morem naložiti novic z navedenega naslova URL.';
$labels['feed_error_content'] = 'Napaka: Vsebina, naložena z navedenega naslova URL, je prazna.';
$labels['setting_show_xnews_feed'] = 'Prikaži novice';
$labels['setting_predefined'] = 'Vnaprej določeni viri';
$labels['setting_title'] = 'Naslov';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Elementi za prikaz';
