<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '新聞饋送';
$labels['news_feed'] = '新聞饋送';
$labels['preview'] = '預覽';
$labels['test_settings'] = '測試新聞饋送設定';
$labels['feed_error'] = '無法載入新聞提要。';
$labels['feed_error_url'] = '錯誤：無法從指定的 URL 載入新聞饋送。';
$labels['feed_error_content'] = '錯誤：從指定 URL 載入的內容為空。';
$labels['setting_show_xnews_feed'] = '顯示新聞饋送';
$labels['setting_predefined'] = '預先定義的供料';
$labels['setting_title'] = '標題';
$labels['setting_url'] = '網址';
$labels['setting_count'] = '要顯示的項目';
