<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Вход в $p';
$labels['all_files'] = 'Всички файлове';
$labels['shared_files'] = 'Споделени файлове';
$labels['select_files'] = 'Изберете файлове';
$labels['save_file'] = 'Запазване на файла:';
$labels['folder_empty'] = 'Тази папка е празна.';
$labels['no_shares'] = 'Няма споделени файлове.';
$labels['cannot_find_directory'] = 'Не мога да намеря директория.';
$labels['cannot_connect_to_server'] = 'Не можете да се свържете със сървъра.';
$labels['cannot_save_attachment'] = 'Не мога да запазя прикачения файл.';
$labels['invalid_login_credentials'] = 'Невалидно потребителско име или парола.';
$labels['file_saved'] = 'Файлът е запазен успешно.';
$labels['button_insert_link'] = 'Вмъкване на връзка';
$labels['incorrect_stored_credentials'] = 'Не можете да влезете в сървъра, тъй като съхранените идентификационни данни за вход са неправилни. Щракнете върху Изход и въведете ново потребителско име и парола.';

// settings
$labels['setting_provider'] = 'Доставчик';
$labels['setting_auth'] = 'Тип удостоверяване';
$labels['setting_url'] = 'URL адрес на WebDAV';
$labels['setting_shared_url'] = 'Споделен URL адрес на WebDAV';
$labels['settings_shared_url_link'] = 'Създаване от WebDAV URL';
$labels['specify_webdav_url'] = 'За да създадете споделения URL адрес, трябва да посочите WebDAV URL адреса.';
