<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Σύνδεση στο $p';
$labels['all_files'] = 'Όλα τα αρχεία';
$labels['shared_files'] = 'Κοινόχρηστα αρχεία';
$labels['select_files'] = 'Επιλογή αρχείων';
$labels['save_file'] = 'Αποθήκευση αρχείου:';
$labels['folder_empty'] = 'Αυτός ο φάκελος είναι άδειος.';
$labels['no_shares'] = 'Δεν υπάρχουν κοινόχρηστα αρχεία.';
$labels['cannot_find_directory'] = 'Δεν μπορεί να βρεθεί ο κατάλογος.';
$labels['cannot_connect_to_server'] = 'Δεν είναι δυνατή η σύνδεση στο διακομιστή.';
$labels['cannot_save_attachment'] = 'Δεν είναι δυνατή η αποθήκευση του συνημμένου.';
$labels['invalid_login_credentials'] = 'Μη έγκυρο όνομα χρήστη ή κωδικός πρόσβασης.';
$labels['file_saved'] = 'Το αρχείο αποθηκεύτηκε με επιτυχία.';
$labels['button_insert_link'] = 'Εισαγωγή συνδέσμου';
$labels['incorrect_stored_credentials'] = 'Δεν είναι δυνατή η σύνδεση στο διακομιστή επειδή τα αποθηκευμένα στοιχεία σύνδεσης είναι λανθασμένα. Κάντε κλικ στην επιλογή Αποσύνδεση και εισαγάγετε ένα νέο όνομα χρήστη και κωδικό πρόσβασης.';

// settings
$labels['setting_provider'] = 'Πάροχος';
$labels['setting_auth'] = 'Τύπος ελέγχου ταυτότητας';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'Κοινή διεύθυνση URL WebDAV';
$labels['settings_shared_url_link'] = 'Δημιουργία από URL WebDAV';
$labels['specify_webdav_url'] = 'Για να δημιουργήσετε το κοινόχρηστο URL πρέπει να καθορίσετε το URL WebDAV.';
