<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Acceder a $p';
$labels['all_files'] = 'Todos los archivos';
$labels['shared_files'] = 'Archivos compartidos';
$labels['select_files'] = 'Seleccionar archivos';
$labels['save_file'] = 'Guardar archivo:';
$labels['folder_empty'] = 'Esta carpeta está vacía.';
$labels['no_shares'] = 'No hay archivos compartidos.';
$labels['cannot_find_directory'] = 'No se encuentra el directorio.';
$labels['cannot_connect_to_server'] = 'No se puede conectar con el servidor.';
$labels['cannot_save_attachment'] = 'No se puede guardar el archivo adjunto.';
$labels['invalid_login_credentials'] = 'Nombre de usuario o contraseña no válidos.';
$labels['file_saved'] = 'Archivo guardado correctamente.';
$labels['button_insert_link'] = 'Insertar enlace';
$labels['incorrect_stored_credentials'] = 'No se puede iniciar sesión en el servidor porque las credenciales de inicio de sesión almacenadas son incorrectas. Haga clic en Cerrar sesión e introduzca un nuevo nombre de usuario y contraseña.';

// settings
$labels['setting_provider'] = 'Proveedor';
$labels['setting_auth'] = 'Tipo de autenticación';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'URL compartida WebDAV';
$labels['settings_shared_url_link'] = 'Crear desde URL WebDAV';
$labels['specify_webdav_url'] = 'Para crear la URL compartida debes especificar la URL WebDAV.';
