<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Logi sisse $p';
$labels['all_files'] = 'Kõik failid';
$labels['shared_files'] = 'Jagatud failid';
$labels['select_files'] = 'Valige failid';
$labels['save_file'] = 'Salvesta fail:';
$labels['folder_empty'] = 'See kaust on tühi.';
$labels['no_shares'] = 'Jagatud faile ei ole.';
$labels['cannot_find_directory'] = 'Ei leia kataloogi.';
$labels['cannot_connect_to_server'] = 'Ei saa serveriga ühendust.';
$labels['cannot_save_attachment'] = 'Ei saa manustust salvestada.';
$labels['invalid_login_credentials'] = 'Vale kasutajanimi või salasõna.';
$labels['file_saved'] = 'Faili salvestatud edukalt.';
$labels['button_insert_link'] = 'Sisesta link';
$labels['incorrect_stored_credentials'] = 'Ei saa serverisse sisse logida, sest salvestatud sisselogimise andmed on valed. Klõpsake Logout ja sisestage uus kasutajanimi ja parool.';

// settings
$labels['setting_provider'] = 'Teenusepakkuja';
$labels['setting_auth'] = 'Autentimise tüüp';
$labels['setting_url'] = 'WebDAV URL';
$labels['setting_shared_url'] = 'WebDAV jagatud URL';
$labels['settings_shared_url_link'] = 'Luua WebDAV URL-ist';
$labels['specify_webdav_url'] = 'Jagatud URL-i loomiseks peate määrama WebDAV-URL-i.';
