<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'p에 로그인';
$labels['all_files'] = '모든 파일';
$labels['shared_files'] = '공유 파일';
$labels['select_files'] = '파일 선택';
$labels['save_file'] = '파일을 저장합니다:';
$labels['folder_empty'] = '이 폴더는 비어 있습니다.';
$labels['no_shares'] = '공유 파일이 없습니다.';
$labels['cannot_find_directory'] = '디렉터리를 찾을 수 없습니다.';
$labels['cannot_connect_to_server'] = '서버에 연결할 수 없습니다.';
$labels['cannot_save_attachment'] = '첨부 파일을 저장할 수 없습니다.';
$labels['invalid_login_credentials'] = '잘못된 사용자 이름 또는 비밀번호입니다.';
$labels['file_saved'] = '파일이 성공적으로 저장되었습니다.';
$labels['button_insert_link'] = '링크 삽입';
$labels['incorrect_stored_credentials'] = '저장된 로그인 자격 증명이 올바르지 않아 서버에 로그인할 수 없습니다. 로그아웃을 클릭하고 새 사용자 아이디와 비밀번호를 입력합니다.';

// settings
$labels['setting_provider'] = '공급자';
$labels['setting_auth'] = '인증 유형';
$labels['setting_url'] = 'WebDAV URL';
$labels['setting_shared_url'] = 'WebDAV 공유 URL';
$labels['settings_shared_url_link'] = 'WebDAV URL에서 생성';
$labels['specify_webdav_url'] = '공유 URL을 만들려면 WebDAV URL을 지정해야 합니다.';
