<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Login para $p';
$labels['all_files'] = 'Todos os arquivos';
$labels['shared_files'] = 'Arquivos compartilhados';
$labels['select_files'] = 'Selecionar arquivos';
$labels['save_file'] = 'Salvar arquivo:';
$labels['folder_empty'] = 'Esta pasta está vazia.';
$labels['no_shares'] = 'Não há arquivos compartilhados.';
$labels['cannot_find_directory'] = 'Não é possível encontrar o diretório.';
$labels['cannot_connect_to_server'] = 'Não é possível conectar-se ao servidor.';
$labels['cannot_save_attachment'] = 'Não é possível salvar a fixação.';
$labels['invalid_login_credentials'] = 'Nome de usuário ou senha inválidos.';
$labels['file_saved'] = 'Arquivo salvo com sucesso.';
$labels['button_insert_link'] = 'Inserir link';
$labels['incorrect_stored_credentials'] = 'Não é possível efetuar login no servidor porque as credenciais de login armazenadas estão incorretas. Clique em Logout e digite um novo nome de usuário e senha.';

// settings
$labels['setting_provider'] = 'Fornecedor';
$labels['setting_auth'] = 'Tipo de autenticação';
$labels['setting_url'] = 'URL do WebDAV';
$labels['setting_shared_url'] = 'URL compartilhada WebDAV';
$labels['settings_shared_url_link'] = 'Criar a partir do URL WebDAV';
$labels['specify_webdav_url'] = 'A fim de criar a URL compartilhada, você deve especificar a URL WebDAV.';
