<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Autentificare la $p';
$labels['all_files'] = 'Toate fișierele';
$labels['shared_files'] = 'Fișiere partajate';
$labels['select_files'] = 'Selectați fișierele';
$labels['save_file'] = 'Salvați fișierul:';
$labels['folder_empty'] = 'Acest dosar este gol.';
$labels['no_shares'] = 'Nu există fișiere partajate.';
$labels['cannot_find_directory'] = 'Nu se poate găsi directorul.';
$labels['cannot_connect_to_server'] = 'Nu se poate conecta la server.';
$labels['cannot_save_attachment'] = 'Nu se poate salva atașamentul.';
$labels['invalid_login_credentials'] = 'Nume de utilizator sau parolă invalidă.';
$labels['file_saved'] = 'Fișier salvat cu succes.';
$labels['button_insert_link'] = 'Inserați un link';
$labels['incorrect_stored_credentials'] = 'Nu se poate conecta la server deoarece credențialele de conectare stocate sunt incorecte. Faceți clic pe Logout (Ieșire) și introduceți un nou nume de utilizator și o nouă parolă.';

// settings
$labels['setting_provider'] = 'Furnizor';
$labels['setting_auth'] = 'Tipul de autentificare';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'URL partajat WebDAV';
$labels['settings_shared_url_link'] = 'Creați din URL WebDAV';
$labels['specify_webdav_url'] = 'Pentru a crea un URL partajat, trebuie să specificați URL-ul WebDAV.';
