<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Вход в систему $p';
$labels['all_files'] = 'Все файлы';
$labels['shared_files'] = 'Общие файлы';
$labels['select_files'] = 'Выберите файлы';
$labels['save_file'] = 'Сохранить файл:';
$labels['folder_empty'] = 'Эта папка пуста.';
$labels['no_shares'] = 'Общих файлов нет.';
$labels['cannot_find_directory'] = 'Невозможно найти каталог.';
$labels['cannot_connect_to_server'] = 'Невозможно подключиться к серверу.';
$labels['cannot_save_attachment'] = 'Невозможно сохранить вложение.';
$labels['invalid_login_credentials'] = 'Неверное имя пользователя или пароль.';
$labels['file_saved'] = 'Файл успешно сохранен.';
$labels['button_insert_link'] = 'Вставить ссылку';
$labels['incorrect_stored_credentials'] = 'Невозможно войти на сервер, поскольку сохраненные учетные данные для входа неверны. Нажмите Выход и введите новое имя пользователя и пароль.';

// settings
$labels['setting_provider'] = 'Провайдер';
$labels['setting_auth'] = 'Тип аутентификации';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'Общий URL-адрес WebDAV';
$labels['settings_shared_url_link'] = 'Создание из URL WebDAV';
$labels['specify_webdav_url'] = 'Чтобы создать общий URL, необходимо указать URL WebDAV.';
