<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Prihlásenie do $p';
$labels['all_files'] = 'Všetky súbory';
$labels['shared_files'] = 'Zdieľané súbory';
$labels['select_files'] = 'Vybrať súbory';
$labels['save_file'] = 'Uložiť súbor:';
$labels['folder_empty'] = 'Tento priečinok je prázdny.';
$labels['no_shares'] = 'Neexistujú žiadne zdieľané súbory.';
$labels['cannot_find_directory'] = 'Nie je možné nájsť adresár.';
$labels['cannot_connect_to_server'] = 'Nemožno sa pripojiť k serveru.';
$labels['cannot_save_attachment'] = 'Nie je možné uložiť prílohu.';
$labels['invalid_login_credentials'] = 'Nesprávne používateľské meno alebo heslo.';
$labels['file_saved'] = 'Súbor bol úspešne uložený.';
$labels['button_insert_link'] = 'Vložiť odkaz';
$labels['incorrect_stored_credentials'] = 'Nemožno sa prihlásiť na server, pretože uložené prihlasovacie údaje sú nesprávne. Kliknite na tlačidlo Odhlásiť a zadajte nové používateľské meno a heslo.';

// settings
$labels['setting_provider'] = 'Poskytovateľ';
$labels['setting_auth'] = 'Typ overovania';
$labels['setting_url'] = 'Adresa URL WebDAV';
$labels['setting_shared_url'] = 'Zdieľaná adresa URL WebDAV';
$labels['settings_shared_url_link'] = 'Vytvorenie z adresy URL WebDAV';
$labels['specify_webdav_url'] = 'Ak chcete vytvoriť zdieľanú adresu URL, musíte zadať adresu URL WebDAV.';
