<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Увійдіть до $p';
$labels['all_files'] = 'Всі файли';
$labels['shared_files'] = 'Файли зі спільним доступом';
$labels['select_files'] = 'Виберіть файли';
$labels['save_file'] = 'Зберегти файл:';
$labels['folder_empty'] = 'Ця тека порожня.';
$labels['no_shares'] = 'Немає спільних файлів.';
$labels['cannot_find_directory'] = 'Не можу знайти каталог.';
$labels['cannot_connect_to_server'] = 'Не вдається підключитися до сервера.';
$labels['cannot_save_attachment'] = 'Не вдається зберегти вкладення.';
$labels['invalid_login_credentials'] = 'Неправильне ім\'я користувача або пароль.';
$labels['file_saved'] = 'Файл успішно збережено.';
$labels['button_insert_link'] = 'Вставити посилання';
$labels['incorrect_stored_credentials'] = 'Не вдається увійти на сервер, оскільки збережені облікові дані невірні. Натисніть Вихід і введіть нове ім\'я користувача та пароль.';

// settings
$labels['setting_provider'] = 'Провайдер';
$labels['setting_auth'] = 'Тип автентифікації';
$labels['setting_url'] = 'URL-адреса WebDAV';
$labels['setting_shared_url'] = 'Спільна URL-адреса WebDAV';
$labels['settings_shared_url_link'] = 'Створити з URL-адреси WebDAV';
$labels['specify_webdav_url'] = 'Щоб створити спільну URL-адресу, ви повинні вказати URL-адресу WebDAV.';
