<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'الطقس';
$labels['weather'] = 'الطقس';
$labels['setting_show_xweather'] = 'عرض الطقس';
$labels['description'] = 'الوصف';
$labels['humidity'] = 'الرطوبة';
$labels['pressure'] = 'الضغط';
$labels['clouds'] = 'السحب';
$labels['wind'] = 'الرياح';
$labels['sunrise'] = 'شروق الشمس';
$labels['sunset'] = 'غروب الشمس';
$labels['more_data'] = 'المزيد من البيانات';
$labels['display'] = 'العرض';
$labels['options'] = 'الخيارات';
$labels['setting_location_type'] = 'ابحث عن الموقع حسب';
$labels['setting_country_code'] = 'البلد';
$labels['setting_city'] = 'المدينة';
$labels['setting_latitude'] = 'خط العرض';
$labels['setting_longitude'] = 'خط الطول';
$labels['setting_units'] = 'الوحدات';
$labels['setting_icons'] = 'الأيقونات';
$labels['setting_show_description'] = 'إظهار الوصف';
$labels['setting_show_pressure'] = 'إظهار الضغط';
$labels['setting_show_humidity'] = 'إظهار الرطوبة';
$labels['setting_show_clouds'] = 'عرض السحب';
$labels['setting_show_wind'] = 'إظهار الرياح';
$labels['setting_show_sunrise'] = 'عرض شروق الشمس';
$labels['setting_show_sunset'] = 'عرض غروب الشمس';
$labels['metric'] = 'متري';
$labels['imperial'] = 'إمبراطوري';
$labels['icon_preview'] = 'معاينة الأيقونة';
$labels['icons_cutout'] = 'قطع';
$labels['icons_glossy'] = 'لامع';
$labels['icons_monochrome'] = 'أحادية اللون';
$labels['icons_moonlight'] = 'ضوء القمر';
$labels['icons_stickers'] = 'الملصقات';
$labels['check_location'] = 'تحقق من الموقع';
$labels['location_found'] = 'تم العثور على الموقع';
$labels['location_not_found'] = 'الموقع غير موجود.';
$labels['loading_error'] = 'حدث خطأ أثناء تحميل بيانات الطقس. يرجى التحقق من إعدادات البلد والمدينة في الخيارات.';
$labels['country_and_city'] = 'البلد والمدينة';
$labels['coordinates'] = 'الإحداثيات';
$labels['coordinates_link'] = 'ابحث عن خط العرض وخط الطول.';
