<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '天気';
$labels['weather'] = '天気';
$labels['setting_show_xweather'] = '天気予報';
$labels['description'] = '説明';
$labels['humidity'] = '湿度';
$labels['pressure'] = '圧力';
$labels['clouds'] = '雲';
$labels['wind'] = '風';
$labels['sunrise'] = '日の出';
$labels['sunset'] = 'サンセット';
$labels['more_data'] = 'その他のデータ';
$labels['display'] = 'ディスプレイ';
$labels['options'] = 'オプション';
$labels['setting_location_type'] = '場所検索';
$labels['setting_country_code'] = '国名';
$labels['setting_city'] = '都市';
$labels['setting_latitude'] = '緯度';
$labels['setting_longitude'] = '経度';
$labels['setting_units'] = '単位';
$labels['setting_icons'] = 'アイコン';
$labels['setting_show_description'] = '説明を表示';
$labels['setting_show_pressure'] = '圧力を表示';
$labels['setting_show_humidity'] = '湿度を表示';
$labels['setting_show_clouds'] = '雲を表示';
$labels['setting_show_wind'] = 'ショーウィンド';
$labels['setting_show_sunrise'] = '日の出を見る';
$labels['setting_show_sunset'] = 'ショー・サンセット';
$labels['metric'] = 'メートル';
$labels['imperial'] = 'インペリアル';
$labels['icon_preview'] = 'アイコンのプレビュー';
$labels['icons_cutout'] = 'カットアウト';
$labels['icons_glossy'] = 'グロッシー';
$labels['icons_monochrome'] = 'モノクローム';
$labels['icons_moonlight'] = '月明かり';
$labels['icons_stickers'] = 'ステッカー';
$labels['check_location'] = '場所を確認する';
$labels['location_found'] = '発見された場所';
$labels['location_not_found'] = '場所が見つかりません。';
$labels['loading_error'] = '気象データの読み込み中にエラーが発生しました。オプションの国と都市の設定を確認してください。';
$labels['country_and_city'] = '国と都市';
$labels['coordinates'] = '座標';
$labels['coordinates_link'] = '緯度と経度を調べる。';
