<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Погода';
$labels['weather'] = 'Погода';
$labels['setting_show_xweather'] = 'Показати погоду';
$labels['description'] = 'Опис';
$labels['humidity'] = 'Вологість';
$labels['pressure'] = 'Тиск';
$labels['clouds'] = 'Хмари';
$labels['wind'] = 'Вітер';
$labels['sunrise'] = 'Схід сонця';
$labels['sunset'] = 'Захід сонця';
$labels['more_data'] = 'Більше';
$labels['display'] = 'Дисплей';
$labels['options'] = 'Опції';
$labels['setting_location_type'] = 'Знайдіть місцезнаходження за';
$labels['setting_country_code'] = 'Країна';
$labels['setting_city'] = 'Місто';
$labels['setting_latitude'] = 'Широта';
$labels['setting_longitude'] = 'Довгота';
$labels['setting_units'] = 'Одиниця';
$labels['setting_icons'] = 'Іконки';
$labels['setting_show_description'] = 'Показати опис';
$labels['setting_show_pressure'] = 'Показати тиск';
$labels['setting_show_humidity'] = 'Показати вологість';
$labels['setting_show_clouds'] = 'Показати хмари';
$labels['setting_show_wind'] = 'Показати вітер';
$labels['setting_show_sunrise'] = 'Показати схід сонця';
$labels['setting_show_sunset'] = 'Показати захід сонця';
$labels['metric'] = 'Метрики';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Попередній перегляд іконки';
$labels['icons_cutout'] = 'Вирізати';
$labels['icons_glossy'] = 'Блискучий';
$labels['icons_monochrome'] = 'Монохромний';
$labels['icons_moonlight'] = 'Місячне світло';
$labels['icons_stickers'] = 'Наліпки';
$labels['check_location'] = 'Перевірте місце';
$labels['location_found'] = 'Місце знайдено:';
$labels['location_not_found'] = 'Місцезнаходження не знайдено.';
$labels['loading_error'] = 'Під час завантаження даних про погоду сталася помилка. Перевірте налаштування країни та міста в параметрах.';
$labels['country_and_city'] = 'Країна та місто';
$labels['coordinates'] = 'Координати';
$labels['coordinates_link'] = 'Знайдіть свою широту та довготу.';
