<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '天气';
$labels['weather'] = '天气';
$labels['setting_show_xweather'] = '显示天气';
$labels['description'] = '说明';
$labels['humidity'] = '湿度';
$labels['pressure'] = '压力';
$labels['clouds'] = '云彩';
$labels['wind'] = '风';
$labels['sunrise'] = '日出';
$labels['sunset'] = '日落';
$labels['more_data'] = '更多数据';
$labels['display'] = '显示屏';
$labels['options'] = '选项';
$labels['setting_location_type'] = '通过以下方式查找位置';
$labels['setting_country_code'] = '国家';
$labels['setting_city'] = '城市';
$labels['setting_latitude'] = '纬度';
$labels['setting_longitude'] = '经度';
$labels['setting_units'] = '单位';
$labels['setting_icons'] = '图标';
$labels['setting_show_description'] = '显示说明';
$labels['setting_show_pressure'] = '显示压力';
$labels['setting_show_humidity'] = '显示湿度';
$labels['setting_show_clouds'] = '显示云彩';
$labels['setting_show_wind'] = '显示风';
$labels['setting_show_sunrise'] = '显示日出';
$labels['setting_show_sunset'] = '显示日落';
$labels['metric'] = '公制';
$labels['imperial'] = '帝国';
$labels['icon_preview'] = '图标预览';
$labels['icons_cutout'] = '切口';
$labels['icons_glossy'] = '光泽';
$labels['icons_monochrome'] = '单色';
$labels['icons_moonlight'] = '月光';
$labels['icons_stickers'] = '贴纸';
$labels['check_location'] = '检查位置';
$labels['location_found'] = '发现地点：';
$labels['location_not_found'] = '未找到位置。';
$labels['loading_error'] = '加载天气数据时出现错误。请检查选项中的国家和城市设置。';
$labels['country_and_city'] = '国家和城市';
$labels['coordinates'] = '坐标';
$labels['coordinates_link'] = '查找您的经纬度。';
