<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '天氣';
$labels['weather'] = '天氣';
$labels['setting_show_xweather'] = '顯示天氣';
$labels['description'] = '說明';
$labels['humidity'] = '濕度';
$labels['pressure'] = '壓力';
$labels['clouds'] = '雲彩';
$labels['wind'] = '風';
$labels['sunrise'] = '日出';
$labels['sunset'] = '日落';
$labels['more_data'] = '更多資料';
$labels['display'] = '顯示器';
$labels['options'] = '選項';
$labels['setting_location_type'] = '透過下列方式尋找位置';
$labels['setting_country_code'] = '國家';
$labels['setting_city'] = '城市';
$labels['setting_latitude'] = '緯度';
$labels['setting_longitude'] = '經度';
$labels['setting_units'] = '單位';
$labels['setting_icons'] = '圖示';
$labels['setting_show_description'] = '顯示說明';
$labels['setting_show_pressure'] = '顯示壓力';
$labels['setting_show_humidity'] = '顯示濕度';
$labels['setting_show_clouds'] = '顯示雲彩';
$labels['setting_show_wind'] = '顯示風';
$labels['setting_show_sunrise'] = '顯示日出';
$labels['setting_show_sunset'] = '顯示日落';
$labels['metric'] = '公制';
$labels['imperial'] = '帝國';
$labels['icon_preview'] = '圖示預覽';
$labels['icons_cutout'] = '剪裁';
$labels['icons_glossy'] = '亮面';
$labels['icons_monochrome'] = '單色';
$labels['icons_moonlight'] = '月光';
$labels['icons_stickers'] = '貼紙';
$labels['check_location'] = '檢查位置';
$labels['location_found'] = '找到地點：';
$labels['location_not_found'] = '未找到位置。';
$labels['loading_error'] = '載入天氣資料時發生錯誤。請檢查選項中的國家和城市設定。';
$labels['country_and_city'] = '國家和城市';
$labels['coordinates'] = '座標';
$labels['coordinates_link'] = '找出您的經緯度。';
