<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Letzte Anmeldung';
$labels['setting_show_xlast_login'] = 'Letzte Anmeldung anzeigen';
$labels['country'] = 'Land';
$labels['city'] = 'Stadt';
$labels['location'] = 'Standort';
$labels['time'] = 'Zeit';
$labels['map'] = 'Karte';
$labels['more_data'] = 'Weitere Daten';
$labels['whats_this'] = 'Was ist das?';
$labels['explanation'] = 'Dieses Feld zeigt den Ort der letzten Anmeldung bei Ihrem E-Mail-Konto an. Wenn Sie diesen Ort nicht erkennen, könnte ein böswilliger Benutzer Ihr Passwort haben. In diesem Fall sollten Sie Ihr Passwort sofort ändern.';
$labels['no_info'] = 'Es werden keine Informationen zur letzten Anmeldung angezeigt. Die Informationen werden verfügbar sein, wenn Sie sich das nächste Mal bei Ihrem Webmail anmelden.';
