<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Last Login';
$labels['setting_show_xlast_login'] = 'Show Last Login';
$labels['country'] = 'Country';
$labels['city'] = 'City';
$labels['location'] = 'Location';
$labels['time'] = 'Time';
$labels['map'] = 'Map';
$labels['more_data'] = 'More data';
$labels['whats_this'] = 'What\'s this?';
$labels['explanation'] = 'This box shows the location of the last login to your email account. If you don\'t recognize this location, a malicious user might have your password. You should change your password immediately if this happens.';
$labels['no_info'] = 'There is no last login information to display. The information will become available next time you log in to your webmail.';
