<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Viimeisin kirjautuminen';
$labels['setting_show_xlast_login'] = 'Näytä viimeinen sisäänkirjautuminen';
$labels['country'] = 'Maa';
$labels['city'] = 'Kaupunki';
$labels['location'] = 'Sijainti';
$labels['time'] = 'Aika';
$labels['map'] = 'Kartta';
$labels['more_data'] = 'Lisää tietoja';
$labels['whats_this'] = 'Mitä tämä on?';
$labels['explanation'] = 'Tämä ruutu näyttää viimeisimmän kirjautumisen sijainnin sähköpostitilillesi. Jos et tunnista tätä sijaintia, salasanasi saattaa olla haitallisella käyttäjällä. Jos näin käy, sinun on vaihdettava salasanasi välittömästi.';
$labels['no_info'] = 'Viimeisintä kirjautumistietoa ei näytetä. Tiedot tulevat saataville seuraavan kerran, kun kirjaudut webmailiin.';
