<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Ultimo accesso';
$labels['setting_show_xlast_login'] = 'Mostra ultimo accesso';
$labels['country'] = 'Paese';
$labels['city'] = 'Città';
$labels['location'] = 'Località';
$labels['time'] = 'Data e Ora';
$labels['map'] = 'Mappa';
$labels['more_data'] = 'Più dati';
$labels['whats_this'] = 'Cos\'è questo?';
$labels['explanation'] = 'Questa casella mostra la posizione dell\'ultimo accesso al tuo account di posta elettronica. Se non riconosci questa posizione, un utente malintenzionato potrebbe avere la tua password. Se questo accade, dovresti cambiare la tua password immediatamente.';
$labels['no_info'] = 'Non ci sono informazioni di accesso da visualizzare. Le informazioni saranno disponibili la prossima volta che accedi alla tua webmail.';
