<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Pēdējais pieteikšanās';
$labels['setting_show_xlast_login'] = 'Rādīt pēdējo pieteikšanos';
$labels['country'] = 'Valsts';
$labels['city'] = 'Pilsēta';
$labels['location'] = 'Atrašanās vieta';
$labels['time'] = 'Laiks';
$labels['map'] = 'Karte';
$labels['more_data'] = 'Vairāk datu';
$labels['whats_this'] = 'Kas tas ir?';
$labels['explanation'] = 'Šajā lodziņā ir norādīta vieta, kur pēdējo reizi pieteicāties savā e-pasta kontā. Ja neatpazīstat šo atrašanās vietu, iespējams, ka jūsu parole ir ļaunprātīga lietotāja rīcībā. Šādā gadījumā nekavējoties nomainiet paroli.';
$labels['no_info'] = 'Pēdējā pieteikšanās informācija netiek rādīta. Informācija būs pieejama nākamreiz, kad pierakstīsieties savā tīmekļa pastkastē.';
