<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = '最後一次登入';
$labels['setting_show_xlast_login'] = '顯示上次登入';
$labels['country'] = '國家';
$labels['city'] = '城市';
$labels['location'] = '地點';
$labels['time'] = '時間';
$labels['map'] = '地圖';
$labels['more_data'] = '更多資料';
$labels['whats_this'] = '這是什麼？';
$labels['explanation'] = '此方框顯示您上次登入電子郵件帳戶的位置。如果您認不出此位置，則可能是惡意使用者擁有您的密碼。如果發生這種情況，您應該立即更改密碼。';
$labels['no_info'] = '沒有上次登入的資訊要顯示。當您下次登入 webmail 時，就會顯示該資訊。';
