<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Plánovač e-mailů';
$labels['email_schedule'] = 'Plánovač e-mailů';
$labels['schedule'] = 'Plán';
$labels['scheduled'] = 'Plánované';
$labels['scheduled_messages'] = 'Naplánované zprávy';
$labels['show_scheduled_messages'] = 'Zobrazit naplánované zprávy.';
$labels['message_scheduled'] = 'Plánovaná zpráva.';
$labels['no_scheduled_messages'] = 'Ve frontě plánu nejsou žádné zprávy.';
$labels['warning_unsent_messages'] = 'Některé z vašich naplánovaných zpráv nebyly odeslány.';
$labels['message_delete_confirm'] = 'Chcete tuto zprávu trvale odstranit?';

$labels['immediately'] = 'Ihned';
$labels['in_5_minutes'] = 'Za 5 minut';
$labels['in_10_minutes'] = 'Za 10 minut';
$labels['in_15_minutes'] = 'Za 15 minut';
$labels['in_30_minutes'] = 'Za 30 minut';
$labels['in_1_hour'] = 'Za 1 hodinu';
$labels['in_2_hours'] = 'Za 2 hodiny';
$labels['in_6_hours'] = 'Za 6 hodin';
$labels['at_a_specific_time'] = 'V určitém čase';

$labels['disabled'] = 'Plánování zpráv je zakázáno. Kontaktujte správce.';
$labels['draft_note'] = 'Tato zpráva byla uložena jako koncept a odstraněna z fronty plánu. Chcete-li ji znovu naplánovat, klikněte na tlačítko Naplánovat.';
$labels['error_editing'] = 'Naplánovanou zprávu nelze upravit; zpráva mohla být odeslána nebo odstraněna.';
$labels['error_deleting'] = 'Zprávu nelze přesunout do koše; zpráva mohla být odeslána, odstraněna nebo schránka koše není k dispozici.';

$labels['send_message'] = 'Odeslat zprávu';
$labels['setting_delay'] = 'Výchozí zpoždění pro odesílání zpráv';
$labels['setting_highlight'] = 'Zvýraznění plánovaných zpráv, které mají být odeslány.';

$labels['email_being_sent'] = 'Odesílání e-mailů';
$labels['send_now'] = 'Odeslat nyní';
$labels['schedule_now'] = 'Naplánujte si nyní';
$labels['cancel_sending'] = 'Zrušit odesílání';
$labels['setting_countdown'] = 'Odpočítávání před odesláním zpráv';
$labels['disable_countdown'] = 'Zakázat';
$labels['3_seconds'] = '3 sekundy';
$labels['5_seconds'] = '5 sekund';
$labels['10_seconds'] = '10 sekund';
$labels['15_seconds'] = '15 sekund';

$labels['cannot_schedule_message'] = 'Zprávu nelze naplánovat:';
$labels['time_has_already_passed'] = 'Plánovaný čas již uplynul.';
$labels['invalid_time_format'] = 'Nesprávný formát času.';
$labels['draft_folder_not_specified'] = 'Chyba zásuvného modulu pro plánování e-mailů: Složka návrhu nebyla zadána.';
$labels['error'] = 'Chyba:';
$labels['attachment_tool_large'] = 'Konfigurace serveru omezuje velikost příloh plánovaných zpráv na $.';
$labels['message_already_scheduled'] = 'Tato zpráva je již naplánována.';

