<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Planlægning af e-mail';
$labels['email_schedule'] = 'Planlægning af e-mail';
$labels['schedule'] = 'Tidsplan';
$labels['scheduled'] = 'Planlagt';
$labels['scheduled_messages'] = 'Planlagte meddelelser';
$labels['show_scheduled_messages'] = 'Vis planlagte meddelelser.';
$labels['message_scheduled'] = 'Besked planlagt.';
$labels['no_scheduled_messages'] = 'Der er ingen meddelelser i køen til planlægningen.';
$labels['warning_unsent_messages'] = 'Nogle af dine planlagte meddelelser er ikke blevet sendt.';
$labels['message_delete_confirm'] = 'Ønsker du at slette denne meddelelse permanent?';

$labels['immediately'] = 'Umiddelbart';
$labels['in_5_minutes'] = 'På 5 minutter';
$labels['in_10_minutes'] = 'På 10 minutter';
$labels['in_15_minutes'] = 'Om 15 minutter';
$labels['in_30_minutes'] = 'Om 30 minutter';
$labels['in_1_hour'] = 'Om 1 time';
$labels['in_2_hours'] = 'Om 2 timer';
$labels['in_6_hours'] = 'Om 6 timer';
$labels['at_a_specific_time'] = 'På et bestemt tidspunkt';

$labels['disabled'] = 'Planlægning af meddelelser er deaktiveret. Kontakt administratoren.';
$labels['draft_note'] = 'Denne meddelelse blev gemt som kladde og fjernet fra tidskøen. Hvis du vil planlægge den igen, skal du klikke på knappen Planlæg for at planlægge den igen.';
$labels['error_editing'] = 'Kan ikke redigere den planlagte meddelelse; meddelelsen er muligvis blevet sendt eller slettet.';
$labels['error_deleting'] = 'Kan ikke flytte meddelelsen til papirkurven; meddelelsen er muligvis blevet sendt eller slettet, eller postkassen til papirkurven er ikke tilgængelig.';

$labels['send_message'] = 'Send besked';
$labels['setting_delay'] = 'Standardforsinkelse for afsendelse af meddelelser';
$labels['setting_highlight'] = 'Fremhæv planlagte meddelelser, der er ved at blive sendt';

$labels['email_being_sent'] = 'Afsendelse af e-mail';
$labels['send_now'] = 'Send nu';
$labels['schedule_now'] = 'Planlæg nu';
$labels['cancel_sending'] = 'Annuller afsendelse';
$labels['setting_countdown'] = 'Nedtælling før afsendelse af meddelelser';
$labels['disable_countdown'] = 'Deaktiver';
$labels['3_seconds'] = '3 sekunder';
$labels['5_seconds'] = '5 sekunder';
$labels['10_seconds'] = '10 sekunder';
$labels['15_seconds'] = '15 sekunder';

$labels['cannot_schedule_message'] = 'Kan ikke planlægge meddelelse:';
$labels['time_has_already_passed'] = 'Det planlagte tidspunkt er allerede overskredet.';
$labels['invalid_time_format'] = 'Ugyldigt tidsformat.';
$labels['draft_folder_not_specified'] = 'Email schedule plugin fejl: Udkastmappe ikke angivet.';
$labels['error'] = 'Fejl:';
$labels['attachment_tool_large'] = 'Serverkonfigurationen begrænser planlagte vedhæftede filer til $size.';
$labels['message_already_scheduled'] = 'Denne besked er allerede planlagt.';

