<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Planificateur d\'emails';
$labels['email_schedule'] = 'Planification des emails';
$labels['schedule'] = 'Programme';
$labels['scheduled'] = 'Prévu';
$labels['scheduled_messages'] = 'Messages programmés';
$labels['show_scheduled_messages'] = 'Afficher les messages programmés.';
$labels['message_scheduled'] = 'Message programmé.';
$labels['no_scheduled_messages'] = 'Il n\'y a aucun message dans la file d\'attente.';
$labels['warning_unsent_messages'] = 'Certains de vos messages programmés n\'ont pas été envoyés.';
$labels['message_delete_confirm'] = 'Voulez-vous supprimer définitivement ce message ?';

$labels['immediately'] = 'Immédiatement';
$labels['in_5_minutes'] = 'Dans 5 minutes';
$labels['in_10_minutes'] = 'Dans 10 minutes';
$labels['in_15_minutes'] = 'Dans 15 minutes';
$labels['in_30_minutes'] = 'Dans 30 minutes';
$labels['in_1_hour'] = 'Dans 1 heure';
$labels['in_2_hours'] = 'Dans 2 heures';
$labels['in_6_hours'] = 'Dans 6 heures';
$labels['at_a_specific_time'] = 'À une heure précise';

$labels['disabled'] = 'La planification des messages est désactivée. Contactez l\'administrateur.';
$labels['draft_note'] = 'Ce message a été enregistré en tant que brouillon et supprimé de la file d\'attente. Pour le planifier à nouveau, cliquez sur le bouton Planifier.';
$labels['error_editing'] = 'Impossible de modifier le message programmé ; le message a peut-être été envoyé ou supprimé.';
$labels['error_deleting'] = 'Impossible de déplacer le message dans la corbeille ; le message a peut-être été envoyé, supprimé ou la Corbeille n\'est pas disponible.';

$labels['send_message'] = 'Envoyer le message';
$labels['setting_delay'] = 'Envoyer des messages';
$labels['setting_highlight'] = 'Mettre en surbrillance les messages sur le point d\'être envoyés';

$labels['email_being_sent'] = 'Envoi d\'un courriel';
$labels['send_now'] = 'Envoyer maintenant';
$labels['schedule_now'] = 'Programmez maintenant';
$labels['cancel_sending'] = 'Annuler l\'envoi';
$labels['setting_countdown'] = 'Compte à rebours avant l\'envoi des messages';
$labels['disable_countdown'] = 'Désactiver';
$labels['3_seconds'] = '3 secondes';
$labels['5_seconds'] = '5 secondes';
$labels['10_seconds'] = '10 secondes';
$labels['15_seconds'] = '15 secondes';

$labels['cannot_schedule_message'] = 'Impossible de programmer le message :';
$labels['time_has_already_passed'] = 'L\'heure prévue est déjà passée.';
$labels['invalid_time_format'] = 'Format d\'heure non valide.';
$labels['draft_folder_not_specified'] = 'Erreur du plugin de planification des emails : Le dossier de brouillon n\'est pas spécifié.';
$labels['error'] = 'Erreur :';
$labels['attachment_tool_large'] = 'La configuration du serveur limite les pièces jointes des messages programmés à $size.';
$labels['message_already_scheduled'] = 'Ce message est déjà programmé.';

