<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Penjadwal Email';
$labels['email_schedule'] = 'Penjadwal Email';
$labels['schedule'] = 'Jadwal';
$labels['scheduled'] = 'Terjadwal';
$labels['scheduled_messages'] = 'Pesan terjadwal';
$labels['show_scheduled_messages'] = 'Menampilkan pesan terjadwal.';
$labels['message_scheduled'] = 'Pesan dijadwalkan.';
$labels['no_scheduled_messages'] = 'Tidak ada pesan dalam antrean jadwal.';
$labels['warning_unsent_messages'] = 'Beberapa pesan terjadwal Anda belum terkirim.';
$labels['message_delete_confirm'] = 'Apakah Anda ingin menghapus pesan ini secara permanen?';

$labels['immediately'] = 'Segera';
$labels['in_5_minutes'] = 'Dalam 5 menit';
$labels['in_10_minutes'] = 'Dalam 10 menit';
$labels['in_15_minutes'] = 'Dalam 15 menit';
$labels['in_30_minutes'] = 'Dalam 30 menit';
$labels['in_1_hour'] = 'Dalam 1 jam';
$labels['in_2_hours'] = 'Dalam 2 jam';
$labels['in_6_hours'] = 'Dalam 6 jam';
$labels['at_a_specific_time'] = 'Pada waktu tertentu';

$labels['disabled'] = 'Penjadwalan pesan dinonaktifkan. Hubungi administrator.';
$labels['draft_note'] = 'Pesan ini disimpan sebagai draf dan dihapus dari antrean jadwal. Untuk menjadwalkannya lagi, klik tombol Jadwalkan.';
$labels['error_editing'] = 'Tidak dapat mengedit pesan terjadwal; pesan mungkin sudah terkirim atau terhapus.';
$labels['error_deleting'] = 'Tidak dapat memindahkan pesan ke kotak sampah; pesan mungkin telah terkirim, terhapus, atau kotak sampah tidak tersedia.';

$labels['send_message'] = 'Kirim pesan';
$labels['setting_delay'] = 'Penundaan default untuk mengirim pesan';
$labels['setting_highlight'] = 'Menyorot pesan terjadwal yang akan dikirim';

$labels['email_being_sent'] = 'Mengirim email';
$labels['send_now'] = 'Kirim sekarang';
$labels['schedule_now'] = 'Jadwalkan sekarang';
$labels['cancel_sending'] = 'Membatalkan pengiriman';
$labels['setting_countdown'] = 'Hitung mundur sebelum mengirim pesan';
$labels['disable_countdown'] = 'Nonaktifkan';
$labels['3_seconds'] = '3 detik';
$labels['5_seconds'] = '5 detik';
$labels['10_seconds'] = '10 detik';
$labels['15_seconds'] = '15 detik';

$labels['cannot_schedule_message'] = 'Tidak dapat menjadwalkan pesan:';
$labels['time_has_already_passed'] = 'Waktu yang dijadwalkan telah berlalu.';
$labels['invalid_time_format'] = 'Format waktu tidak valid.';
$labels['draft_folder_not_specified'] = 'Kesalahan plugin jadwal email: Folder draf tidak ditentukan.';
$labels['error'] = 'Kesalahan:';
$labels['attachment_tool_large'] = 'Konfigurasi server membatasi lampiran pesan terjadwal hingga $size.';
$labels['message_already_scheduled'] = 'Pesan ini sudah dijadwalkan.';

