<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'El. pašto tvarkaraštis';
$labels['email_schedule'] = 'El. pašto tvarkaraštis';
$labels['schedule'] = 'Tvarkaraštis';
$labels['scheduled'] = 'Suplanuota';
$labels['scheduled_messages'] = 'Suplanuoti pranešimai';
$labels['show_scheduled_messages'] = 'Rodyti suplanuotus pranešimus.';
$labels['message_scheduled'] = 'Suplanuota žinutė.';
$labels['no_scheduled_messages'] = 'Tvarkaraščio eilėje nėra pranešimų.';
$labels['warning_unsent_messages'] = 'Kai kurie jūsų suplanuoti pranešimai nebuvo išsiųsti.';
$labels['message_delete_confirm'] = 'Ar norite visam laikui ištrinti šią žinutę?';

$labels['immediately'] = 'Iškart';
$labels['in_5_minutes'] = 'Per 5 minutes';
$labels['in_10_minutes'] = 'Per 10 minučių';
$labels['in_15_minutes'] = 'Per 15 minučių';
$labels['in_30_minutes'] = 'Per 30 minučių';
$labels['in_1_hour'] = 'Per 1 valandą';
$labels['in_2_hours'] = 'Per 2 valandas';
$labels['in_6_hours'] = 'Per 6 valandas';
$labels['at_a_specific_time'] = 'Tam tikru metu';

$labels['disabled'] = 'Pranešimų planavimas išjungtas. Kreipkitės į administratorių.';
$labels['draft_note'] = 'Šis pranešimas buvo išsaugotas kaip juodraštis ir pašalintas iš tvarkaraščio eilės. Norėdami jį vėl suplanuoti, spustelėkite mygtuką Suplanuoti.';
$labels['error_editing'] = 'Negalima redaguoti suplanuoto pranešimo; pranešimas galėjo būti išsiųstas arba ištrintas.';
$labels['error_deleting'] = 'Pranešimo negalima perkelti į šiukšliadėžę; pranešimas galėjo būti išsiųstas, ištrintas arba šiukšliadėžė nepasiekiama.';

$labels['send_message'] = 'Siųsti žinutę';
$labels['setting_delay'] = 'Numatytoji pranešimų siuntimo delsa';
$labels['setting_highlight'] = 'Išryškinkite suplanuotus pranešimus, kuriuos ketinama išsiųsti';

$labels['email_being_sent'] = 'El. pašto siuntimas';
$labels['send_now'] = 'Siųsti dabar';
$labels['schedule_now'] = 'Planuokite dabar';
$labels['cancel_sending'] = 'Atšaukti siuntimą';
$labels['setting_countdown'] = 'Atgalinė atskaita prieš siunčiant pranešimus';
$labels['disable_countdown'] = 'Išjungti';
$labels['3_seconds'] = '3 sekundės';
$labels['5_seconds'] = '5 sekundės';
$labels['10_seconds'] = '10 sekundžių';
$labels['15_seconds'] = '15 sekundžių';

$labels['cannot_schedule_message'] = 'Negalima suplanuoti pranešimo:';
$labels['time_has_already_passed'] = 'Numatytas laikas jau praėjo.';
$labels['invalid_time_format'] = 'Netinkamas laiko formatas.';
$labels['draft_folder_not_specified'] = 'El. pašto tvarkaraščio įskiepio klaida: Nenurodytas juodraščio aplankas.';
$labels['error'] = 'Klaida:';
$labels['attachment_tool_large'] = 'Serverio konfigūracija riboja suplanuotų pranešimų priedus iki $ dydžio.';
$labels['message_already_scheduled'] = 'Šis pranešimas jau suplanuotas.';

