<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'E-mailplanner';
$labels['email_schedule'] = 'E-mailplanner';
$labels['schedule'] = 'Schema';
$labels['scheduled'] = 'Gepland';
$labels['scheduled_messages'] = 'Geplande berichten';
$labels['show_scheduled_messages'] = 'Toon geplande berichten.';
$labels['message_scheduled'] = 'Bericht gepland.';
$labels['no_scheduled_messages'] = 'Er zijn geen berichten in de agenda wachtrij.';
$labels['warning_unsent_messages'] = 'Sommige van uw geplande berichten zijn niet verzonden.';
$labels['message_delete_confirm'] = 'Wilt u dit bericht definitief verwijderen?';

$labels['immediately'] = 'Onmiddellijk';
$labels['in_5_minutes'] = 'In 5 minuten';
$labels['in_10_minutes'] = 'In 10 minuten';
$labels['in_15_minutes'] = 'In 15 minuten';
$labels['in_30_minutes'] = 'In 30 minuten';
$labels['in_1_hour'] = 'In 1 uur';
$labels['in_2_hours'] = 'Over 2 uur';
$labels['in_6_hours'] = 'Over 6 uur';
$labels['at_a_specific_time'] = 'Op een bepaald tijdstip';

$labels['disabled'] = 'Planning van berichten is uitgeschakeld. Neem contact op met de beheerder.';
$labels['draft_note'] = 'Dit bericht is opgeslagen als concept en verwijderd uit de planningswachtrij. Om het opnieuw in te plannen, klikt u op de knop Plannen.';
$labels['error_editing'] = 'Kan het geplande bericht niet bewerken; het bericht kan zijn verzonden of verwijderd.';
$labels['error_deleting'] = 'Kan het bericht niet naar de prullenbak verplaatsen; het bericht kan zijn verzonden, verwijderd of de prullenbak is niet beschikbaar.';

$labels['send_message'] = 'Verstuur bericht';
$labels['setting_delay'] = 'Standaard vertraging voor het verzenden van berichten';
$labels['setting_highlight'] = 'Markeer geplande berichten die op het punt staan te worden verzonden';

$labels['email_being_sent'] = 'E-mail verzenden';
$labels['send_now'] = 'Verstuur nu';
$labels['schedule_now'] = 'Plan nu';
$labels['cancel_sending'] = 'Annuleren verzenden';
$labels['setting_countdown'] = 'Aftellen voor het verzenden van berichten';
$labels['disable_countdown'] = 'Schakel  uit.';
$labels['3_seconds'] = '3 seconden';
$labels['5_seconds'] = '5 seconden';
$labels['10_seconds'] = '10 seconden.';
$labels['15_seconds'] = '15 seconden.';

$labels['cannot_schedule_message'] = 'Kan bericht niet inplannen:';
$labels['time_has_already_passed'] = 'De geplande tijd is al voorbij.';
$labels['invalid_time_format'] = 'Ongeldig tijdformaat.';
$labels['draft_folder_not_specified'] = 'Email schema plugin fout: Concept map niet gespecificeerd.';
$labels['error'] = 'Fout:';
$labels['attachment_tool_large'] = 'Serverconfiguratie beperkt geplande berichtbijlagen tot $grootte.';
$labels['message_already_scheduled'] = 'Dit bericht is al ingepland.';

