<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Planowanie wiadomości';
$labels['email_schedule'] = 'Planowanie wiadomości';
$labels['schedule'] = 'Zaplanuj';
$labels['scheduled'] = 'Zaplanowane';
$labels['scheduled_messages'] = 'Zaplanowane wiadomości';
$labels['show_scheduled_messages'] = 'Pokaż zaplanowane wiadomości.';
$labels['message_scheduled'] = 'Wiadomość zaplanowane.';
$labels['no_scheduled_messages'] = 'Nie ma zaplanowanych wiadomości.';
$labels['warning_unsent_messages'] = 'Niektóre z zaplanowanych wiadomości nie zostały wysłane.';
$labels['message_delete_confirm'] = 'Czy chcesz trwale usunąć tę wiadomość?';

$labels['immediately'] = 'Natychmiast';
$labels['in_5_minutes'] = 'Za 5 minut';
$labels['in_10_minutes'] = 'Za 10 minut';
$labels['in_15_minutes'] = 'Za 15 minut';
$labels['in_30_minutes'] = 'Za 30 minut';
$labels['in_1_hour'] = 'Za 1 godzinę';
$labels['in_2_hours'] = 'Za 2 godziny';
$labels['in_6_hours'] = 'Za 6 godzin';
$labels['at_a_specific_time'] = 'O zaplanowanej porze';

$labels['disabled'] = 'Planowanie wiadomości jest wyłączone. Skontaktuj się z administratorem.';
$labels['draft_note'] = 'Wiadomość została zapisana jako kopia robocza i usunięta z listy zaplanowanych wiadomości. Aby zaplanować ją ponownie, kliknij przycisk Planowanie.';
$labels['error_editing'] = 'Zaplanowana wiadomość nie może być edytowana. Wiadomość mogła zostać już wysłana lub usunięta.';
$labels['error_deleting'] = 'Nie można przenieść wiadomości do kosza. Wiadomość mogła już zostać wysłana / usunięta lub kosz jest niedostępny.';

$labels['send_message'] = 'Wyślij wiadomość';
$labels['setting_delay'] = 'Domyślne opóźnienie wysyłanie wiadomości';
$labels['setting_highlight'] = 'Podświetl zaplanowane wiadomości, które zostaną za chwilę wysłane';

$labels['email_being_sent'] = 'Wysyłanie wiadomości';
$labels['send_now'] = 'Wyślij teraz';
$labels['schedule_now'] = 'Zaplanuj teraz';
$labels['cancel_sending'] = 'Anuluj';
$labels['setting_countdown'] = 'Odliczanie przed wysyłaniem wiadomości';
$labels['disable_countdown'] = 'Wyłączone';
$labels['3_seconds'] = '3 sekundy';
$labels['5_seconds'] = '5 sekund';
$labels['10_seconds'] = '10 sekund';
$labels['15_seconds'] = '15 sekund';

$labels['cannot_schedule_message'] = 'Nie można zaplanować wiadomości:';
$labels['time_has_already_passed'] = 'Wybrany czas już minął.';
$labels['invalid_time_format'] = 'Niewłaściwy format czasu.';
$labels['draft_folder_not_specified'] = 'Błąd we wtyczce planowania wiadomosci: brak foldera kopii roboczych.';
$labels['error'] = 'Błąd:';
$labels['attachment_tool_large'] = 'Konfiguracja serwera ogranicza zaplanowane załączniki wiadomości do rozmiaru $.';
$labels['message_already_scheduled'] = 'Ta wiadomość jest już zaplanowana.';

