<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Планировщик электронной почты';
$labels['email_schedule'] = 'Расписание электронной почты';
$labels['schedule'] = 'Расписание';
$labels['scheduled'] = 'По расписанию';
$labels['scheduled_messages'] = 'Запланированные сообщения';
$labels['show_scheduled_messages'] = 'Показать запланированные сообщения.';
$labels['message_scheduled'] = 'Сообщение запланировано.';
$labels['no_scheduled_messages'] = 'у Вас нет запланированных сообщений.';
$labels['warning_unsent_messages'] = 'Некоторые Ваши апланированные сообщение не были отправлены.';
$labels['message_delete_confirm'] = 'Вы хотите навсегда удалить это сообщение?';

$labels['immediately'] = 'Немедленно';
$labels['in_5_minutes'] = 'Через 5 минут';
$labels['in_10_minutes'] = 'Через 10 минут';
$labels['in_15_minutes'] = 'Через 15 минут';
$labels['in_30_minutes'] = 'Через 30 минут';
$labels['in_1_hour'] = 'Через 1 час';
$labels['in_2_hours'] = 'Через 2 часа';
$labels['in_6_hours'] = 'Через 6 часов';
$labels['at_a_specific_time'] = 'В определенное время';

$labels['disabled'] = 'Запланированное сообщение не отпавлено. Свяжитесь с администратором';
$labels['draft_note'] = 'Это сообщение было сохранено как черновик и удалено из очереди расписания. Чтобы запланировать его снова, нажмите кнопку Расписание.';
$labels['error_editing'] = 'Невозможно отредактировать запланированное сообщение; сообщение могло быть отправлено или удалено.';
$labels['error_deleting'] = 'Невозможно переместить сообщение в корзину; возможно, сообщение отправлено, удалено или корзина переполнена.';

$labels['send_message'] = 'Отправить сообщение';
$labels['setting_delay'] = 'Отправить сообщения';
$labels['setting_highlight'] = 'Выделите сообщения, которые должны быть отправлены';

$labels['email_being_sent'] = 'Отправка электронной почты';
$labels['send_now'] = 'Отправить сейчас';
$labels['schedule_now'] = 'Расписание сейчас';
$labels['cancel_sending'] = 'Отменить отправку';
$labels['setting_countdown'] = 'Обратный отсчет времени до отправки сообщений';
$labels['disable_countdown'] = 'Отключить';
$labels['3_seconds'] = '3 секунды';
$labels['5_seconds'] = '5 секунд';
$labels['10_seconds'] = '10 секунд';
$labels['15_seconds'] = '15 секунд';

$labels['cannot_schedule_message'] = 'Невозможно запланировать сообщение:';
$labels['time_has_already_passed'] = 'Запланированное время уже прошло.';
$labels['invalid_time_format'] = 'Неверный формат времени.';
$labels['draft_folder_not_specified'] = 'Ошибка плагина расписания электронной почты: Не указана папка черновиков.';
$labels['error'] = 'Ошибка:';
$labels['attachment_tool_large'] = 'Конфигурация сервера ограничивает размер вложений запланированных сообщений $size.';
$labels['message_already_scheduled'] = 'Это сообщение уже запланировано.';

