<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'آخر تسجيل دخول';
$labels['setting_show_xlast_login'] = 'إظهار آخر تسجيل دخول';
$labels['country'] = 'البلد';
$labels['city'] = 'المدينة';
$labels['location'] = 'الموقع';
$labels['time'] = 'الوقت';
$labels['map'] = 'الخريطة';
$labels['more_data'] = 'المزيد من البيانات';
$labels['whats_this'] = 'ما هذا؟';
$labels['explanation'] = 'يعرض هذا المربع موقع آخر تسجيل دخول لحساب بريدك الإلكتروني. إذا لم تتعرف على هذا الموقع، فقد يكون مستخدم خبيث قد حصل على كلمة المرور الخاصة بك. يجب عليك تغيير كلمة المرور الخاصة بك على الفور إذا حدث ذلك.';
$labels['no_info'] = 'لا توجد معلومات آخر تسجيل دخول لعرضها. ستصبح المعلومات متاحة في المرة التالية التي تقوم فيها بتسجيل الدخول إلى بريد الويب الخاص بك.';
