<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Última conexión';
$labels['setting_show_xlast_login'] = 'Mostrar último inicio de sesión';
$labels['country'] = 'País';
$labels['city'] = 'Ciudad';
$labels['location'] = 'Ubicación';
$labels['time'] = 'Tiempo';
$labels['map'] = 'Mapa';
$labels['more_data'] = 'Más datos';
$labels['whats_this'] = '¿Qué es esto?';
$labels['explanation'] = 'Este cuadro muestra la ubicación del último inicio de sesión en su cuenta de correo electrónico. Si no reconoces esta ubicación, es posible que un usuario malintencionado tenga tu contraseña. Deberías cambiar tu contraseña inmediatamente si esto ocurre.';
$labels['no_info'] = 'No hay información sobre el último inicio de sesión que mostrar. La información estará disponible la próxima vez que inicie sesión en su webmail.';
