<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Viimane sisselogimine';
$labels['setting_show_xlast_login'] = 'Näita viimast sisselogimist';
$labels['country'] = 'Riik';
$labels['city'] = 'Linn';
$labels['location'] = 'Asukoht';
$labels['time'] = 'Aeg';
$labels['map'] = 'Kaart';
$labels['more_data'] = 'Rohkem andmeid';
$labels['whats_this'] = 'Mis see on?';
$labels['explanation'] = 'See kast näitab teie e-posti kontole viimase sisselogimise kohta. Kui te ei tunne seda asukohta ära, võib teie parool olla pahatahtlikul kasutajal. Kui see juhtub, peaksite oma salasõna viivitamatult muutma.';
$labels['no_info'] = 'Viimase sisselogimise andmeid ei kuvata. Teave muutub kättesaadavaks järgmisel korral, kui logite oma veebipostile sisse.';
