<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Login Terakhir';
$labels['setting_show_xlast_login'] = 'Tampilkan Login Terakhir';
$labels['country'] = 'Negara';
$labels['city'] = 'Kota';
$labels['location'] = 'Lokasi';
$labels['time'] = 'Waktu';
$labels['map'] = 'Peta';
$labels['more_data'] = 'Lebih banyak data';
$labels['whats_this'] = 'Apa ini?';
$labels['explanation'] = 'Kotak ini menunjukkan lokasi login terakhir ke akun email Anda. Jika Anda tidak mengenali lokasi ini, pengguna jahat mungkin memiliki kata sandi Anda. Anda harus segera mengubah kata sandi Anda jika hal ini terjadi.';
$labels['no_info'] = 'Tidak ada informasi login terakhir yang ditampilkan. Informasi ini akan tersedia saat Anda masuk ke webmail.';
