<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Paskutinis prisijungimas';
$labels['setting_show_xlast_login'] = 'Rodyti paskutinį prisijungimą';
$labels['country'] = 'Šalis';
$labels['city'] = 'Miestas';
$labels['location'] = 'Vieta';
$labels['time'] = 'Laikas';
$labels['map'] = 'Žemėlapis';
$labels['more_data'] = 'Daugiau duomenų';
$labels['whats_this'] = 'Kas tai?';
$labels['explanation'] = 'Šiame lange rodoma paskutinio prisijungimo prie el. pašto paskyros vieta. Jei šios vietos neatpažįstate, jūsų slaptažodį gali turėti piktavalis naudotojas. Tokiu atveju turėtumėte nedelsdami pakeisti slaptažodį.';
$labels['no_info'] = 'Paskutinio prisijungimo informacijos rodyti nereikia. Ši informacija bus pateikta kitą kartą, kai prisijungsite prie savo internetinio pašto.';
