<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Siste pålogging';
$labels['setting_show_xlast_login'] = 'Vis siste pålogging';
$labels['country'] = 'Land';
$labels['city'] = 'By';
$labels['location'] = 'Beliggenhet';
$labels['time'] = 'Tid';
$labels['map'] = 'Kart';
$labels['more_data'] = 'Mer data';
$labels['whats_this'] = 'Hva er dette?';
$labels['explanation'] = 'Denne boksen viser hvor du sist logget inn på e-postkontoen din. Hvis du ikke gjenkjenner denne plasseringen, kan en ondsinnet bruker ha passordet ditt. Du bør endre passordet ditt umiddelbart hvis dette skjer.';
$labels['no_info'] = 'Det er ingen siste påloggingsinformasjon å vise. Informasjonen blir tilgjengelig neste gang du logger deg på webmailen din.';
