<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Laatste aanmelding';
$labels['setting_show_xlast_login'] = 'Toon laatste aanmelding';
$labels['country'] = 'Land';
$labels['city'] = 'Stad';
$labels['location'] = 'Locatie';
$labels['time'] = 'Tijd';
$labels['map'] = 'Kaart';
$labels['more_data'] = 'Meer gegevens';
$labels['whats_this'] = 'Wat is dit?';
$labels['explanation'] = 'Dit vak toont de locatie van de laatste aanmelding bij uw e-mailaccount. Als u deze locatie niet herkent, kan een kwaadwillende gebruiker uw wachtwoord hebben. U moet uw wachtwoord onmiddellijk wijzigen als dit gebeurt.';
$labels['no_info'] = 'Er is geen informatie over de laatste aanmelding om weer te geven. De informatie komt beschikbaar wanneer u de volgende keer inlogt op uw webmail.';
