<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Posledné prihlásenie';
$labels['setting_show_xlast_login'] = 'Zobraziť posledné prihlásenie';
$labels['country'] = 'Krajina';
$labels['city'] = 'Mesto';
$labels['location'] = 'Umiestnenie';
$labels['time'] = 'Čas';
$labels['map'] = 'Mapa';
$labels['more_data'] = 'Viac údajov';
$labels['whats_this'] = 'Čo je to?';
$labels['explanation'] = 'V tomto poli sa zobrazuje miesto posledného prihlásenia do vášho e-mailového konta. Ak toto umiestnenie nerozpoznáte, vaše heslo môže mať k dispozícii škodlivý používateľ. V takom prípade by ste si mali heslo okamžite zmeniť.';
$labels['no_info'] = 'Nezobrazujú sa žiadne informácie o poslednom prihlásení. Tieto informácie budú k dispozícii pri ďalšom prihlásení do webovej pošty.';
