<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Son Giriş';
$labels['setting_show_xlast_login'] = 'Son Girişi Göster';
$labels['country'] = 'Ülke';
$labels['city'] = 'Şehir';
$labels['location'] = 'Konum';
$labels['time'] = 'Zaman';
$labels['map'] = 'Harita';
$labels['more_data'] = 'Daha fazla veri';
$labels['whats_this'] = 'Bu da ne?';
$labels['explanation'] = 'Bu kutu, e-posta hesabınıza en son giriş yaptığınız konumu gösterir. Bu konumu tanımıyorsanız, kötü niyetli bir kullanıcı şifrenizi ele geçirmiş olabilir. Böyle bir durumda parolanızı hemen değiştirmelisiniz.';
$labels['no_info'] = 'Görüntülenecek son oturum açma bilgisi yoktur. Bilgiler, web postanızda bir sonraki oturum açışınızda kullanılabilir hale gelecektir.';
