<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = '最后登录';
$labels['setting_show_xlast_login'] = '显示上次登录';
$labels['country'] = '国家';
$labels['city'] = '城市';
$labels['location'] = '地点';
$labels['time'] = '时间';
$labels['map'] = '地图';
$labels['more_data'] = '更多数据';
$labels['whats_this'] = '这是什么？';
$labels['explanation'] = '此框显示上次登录电子邮件帐户的位置。如果您无法识别该位置，则您的密码可能被恶意用户盗用。如果出现这种情况，应立即更改密码。';
$labels['no_info'] = '不显示上次登录信息。下次登录网络邮件时，就会显示该信息。';
