<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Tapete';
$labels['setting_compact'] = 'Kompakte Meldungsliste anzeigen';
$labels['with_vertical_preview'] = 'mit vertikaler Vorschau';
$labels['setting_compose_plain_font_size'] = 'Standard-Schriftgröße einer reinen Textnachricht';
$labels['background'] = 'Hintergrund';
$labels['setting_image'] = 'Hintergrundbild';
$labels['setting_image_opacity'] = 'Opazität des Bildes';
$labels['setting_content_opacity'] = 'Deckkraft der Inhaltsbox';
$labels['more_background_options'] = 'Mehr Hintergrundoptionen...';
$labels['upload_image'] = 'Bild hochladen';
$labels['upload_background_image'] = 'Hintergrundbild hochladen';
$labels['setting_placement'] = 'Bildplatzierung';
$labels['tile'] = 'Fliese';
$labels['cover'] = 'Abdeckung';
$labels['setting_text_color'] = 'Textfarbe';
$labels['auto'] = 'Automatisch';
$labels['light'] = 'Helles';
$labels['dark'] = 'Dunkelheit';
$labels['none'] = 'Keine';
$labels['setting_blur'] = 'Unschärfe im Bild';
$labels['setting_gray'] = 'In Grau umwandeln';
$labels['placement_help'] = 'Gibt an, ob das Bild gekachelt (wiederholt) werden oder den gesamten Hintergrund bedecken soll.';
$labels['text_color_help'] = 'Gibt an, ob die Farbe des Textes, der direkt auf dem Hintergrundbild angezeigt wird, dunkel oder hell sein soll.';
