<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Bakgrunn';
$labels['setting_compact'] = 'Vis kompakt meldingsliste';
$labels['with_vertical_preview'] = 'med vertikal forhåndsvisning';
$labels['setting_compose_plain_font_size'] = 'Standard skriftstørrelse for ren tekstmelding';
$labels['background'] = 'Bakgrunn';
$labels['setting_image'] = 'Bakgrunnsbilde';
$labels['setting_image_opacity'] = 'Bildets opasitet';
$labels['setting_content_opacity'] = 'Innholdsboksens ugjennomsiktighet';
$labels['more_background_options'] = 'Flere bakgrunnsalternativer...';
$labels['upload_image'] = 'Last opp bilde';
$labels['upload_background_image'] = 'Last opp bakgrunnsbilde';
$labels['setting_placement'] = 'Plassering av bilder';
$labels['tile'] = 'Fliser';
$labels['cover'] = 'Dekning';
$labels['setting_text_color'] = 'Tekstfarge';
$labels['auto'] = 'Automatisk';
$labels['light'] = 'Lys';
$labels['dark'] = 'Mørk';
$labels['none'] = 'Ingen';
$labels['setting_blur'] = 'Bilde uskarphet';
$labels['setting_gray'] = 'Konverter til grå';
$labels['placement_help'] = 'Angir om bildet skal flislegges (gjentas) eller dekke hele bakgrunnen.';
$labels['text_color_help'] = 'Angir om fargen på teksten som vises direkte på bakgrunnsbildet skal være mørk eller lys.';
