<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Duvar Kağıdı';
$labels['setting_compact'] = 'Kompakt mesaj listesini görüntüleme';
$labels['with_vertical_preview'] = 'dikey önizleme ile';
$labels['setting_compose_plain_font_size'] = 'Düz metin mesajının varsayılan yazı tipi boyutu';
$labels['background'] = 'Arka plan';
$labels['setting_image'] = 'Arka plan görüntüsü';
$labels['setting_image_opacity'] = 'Görüntü opaklığı';
$labels['setting_content_opacity'] = 'İçerik kutusu opaklığı';
$labels['more_background_options'] = 'Daha fazla arka plan seçeneği...';
$labels['upload_image'] = 'Resim yükle';
$labels['upload_background_image'] = 'Arka plan resmi yükleme';
$labels['setting_placement'] = 'Resim yerleştirme';
$labels['tile'] = 'Çini';
$labels['cover'] = 'Kapak';
$labels['setting_text_color'] = 'Metin rengi';
$labels['auto'] = 'Otomatik';
$labels['light'] = 'Parlak';
$labels['dark'] = 'Karanlık';
$labels['none'] = 'Hiçbiri';
$labels['setting_blur'] = 'Görüntü bulanıklığı';
$labels['setting_gray'] = 'Griye dönüştür';
$labels['placement_help'] = 'Görüntünün döşenip döşenmeyeceğini (tekrarlanıp tekrarlanmayacağını) veya tüm arka planı kaplayıp kaplamayacağını belirtir.';
$labels['text_color_help'] = 'Doğrudan arka plan görüntüsü üzerinde gösterilen metnin renginin koyu mu yoksa açık mı olması gerektiğini belirtir.';
