<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '壁紙';
$labels['setting_compact'] = '顯示精簡訊息清單';
$labels['with_vertical_preview'] = '具有垂直預覽';
$labels['setting_compose_plain_font_size'] = '純文字訊息的預設字型大小';
$labels['background'] = '背景資料';
$labels['setting_image'] = '背景圖片';
$labels['setting_image_opacity'] = '影像不透明度';
$labels['setting_content_opacity'] = '內容方塊不透明度';
$labels['more_background_options'] = '更多背景選項...';
$labels['upload_image'] = '上傳圖片';
$labels['upload_background_image'] = '上傳背景圖片';
$labels['setting_placement'] = '圖片放置';
$labels['tile'] = '磁磚';
$labels['cover'] = '封面';
$labels['setting_text_color'] = '文字顏色';
$labels['auto'] = '自動';
$labels['light'] = '明亮';
$labels['dark'] = '黑暗';
$labels['none'] = '無';
$labels['setting_blur'] = '影像模糊';
$labels['setting_gray'] = '轉換為灰色';
$labels['placement_help'] = '指定圖片應該平鋪（重複）還是覆蓋整個背景。';
$labels['text_color_help'] = '指定背景圖片上直接顯示的文字顏色應為深色或淺色。';
