<?php
/**
 * Roundcube Plus AI plugin.
 *
 * Copyright 2023, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'AIアシスタント';
$labels['ai_assistant'] = 'AIアシスタント';
$labels['ai_assistant_settings'] = 'AIアシスタントの設定';

// compose page
$labels['compose_dialog_button_text'] = 'AI';
$labels['compose_dialog_button_title'] = 'AIでメッセージを書く';

$labels['compose_label_to'] = '受取人名';
$labels['compose_label_from'] = '送信者名';
$labels['compose_label_style'] = 'スタイル';
$labels['compose_label_length'] = '長さ';
$labels['compose_label_language'] = '言語';
$labels['compose_label_creativity'] = '創造性';
$labels['compose_label_instructions'] = '使用方法';
$labels['compose_no_change'] = '変更なし';
$labels['compose_instructions_placeholder'] = '例：来週の予約を変更してもらう';

$labels['compose_style_assertive'] = 'アサーティブ';
$labels['compose_style_casual'] = 'カジュアル';
$labels['compose_style_enthusiastic'] = '熱狂的';
$labels['compose_style_funny'] = '面白い';
$labels['compose_style_informational'] = '情報提供';
$labels['compose_style_professional'] = 'プロフェッショナル';
$labels['compose_style_urgent'] = '緊急';
$labels['compose_style_witty'] = 'ウィットに富んだ';

$labels['compose_length_short'] = 'ショート';
$labels['compose_length_medium'] = 'ミディアム';
$labels['compose_length_long'] = 'ロング';

$labels['compose_creativity_low'] = '低い';
$labels['compose_creativity_medium'] = 'ミディアム';
$labels['compose_creativity_high'] = '高い';

$labels['compose_insert_email'] = 'Eメール';
$labels['compose_generate_email'] = '電子メールの作成';
$labels['compose_generate_again'] = '再び生成する';
$labels['compose_stop_generating'] = '発電停止';
$labels['compose_error_help_button'] = 'ヘルプ';

$labels['compose_no_instructions'] = '指示を入力する。';
$labels['compose_instructions_too_long'] = 'あなたの指示は長すぎます。';
$labels['compose_empty_response'] = 'サーバーは空の応答を返した。';

$labels['compose_tip_to'] = '新しいメールの受信者の名前。複数の名前を指定することも、"everybody"、"team "などの文字列を使用することもできます。';
$labels['compose_tip_from'] = '新しいメールはこの名前で署名されます。';
$labels['compose_tip_style'] = '新しいEメールに望ましい書き方。';
$labels['compose_tip_length'] = '新しいEメールの長さ。';
$labels['compose_tip_language'] = '新しいEメールを記述する言語。変更なし」を指定すると、指示された言語で書かれます。';
$labels['compose_tip_creativity'] = 'クリエイティビティが高ければ高いほど、予測不可能で多様性のあるメールが作成され、クリエイティビティが低ければ低いほど、事実に忠実で要領を得たメールが作成される。';
$labels['compose_tip_instructions'] = '新しいEメールに記載する内容を説明します。例文を見るには、指示例ボタンをクリックしてください。';

$labels['compose_help_button_show'] = '指導例';
$labels['compose_help_button_hide'] = 'バック';
$labels['compose_help_title'] = 'ヘルプと例';
$labels['compose_help_info'] = '書きたいメールについてAIに伝える。名前、日付、場所、理由など、具体的に書いてください。クリエイティブなアイデアや説明を求めることもできます。メールが作成されたら、それを微調整してメール作成ページに挿入します。以下にいくつかの指示例を示しますので、参考にしてください：';

$labels['compose_help_example_1'] = 'こんにちは';
$labels['compose_help_example_2'] = '本日の会議は中止となりました';
$labels['compose_help_example_3'] = '水曜日の午後3時にマーギーとのミーティングを設定し、マーケティング・キャンペーンにAIを活用する利点についてプレゼンを準備し、彼女を説得した。';
$labels['compose_help_example_4'] = 'AIによって生成されたコンテンツのサポートを追加することにしました。';
$labels['compose_help_example_5'] = '先週の仕事のフォローアップ、明日必要なんだ。';
$labels['compose_help_example_6'] = '私は1年以上昇給がなかった。';
$labels['compose_help_example_7'] = '明日、報告書を提出するように。さもないと、チームはストレスを感じているマーギーに迷惑がかかる。';
$labels['compose_help_example_8'] = '火曜日まで全品20％割引のお知らせ。';
$labels['compose_help_example_9'] = '今週末のケビンの誕生日に集まるよう、ローラに手紙を書くよう頼む。';
$labels['compose_help_example_10'] = '新しいウェブサイトの進捗状況について尋ね、トップページ用のマーケティング・スローガンのアイデアを5つ盛り込む。';
$labels['compose_help_example_11'] = '私たちが追加した新しいvpn機能についてのニュースレター：ワイヤガードプロトコル、ポートフォワーディング、キルスイッチ、専用IP。';
$labels['compose_help_example_12'] = '新しいロイヤリティ・プログラムについてのニュースレター。';
$labels['compose_help_example_13'] = '尊敬する人、プロとしてつながりたい人へのネットワーキング・メール';
$labels['compose_help_example_14'] = '昨日はプロフェッショナルなプロジェクトでお世話になりました。';
$labels['compose_help_example_15'] = '投資家への効果的な売り込みメールを作成するための戦略を10個思いついた。';
$labels['compose_help_example_16'] = '契約に従って1ヶ月前に通知するプロフェッショナルな退職メール。';
$labels['compose_help_example_17'] = '昇進を要請するメールを強要し、もし昇進できなかったら辞職するかもしれないとほのめかす。';
$labels['compose_help_example_18'] = '昨日のカンファレンスでお会いできてよかったです。';

$labels['compose_help_use_example'] = '（これを使って）';

// summaries
$labels['creating_summary'] = '要約の作成...';
$labels['show_summary'] = '要約を表示';
$labels['hide_summary'] = '要約を隠す';
$labels['recreate_summary'] = '要約の再作成';
$labels['email_has_no_text'] = 'このメールには本文はありません。';

// settings
$labels['setting_compose_style'] = 'スタイル';
$labels['setting_compose_length'] = '長さ';
$labels['setting_compose_language'] = '言語';
$labels['setting_compose_creativity'] = '創造性';
$labels['setting_language'] = '言語';

$labels['summarizing_messages'] = 'メッセージの要約';
$labels['setting_show_summary_on_mail_view'] = 'メール閲覧時にAIサマリーを表示';
$labels['setting_show_summary_on_list_hover'] = 'メールリストにカーソルを合わせるとAIのサマリーが表示されます。';
$labels['setting_list_summary_placement'] = 'リスト要約ポップアップの配置';

$labels['above'] = '上記';
$labels['below'] = '以下';
$labels['left'] = '左';
$labels['right'] = '右';

$labels['ai_disclaimer'] = 'AIの出力は時に不完全であったり、正しくない場合があります。必要な情報は常に再確認してください。';

// errors
$labels['api_error'] = 'AIサーバーへの接続中にエラーが発生しました。管理者に連絡してください。';
