<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Тапети';
$labels['setting_compact'] = 'Показване на компактен списък със съобщения';
$labels['with_vertical_preview'] = 'с вертикален преглед';
$labels['setting_compose_plain_font_size'] = 'Размер на шрифта по подразбиране на обикновеното текстово съобщение';
$labels['background'] = 'Фон';
$labels['setting_image'] = 'Фоново изображение';
$labels['setting_image_opacity'] = 'Непрозрачност на изображението';
$labels['setting_content_opacity'] = 'Непрозрачност на полето за съдържание';
$labels['more_background_options'] = 'Още опции за фон...';
$labels['upload_image'] = 'Качване на изображение';
$labels['upload_background_image'] = 'Качване на фоново изображение';
$labels['setting_placement'] = 'Поставяне на изображения';
$labels['tile'] = 'Плочки';
$labels['cover'] = 'Корица';
$labels['setting_text_color'] = 'Цвят на текста';
$labels['auto'] = 'Автоматичен';
$labels['light'] = 'Bright';
$labels['dark'] = 'Dark';
$labels['none'] = 'Няма';
$labels['setting_blur'] = 'Размазване на изображението';
$labels['setting_gray'] = 'Превръщане в сив';
$labels['placement_help'] = 'Указва дали изображението трябва да бъде на плочки (да се повтаря) или да покрива целия фон.';
$labels['text_color_help'] = 'Указва дали цветът на текста, показан директно върху фоновото изображение, да бъде тъмен или светъл.';
