<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Wallpaper';
$labels['setting_compact'] = 'Display compact message list';
$labels['with_vertical_preview'] = 'with vertical preview';
$labels['setting_compose_plain_font_size'] = 'Default font size of plain text message';
$labels['background'] = 'Background';
$labels['setting_image'] = 'Background image';
$labels['setting_image_opacity'] = 'Image opacity';
$labels['setting_content_opacity'] = 'Content box opacity';
$labels['more_background_options'] = 'More background options...';
$labels['upload_image'] = 'Upload image';
$labels['upload_background_image'] = 'Upload background image';
$labels['setting_placement'] = 'Image placement';
$labels['tile'] = 'Tile';
$labels['cover'] = 'Cover';
$labels['setting_text_color'] = 'Text color';
$labels['auto'] = 'Automatic';
$labels['light'] = 'Bright';
$labels['dark'] = 'Dark';
$labels['none'] = 'None';
$labels['setting_blur'] = 'Image blur';
$labels['setting_gray'] = 'Convert to gray';
$labels['placement_help'] = 'Specifies whether the image should be tiled (repeated) or cover the entire background.';
$labels['text_color_help'] = 'Specifies whether the color of the text shown directly on the background image should be dark or light.';
