<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Taustakuva';
$labels['setting_compact'] = 'Näytä kompakti viestiluettelo';
$labels['with_vertical_preview'] = 'pystysuoralla esikatselulla';
$labels['setting_compose_plain_font_size'] = 'Tavallisen tekstiviestin oletuskirjasinkoko';
$labels['background'] = 'Tausta';
$labels['setting_image'] = 'Taustakuva';
$labels['setting_image_opacity'] = 'Kuvan läpinäkymättömyys';
$labels['setting_content_opacity'] = 'Sisältölaatikon läpinäkymättömyys';
$labels['more_background_options'] = 'Lisää taustavaihtoehtoja...';
$labels['upload_image'] = 'Lataa kuva';
$labels['upload_background_image'] = 'Lataa taustakuva';
$labels['setting_placement'] = 'Kuvan sijoittelu';
$labels['tile'] = 'Laatta';
$labels['cover'] = 'Kansi';
$labels['setting_text_color'] = 'Tekstin väri';
$labels['auto'] = 'Automaattinen';
$labels['light'] = 'Kirkas';
$labels['dark'] = 'Tumma';
$labels['none'] = 'Ei ole';
$labels['setting_blur'] = 'Kuvan epätarkkuus';
$labels['setting_gray'] = 'Muunna harmaaksi';
$labels['placement_help'] = 'Määrittää, tuleeko kuva laatoittaa (toistaa) vai peittääkö se koko taustan.';
$labels['text_color_help'] = 'Määrittää, onko suoraan taustakuvassa näkyvän tekstin värin oltava tumma vai vaalea.';
