<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Wallpaper';
$labels['setting_compact'] = 'Menampilkan daftar pesan ringkas';
$labels['with_vertical_preview'] = 'dengan pratinjau vertikal';
$labels['setting_compose_plain_font_size'] = 'Ukuran font default untuk pesan teks biasa';
$labels['background'] = 'Latar Belakang';
$labels['setting_image'] = 'Gambar latar belakang';
$labels['setting_image_opacity'] = 'Keburaman gambar';
$labels['setting_content_opacity'] = 'Opacity kotak konten';
$labels['more_background_options'] = 'Opsi latar belakang lainnya...';
$labels['upload_image'] = 'Unggah gambar';
$labels['upload_background_image'] = 'Unggah gambar latar belakang';
$labels['setting_placement'] = 'Penempatan gambar';
$labels['tile'] = 'Ubin';
$labels['cover'] = 'Penutup';
$labels['setting_text_color'] = 'Warna teks';
$labels['auto'] = 'Otomatis';
$labels['light'] = 'Terang';
$labels['dark'] = 'Gelap';
$labels['none'] = 'Tidak ada';
$labels['setting_blur'] = 'Gambar buram';
$labels['setting_gray'] = 'Ubah menjadi abu-abu';
$labels['placement_help'] = 'Menentukan apakah gambar akan diubin (diulang) atau menutupi seluruh latar belakang.';
$labels['text_color_help'] = 'Menentukan apakah warna teks yang ditampilkan secara langsung pada gambar latar belakang harus gelap atau terang.';
