<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Behang';
$labels['setting_compact'] = 'Weergave compacte berichtenlijst';
$labels['with_vertical_preview'] = 'met verticale preview';
$labels['setting_compose_plain_font_size'] = 'Standaard lettergrootte van bericht in platte tekst';
$labels['background'] = 'Achtergrond';
$labels['setting_image'] = 'Achtergrondbeeld';
$labels['setting_image_opacity'] = 'Beeldopaciteit';
$labels['setting_content_opacity'] = 'Opaciteit inhoudsvak';
$labels['more_background_options'] = 'Meer achtergrond opties...';
$labels['upload_image'] = 'Afbeelding uploaden';
$labels['upload_background_image'] = 'Upload achtergrondafbeelding';
$labels['setting_placement'] = 'Afbeelding plaatsing';
$labels['tile'] = 'Tegel';
$labels['cover'] = 'Dekking';
$labels['setting_text_color'] = 'Tekstkleur';
$labels['auto'] = 'Automatisch';
$labels['light'] = 'Helder';
$labels['dark'] = 'Donker';
$labels['none'] = 'Geen';
$labels['setting_blur'] = 'Beeldvervaging';
$labels['setting_gray'] = 'Omzetten naar grijs';
$labels['placement_help'] = 'Geeft aan of de afbeelding moet worden getegeld (herhaald) of de hele achtergrond moet bedekken.';
$labels['text_color_help'] = 'Geeft aan of de kleur van de tekst die direct op de achtergrondafbeelding staat donker of licht moet zijn.';
