<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Tapety';
$labels['setting_compact'] = 'Zobrazenie kompaktného zoznamu správ';
$labels['with_vertical_preview'] = 's vertikálnym náhľadom';
$labels['setting_compose_plain_font_size'] = 'Predvolená veľkosť písma jednoduchej textovej správy';
$labels['background'] = 'Pozadie';
$labels['setting_image'] = 'Obrázok na pozadí';
$labels['setting_image_opacity'] = 'Nepriehľadnosť obrázka';
$labels['setting_content_opacity'] = 'Nepriehľadnosť poľa obsahu';
$labels['more_background_options'] = 'Ďalšie možnosti pozadia...';
$labels['upload_image'] = 'Nahrať obrázok';
$labels['upload_background_image'] = 'Nahratie obrázka na pozadí';
$labels['setting_placement'] = 'Umiestnenie obrázku';
$labels['tile'] = 'Dlaždice';
$labels['cover'] = 'Obal';
$labels['setting_text_color'] = 'Farba textu';
$labels['auto'] = 'Automatické';
$labels['light'] = 'Bright';
$labels['dark'] = 'Dark';
$labels['none'] = 'Žiadne';
$labels['setting_blur'] = 'Rozmazanie obrazu';
$labels['setting_gray'] = 'Previesť na sivú';
$labels['placement_help'] = 'Určuje, či má byť obrázok dlaždicový (opakovaný) alebo má pokrývať celé pozadie.';
$labels['text_color_help'] = 'Určuje, či má byť farba textu zobrazeného priamo na obrázku na pozadí tmavá alebo svetlá.';
