<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Шпалери';
$labels['setting_compact'] = 'Показати компактний перелік повідомлень';
$labels['with_vertical_preview'] = 'з вертикальним переглядом';
$labels['setting_compose_plain_font_size'] = 'Розмір шрифта для звичайного текстового повідомлення';
$labels['background'] = 'Фон';
$labels['setting_image'] = 'Фонове зображення';
$labels['setting_image_opacity'] = 'Прозорість зображення';
$labels['setting_content_opacity'] = 'Прозорість вікна контенту';
$labels['more_background_options'] = 'Додаткові параметри фону...';
$labels['upload_image'] = 'Завантажити зображення';
$labels['upload_background_image'] = 'Завантажити фонове зображення';
$labels['setting_placement'] = 'Розміщення зображень';
$labels['tile'] = 'Плитка';
$labels['cover'] = 'Обкладинка';
$labels['setting_text_color'] = 'Колір тексту';
$labels['auto'] = 'Автоматично';
$labels['light'] = 'Світлий';
$labels['dark'] = 'Темний';
$labels['none'] = 'Немає';
$labels['setting_blur'] = 'Розмиття зображення';
$labels['setting_gray'] = 'Перетворити на сірий';
$labels['placement_help'] = 'Визначте, малюнок має бути плиткою (повторюватися) або покривати весь фон.';
$labels['text_color_help'] = 'Визначає, колір тексту, що відображається безпосередньо на фоновому зображенні, повинен бути темним або світлим.';
