<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '壁纸';
$labels['setting_compact'] = '显示紧凑型信息列表';
$labels['with_vertical_preview'] = '带垂直预览';
$labels['setting_compose_plain_font_size'] = '纯文本信息的默认字体大小';
$labels['background'] = '背景介绍';
$labels['setting_image'] = '背景图片';
$labels['setting_image_opacity'] = '图像不透明度';
$labels['setting_content_opacity'] = '内容框不透明度';
$labels['more_background_options'] = '更多背景选项...';
$labels['upload_image'] = '上传图片';
$labels['upload_background_image'] = '上传背景图片';
$labels['setting_placement'] = '图片位置';
$labels['tile'] = '瓷砖';
$labels['cover'] = '封面';
$labels['setting_text_color'] = '文字颜色';
$labels['auto'] = '自动';
$labels['light'] = '明亮';
$labels['dark'] = '黑暗';
$labels['none'] = '无';
$labels['setting_blur'] = '图像模糊';
$labels['setting_gray'] = '转换为灰色';
$labels['placement_help'] = '指定图像是平铺（重复）还是覆盖整个背景。';
$labels['text_color_help'] = '指定直接显示在背景图片上的文字颜色是深色还是浅色。';
