<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'موجز الأخبار';
$labels['news_feed'] = 'موجز الأخبار';
$labels['preview'] = 'معاينة';
$labels['test_settings'] = 'اختبار إعدادات موجز الأخبار';
$labels['feed_error'] = 'لا يمكن تحميل موجز الأخبار.';
$labels['feed_error_url'] = 'خطأ: لا يمكن تحميل موجز الأخبار من عنوان URL المحدد.';
$labels['feed_error_content'] = 'خطأ: المحتوى الذي تم تحميله من عنوان URL المحدد فارغ.';
$labels['setting_show_xnews_feed'] = 'عرض موجز الأخبار';
$labels['setting_predefined'] = 'الخلاصات المحددة مسبقاً';
$labels['setting_title'] = 'العنوان';
$labels['setting_url'] = 'عنوان URL';
$labels['setting_count'] = 'عناصر للعرض';
