<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'News Feed';
$labels['news_feed'] = 'News Feed';
$labels['preview'] = 'Preview';
$labels['test_settings'] = 'Test news feed settings';
$labels['feed_error'] = 'Cannot load news feed.';
$labels['feed_error_url'] = 'Error: Cannot load news feed from the specified URL.';
$labels['feed_error_content'] = 'Error: Content loaded from the specified URL is empty.';
$labels['setting_show_xnews_feed'] = 'Show News Feed';
$labels['setting_predefined'] = 'Predefined feeds';
$labels['setting_title'] = 'Title';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Items to show';
