<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Uudised';
$labels['news_feed'] = 'Uudised';
$labels['preview'] = 'Eelvaade';
$labels['test_settings'] = 'Testi uudisvoo seaded';
$labels['feed_error'] = 'Ei saa laadida uudisvoogu.';
$labels['feed_error_url'] = 'Viga: Ei saa laadida uudisvoogu määratud URL-ilt.';
$labels['feed_error_content'] = 'Viga: Sisu, mis laaditakse määratud URL-ist, on tühi.';
$labels['setting_show_xnews_feed'] = 'Näita uudistevooge';
$labels['setting_predefined'] = 'Etteantud söötmine';
$labels['setting_title'] = 'Pealkiri';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Näidatavad esemed';
