<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '뉴스 피드';
$labels['news_feed'] = '뉴스 피드';
$labels['preview'] = '미리 보기';
$labels['test_settings'] = '뉴스피드 설정 테스트';
$labels['feed_error'] = '뉴스 피드를 로드할 수 없습니다.';
$labels['feed_error_url'] = '오류가 발생했습니다: 지정한 URL에서 뉴스 피드를 로드할 수 없습니다.';
$labels['feed_error_content'] = '오류가 발생했습니다: 지정한 URL에서 로드한 콘텐츠가 비어 있습니다.';
$labels['setting_show_xnews_feed'] = '뉴스피드 보기';
$labels['setting_predefined'] = '미리 정의된 피드';
$labels['setting_title'] = '제목';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = '표시할 항목';
