<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Nyheter';
$labels['news_feed'] = 'Nyheter';
$labels['preview'] = 'Forhåndsvisning';
$labels['test_settings'] = 'Test innstillinger for nyhetsfeed';
$labels['feed_error'] = 'Kan ikke laste inn nyhetsfeed.';
$labels['feed_error_url'] = 'Feil: Kan ikke laste inn nyhetsfeeden fra den angitte nettadressen.';
$labels['feed_error_content'] = 'Det oppstod en feil: Innhold lastet fra den angitte nettadressen er tomt.';
$labels['setting_show_xnews_feed'] = 'Vis nyhetsfeed';
$labels['setting_predefined'] = 'Forhåndsdefinerte feeder';
$labels['setting_title'] = 'Tittel';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Elementer som skal vises';
