<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Kanálik noviniek';
$labels['news_feed'] = 'Kanálik noviniek';
$labels['preview'] = 'Náhľad';
$labels['test_settings'] = 'Testovanie nastavení informačného kanála';
$labels['feed_error'] = 'Nie je možné načítať kanál správ.';
$labels['feed_error_url'] = 'Chyba: Nemožno načítať informačný kanál zo zadanej adresy URL.';
$labels['feed_error_content'] = 'Chyba: Obsah načítaný zo zadanej adresy URL je prázdny.';
$labels['setting_show_xnews_feed'] = 'Zobraziť kanál noviniek';
$labels['setting_predefined'] = 'Preddefinované kanály';
$labels['setting_title'] = 'Názov';
$labels['setting_url'] = 'ADRESA URL';
$labels['setting_count'] = 'Položky, ktoré sa majú zobraziť';
