<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Времето';
$labels['weather'] = 'Времето';
$labels['setting_show_xweather'] = 'Показване на времето';
$labels['description'] = 'Описание';
$labels['humidity'] = 'Влажност';
$labels['pressure'] = 'Налягане';
$labels['clouds'] = 'Облаци';
$labels['wind'] = 'Вятър';
$labels['sunrise'] = 'Изгревът на слънцето';
$labels['sunset'] = 'Залез';
$labels['more_data'] = 'Повече данни';
$labels['display'] = 'Дисплей';
$labels['options'] = 'Опции';
$labels['setting_location_type'] = 'Намерете местоположението чрез';
$labels['setting_country_code'] = 'Държава';
$labels['setting_city'] = 'Град';
$labels['setting_latitude'] = 'Географска ширина';
$labels['setting_longitude'] = 'Дължина';
$labels['setting_units'] = 'Единици';
$labels['setting_icons'] = 'Икони';
$labels['setting_show_description'] = 'Покажи описание';
$labels['setting_show_pressure'] = 'Показване на налягане';
$labels['setting_show_humidity'] = 'Показване на влажността';
$labels['setting_show_clouds'] = 'Показване на облаци';
$labels['setting_show_wind'] = 'Показване на вятъра';
$labels['setting_show_sunrise'] = 'Покажи изгрева на слънцето';
$labels['setting_show_sunset'] = 'Показване на залеза';
$labels['metric'] = 'Метричен';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Преглед на иконата';
$labels['icons_cutout'] = 'Изрезка';
$labels['icons_glossy'] = 'Гланциран';
$labels['icons_monochrome'] = 'Монохромен';
$labels['icons_moonlight'] = 'Лунна светлина';
$labels['icons_stickers'] = 'Стикери';
$labels['check_location'] = 'Проверете местоположението';
$labels['location_found'] = 'Намерено местоположение:';
$labels['location_not_found'] = 'Местоположението не е намерено.';
$labels['loading_error'] = 'При зареждането на метеорологичните данни е възникнала грешка. Моля, проверете настройките на страната и града в опциите.';
$labels['country_and_city'] = 'Държава и град';
$labels['coordinates'] = 'Координати';
$labels['coordinates_link'] = 'Намерете географската си ширина и дължина.';
