<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Vejret';
$labels['weather'] = 'Vejret';
$labels['setting_show_xweather'] = 'Vis vejret';
$labels['description'] = 'Beskrivelse';
$labels['humidity'] = 'Fugtighed';
$labels['pressure'] = 'Tryk';
$labels['clouds'] = 'Skyer';
$labels['wind'] = 'Vind';
$labels['sunrise'] = 'Solopgang';
$labels['sunset'] = 'Solnedgang';
$labels['more_data'] = 'Flere data';
$labels['display'] = 'Vis';
$labels['options'] = 'Indstillinger';
$labels['setting_location_type'] = 'Find placering ved at';
$labels['setting_country_code'] = 'Land';
$labels['setting_city'] = 'By';
$labels['setting_latitude'] = 'Breddegrad';
$labels['setting_longitude'] = 'Længdegrad';
$labels['setting_units'] = 'Enheder';
$labels['setting_icons'] = 'Ikoner';
$labels['setting_show_description'] = 'Vis beskrivelse';
$labels['setting_show_pressure'] = 'Vis tryk';
$labels['setting_show_humidity'] = 'Vis fugtighed';
$labels['setting_show_clouds'] = 'Vis skyer';
$labels['setting_show_wind'] = 'Vis vind';
$labels['setting_show_sunrise'] = 'Vis solopgang';
$labels['setting_show_sunset'] = 'Vis solnedgang';
$labels['metric'] = 'Metrisk';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Visning af ikon';
$labels['icons_cutout'] = 'Udskæring';
$labels['icons_glossy'] = 'Glansende';
$labels['icons_monochrome'] = 'Monokrom';
$labels['icons_moonlight'] = 'Måneskin';
$labels['icons_stickers'] = 'Klistermærker';
$labels['check_location'] = 'Tjek placering';
$labels['location_found'] = 'Findes på stedet:';
$labels['location_not_found'] = 'Placering ikke fundet.';
$labels['loading_error'] = 'Der opstod en fejl under indlæsning af vejrdata. Kontroller venligst indstillingerne for land og by i indstillingerne.';
$labels['country_and_city'] = 'Land og by';
$labels['coordinates'] = 'Koordinater';
$labels['coordinates_link'] = 'Find din bredde- og længdegrad.';
