<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Sää';
$labels['weather'] = 'Sää';
$labels['setting_show_xweather'] = 'Näytä sää';
$labels['description'] = 'Kuvaus';
$labels['humidity'] = 'Kosteus';
$labels['pressure'] = 'Paine';
$labels['clouds'] = 'Pilvet';
$labels['wind'] = 'Tuuli';
$labels['sunrise'] = 'Auringonnousu';
$labels['sunset'] = 'Auringonlasku';
$labels['more_data'] = 'Lisää tietoja';
$labels['display'] = 'Näyttö';
$labels['options'] = 'Vaihtoehdot';
$labels['setting_location_type'] = 'Etsi sijainti';
$labels['setting_country_code'] = 'Maa';
$labels['setting_city'] = 'Kaupunki';
$labels['setting_latitude'] = 'Leveysaste';
$labels['setting_longitude'] = 'Pituusaste';
$labels['setting_units'] = 'Yksiköt';
$labels['setting_icons'] = 'Kuvakkeet';
$labels['setting_show_description'] = 'Näytä kuvaus';
$labels['setting_show_pressure'] = 'Näytä paine';
$labels['setting_show_humidity'] = 'Näytä kosteus';
$labels['setting_show_clouds'] = 'Näytä pilvet';
$labels['setting_show_wind'] = 'Näytä tuuli';
$labels['setting_show_sunrise'] = 'Näytä auringonnousu';
$labels['setting_show_sunset'] = 'Näytä auringonlasku';
$labels['metric'] = 'Metrinen';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Kuvakkeen esikatselu';
$labels['icons_cutout'] = 'Leikkaus';
$labels['icons_glossy'] = 'Kiiltävä';
$labels['icons_monochrome'] = 'Yksivärinen';
$labels['icons_moonlight'] = 'Kuunvalo';
$labels['icons_stickers'] = 'Tarrat';
$labels['check_location'] = 'Tarkista sijainti';
$labels['location_found'] = 'Sijainti löydetty:';
$labels['location_not_found'] = 'Sijaintia ei löydy.';
$labels['loading_error'] = 'Säätietojen lataamisessa tapahtui virhe. Tarkista maa- ja kaupunkiasetukset asetuksista.';
$labels['country_and_city'] = 'Maa ja kaupunki';
$labels['coordinates'] = 'Koordinaatit';
$labels['coordinates_link'] = 'Etsi leveys- ja pituusasteesi.';
