<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Időjárás';
$labels['weather'] = 'Időjárás';
$labels['setting_show_xweather'] = 'Időjárás megjelenítése';
$labels['description'] = 'Leírás';
$labels['humidity'] = 'Páratartalom';
$labels['pressure'] = 'Nyomás';
$labels['clouds'] = 'Felhők';
$labels['wind'] = 'Szél';
$labels['sunrise'] = 'Napfelkelte';
$labels['sunset'] = 'Naplemente';
$labels['more_data'] = 'További adatok';
$labels['display'] = 'Megjelenítés';
$labels['options'] = 'Opciók';
$labels['setting_location_type'] = 'Helyszín keresése';
$labels['setting_country_code'] = 'Ország';
$labels['setting_city'] = 'Város';
$labels['setting_latitude'] = 'Szélesség';
$labels['setting_longitude'] = 'Hosszúság';
$labels['setting_units'] = 'Egységek';
$labels['setting_icons'] = 'Ikonok';
$labels['setting_show_description'] = 'Leírás megjelenítése';
$labels['setting_show_pressure'] = 'Nyomás megjelenítése';
$labels['setting_show_humidity'] = 'Páratartalom megjelenítése';
$labels['setting_show_clouds'] = 'Felhők megjelenítése';
$labels['setting_show_wind'] = 'Szél megjelenítése';
$labels['setting_show_sunrise'] = 'Mutasd a napfelkeltét';
$labels['setting_show_sunset'] = 'Mutasd a naplementét';
$labels['metric'] = 'Metrikus';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Ikon előnézet';
$labels['icons_cutout'] = 'Kivágás';
$labels['icons_glossy'] = 'Fényes';
$labels['icons_monochrome'] = 'Monokróm';
$labels['icons_moonlight'] = 'Holdfény';
$labels['icons_stickers'] = 'Matricák';
$labels['check_location'] = 'Helyszín ellenőrzése';
$labels['location_found'] = 'Megtalált helyszín:';
$labels['location_not_found'] = 'Nem talált hely.';
$labels['loading_error'] = 'Az időjárási adatok betöltése során hiba történt. Kérjük, ellenőrizze az ország és a város beállításait az opciókban.';
$labels['country_and_city'] = 'Ország és város';
$labels['coordinates'] = 'Koordináták';
$labels['coordinates_link'] = 'Keresse meg a szélességi és hosszúsági fokot.';
