<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '날씨';
$labels['weather'] = '날씨';
$labels['setting_show_xweather'] = '날씨 표시';
$labels['description'] = '설명';
$labels['humidity'] = '습도';
$labels['pressure'] = '압력';
$labels['clouds'] = '클라우드';
$labels['wind'] = '바람';
$labels['sunrise'] = '일출';
$labels['sunset'] = '일몰';
$labels['more_data'] = '더 많은 데이터';
$labels['display'] = '디스플레이';
$labels['options'] = '옵션';
$labels['setting_location_type'] = '위치 찾기';
$labels['setting_country_code'] = '국가';
$labels['setting_city'] = '도시';
$labels['setting_latitude'] = '위도';
$labels['setting_longitude'] = '경도';
$labels['setting_units'] = '단위';
$labels['setting_icons'] = '아이콘';
$labels['setting_show_description'] = '설명 표시';
$labels['setting_show_pressure'] = '압력 표시';
$labels['setting_show_humidity'] = '습도 표시';
$labels['setting_show_clouds'] = '클라우드 표시';
$labels['setting_show_wind'] = '바람 표시';
$labels['setting_show_sunrise'] = '일출 보기';
$labels['setting_show_sunset'] = '일몰 표시';
$labels['metric'] = 'Metric';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = '아이콘 미리보기';
$labels['icons_cutout'] = '컷아웃';
$labels['icons_glossy'] = '광택';
$labels['icons_monochrome'] = '단색';
$labels['icons_moonlight'] = '달빛';
$labels['icons_stickers'] = '스티커';
$labels['check_location'] = '위치 확인';
$labels['location_found'] = '위치를 찾았습니다:';
$labels['location_not_found'] = '위치를 찾을 수 없습니다.';
$labels['loading_error'] = '날씨 데이터를 로드하는 동안 오류가 발생했습니다. 옵션에서 국가 및 도시 설정을 확인하세요.';
$labels['country_and_city'] = '국가 및 도시';
$labels['coordinates'] = '좌표';
$labels['coordinates_link'] = '위도와 경도를 찾아보세요.';
