<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Погода';
$labels['weather'] = 'Погода';
$labels['setting_show_xweather'] = 'Показать погоду';
$labels['description'] = 'Описание';
$labels['humidity'] = 'Влажность';
$labels['pressure'] = 'Давление';
$labels['clouds'] = 'Облачность';
$labels['wind'] = 'Ветер';
$labels['sunrise'] = 'Восход';
$labels['sunset'] = 'Закат';
$labels['more_data'] = 'Больше данных';
$labels['display'] = 'Дисплей';
$labels['options'] = 'Опции';
$labels['setting_location_type'] = 'Найти местоположение по';
$labels['setting_country_code'] = 'Страна';
$labels['setting_city'] = 'Город';
$labels['setting_latitude'] = 'Широта';
$labels['setting_longitude'] = 'Долгота';
$labels['setting_units'] = 'Единицы';
$labels['setting_icons'] = 'Иконки';
$labels['setting_show_description'] = 'Показать описание';
$labels['setting_show_pressure'] = 'Показать давление';
$labels['setting_show_humidity'] = 'Показать влажность';
$labels['setting_show_clouds'] = 'Показать облачность';
$labels['setting_show_wind'] = 'Показать ветер';
$labels['setting_show_sunrise'] = 'Показать восход';
$labels['setting_show_sunset'] = 'Показать закат';
$labels['metric'] = 'Метрика';
$labels['imperial'] = 'Установленный';
$labels['icon_preview'] = 'Предварительный просмотр иконки';
$labels['icons_cutout'] = 'Выключит';
$labels['icons_glossy'] = 'Глянцевый';
$labels['icons_monochrome'] = 'Монохром';
$labels['icons_moonlight'] = 'Лунный свет';
$labels['icons_stickers'] = 'Стикеры';
$labels['check_location'] = 'Проверить местоположение';
$labels['location_found'] = 'Местонахождение найдено:';
$labels['location_not_found'] = 'Местоположение не найдено.';
$labels['loading_error'] = 'При загрузке данных о погоде произошла ошибка. Пожалуйста, проверьте настройки страны и города в опциях.';
$labels['country_and_city'] = 'Страна и город';
$labels['coordinates'] = 'Координаты';
$labels['coordinates_link'] = 'Найдите свою широту и долготу.';
