<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Anmeldung bei $p';
$labels['all_files'] = 'Alle Dateien';
$labels['shared_files'] = 'Gemeinsame Dateien';
$labels['select_files'] = 'Dateien auswählen';
$labels['save_file'] = 'Datei speichern:';
$labels['folder_empty'] = 'Dieser Ordner ist leer.';
$labels['no_shares'] = 'Es gibt keine gemeinsamen Dateien.';
$labels['cannot_find_directory'] = 'Verzeichnis kann nicht gefunden werden.';
$labels['cannot_connect_to_server'] = 'Es kann keine Verbindung zum Server hergestellt werden.';
$labels['cannot_save_attachment'] = 'Anhang kann nicht gespeichert werden.';
$labels['invalid_login_credentials'] = 'Ungültiger Benutzername oder Passwort.';
$labels['file_saved'] = 'Datei erfolgreich gespeichert.';
$labels['button_insert_link'] = 'Link einfügen';
$labels['incorrect_stored_credentials'] = 'Sie können sich nicht am Server anmelden, weil die gespeicherten Anmeldedaten falsch sind. Klicken Sie auf Abmelden und geben Sie einen neuen Benutzernamen und ein neues Passwort ein.';

// settings
$labels['setting_provider'] = 'Anbieter';
$labels['setting_auth'] = 'Art der Authentifizierung';
$labels['setting_url'] = 'WebDAV-URL';
$labels['setting_shared_url'] = 'WebDAV-freigegebene URL';
$labels['settings_shared_url_link'] = 'Aus WebDAV-URL erstellen';
$labels['specify_webdav_url'] = 'Um die gemeinsame URL zu erstellen, müssen Sie die WebDAV-URL angeben.';
