<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Login to $p'; // $p - provider name
$labels['all_files'] = 'All files';
$labels['shared_files'] = 'Shared files';
$labels['select_files'] = 'Select files';
$labels['save_file'] = 'Save file:';
$labels['folder_empty'] = 'This folder is empty.';
$labels['no_shares'] = 'There are no shared files.';
$labels['cannot_find_directory'] = 'Cannot find directory.';
$labels['cannot_connect_to_server'] = 'Cannot connect to the server.';
$labels['cannot_save_attachment'] = 'Cannot save attachment.';
$labels['invalid_login_credentials'] = 'Invalid username or password.';
$labels['file_saved'] = 'File saved successfully.';
$labels['button_insert_link'] = 'Insert link';
$labels['incorrect_stored_credentials'] = 'Cannot log in to the server because the stored login credentials are incorrect. Click Logout and enter a new username and password.';

// settings
$labels['setting_provider'] = 'Provider';
$labels['setting_auth'] = 'Authentication type';
$labels['setting_url'] = 'WebDAV URL';
$labels['setting_shared_url'] = 'WebDAV shared URL';
$labels['settings_shared_url_link'] = 'Create from WebDAV URL';
$labels['specify_webdav_url'] = 'In order to create the shared URL you must specify the WebDAV URL.';