<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Kirjaudu sisään $p';
$labels['all_files'] = 'Kaikki tiedostot';
$labels['shared_files'] = 'Jaetut tiedostot';
$labels['select_files'] = 'Valitse tiedostot';
$labels['save_file'] = 'Tallenna tiedosto:';
$labels['folder_empty'] = 'Tämä kansio on tyhjä.';
$labels['no_shares'] = 'Jaettuja tiedostoja ei ole.';
$labels['cannot_find_directory'] = 'Hakemistoa ei löydy.';
$labels['cannot_connect_to_server'] = 'Yhteyttä palvelimeen ei voida muodostaa.';
$labels['cannot_save_attachment'] = 'Liitetiedostoa ei voi tallentaa.';
$labels['invalid_login_credentials'] = 'Virheellinen käyttäjätunnus tai salasana.';
$labels['file_saved'] = 'Tiedosto tallennettu onnistuneesti.';
$labels['button_insert_link'] = 'Lisää linkki';
$labels['incorrect_stored_credentials'] = 'Palvelimeen ei voi kirjautua, koska tallennetut kirjautumistiedot ovat virheelliset. Valitse Kirjaudu ulos ja anna uusi käyttäjätunnus ja salasana.';

// settings
$labels['setting_provider'] = 'Palveluntarjoaja';
$labels['setting_auth'] = 'Todennustyyppi';
$labels['setting_url'] = 'WebDAV URL-osoite';
$labels['setting_shared_url'] = 'WebDAV jaettu URL-osoite';
$labels['settings_shared_url_link'] = 'Luo WebDAV URL-osoitteesta';
$labels['specify_webdav_url'] = 'Jaetun URL-osoitteen luomiseksi sinun on määritettävä WebDAV-osoite.';
