<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Bejelentkezés $p';
$labels['all_files'] = 'Minden fájl';
$labels['shared_files'] = 'Megosztott fájlok';
$labels['select_files'] = 'Fájlok kiválasztása';
$labels['save_file'] = 'Fájl mentése:';
$labels['folder_empty'] = 'Ez a mappa üres.';
$labels['no_shares'] = 'Nincsenek megosztott fájlok.';
$labels['cannot_find_directory'] = 'Nem találja a könyvtárat.';
$labels['cannot_connect_to_server'] = 'Nem tud csatlakozni a kiszolgálóhoz.';
$labels['cannot_save_attachment'] = 'Nem lehet menteni a mellékletet.';
$labels['invalid_login_credentials'] = 'Érvénytelen felhasználónév vagy jelszó.';
$labels['file_saved'] = 'A fájl sikeresen mentve.';
$labels['button_insert_link'] = 'Link beillesztése';
$labels['incorrect_stored_credentials'] = 'Nem lehet bejelentkezni a kiszolgálóra, mert a tárolt bejelentkezési adatok helytelenek. Kattintson a Kijelentkezés gombra, és adjon meg egy új felhasználónevet és jelszót.';

// settings
$labels['setting_provider'] = 'Szolgáltató';
$labels['setting_auth'] = 'Hitelesítési típus';
$labels['setting_url'] = 'WebDAV URL cím';
$labels['setting_shared_url'] = 'WebDAV megosztott URL';
$labels['settings_shared_url_link'] = 'Létrehozás WebDAV URL-címről';
$labels['specify_webdav_url'] = 'A megosztott URL létrehozásához meg kell adnia a WebDAV URL-címet.';
