<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Masuk ke $p';
$labels['all_files'] = 'Semua file';
$labels['shared_files'] = 'File bersama';
$labels['select_files'] = 'Memilih file';
$labels['save_file'] = 'Simpan file:';
$labels['folder_empty'] = 'Folder ini kosong.';
$labels['no_shares'] = 'Tidak ada file yang dibagikan.';
$labels['cannot_find_directory'] = 'Tidak dapat menemukan direktori.';
$labels['cannot_connect_to_server'] = 'Tidak dapat tersambung ke server.';
$labels['cannot_save_attachment'] = 'Tidak dapat menyimpan lampiran.';
$labels['invalid_login_credentials'] = 'Nama pengguna atau kata sandi tidak valid.';
$labels['file_saved'] = 'File berhasil disimpan.';
$labels['button_insert_link'] = 'Sisipkan tautan';
$labels['incorrect_stored_credentials'] = 'Tidak dapat masuk ke server karena kredensial masuk yang disimpan salah. Klik Logout dan masukkan nama pengguna dan kata sandi baru.';

// settings
$labels['setting_provider'] = 'Penyedia';
$labels['setting_auth'] = 'Jenis otentikasi';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'URL bersama WebDAV';
$labels['settings_shared_url_link'] = 'Buat dari URL WebDAV';
$labels['specify_webdav_url'] = 'Untuk membuat URL bersama, Anda harus menentukan URL WebDAV.';
