<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Accesso a $p';
$labels['all_files'] = 'Tutti i file';
$labels['shared_files'] = 'File condivisi';
$labels['select_files'] = 'Selezionare i file';
$labels['save_file'] = 'Salvare il file:';
$labels['folder_empty'] = 'Questa cartella è vuota.';
$labels['no_shares'] = 'Non ci sono file condivisi.';
$labels['cannot_find_directory'] = 'Impossibile trovare la directory.';
$labels['cannot_connect_to_server'] = 'Impossibile connettersi al server.';
$labels['cannot_save_attachment'] = 'Impossibile salvare l\'allegato.';
$labels['invalid_login_credentials'] = 'Nome utente o password non validi.';
$labels['file_saved'] = 'Il file è stato salvato con successo.';
$labels['button_insert_link'] = 'Inserire il link';
$labels['incorrect_stored_credentials'] = 'Non è possibile accedere al server perché le credenziali di accesso memorizzate non sono corrette. Fare clic su Logout e inserire un nuovo nome utente e una nuova password.';

// settings
$labels['setting_provider'] = 'Fornitore';
$labels['setting_auth'] = 'Tipo di autenticazione';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'URL condiviso WebDAV';
$labels['settings_shared_url_link'] = 'Creare da URL WebDAV';
$labels['specify_webdav_url'] = 'Per creare l\'URL condiviso è necessario specificare l\'URL WebDAV.';
