<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Inloggen op $p';
$labels['all_files'] = 'Alle bestanden';
$labels['shared_files'] = 'Gedeelde bestanden';
$labels['select_files'] = 'Bestanden selecteren';
$labels['save_file'] = 'Bestand opslaan:';
$labels['folder_empty'] = 'Deze map is leeg.';
$labels['no_shares'] = 'Er zijn geen gedeelde bestanden.';
$labels['cannot_find_directory'] = 'Kan directory niet vinden.';
$labels['cannot_connect_to_server'] = 'Kan geen verbinding maken met de server.';
$labels['cannot_save_attachment'] = 'Kan bijlage niet opslaan.';
$labels['invalid_login_credentials'] = 'Ongeldige gebruikersnaam of wachtwoord.';
$labels['file_saved'] = 'Bestand succesvol opgeslagen.';
$labels['button_insert_link'] = 'Link invoegen';
$labels['incorrect_stored_credentials'] = 'Kan niet inloggen op de server omdat de opgeslagen aanmeldingsgegevens onjuist zijn. Klik op Uitloggen en voer een nieuwe gebruikersnaam en wachtwoord in.';

// settings
$labels['setting_provider'] = 'Aanbieder';
$labels['setting_auth'] = 'Type verificatie';
$labels['setting_url'] = 'WebDAV URL';
$labels['setting_shared_url'] = 'WebDAV gedeelde URL';
$labels['settings_shared_url_link'] = 'Aanmaken vanuit WebDAV URL';
$labels['specify_webdav_url'] = 'Om de gedeelde URL aan te maken moet u de WebDAV URL opgeven.';
