<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Prijava v $p';
$labels['all_files'] = 'Vse datoteke';
$labels['shared_files'] = 'Datoteke v skupni rabi';
$labels['select_files'] = 'Izberite datoteke';
$labels['save_file'] = 'Shranite datoteko:';
$labels['folder_empty'] = 'Ta mapa je prazna.';
$labels['no_shares'] = 'Datotek v skupni rabi ni.';
$labels['cannot_find_directory'] = 'Ni mogoče najti imenika.';
$labels['cannot_connect_to_server'] = 'Ne morete se povezati s strežnikom.';
$labels['cannot_save_attachment'] = 'Priponke ni mogoče shraniti.';
$labels['invalid_login_credentials'] = 'Nepravilno uporabniško ime ali geslo.';
$labels['file_saved'] = 'Datoteka je bila uspešno shranjena.';
$labels['button_insert_link'] = 'Vstavite povezavo';
$labels['incorrect_stored_credentials'] = 'Ne morete se prijaviti v strežnik, ker so shranjeni prijavni podatki nepravilni. Kliknite Odjava ter vnesite novo uporabniško ime in geslo.';

// settings
$labels['setting_provider'] = 'Ponudnik';
$labels['setting_auth'] = 'Vrsta avtentikacije';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'URL v skupni rabi WebDAV';
$labels['settings_shared_url_link'] = 'Ustvarjanje iz naslova URL WebDAV';
$labels['specify_webdav_url'] = 'Če želite ustvariti skupni URL, morate določiti URL WebDAV.';
