<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = '登录 $p';
$labels['all_files'] = '所有文件';
$labels['shared_files'] = '共享文件';
$labels['select_files'] = '选择文件';
$labels['save_file'] = '保存文件：';
$labels['folder_empty'] = '该文件夹为空。';
$labels['no_shares'] = '没有共享文件。';
$labels['cannot_find_directory'] = '无法找到目录。';
$labels['cannot_connect_to_server'] = '无法连接服务器。';
$labels['cannot_save_attachment'] = '无法保存附件。';
$labels['invalid_login_credentials'] = '用户名或密码无效。';
$labels['file_saved'] = '文件已成功保存。';
$labels['button_insert_link'] = '插入链接';
$labels['incorrect_stored_credentials'] = '由于存储的登录凭证不正确，因此无法登录服务器。单击注销并输入新的用户名和密码。';

// settings
$labels['setting_provider'] = '提供商';
$labels['setting_auth'] = '验证类型';
$labels['setting_url'] = 'WebDAV URL';
$labels['setting_shared_url'] = 'WebDAV 共享 URL';
$labels['settings_shared_url_link'] = '从 WebDAV URL 创建';
$labels['specify_webdav_url'] = '要创建共享 URL，必须指定 WebDAV URL。';
