<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Kanál novinek';
$labels['news_feed'] = 'Kanál novinek';
$labels['preview'] = 'Náhled';
$labels['test_settings'] = 'Testování nastavení kanálu novinek';
$labels['feed_error'] = 'Nelze načíst kanál novinek.';
$labels['feed_error_url'] = 'Chyba: Nelze načíst zpravodajský kanál ze zadané adresy URL.';
$labels['feed_error_content'] = 'Chyba: Obsah načtený ze zadané adresy URL je prázdný.';
$labels['setting_show_xnews_feed'] = 'Zobrazit kanál novinek';
$labels['setting_predefined'] = 'Předdefinované kanály';
$labels['setting_title'] = 'Název';
$labels['setting_url'] = 'ADRESA URL';
$labels['setting_count'] = 'Položky k zobrazení';
