<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Naujienų kanalas';
$labels['news_feed'] = 'Naujienų kanalas';
$labels['preview'] = 'Peržiūra';
$labels['test_settings'] = 'Naujienų kanalo nustatymų testavimas';
$labels['feed_error'] = 'Negalima įkelti naujienų kanalo.';
$labels['feed_error_url'] = 'Klaida: Nepavyksta įkelti naujienų kanalo iš nurodyto URL adreso.';
$labels['feed_error_content'] = 'Klaida: Iš nurodyto URL įkeltas turinys yra tuščias.';
$labels['setting_show_xnews_feed'] = 'Rodyti naujienų kanalą';
$labels['setting_predefined'] = 'Iš anksto nustatyti kanalai';
$labels['setting_title'] = 'Pavadinimas';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Rodomi elementai';
