<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Wiadomości';
$labels['news_feed'] = 'Wiadomości';
$labels['preview'] = 'Podgląd';
$labels['test_settings'] = 'Przetestuj ustawienia';
$labels['feed_error'] = 'Problem z załadowaniem wiadomości.';
$labels['feed_error_url'] = 'Błąd: Nie można załadować wiadomości z podanego adresu URL.';
$labels['feed_error_content'] = 'Błąd: Zawartość załadowana z podanego adresu URL jest pusta.';
$labels['setting_show_xnews_feed'] = 'Pokaż wiadomości';
$labels['setting_predefined'] = 'Predefiniowane kanały';
$labels['setting_title'] = 'Tytuł';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Pokazywane artykuły';
