<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Nyhetsflöde';
$labels['news_feed'] = 'Nyhetsflöde';
$labels['preview'] = 'Förhandsgranskning';
$labels['test_settings'] = 'Testa inställningar för nyhetsflöde';
$labels['feed_error'] = 'Det går inte att ladda nyhetsflödet.';
$labels['feed_error_url'] = 'Felmeddelande: Det går inte att ladda nyhetsflödet från den angivna URL:en.';
$labels['feed_error_content'] = 'Error (Fel): Innehållet som laddats från den angivna URL:en är tomt.';
$labels['setting_show_xnews_feed'] = 'Visa nyhetsflöde';
$labels['setting_predefined'] = 'Fördefinierade flöden';
$labels['setting_title'] = 'Titel';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Föremål att visa';
