<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Стрічка новин';
$labels['news_feed'] = 'Стрічка новин';
$labels['preview'] = 'Попередній перегляд';
$labels['test_settings'] = 'Перевірте налаштування каналу новин';
$labels['feed_error'] = 'Не вдається завантажити канал новин.';
$labels['feed_error_url'] = 'Помилка: не вдається завантажити стрічку новин із зазначеної URL-адреси.';
$labels['feed_error_content'] = 'Помилка: вміст, завантажений із зазначеної URL-адреси, порожній.';
$labels['setting_show_xnews_feed'] = 'Показати стрічку новин';
$labels['setting_predefined'] = 'Попередньо задані канали';
$labels['setting_title'] = 'Назва';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Елементи для показу';
