<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '新闻提要';
$labels['news_feed'] = '新闻提要';
$labels['preview'] = '预览';
$labels['test_settings'] = '测试新闻源设置';
$labels['feed_error'] = '无法加载新闻源。';
$labels['feed_error_url'] = '错误：无法从指定的 URL 加载新闻源。';
$labels['feed_error_content'] = '错误：从指定 URL 加载的内容为空。';
$labels['setting_show_xnews_feed'] = '节目新闻源';
$labels['setting_predefined'] = '预定义馈送';
$labels['setting_title'] = '标题';
$labels['setting_url'] = '网址';
$labels['setting_count'] = '展示项目';
