<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Počasí';
$labels['weather'] = 'Počasí';
$labels['setting_show_xweather'] = 'Zobrazit počasí';
$labels['description'] = 'Popis';
$labels['humidity'] = 'Vlhkost';
$labels['pressure'] = 'Tlak';
$labels['clouds'] = 'Mraky';
$labels['wind'] = 'Vítr';
$labels['sunrise'] = 'Východ slunce';
$labels['sunset'] = 'Západ slunce';
$labels['more_data'] = 'Další údaje';
$labels['display'] = 'Zobrazit';
$labels['options'] = 'Možnosti';
$labels['setting_location_type'] = 'Najděte polohu podle';
$labels['setting_country_code'] = 'Země';
$labels['setting_city'] = 'Město';
$labels['setting_latitude'] = 'Zeměpisná šířka';
$labels['setting_longitude'] = 'Zeměpisná délka';
$labels['setting_units'] = 'Jednotky';
$labels['setting_icons'] = 'Ikony';
$labels['setting_show_description'] = 'Zobrazit popis';
$labels['setting_show_pressure'] = 'Zobrazit tlak';
$labels['setting_show_humidity'] = 'Zobrazit vlhkost';
$labels['setting_show_clouds'] = 'Zobrazit mraky';
$labels['setting_show_wind'] = 'Zobrazit vítr';
$labels['setting_show_sunrise'] = 'Zobrazit východ slunce';
$labels['setting_show_sunset'] = 'Zobrazit západ slunce';
$labels['metric'] = 'Metrické';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Náhled ikony';
$labels['icons_cutout'] = 'Výřez';
$labels['icons_glossy'] = 'Lesklý';
$labels['icons_monochrome'] = 'Monochromatické';
$labels['icons_moonlight'] = 'Moonlight';
$labels['icons_stickers'] = 'Nálepky';
$labels['check_location'] = 'Zkontrolujte umístění';
$labels['location_found'] = 'Nalezená lokalita:';
$labels['location_not_found'] = 'Místo nebylo nalezeno.';
$labels['loading_error'] = 'Při načítání dat o počasí došlo k chybě. Zkontrolujte prosím nastavení země a města v možnostech.';
$labels['country_and_city'] = 'Země a město';
$labels['coordinates'] = 'Souřadnice';
$labels['coordinates_link'] = 'Zjistěte svou zeměpisnou šířku a délku.';
