<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Wetter';
$labels['weather'] = 'Wetter';
$labels['setting_show_xweather'] = 'Wetter anzeigen';
$labels['description'] = 'Beschreibung';
$labels['humidity'] = 'Luftfeuchtigkeit';
$labels['pressure'] = 'Luftdruck';
$labels['clouds'] = 'Wolken';
$labels['wind'] = 'Wind';
$labels['sunrise'] = 'Sonnenaufgang';
$labels['sunset'] = 'Sonnenuntergang';
$labels['more_data'] = 'Weitere Daten';
$labels['display'] = 'Ansicht';
$labels['options'] = 'Optionen';
$labels['setting_location_type'] = 'Ort suchen nach';
$labels['setting_country_code'] = 'Land';
$labels['setting_city'] = 'Stadt';
$labels['setting_latitude'] = 'Breitengrad';
$labels['setting_longitude'] = 'Längengrad';
$labels['setting_units'] = 'Einheit';
$labels['setting_icons'] = 'Icons';
$labels['setting_show_description'] = 'Beschreibung anzeigen';
$labels['setting_show_pressure'] = 'Luftdruck anzeigen';
$labels['setting_show_humidity'] = 'Luftfeuchtigkeit anzeigen';
$labels['setting_show_clouds'] = 'Bewölkung anzeigen';
$labels['setting_show_wind'] = 'Windgeschwindigkeit anzeigen';
$labels['setting_show_sunrise'] = 'Sonnenaufgang anzeigen';
$labels['setting_show_sunset'] = 'Sonnenuntergang anzeigen';
$labels['metric'] = 'Celsius';
$labels['imperial'] = 'Fahrenheit';
$labels['icon_preview'] = 'Icons Vorschau';
$labels['icons_cutout'] = 'Cutout';
$labels['icons_glossy'] = 'Glossy';
$labels['icons_monochrome'] = 'Monochrome';
$labels['icons_moonlight'] = 'Moonlight';
$labels['icons_stickers'] = 'Stickers';
$labels['check_location'] = 'Stadt suchen';
$labels['location_found'] = 'Stadt gefunden:';
$labels['location_not_found'] = 'Ort nicht gefunden';
$labels['loading_error'] = 'Es konnten keine Wetterdaten abgerufen werden. Bitte überprüfen Sie die Ortsangaben unter Optionen.';
$labels['country_and_city'] = 'Land und Städtename';
$labels['coordinates'] = 'Koordinaten';
$labels['coordinates_link'] = 'Finden Sie Ihren Längen- und Breitengrad';
