<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Καιρός';
$labels['weather'] = 'Καιρός';
$labels['setting_show_xweather'] = 'Εμφάνιση καιρού';
$labels['description'] = 'Περιγραφή';
$labels['humidity'] = 'Υγρασία';
$labels['pressure'] = 'Πίεση';
$labels['clouds'] = 'Σύννεφα';
$labels['wind'] = 'Άνεμος';
$labels['sunrise'] = 'Sunrise';
$labels['sunset'] = 'Ηλιοβασίλεμα';
$labels['more_data'] = 'Περισσότερα στοιχεία';
$labels['display'] = 'Εμφάνιση';
$labels['options'] = 'Επιλογές';
$labels['setting_location_type'] = 'Εύρεση τοποθεσίας από';
$labels['setting_country_code'] = 'Χώρα';
$labels['setting_city'] = 'Πόλη';
$labels['setting_latitude'] = 'Γεωγραφικό πλάτος';
$labels['setting_longitude'] = 'Γεωγραφικό μήκος';
$labels['setting_units'] = 'Μονάδες';
$labels['setting_icons'] = 'Εικόνες';
$labels['setting_show_description'] = 'Εμφάνιση περιγραφής';
$labels['setting_show_pressure'] = 'Εμφάνιση πίεσης';
$labels['setting_show_humidity'] = 'Εμφάνιση υγρασίας';
$labels['setting_show_clouds'] = 'Εμφάνιση σύννεφων';
$labels['setting_show_wind'] = 'Εμφάνιση ανέμου';
$labels['setting_show_sunrise'] = 'Εμφάνιση ανατολής';
$labels['setting_show_sunset'] = 'Εμφάνιση ηλιοβασιλέματος';
$labels['metric'] = 'Μετρικό';
$labels['imperial'] = 'Αυτοκρατορικό';
$labels['icon_preview'] = 'Προεπισκόπηση εικονιδίων';
$labels['icons_cutout'] = 'Cutout';
$labels['icons_glossy'] = 'Γυαλιστερό';
$labels['icons_monochrome'] = 'Μονοχρωμία';
$labels['icons_moonlight'] = 'Σεληνόφως';
$labels['icons_stickers'] = 'Αυτοκόλλητα';
$labels['check_location'] = 'Ελέγξτε τη θέση';
$labels['location_found'] = 'Βρέθηκε η τοποθεσία:';
$labels['location_not_found'] = 'Η τοποθεσία δεν βρέθηκε.';
$labels['loading_error'] = 'Υπήρξε ένα σφάλμα κατά τη φόρτωση των δεδομένων καιρού. Ελέγξτε τις ρυθμίσεις χώρας και πόλης στις επιλογές.';
$labels['country_and_city'] = 'Χώρα και πόλη';
$labels['coordinates'] = 'Συντεταγμένες';
$labels['coordinates_link'] = 'Βρείτε το γεωγραφικό σας πλάτος και μήκος.';
