<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Ilm';
$labels['weather'] = 'Ilm';
$labels['setting_show_xweather'] = 'Näita ilma';
$labels['description'] = 'Kirjeldus';
$labels['humidity'] = 'Niiskus';
$labels['pressure'] = 'Surve';
$labels['clouds'] = 'Pilved';
$labels['wind'] = 'Tuul';
$labels['sunrise'] = 'Päikesetõus';
$labels['sunset'] = 'Päikeseloojang';
$labels['more_data'] = 'Rohkem andmeid';
$labels['display'] = 'Näita';
$labels['options'] = 'Valikud';
$labels['setting_location_type'] = 'Leia asukoht';
$labels['setting_country_code'] = 'Riik';
$labels['setting_city'] = 'Linn';
$labels['setting_latitude'] = 'Laiuskraad';
$labels['setting_longitude'] = 'Pikkuskraad';
$labels['setting_units'] = 'Üksused';
$labels['setting_icons'] = 'Ikoonid';
$labels['setting_show_description'] = 'Näita kirjeldust';
$labels['setting_show_pressure'] = 'Näita survet';
$labels['setting_show_humidity'] = 'Näita niiskust';
$labels['setting_show_clouds'] = 'Näita pilvi';
$labels['setting_show_wind'] = 'Näita tuult';
$labels['setting_show_sunrise'] = 'Näita päikesetõusu';
$labels['setting_show_sunset'] = 'Näita päikeseloojangut';
$labels['metric'] = 'Metriline';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Ikooni eelvaade';
$labels['icons_cutout'] = 'Väljalõige';
$labels['icons_glossy'] = 'Läikiv';
$labels['icons_monochrome'] = 'Ühevärviline';
$labels['icons_moonlight'] = 'Moonlight';
$labels['icons_stickers'] = 'Kleebised';
$labels['check_location'] = 'Kontrollida asukohta';
$labels['location_found'] = 'Asukoht leitud:';
$labels['location_not_found'] = 'Asukohta ei leitud.';
$labels['loading_error'] = 'Ilmastikuandmete laadimisel tekkis viga. Palun kontrollige riigi ja linna seadeid valikutes.';
$labels['country_and_city'] = 'Riik ja linn';
$labels['coordinates'] = 'Koordinaadid';
$labels['coordinates_link'] = 'Leidke oma laius- ja pikkuskraad.';
