<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Cuaca';
$labels['weather'] = 'Cuaca';
$labels['setting_show_xweather'] = 'Tampilkan Cuaca';
$labels['description'] = 'Deskripsi';
$labels['humidity'] = 'Kelembaban';
$labels['pressure'] = 'Tekanan';
$labels['clouds'] = 'Awan';
$labels['wind'] = 'Angin';
$labels['sunrise'] = 'Matahari terbit';
$labels['sunset'] = 'Matahari terbenam';
$labels['more_data'] = 'Lebih banyak data';
$labels['display'] = 'Tampilan';
$labels['options'] = 'Pilihan';
$labels['setting_location_type'] = 'Temukan lokasi dengan';
$labels['setting_country_code'] = 'Negara';
$labels['setting_city'] = 'Kota';
$labels['setting_latitude'] = 'Lintang';
$labels['setting_longitude'] = 'Bujur';
$labels['setting_units'] = 'Unit';
$labels['setting_icons'] = 'Ikon';
$labels['setting_show_description'] = 'Tampilkan deskripsi';
$labels['setting_show_pressure'] = 'Tunjukkan tekanan';
$labels['setting_show_humidity'] = 'Tunjukkan kelembaban';
$labels['setting_show_clouds'] = 'Tampilkan awan';
$labels['setting_show_wind'] = 'Tampilkan angin';
$labels['setting_show_sunrise'] = 'Tampilkan matahari terbit';
$labels['setting_show_sunset'] = 'Tampilkan matahari terbenam';
$labels['metric'] = 'Metrik';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Pratinjau ikon';
$labels['icons_cutout'] = 'Guntingan';
$labels['icons_glossy'] = 'Mengkilap';
$labels['icons_monochrome'] = 'Monokrom';
$labels['icons_moonlight'] = 'Cahaya bulan';
$labels['icons_stickers'] = 'Stiker';
$labels['check_location'] = 'Periksa lokasi';
$labels['location_found'] = 'Lokasi ditemukan:';
$labels['location_not_found'] = 'Lokasi tidak ditemukan.';
$labels['loading_error'] = 'Terjadi kesalahan saat memuat data cuaca. Silakan periksa pengaturan negara dan kota dalam opsi.';
$labels['country_and_city'] = 'Negara dan kota';
$labels['coordinates'] = 'Koordinat';
$labels['coordinates_link'] = 'Temukan garis lintang dan garis bujur Anda.';
