<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Orai';
$labels['weather'] = 'Orai';
$labels['setting_show_xweather'] = 'Rodyti orus';
$labels['description'] = 'Aprašymas';
$labels['humidity'] = 'Drėgmė';
$labels['pressure'] = 'Slėgis';
$labels['clouds'] = 'Debesys';
$labels['wind'] = 'Vėjas';
$labels['sunrise'] = 'Saulėlydis';
$labels['sunset'] = 'Saulėlydis';
$labels['more_data'] = 'Daugiau duomenų';
$labels['display'] = 'Ekranas';
$labels['options'] = 'Parinktys';
$labels['setting_location_type'] = 'Raskite vietą pagal';
$labels['setting_country_code'] = 'Šalis';
$labels['setting_city'] = 'Miestas';
$labels['setting_latitude'] = 'Platuma';
$labels['setting_longitude'] = 'Ilguma';
$labels['setting_units'] = 'Vienetai';
$labels['setting_icons'] = 'Ikonos';
$labels['setting_show_description'] = 'Rodyti aprašymą';
$labels['setting_show_pressure'] = 'Rodyti slėgį';
$labels['setting_show_humidity'] = 'Rodyti drėgmę';
$labels['setting_show_clouds'] = 'Rodyti debesis';
$labels['setting_show_wind'] = 'Rodyti vėją';
$labels['setting_show_sunrise'] = 'Rodyti saulėtekį';
$labels['setting_show_sunset'] = 'Rodyti saulėlydį';
$labels['metric'] = 'Metrinis';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Ikonos peržiūra';
$labels['icons_cutout'] = 'Išpjova';
$labels['icons_glossy'] = 'Blizgus';
$labels['icons_monochrome'] = 'Vienspalvis';
$labels['icons_moonlight'] = 'Mėnulio šviesa';
$labels['icons_stickers'] = 'Lipdukai';
$labels['check_location'] = 'Patikrinkite vietą';
$labels['location_found'] = 'Rasta vieta:';
$labels['location_not_found'] = 'Vieta nerasta.';
$labels['loading_error'] = 'Įkeliant orų duomenis įvyko klaida. Patikrinkite šalies ir miesto nustatymus parinktyse.';
$labels['country_and_city'] = 'Šalis ir miestas';
$labels['coordinates'] = 'Koordinatės';
$labels['coordinates_link'] = 'Raskite savo platumą ir ilgumą.';
