<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Været';
$labels['weather'] = 'Vær';
$labels['setting_show_xweather'] = 'Vis vær';
$labels['description'] = 'Beskrivelse';
$labels['humidity'] = 'Luftfuktighet';
$labels['pressure'] = 'Press';
$labels['clouds'] = 'Skyer';
$labels['wind'] = 'Vind';
$labels['sunrise'] = 'Soloppgang';
$labels['sunset'] = 'Solnedgang';
$labels['more_data'] = 'Mer data';
$labels['display'] = 'Vis';
$labels['options'] = 'Alternativer';
$labels['setting_location_type'] = 'Finn sted etter';
$labels['setting_country_code'] = 'Land';
$labels['setting_city'] = 'By';
$labels['setting_latitude'] = 'Breddegrad';
$labels['setting_longitude'] = 'Lengdegrad';
$labels['setting_units'] = 'Enheter';
$labels['setting_icons'] = 'Ikoner';
$labels['setting_show_description'] = 'Vis beskrivelse';
$labels['setting_show_pressure'] = 'Vis press';
$labels['setting_show_humidity'] = 'Vis luftfuktighet';
$labels['setting_show_clouds'] = 'Vis skyer';
$labels['setting_show_wind'] = 'Vis vind';
$labels['setting_show_sunrise'] = 'Vis soloppgang';
$labels['setting_show_sunset'] = 'Vis solnedgang';
$labels['metric'] = 'Metrisk';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Forhåndsvisning av ikon';
$labels['icons_cutout'] = 'Utklipp';
$labels['icons_glossy'] = 'Glanset';
$labels['icons_monochrome'] = 'Monokrom';
$labels['icons_moonlight'] = 'Måneskinn';
$labels['icons_stickers'] = 'Klistremerker';
$labels['check_location'] = 'Sjekk plassering';
$labels['location_found'] = 'Plassering funnet:';
$labels['location_not_found'] = 'Sted ikke funnet.';
$labels['loading_error'] = 'Det oppstod en feil under innlasting av værdata. Vennligst sjekk innstillingene for land og by i alternativene.';
$labels['country_and_city'] = 'Land og by';
$labels['coordinates'] = 'Koordinater';
$labels['coordinates_link'] = 'Finn din breddegrad og lengdegrad.';
