<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Weer';
$labels['weather'] = 'Weer';
$labels['setting_show_xweather'] = 'Toon het weer';
$labels['description'] = 'Beschrijving';
$labels['humidity'] = 'Vochtigheid';
$labels['pressure'] = 'Druk';
$labels['clouds'] = 'Wolken';
$labels['wind'] = 'Wind';
$labels['sunrise'] = 'Sunrise';
$labels['sunset'] = 'Zonsondergang';
$labels['more_data'] = 'Meer gegevens';
$labels['display'] = 'Display';
$labels['options'] = 'Opties';
$labels['setting_location_type'] = 'Vind locatie door';
$labels['setting_country_code'] = 'Land';
$labels['setting_city'] = 'Stad';
$labels['setting_latitude'] = 'Breedtegraad';
$labels['setting_longitude'] = 'Lengtegraad';
$labels['setting_units'] = 'Eenheden';
$labels['setting_icons'] = 'Pictogrammen';
$labels['setting_show_description'] = 'Beschrijving tonen';
$labels['setting_show_pressure'] = 'Toon druk';
$labels['setting_show_humidity'] = 'Vochtigheid tonen';
$labels['setting_show_clouds'] = 'Wolken tonen';
$labels['setting_show_wind'] = 'Toon wind';
$labels['setting_show_sunrise'] = 'Toon zonsopgang';
$labels['setting_show_sunset'] = 'Toon zonsondergang';
$labels['metric'] = 'Metrisch';
$labels['imperial'] = 'Keizerlijke';
$labels['icon_preview'] = 'Pictogrammenvoorbeeld';
$labels['icons_cutout'] = 'Uitgesneden';
$labels['icons_glossy'] = 'Glanzend';
$labels['icons_monochrome'] = 'Monochroom';
$labels['icons_moonlight'] = 'Maanlicht';
$labels['icons_stickers'] = 'Stickers';
$labels['check_location'] = 'Locatie controleren';
$labels['location_found'] = 'Locatie gevonden:';
$labels['location_not_found'] = 'Locatie niet gevonden.';
$labels['loading_error'] = 'Er is een fout opgetreden bij het laden van de weergegevens. Controleer de land en stad instellingen in de opties.';
$labels['country_and_city'] = 'Land en stad';
$labels['coordinates'] = 'Coördinaten';
$labels['coordinates_link'] = 'Zoek uw lengte- en breedtegraad.';
