<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Pogoda';
$labels['weather'] = 'Pogoda';
$labels['setting_show_xweather'] = 'Pokaż Pogodę';
$labels['description'] = 'Opis';
$labels['humidity'] = 'Wilgotność';
$labels['pressure'] = 'Ciśnienie';
$labels['clouds'] = 'Zachmurzenie';
$labels['wind'] = 'Wiatr';
$labels['sunrise'] = 'Wchód słońca';
$labels['sunset'] = 'Zachód słońca';
$labels['more_data'] = 'Więcej danych';
$labels['display'] = 'Wyświetl';
$labels['options'] = 'Opcje';
$labels['setting_location_type'] = 'Znajdź lokalizację wg.';
$labels['setting_country_code'] = 'Kraj';
$labels['setting_city'] = 'Miasto';
$labels['setting_latitude'] = 'Szerokość geograficzna';
$labels['setting_longitude'] = 'Długość geograficzna';
$labels['setting_units'] = 'Jednostki';
$labels['setting_icons'] = 'Ikony';
$labels['setting_show_description'] = 'Pokaż opis';
$labels['setting_show_pressure'] = 'Pokaż ciśnienie';
$labels['setting_show_humidity'] = 'Pokaż wilgotność';
$labels['setting_show_clouds'] = 'Pokaż zachmurzenie';
$labels['setting_show_wind'] = 'Pokaż wiatr';
$labels['setting_show_sunrise'] = 'Pokaż wschód słońca';
$labels['setting_show_sunset'] = 'Pokaż zachód słońca';
$labels['metric'] = 'Metryczny';
$labels['imperial'] = 'Imperialny';
$labels['icon_preview'] = 'Podgląd ikon';
$labels['icons_cutout'] = 'Wycinanka';
$labels['icons_glossy'] = 'Błyszczące';
$labels['icons_monochrome'] = 'Monochromatyczne';
$labels['icons_moonlight'] = 'Księżycowe';
$labels['icons_stickers'] = 'Nalepki';
$labels['check_location'] = 'Sprawdź lokalizację';
$labels['location_found'] = 'Znaleziono lokalizację:';
$labels['location_not_found'] = 'Nie znaleziono lokalizacji.';
$labels['loading_error'] = 'W trakcie ładowania danych pogodowych wystąpił błąd. Sprawdź ustawienia kraju i miasta w opcjach.';
$labels['country_and_city'] = 'Kraj i miasto';
$labels['coordinates'] = 'Współrzędne';
$labels['coordinates_link'] = 'Znajdź swoje współrzędne.';
