<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Clima';
$labels['weather'] = 'Clima';
$labels['setting_show_xweather'] = 'Mostrar o tempo';
$labels['description'] = 'Descrição';
$labels['humidity'] = 'Umidade';
$labels['pressure'] = 'Pressão';
$labels['clouds'] = 'Nuvens';
$labels['wind'] = 'Vento';
$labels['sunrise'] = 'Nascer do sol';
$labels['sunset'] = 'Pôr-do-sol';
$labels['more_data'] = 'Mais dados';
$labels['display'] = 'Mostrar';
$labels['options'] = 'Opções';
$labels['setting_location_type'] = 'Encontrar localização por';
$labels['setting_country_code'] = 'País';
$labels['setting_city'] = 'Cidade';
$labels['setting_latitude'] = 'Latitude';
$labels['setting_longitude'] = 'Longitude';
$labels['setting_units'] = 'Unidades';
$labels['setting_icons'] = 'Ícones';
$labels['setting_show_description'] = 'Mostrar descrição';
$labels['setting_show_pressure'] = 'Mostrar pressão';
$labels['setting_show_humidity'] = 'Mostrar umidade';
$labels['setting_show_clouds'] = 'Mostrar nuvens';
$labels['setting_show_wind'] = 'Mostrar vento';
$labels['setting_show_sunrise'] = 'Mostrar o nascer do sol';
$labels['setting_show_sunset'] = 'Mostrar o pôr-do-sol';
$labels['metric'] = 'Métrica';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Visualização de ícones';
$labels['icons_cutout'] = 'Recorte';
$labels['icons_glossy'] = 'Glossy';
$labels['icons_monochrome'] = 'Monocromático';
$labels['icons_moonlight'] = 'Luz da Lua';
$labels['icons_stickers'] = 'Adesivos';
$labels['check_location'] = 'Verificar localização';
$labels['location_found'] = 'Localização encontrada:';
$labels['location_not_found'] = 'Localização não encontrada.';
$labels['loading_error'] = 'Houve um erro ao carregar os dados meteorológicos. Por favor, verifique as configurações do país e da cidade nas opções.';
$labels['country_and_city'] = 'País e cidade';
$labels['coordinates'] = 'Coordenadas';
$labels['coordinates_link'] = 'Encontre sua latitude e longitude.';
