<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Tempo';
$labels['weather'] = 'Tempo';
$labels['setting_show_xweather'] = 'Mostrar o tempo';
$labels['description'] = 'Descrição';
$labels['humidity'] = 'Humidade';
$labels['pressure'] = 'Pressão';
$labels['clouds'] = 'Nuvens';
$labels['wind'] = 'Vento';
$labels['sunrise'] = 'Nascer do sol';
$labels['sunset'] = 'Pôr do sol';
$labels['more_data'] = 'Mais dados';
$labels['display'] = 'Ecrã';
$labels['options'] = 'Opções';
$labels['setting_location_type'] = 'Procurar localização por';
$labels['setting_country_code'] = 'País';
$labels['setting_city'] = 'Cidade';
$labels['setting_latitude'] = 'Latitude';
$labels['setting_longitude'] = 'Longitude';
$labels['setting_units'] = 'Unidades';
$labels['setting_icons'] = 'Ícones';
$labels['setting_show_description'] = 'Mostrar descrição';
$labels['setting_show_pressure'] = 'Mostrar pressão';
$labels['setting_show_humidity'] = 'Mostrar humidade';
$labels['setting_show_clouds'] = 'Mostrar nuvens';
$labels['setting_show_wind'] = 'Mostrar o vento';
$labels['setting_show_sunrise'] = 'Mostrar o nascer do sol';
$labels['setting_show_sunset'] = 'Mostrar o pôr do sol';
$labels['metric'] = 'Métrica';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Pré-visualização do ícone';
$labels['icons_cutout'] = 'Recorte';
$labels['icons_glossy'] = 'Brilhante';
$labels['icons_monochrome'] = 'Monocromático';
$labels['icons_moonlight'] = 'Luar';
$labels['icons_stickers'] = 'Autocolantes';
$labels['check_location'] = 'Verificar a localização';
$labels['location_found'] = 'Localização encontrada:';
$labels['location_not_found'] = 'Local não encontrado.';
$labels['loading_error'] = 'Ocorreu um erro ao carregar os dados meteorológicos. Verifique as definições de país e cidade nas opções.';
$labels['country_and_city'] = 'País e cidade';
$labels['coordinates'] = 'Coordenadas';
$labels['coordinates_link'] = 'Encontre a sua latitude e longitude.';
