<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Vremea';
$labels['weather'] = 'Vremea';
$labels['setting_show_xweather'] = 'Arată vremea';
$labels['description'] = 'Descriere';
$labels['humidity'] = 'Umiditate';
$labels['pressure'] = 'Presiune';
$labels['clouds'] = 'Nori';
$labels['wind'] = 'Vânt';
$labels['sunrise'] = 'Răsărit de soare';
$labels['sunset'] = 'Apus de soare';
$labels['more_data'] = 'Mai multe date';
$labels['display'] = 'Afișare';
$labels['options'] = 'Opțiuni';
$labels['setting_location_type'] = 'Găsiți locația prin';
$labels['setting_country_code'] = 'Țara';
$labels['setting_city'] = 'Orașul';
$labels['setting_latitude'] = 'Latitudine';
$labels['setting_longitude'] = 'Longitudine';
$labels['setting_units'] = 'Unități';
$labels['setting_icons'] = 'Icoane';
$labels['setting_show_description'] = 'Arată descrierea';
$labels['setting_show_pressure'] = 'Afișați presiunea';
$labels['setting_show_humidity'] = 'Arată umiditatea';
$labels['setting_show_clouds'] = 'Arată nori';
$labels['setting_show_wind'] = 'Arată vântul';
$labels['setting_show_sunrise'] = 'Arată răsăritul soarelui';
$labels['setting_show_sunset'] = 'Arată apusul de soare';
$labels['metric'] = 'Metric';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Previzualizare pictogramă';
$labels['icons_cutout'] = 'Decupaj';
$labels['icons_glossy'] = 'Glossy';
$labels['icons_monochrome'] = 'Monocromie';
$labels['icons_moonlight'] = 'Lumina lunii';
$labels['icons_stickers'] = 'Autocolante';
$labels['check_location'] = 'Verificați locația';
$labels['location_found'] = 'Locația găsită:';
$labels['location_not_found'] = 'Locația nu a fost găsită.';
$labels['loading_error'] = 'S-a produs o eroare la încărcarea datelor meteo. Vă rugăm să verificați setările de țară și de oraș din opțiuni.';
$labels['country_and_city'] = 'Țara și orașul';
$labels['coordinates'] = 'Coordonate';
$labels['coordinates_link'] = 'Găsiți latitudinea și longitudinea.';
