<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'جدولة البريد الإلكتروني';
$labels['email_schedule'] = 'جدولة البريد الإلكتروني';
$labels['schedule'] = 'الجدول الزمني';
$labels['scheduled'] = 'المقرر';
$labels['scheduled_messages'] = 'الرسائل المجدولة';
$labels['show_scheduled_messages'] = 'إظهار الرسائل المجدولة.';
$labels['message_scheduled'] = 'الرسالة مجدولة.';
$labels['no_scheduled_messages'] = 'لا توجد رسائل في قائمة انتظار الجدول الزمني.';
$labels['warning_unsent_messages'] = 'لم يتم إرسال بعض رسائلك المجدولة.';
$labels['message_delete_confirm'] = 'هل تريد حذف هذه الرسالة نهائياً؟';

$labels['immediately'] = 'على الفور';
$labels['in_5_minutes'] = 'في 5 دقائق';
$labels['in_10_minutes'] = 'خلال 10 دقائق';
$labels['in_15_minutes'] = 'خلال 15 دقيقة';
$labels['in_30_minutes'] = 'خلال 30 دقيقة';
$labels['in_1_hour'] = 'في 1 ساعة';
$labels['in_2_hours'] = 'خلال ساعتين';
$labels['in_6_hours'] = 'خلال 6 ساعات';
$labels['at_a_specific_time'] = 'في وقت محدد';

$labels['disabled'] = 'تم تعطيل جدولة الرسائل. اتصل بالمسؤول.';
$labels['draft_note'] = 'تم حفظ هذه الرسالة كمسودة وإزالتها من قائمة انتظار الجدولة. لجدولتها مرة أخرى، انقر فوق الزر جدولة.';
$labels['error_editing'] = 'لا يمكن تحرير الرسالة المجدولة؛ ربما تم إرسال الرسالة أو حذفها.';
$labels['error_deleting'] = 'لا يمكن نقل الرسالة إلى سلة المهملات؛ قد تكون الرسالة قد تم إرسالها أو حذفها أو أن صندوق البريد الخاص بالمهملات غير متوفر.';

$labels['send_message'] = 'إرسال رسالة';
$labels['setting_delay'] = 'التأخير الافتراضي لإرسال الرسائل';
$labels['setting_highlight'] = 'تمييز الرسائل المجدولة التي على وشك الإرسال';

$labels['email_being_sent'] = 'إرسال البريد الإلكتروني';
$labels['send_now'] = 'أرسل الآن';
$labels['schedule_now'] = 'الجدول الزمني الآن';
$labels['cancel_sending'] = 'إلغاء الإرسال';
$labels['setting_countdown'] = 'العد التنازلي قبل إرسال الرسائل';
$labels['disable_countdown'] = 'تعطيل';
$labels['3_seconds'] = '3 ثوانٍ';
$labels['5_seconds'] = '5 ثوانٍ';
$labels['10_seconds'] = '10 ثوانٍ';
$labels['15_seconds'] = '15 ثانية';

$labels['cannot_schedule_message'] = 'لا يمكن جدولة الرسالة:';
$labels['time_has_already_passed'] = 'لقد انقضى الوقت المحدد بالفعل.';
$labels['invalid_time_format'] = 'تنسيق الوقت غير صالح.';
$labels['draft_folder_not_specified'] = 'خطأ في المكون الإضافي لجدول البريد الإلكتروني: لم يتم تحديد مجلد المسودة.';
$labels['error'] = 'خطأ:';
$labels['attachment_tool_large'] = 'يحدد تكوين الخادم مرفقات الرسائل المجدولة بحجم $.';
$labels['message_already_scheduled'] = 'تمت جدولة هذه الرسالة بالفعل.';

