<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Email Scheduler';
$labels['email_schedule'] = 'Email Scheduler';
$labels['schedule'] = 'Schedule';
$labels['scheduled'] = 'Scheduled';
$labels['scheduled_messages'] = 'Scheduled messages';
$labels['show_scheduled_messages'] = 'Show scheduled messages.';
$labels['message_scheduled'] = 'Message scheduled.';
$labels['no_scheduled_messages'] = 'There are no messages in the schedule queue.';
$labels['warning_unsent_messages'] = 'Some of your scheduled messages have not been sent.';
$labels['message_delete_confirm'] = 'Do you want to permanently delete this message?';

$labels['immediately'] = 'Immediately';
$labels['in_5_minutes'] = 'In 5 minutes';
$labels['in_10_minutes'] = 'In 10 minutes';
$labels['in_15_minutes'] = 'In 15 minutes';
$labels['in_30_minutes'] = 'In 30 minutes';
$labels['in_1_hour'] = 'In 1 hour';
$labels['in_2_hours'] = 'In 2 hours';
$labels['in_6_hours'] = 'In 6 hours';
$labels['at_a_specific_time'] = 'At a specific time';

$labels['disabled'] = 'Message scheduling is disabled. Contact the administrator.';
$labels['draft_note'] = 'This message was saved as draft and removed from the schedule queue. To schedule it again, click the Schedule button.';
$labels['error_editing'] = 'Cannot edit the scheduled message; the message might have been sent or deleted.';
$labels['error_deleting'] = 'Cannot move the message to trash; the message might have been sent, deleted or the trash mailbox is not available.';

$labels['send_message'] = 'Send message';
$labels['setting_delay'] = 'Default delay for sending messages';
$labels['setting_highlight'] = 'Highlight scheduled messages that are about to be sent';

$labels['email_being_sent'] = 'Sending email';
$labels['send_now'] = 'Send now';
$labels['schedule_now'] = 'Schedule now';
$labels['cancel_sending'] = 'Cancel sending';
$labels['setting_countdown'] = 'Countdown before sending messages';
$labels['disable_countdown'] = 'Disable';
$labels['3_seconds'] = '3 seconds';
$labels['5_seconds'] = '5 seconds';
$labels['10_seconds'] = '10 seconds';
$labels['15_seconds'] = '15 seconds';

$labels['cannot_schedule_message'] = 'Cannot schedule message:';
$labels['time_has_already_passed'] = 'The scheduled time has already passed.';
$labels['invalid_time_format'] = 'Invalid time format.';
$labels['draft_folder_not_specified'] = 'Email schedule plugin error: Draft folder not specified.';
$labels['error'] = 'Error:';
$labels['attachment_tool_large'] = 'Server configuration limits scheduled message attachments to $size.';
$labels['message_already_scheduled'] = 'This message is already scheduled.';

