<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '이메일 스케줄러';
$labels['email_schedule'] = '이메일 스케줄러';
$labels['schedule'] = '일정';
$labels['scheduled'] = '예약됨';
$labels['scheduled_messages'] = '예약된 메시지';
$labels['show_scheduled_messages'] = '예약된 메시지를 표시합니다.';
$labels['message_scheduled'] = '메시지 예약됨.';
$labels['no_scheduled_messages'] = '일정 대기열에 메시지가 없습니다.';
$labels['warning_unsent_messages'] = '예약된 메시지 중 일부가 전송되지 않았습니다.';
$labels['message_delete_confirm'] = '이 메시지를 영구 삭제하시겠습니까?';

$labels['immediately'] = '즉시';
$labels['in_5_minutes'] = '5분 후';
$labels['in_10_minutes'] = '10분 후';
$labels['in_15_minutes'] = '15분 후';
$labels['in_30_minutes'] = '30분 후';
$labels['in_1_hour'] = '1시간 후';
$labels['in_2_hours'] = '2시간 후';
$labels['in_6_hours'] = '6시간 후';
$labels['at_a_specific_time'] = '특정 시간에';

$labels['disabled'] = '메시지 예약이 비활성화되었습니다. 관리자에게 문의하세요.';
$labels['draft_note'] = '이 메시지는 초안으로 저장되어 일정 대기열에서 제거되었습니다. 다시 예약하려면 예약 버튼을 클릭합니다.';
$labels['error_editing'] = '예약된 메시지를 수정할 수 없습니다. 메시지가 전송되었거나 삭제되었을 수 있습니다.';
$labels['error_deleting'] = '메시지를 휴지통으로 이동할 수 없습니다. 메시지가 전송되었거나 삭제되었거나 휴지통 사서함을 사용할 수 없을 수 있습니다.';

$labels['send_message'] = '메시지 보내기';
$labels['setting_delay'] = '메시지 전송 기본 지연 시간';
$labels['setting_highlight'] = '곧 전송될 예약된 메시지 강조 표시하기';

$labels['email_being_sent'] = '이메일 보내기';
$labels['send_now'] = '지금 보내기';
$labels['schedule_now'] = '지금 예약하기';
$labels['cancel_sending'] = '전송 취소';
$labels['setting_countdown'] = '메시지 보내기 전 카운트다운';
$labels['disable_countdown'] = '비활성화';
$labels['3_seconds'] = '3초';
$labels['5_seconds'] = '5초';
$labels['10_seconds'] = '10초';
$labels['15_seconds'] = '15초';

$labels['cannot_schedule_message'] = '메시지를 예약할 수 없습니다:';
$labels['time_has_already_passed'] = '예정된 시간이 이미 지났습니다.';
$labels['invalid_time_format'] = '잘못된 시간 형식입니다.';
$labels['draft_folder_not_specified'] = '이메일 일정 플러그인 오류입니다: 임시 보관함 폴더가 지정되지 않았습니다.';
$labels['error'] = '오류:';
$labels['attachment_tool_large'] = '서버 구성은 예약된 메시지 첨부 파일을 $size로 제한합니다.';
$labels['message_already_scheduled'] = '이 메시지는 이미 예약되어 있습니다.';

