<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'E-postplanlegger';
$labels['email_schedule'] = 'E-postplanlegger';
$labels['schedule'] = 'Tidsplan';
$labels['scheduled'] = 'Planlagt';
$labels['scheduled_messages'] = 'Planlagte meldinger';
$labels['show_scheduled_messages'] = 'Vis planlagte meldinger.';
$labels['message_scheduled'] = 'Melding planlagt.';
$labels['no_scheduled_messages'] = 'Det er ingen meldinger i planleggingskøen.';
$labels['warning_unsent_messages'] = 'Noen av de planlagte meldingene dine er ikke sendt.';
$labels['message_delete_confirm'] = 'Vil du slette denne meldingen permanent?';

$labels['immediately'] = 'Umiddelbart';
$labels['in_5_minutes'] = 'På 5 minutter';
$labels['in_10_minutes'] = 'På 10 minutter';
$labels['in_15_minutes'] = 'På 15 minutter';
$labels['in_30_minutes'] = 'På 30 minutter';
$labels['in_1_hour'] = 'Om 1 time';
$labels['in_2_hours'] = 'Om 2 timer';
$labels['in_6_hours'] = 'Om 6 timer';
$labels['at_a_specific_time'] = 'På et bestemt tidspunkt';

$labels['disabled'] = 'Meldingsplanlegging er deaktivert. Kontakt administratoren.';
$labels['draft_note'] = 'Denne meldingen ble lagret som kladd og fjernet fra planleggingskøen. Klikk på knappen Planlegg for å planlegge den på nytt.';
$labels['error_editing'] = 'Kan ikke redigere den planlagte meldingen; meldingen kan ha blitt sendt eller slettet.';
$labels['error_deleting'] = 'Kan ikke flytte meldingen til papirkurven; meldingen kan ha blitt sendt, slettet eller papirkurven er ikke tilgjengelig.';

$labels['send_message'] = 'Send melding';
$labels['setting_delay'] = 'Standard forsinkelse for sending av meldinger';
$labels['setting_highlight'] = 'Marker planlagte meldinger som er i ferd med å bli sendt';

$labels['email_being_sent'] = 'Sende e-post';
$labels['send_now'] = 'Send nå';
$labels['schedule_now'] = 'Planlegg nå';
$labels['cancel_sending'] = 'Avbryt sending';
$labels['setting_countdown'] = 'Nedtelling før sending av meldinger';
$labels['disable_countdown'] = 'Deaktiver';
$labels['3_seconds'] = '3 sekunder';
$labels['5_seconds'] = '5 sekunder';
$labels['10_seconds'] = '10 sekunder';
$labels['15_seconds'] = '15 sekunder';

$labels['cannot_schedule_message'] = 'Kan ikke planlegge melding:';
$labels['time_has_already_passed'] = 'Den planlagte tiden er allerede overskredet.';
$labels['invalid_time_format'] = 'Ugyldig tidsformat.';
$labels['draft_folder_not_specified'] = 'Feil i plugin for e-postplanlegging: Utkastmappe ikke spesifisert.';
$labels['error'] = 'Feil:';
$labels['attachment_tool_large'] = 'Serverkonfigurasjonen begrenser planlagte meldingsvedlegg til $size.';
$labels['message_already_scheduled'] = 'Denne meldingen er allerede planlagt.';

