<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Schemaläggare för e-post';
$labels['email_schedule'] = 'Schemaläggare för e-post';
$labels['schedule'] = 'Schema';
$labels['scheduled'] = 'Planerad';
$labels['scheduled_messages'] = 'Schemalagda meddelanden';
$labels['show_scheduled_messages'] = 'Visa schemalagda meddelanden.';
$labels['message_scheduled'] = 'Meddelande inplanerat.';
$labels['no_scheduled_messages'] = 'Det finns inga meddelanden i schemakön.';
$labels['warning_unsent_messages'] = 'Några av dina schemalagda meddelanden har inte skickats.';
$labels['message_delete_confirm'] = 'Vill du radera det här meddelandet permanent?';

$labels['immediately'] = 'Omedelbart';
$labels['in_5_minutes'] = 'Om 5 minuter';
$labels['in_10_minutes'] = 'På 10 minuter';
$labels['in_15_minutes'] = 'På 15 minuter';
$labels['in_30_minutes'] = 'På 30 minuter';
$labels['in_1_hour'] = 'Om 1 timme';
$labels['in_2_hours'] = 'Om 2 timmar';
$labels['in_6_hours'] = 'Om 6 timmar';
$labels['at_a_specific_time'] = 'Vid en viss tidpunkt';

$labels['disabled'] = 'Schemaläggning av meddelanden är inaktiverad. Kontakta administratören.';
$labels['draft_note'] = 'Det här meddelandet sparades som utkast och togs bort från schemakön. Om du vill schemalägga det igen klickar du på knappen Schemalägg.';
$labels['error_editing'] = 'Det går inte att redigera det schemalagda meddelandet; meddelandet kan ha skickats eller tagits bort.';
$labels['error_deleting'] = 'Det går inte att flytta meddelandet till papperskorgen; meddelandet kan ha skickats, tagits bort eller så är papperskorgen inte tillgänglig.';

$labels['send_message'] = 'Skicka meddelande';
$labels['setting_delay'] = 'Standardfördröjning för att skicka meddelanden';
$labels['setting_highlight'] = 'Markera schemalagda meddelanden som är på väg att skickas';

$labels['email_being_sent'] = 'Skicka e-post';
$labels['send_now'] = 'Skicka nu';
$labels['schedule_now'] = 'Schemalägg nu';
$labels['cancel_sending'] = 'Avbryt sändning';
$labels['setting_countdown'] = 'Nedräkning innan meddelanden skickas';
$labels['disable_countdown'] = 'Avaktivera';
$labels['3_seconds'] = '3 sekunder';
$labels['5_seconds'] = '5 sekunder';
$labels['10_seconds'] = '10 sekunder';
$labels['15_seconds'] = '15 sekunder';

$labels['cannot_schedule_message'] = 'Det går inte att schemalägga meddelandet:';
$labels['time_has_already_passed'] = 'Den schemalagda tiden har redan passerat.';
$labels['invalid_time_format'] = 'Ogiltigt tidsformat.';
$labels['draft_folder_not_specified'] = 'Fel i plugin för e-postschema: Utkastmapp inte angiven.';
$labels['error'] = 'Fel:';
$labels['attachment_tool_large'] = 'Serverkonfigurationen begränsar bilagor till schemalagda meddelanden till $size.';
$labels['message_already_scheduled'] = 'Detta meddelande är redan inplanerat.';

