<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'E-posta Zamanlayıcı';
$labels['email_schedule'] = 'E-posta Zamanlayıcı';
$labels['schedule'] = 'Program';
$labels['scheduled'] = 'Planlanmış';
$labels['scheduled_messages'] = 'Zamanlanmış mesajlar';
$labels['show_scheduled_messages'] = 'Zamanlanmış mesajları göster.';
$labels['message_scheduled'] = 'Mesaj planlandı.';
$labels['no_scheduled_messages'] = 'Program kuyruğunda hiç mesaj yok.';
$labels['warning_unsent_messages'] = 'Zamanlanmış mesajlarınızdan bazıları gönderilmedi.';
$labels['message_delete_confirm'] = 'Bu mesajı kalıcı olarak silmek istiyor musunuz?';

$labels['immediately'] = 'Derhal';
$labels['in_5_minutes'] = '5 dakika içinde';
$labels['in_10_minutes'] = '10 dakika içinde';
$labels['in_15_minutes'] = '15 dakika içinde';
$labels['in_30_minutes'] = '30 dakika içinde';
$labels['in_1_hour'] = '1 saat içinde';
$labels['in_2_hours'] = '2 saat içinde';
$labels['in_6_hours'] = '6 saat içinde';
$labels['at_a_specific_time'] = 'Belirli bir zamanda';

$labels['disabled'] = 'Mesaj zamanlama devre dışı. Yönetici ile iletişime geçin.';
$labels['draft_note'] = 'Bu mesaj taslak olarak kaydedildi ve zamanlama kuyruğundan kaldırıldı. Tekrar zamanlamak için Zamanla düğmesine tıklayın.';
$labels['error_editing'] = 'Zamanlanmış mesaj düzenlenemiyor; mesaj gönderilmiş veya silinmiş olabilir.';
$labels['error_deleting'] = 'İleti çöp kutusuna taşınamıyor; ileti gönderilmiş, silinmiş veya çöp kutusu kullanılamıyor olabilir.';

$labels['send_message'] = 'Mesaj gönder';
$labels['setting_delay'] = 'Mesaj göndermek için varsayılan gecikme';
$labels['setting_highlight'] = 'Gönderilmek üzere olan zamanlanmış mesajları vurgulayın';

$labels['email_being_sent'] = 'E-posta gönderme';
$labels['send_now'] = 'Şimdi gönder';
$labels['schedule_now'] = 'Şimdi planlayın';
$labels['cancel_sending'] = 'Göndermeyi iptal et';
$labels['setting_countdown'] = 'Mesaj göndermeden önce geri sayım';
$labels['disable_countdown'] = 'Devre dışı bırak';
$labels['3_seconds'] = '3 saniye';
$labels['5_seconds'] = '5 saniye';
$labels['10_seconds'] = '10 saniye';
$labels['15_seconds'] = '15 saniye';

$labels['cannot_schedule_message'] = 'Mesaj zamanlanamıyor:';
$labels['time_has_already_passed'] = 'Planlanan süre çoktan geçti.';
$labels['invalid_time_format'] = 'Geçersiz saat biçimi.';
$labels['draft_folder_not_specified'] = 'E-posta zamanlama eklentisi hatası: Taslak klasörü belirtilmemiş.';
$labels['error'] = 'Hata:';
$labels['attachment_tool_large'] = 'Sunucu yapılandırması zamanlanmış mesaj eklerini $boyut ile sınırlar.';
$labels['message_already_scheduled'] = 'Bu mesaj zaten planlanmıştır.';

