<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Последно влизане';
$labels['setting_show_xlast_login'] = 'Покажи последното влизане';
$labels['country'] = 'Държава';
$labels['city'] = 'Град';
$labels['location'] = 'Местоположение';
$labels['time'] = 'Време';
$labels['map'] = 'Карта';
$labels['more_data'] = 'Повече данни';
$labels['whats_this'] = 'Какво е това?';
$labels['explanation'] = 'Това поле показва местоположението на последното влизане в имейл акаунта ви. Ако не разпознаете това местоположение, паролата ви може да е на злонамерен потребител. Ако това се случи, трябва незабавно да смените паролата си.';
$labels['no_info'] = 'Няма информация за последното влизане, която да се показва. Информацията ще бъде налична следващия път, когато влезете в уеб пощата си.';
