<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Τελευταία σύνδεση';
$labels['setting_show_xlast_login'] = 'Εμφάνιση τελευταίας σύνδεσης';
$labels['country'] = 'Χώρα';
$labels['city'] = 'Πόλη';
$labels['location'] = 'Τοποθεσία';
$labels['time'] = 'Χρόνος';
$labels['map'] = 'Χάρτης';
$labels['more_data'] = 'Περισσότερα στοιχεία';
$labels['whats_this'] = 'Τι είναι αυτό;';
$labels['explanation'] = 'Αυτό το πλαίσιο δείχνει τη θέση της τελευταίας σύνδεσης στο λογαριασμό ηλεκτρονικού ταχυδρομείου σας. Εάν δεν αναγνωρίζετε αυτή τη θέση, ένας κακόβουλος χρήστης μπορεί να έχει τον κωδικό πρόσβασής σας. Αν συμβεί αυτό, θα πρέπει να αλλάξετε αμέσως τον κωδικό πρόσβασής σας.';
$labels['no_info'] = 'Δεν υπάρχουν πληροφορίες τελευταίας σύνδεσης για να εμφανιστούν. Οι πληροφορίες θα είναι διαθέσιμες την επόμενη φορά που θα συνδεθείτε στο webmail σας.';
