<?php

$labels = [];
$labels['last_login'] = 'Dernière connexion';
$labels['setting_show_xlast_login'] = 'Afficher la dernière connexion';
$labels['country'] = 'Pays';
$labels['city'] = 'Ville';
$labels['location'] = 'Emplacement';
$labels['time'] = 'Temps';
$labels['map'] = 'Carte';
$labels['more_data'] = 'Plus de données';
$labels['whats_this'] = 'Qu\'est-ce que c\'est ?';
$labels['explanation'] = 'Cette zone indique l\'emplacement de la dernière connexion à votre compte de messagerie. Si vous ne reconnaissez pas cet emplacement, un utilisateur malveillant pourrait avoir votre mot de passe. Si cela se produit, vous devez changer votre mot de passe immédiatement.';
$labels['no_info'] = 'Il n\'y a pas de dernière information de connexion à afficher. Les informations deviendront disponibles la prochaine fois que vous vous connecterez à votre messagerie Web.';
