<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = '最終ログイン';
$labels['setting_show_xlast_login'] = '最終ログインを表示';
$labels['country'] = '国名';
$labels['city'] = '都市';
$labels['location'] = '所在地';
$labels['time'] = '時間';
$labels['map'] = '地図';
$labels['more_data'] = 'その他のデータ';
$labels['whats_this'] = 'これは何だ？';
$labels['explanation'] = 'このボックスには、メールアカウントに最後にログインした場所が表示されます。この場所がわからない場合、悪意のあるユーザーがあなたのパスワードを知っている可能性があります。このような場合は、すぐにパスワードを変更する必要があります。';
$labels['no_info'] = '最終ログイン情報は表示されません。次回ログイン時に表示されます。';
