<?php

$labels = [];
$labels['last_login'] = 'Ostatnie Logowanie';
$labels['setting_show_xlast_login'] = 'Pokaż Ostatnie Logowanie';
$labels['country'] = 'Kraj';
$labels['city'] = 'Miasto';
$labels['location'] = 'Lokalizacja';
$labels['time'] = 'Data';
$labels['map'] = 'Mapa';
$labels['more_data'] = 'Więcej danych';
$labels['whats_this'] = 'Co to jest?';
$labels['explanation'] = 'Ten obszar pokazuje skąd miało miejsce ostatnie logowanie na twoje konto email. Jeśli nie znasz tej lokalizacji to możliwe, że złośliwy użytkownik poznał twoje hasło. Jeśli taka sytuacja ma miejsce powinieneś jak najszybciej zmienić hasło.';
$labels['no_info'] = 'Nie posiadamy informacji o ostatnim logowaniu. Informacja będzie dostępna, gdy następnym razem zalogujesz się do usługi webmail.';


