<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Ultima autentificare';
$labels['setting_show_xlast_login'] = 'Afișați ultima autentificare';
$labels['country'] = 'Țara';
$labels['city'] = 'Orașul';
$labels['location'] = 'Locație';
$labels['time'] = 'Timp';
$labels['map'] = 'Hartă';
$labels['more_data'] = 'Mai multe date';
$labels['whats_this'] = 'Ce-i asta?';
$labels['explanation'] = 'Această casetă arată locația ultimei autentificări în contul dvs. de e-mail. Dacă nu recunoașteți această locație, este posibil ca un utilizator rău intenționat să dețină parola dumneavoastră. În acest caz, trebuie să vă schimbați imediat parola.';
$labels['no_info'] = 'Nu se afișează ultimele informații de conectare. Informațiile vor fi disponibile data viitoare când vă veți conecta la webmail.';
