<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Senaste inloggning';
$labels['setting_show_xlast_login'] = 'Visa senaste inloggning';
$labels['country'] = 'Land';
$labels['city'] = 'Stad';
$labels['location'] = 'Plats';
$labels['time'] = 'Tid';
$labels['map'] = 'Karta';
$labels['more_data'] = 'Mer data';
$labels['whats_this'] = 'Vad är det här?';
$labels['explanation'] = 'Den här rutan visar platsen för den senaste inloggningen på ditt e-postkonto. Om du inte känner igen den här platsen kan en illvillig användare ha ditt lösenord. Du bör ändra ditt lösenord omedelbart om detta händer.';
$labels['no_info'] = 'Det finns ingen information om senaste inloggning att visa. Informationen blir tillgänglig nästa gång du loggar in på din webbmail.';
