<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'تسجيل الدخول إلى $p';
$labels['all_files'] = 'جميع الملفات';
$labels['shared_files'] = 'الملفات المشتركة';
$labels['select_files'] = 'تحديد الملفات';
$labels['save_file'] = 'احفظ الملف:';
$labels['folder_empty'] = 'هذا المجلد فارغ.';
$labels['no_shares'] = 'لا توجد ملفات مشتركة.';
$labels['cannot_find_directory'] = 'لا يمكن العثور على الدليل.';
$labels['cannot_connect_to_server'] = 'لا يمكن الاتصال بالخادم.';
$labels['cannot_save_attachment'] = 'لا يمكن حفظ المرفق.';
$labels['invalid_login_credentials'] = 'اسم المستخدم أو كلمة المرور غير صالحين.';
$labels['file_saved'] = 'تم حفظ الملف بنجاح.';
$labels['button_insert_link'] = 'إدراج الرابط';
$labels['incorrect_stored_credentials'] = 'لا يمكن تسجيل الدخول إلى الخادم لأن بيانات اعتماد تسجيل الدخول المخزنة غير صحيحة. انقر فوق تسجيل الخروج وأدخل اسم مستخدم وكلمة مرور جديدين.';

// settings
$labels['setting_provider'] = 'المزود';
$labels['setting_auth'] = 'نوع المصادقة';
$labels['setting_url'] = 'عنوان URL WebDAV';
$labels['setting_shared_url'] = 'عنوان URL مشترك WebDAV';
$labels['settings_shared_url_link'] = 'إنشاء من عنوان URL WebDAV';
$labels['specify_webdav_url'] = 'لإنشاء عنوان URL المشترك يجب تحديد عنوان URL الخاص بـ WebDAV.';
