<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Log ind på $p';
$labels['all_files'] = 'Alle filer';
$labels['shared_files'] = 'Delte filer';
$labels['select_files'] = 'Vælg filer';
$labels['save_file'] = 'Gem fil:';
$labels['folder_empty'] = 'Denne mappe er tom.';
$labels['no_shares'] = 'Der er ingen delte filer.';
$labels['cannot_find_directory'] = 'Kan ikke finde mappe.';
$labels['cannot_connect_to_server'] = 'Kan ikke oprette forbindelse til serveren.';
$labels['cannot_save_attachment'] = 'Kan ikke gemme vedhæftede fil.';
$labels['invalid_login_credentials'] = 'Ugyldigt brugernavn eller password.';
$labels['file_saved'] = 'Filen er gemt.';
$labels['button_insert_link'] = 'Indsæt link';
$labels['incorrect_stored_credentials'] = 'Kan ikke logge ind på serveren, fordi de gemte loginoplysninger er forkerte. Klik på Log af, og indtast et nyt brugernavn og en ny adgangskode.';

// settings
$labels['setting_provider'] = 'Udbyder';
$labels['setting_auth'] = 'Godkendelsestype';
$labels['setting_url'] = 'WebDAV-URL';
$labels['setting_shared_url'] = 'WebDAV delt URL';
$labels['settings_shared_url_link'] = 'Opret fra WebDAV-URL';
$labels['specify_webdav_url'] = 'For at oprette den delte URL skal du angive WebDAV-URL\'en.';
