<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Se connecter à $p';
$labels['all_files'] = 'Tous les dossiers';
$labels['shared_files'] = 'Fichiers partagés';
$labels['select_files'] = 'Sélectionner les fichiers';
$labels['save_file'] = 'Sauvegarder le fichier :';
$labels['folder_empty'] = 'Ce dossier est vide.';
$labels['no_shares'] = 'Il n\'y a pas de fichiers partagés.';
$labels['cannot_find_directory'] = 'Impossible de trouver le répertoire.';
$labels['cannot_connect_to_server'] = 'Impossible de se connecter au serveur.';
$labels['cannot_save_attachment'] = 'Impossible d\'enregistrer la pièce jointe.';
$labels['invalid_login_credentials'] = 'Nom d\'utilisateur ou mot de passe invalide.';
$labels['file_saved'] = 'Fichier enregistré avec succès.';
$labels['button_insert_link'] = 'Insérer un lien';
$labels['incorrect_stored_credentials'] = 'Impossible de se connecter au serveur car les informations d\'identification enregistrées sont incorrectes. Cliquez sur Déconnexion et entrez un nouveau nom d\'utilisateur et un nouveau mot de passe.';

// settings
$labels['setting_provider'] = 'Prestataire';
$labels['setting_auth'] = 'Type d\'authentification';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'URL partagée WebDAV';
$labels['settings_shared_url_link'] = 'Créer à partir d\'une URL WebDAV';
$labels['specify_webdav_url'] = 'Afin de créer l\'URL partagée, vous devez spécifier l\'URL WebDAV.';
