<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Prisijungimas prie $p';
$labels['all_files'] = 'Visi failai';
$labels['shared_files'] = 'Bendrai naudojami failai';
$labels['select_files'] = 'Pasirinkite failus';
$labels['save_file'] = 'Išsaugoti failą:';
$labels['folder_empty'] = 'Šis aplankas yra tuščias.';
$labels['no_shares'] = 'Bendrai naudojamų failų nėra.';
$labels['cannot_find_directory'] = 'Nepavyksta rasti katalogo.';
$labels['cannot_connect_to_server'] = 'Nepavyksta prisijungti prie serverio.';
$labels['cannot_save_attachment'] = 'Negalima išsaugoti priedo.';
$labels['invalid_login_credentials'] = 'Netinkamas vartotojo vardas arba slaptažodis.';
$labels['file_saved'] = 'Failas sėkmingai išsaugotas.';
$labels['button_insert_link'] = 'Įterpti nuorodą';
$labels['incorrect_stored_credentials'] = 'Negalima prisijungti prie serverio, nes išsaugoti prisijungimo duomenys yra neteisingi. Spustelėkite Atsijungti ir įveskite naują vartotojo vardą ir slaptažodį.';

// settings
$labels['setting_provider'] = 'Teikėjas';
$labels['setting_auth'] = 'Autentifikavimo tipas';
$labels['setting_url'] = 'WebDAV URL';
$labels['setting_shared_url'] = 'WebDAV bendrinis URL adresas';
$labels['settings_shared_url_link'] = 'Sukurti iš WebDAV URL';
$labels['specify_webdav_url'] = 'Norėdami sukurti bendrinamąjį URL, turite nurodyti WebDAV URL.';
