<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Pieslēgties uz $p';
$labels['all_files'] = 'Visi faili';
$labels['shared_files'] = 'Koplietojamie faili';
$labels['select_files'] = 'Atlasiet failus';
$labels['save_file'] = 'Saglabāt failu:';
$labels['folder_empty'] = 'Šī mape ir tukša.';
$labels['no_shares'] = 'Koplietojamie faili nav koplietojami.';
$labels['cannot_find_directory'] = 'Nevar atrast direktoriju.';
$labels['cannot_connect_to_server'] = 'Nevar izveidot savienojumu ar serveri.';
$labels['cannot_save_attachment'] = 'Nevar saglabāt pielikumu.';
$labels['invalid_login_credentials'] = 'Nederīgs lietotājvārds vai parole.';
$labels['file_saved'] = 'Faili ir veiksmīgi saglabāti.';
$labels['button_insert_link'] = 'Ievietot saiti';
$labels['incorrect_stored_credentials'] = 'Nav iespējams pieteikties serverī, jo saglabātie pieteikšanās akreditācijas dati ir nepareizi. Noklikšķiniet uz Iziet un ievadiet jaunu lietotājvārdu un paroli.';

// settings
$labels['setting_provider'] = 'Nodrošinātājs';
$labels['setting_auth'] = 'Autentifikācijas veids';
$labels['setting_url'] = 'WebDAV URL';
$labels['setting_shared_url'] = 'WebDAV kopīgotais URL';
$labels['settings_shared_url_link'] = 'Izveidot no WebDAV URL';
$labels['specify_webdav_url'] = 'Lai izveidotu koplietojamo URL, jānorāda WebDAV URL.';
