<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Logg inn på $p';
$labels['all_files'] = 'Alle filer';
$labels['shared_files'] = 'Delte filer';
$labels['select_files'] = 'Velg filer';
$labels['save_file'] = 'Lagre fil:';
$labels['folder_empty'] = 'Denne mappen er tom.';
$labels['no_shares'] = 'Det er ingen delte filer.';
$labels['cannot_find_directory'] = 'Finner ikke katalogen.';
$labels['cannot_connect_to_server'] = 'Kan ikke koble til serveren.';
$labels['cannot_save_attachment'] = 'Kan ikke lagre vedlegg.';
$labels['invalid_login_credentials'] = 'Ugyldig brukernavn eller passord.';
$labels['file_saved'] = 'Filen ble lagret.';
$labels['button_insert_link'] = 'Sett inn lenke';
$labels['incorrect_stored_credentials'] = 'Kan ikke logge på serveren fordi den lagrede påloggingsinformasjonen er feil. Klikk på Logg av og skriv inn et nytt brukernavn og passord.';

// settings
$labels['setting_provider'] = 'Tilbyder';
$labels['setting_auth'] = 'Autentiseringstype';
$labels['setting_url'] = 'WebDAV-URL';
$labels['setting_shared_url'] = 'WebDAV delt URL';
$labels['settings_shared_url_link'] = 'Opprett fra WebDAV-URL';
$labels['specify_webdav_url'] = 'For å opprette den delte nettadressen må du angi WebDAV-adressen.';
