<?php
/**
 * Roundcube Plus WebDAV plugin.
 *
 * Copyright 2022, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'WebDAV';
$labels['webdav'] = 'WebDAV';
$labels['login_to_provider'] = 'Iniciar sessão em $p';
$labels['all_files'] = 'Todos os ficheiros';
$labels['shared_files'] = 'Ficheiros partilhados';
$labels['select_files'] = 'Selecionar ficheiros';
$labels['save_file'] = 'Guardar ficheiro:';
$labels['folder_empty'] = 'Esta pasta está vazia.';
$labels['no_shares'] = 'Não existem ficheiros partilhados.';
$labels['cannot_find_directory'] = 'Não é possível encontrar o diretório.';
$labels['cannot_connect_to_server'] = 'Não é possível ligar ao servidor.';
$labels['cannot_save_attachment'] = 'Não é possível guardar o anexo.';
$labels['invalid_login_credentials'] = 'Nome de utilizador ou palavra-passe inválidos.';
$labels['file_saved'] = 'Ficheiro guardado com sucesso.';
$labels['button_insert_link'] = 'Inserir ligação';
$labels['incorrect_stored_credentials'] = 'Não é possível iniciar sessão no servidor porque as credenciais de início de sessão armazenadas estão incorrectas. Clique em Logout e introduza um novo nome de utilizador e palavra-passe.';

// settings
$labels['setting_provider'] = 'Fornecedor';
$labels['setting_auth'] = 'Tipo de autenticação';
$labels['setting_url'] = 'URL WebDAV';
$labels['setting_shared_url'] = 'URL partilhado WebDAV';
$labels['settings_shared_url_link'] = 'Criar a partir de URL WebDAV';
$labels['specify_webdav_url'] = 'Para criar o URL partilhado, é necessário especificar o URL WebDAV.';
