Toutes les réalisations, toutes les richesses gagnées, commencent par une idée. | Napoleon Hill
Ne confondez jamais activité et réalisation. | John Wooden
La réalisation résulte du travail qui réalise l'ambition. | Adam Ant
Les réalisations les plus compliquées de la pensée sont possibles sans l'aide de la conscience. | Sigmund Freud
La grande réalisation naît généralement de grands sacrifices, et n'est jamais le résultat de l'égoïsme. | Napoleon Hill
La mort vient à tous, mais les grandes réalisations construisent un monument qui durera jusqu'à ce que le soleil devienne froid. | Ralph Waldo Emerson
Chérissez vos visions et vos rêves car ils sont les enfants de votre âme ; les plans de vos réalisations ultimes. | Napoleon Hill
Vous devez apprendre les règles du jeu. Et ensuite, vous devez jouer mieux que n'importe qui d'autre. | Albert Einstein
Je suis content de l'avoir fait, en partie parce que ça valait le coup, mais surtout parce que je n'aurai jamais à le refaire. | Mark Twain
Ce n'est pas la montagne que nous conquérons, mais nous-mêmes. | Edmund Hillary
Notre tâche doit être de nous libérer de cette prison en élargissant nos cercles de compassion pour embrasser toutes les créatures vivantes et toute la nature dans sa beauté. | Albert Einstein
La haute réalisation se produit toujours dans le cadre de hautes attentes. | Charles F. Kettering
Vous pouvez avoir tout ce que vous voulez dans la vie, si vous aidez les autres à obtenir ce qu'ils veulent. | Zig Ziglar
Le grand effort jaillit naturellement d'une grande attitude. | Pat Riley
Votre attitude, pas votre aptitude, déterminera votre altitude. | Zig Ziglar
Vous pouvez adopter l'attitude qu'il n'y a rien que vous puissiez faire, ou vous pouvez voir le défi comme votre appel à l'action. | Catherine Pulsifer
Un optimiste est une personne qui voit un feu vert partout, tandis que le pessimiste ne voit que le feu rouge - La personne vraiment sage est daltonienne. | Albert Schweitzer
La pensée positive vous permettra de tout faire mieux que la pensée négative. | Zig Ziglar
Vous ne pouvez pas contrôler ce qui vous arrive, mais vous pouvez contrôler votre attitude envers ce qui vous arrive, et en cela, vous maîtriserez le changement au lieu de le laisser vous maîtriser. | Brian Tracy
Vous pouvez le faire si vous croyez que vous pouvez ! | Napoleon Hill
Si vous ne fixez pas une norme de base pour ce que vous acceptez dans la vie, vous constaterez qu'il est facile de glisser dans des comportements et des attitudes ou une qualité de vie bien en dessous de ce que vous méritez. | Anthony Robbins
Si vous n'aimez pas quelque chose, changez-le. Si vous ne pouvez pas le changer, changez votre attitude. Ne vous plaignez pas. | Maya Angelou
La personne qui envoie des pensées positives active le monde autour de lui de manière positive et attire à lui des résultats positifs. | Norman Vincent Peale
Si votre bonheur dépend de ce que fait quelqu'un d'autre, je suppose que vous avez un problème. | Richard Bach
Se sentir désolé pour soi-même et pour sa condition actuelle n'est pas seulement une perte d'énergie, mais c'est la pire habitude que vous puissiez avoir. | Dale Carnegie
N'importe qui peut faire à peu près tout ce qu'il veut vraiment et qu'il se décide à faire. Nous sommes capables de plus grandes choses que nous ne réalisons. | Norman Vincent Peale
Il y a deux choix principaux dans la vie : accepter les conditions telles qu'elles existent, ou accepter la responsabilité de les changer. | Denis Waitley
La vie, c'est comme jouer du violon en public et apprendre l'instrument au fur et à mesure. | Samuel Butler
La première étape pour obtenir ce que vous voulez dans la vie est la suivante : décidez ce que vous voulez. | Ben Stein
La vie, c'est ce qui vous arrive pendant que vous êtes occupé à faire d'autres projets. | John Lennon
Où vous finissez n'est pas la chose la plus importante. C'est la route que vous prenez pour y arriver. La route que vous prenez est ce sur quoi vous vous retournerez et appellerez votre vie. | Tim Wiley
Il n'y a que deux façons de vivre votre vie. L'une est comme si rien n'était un miracle. L'autre est comme si tout était un miracle. | Albert Einstein
La qualité de la vie d'une personne est en proportion directe avec son engagement envers l'excellence, quelle que soit sa branche d'activité choisie. | Vince Lombardi
La vie n'est qu'un miroir, et ce que vous voyez là-bas, vous devez d'abord le voir en vous. | Wally Amos
Emballer tout ce qu'il y a dans votre vie ; vous ne passez qu'une seule fois par ce chemin ! Asseyez-vous et réfléchissez à ce que vous aimez. Suivez des cours, lisez des livres, trouvez votre passion. | Catherine Pulsifer
Le grand secret de la vie est qu'il n'y a pas de grand secret. Quel que soit votre objectif, vous pouvez y parvenir si vous êtes prêt à travailler. | Oprah Winfrey
La vie doit être vécue et la curiosité maintenue en vie. On ne doit jamais, pour quelque raison que ce soit, tourner le dos à la vie. | Eleanor Roosevelt
Savoir qu'au moins une vie a respiré plus facilement parce que vous avez vécu. C'est avoir réussi. | Ralph Waldo Emerson
Les batailles de la vie ne vont pas toujours à l'homme le plus fort ou le plus rapide. Mais tôt ou tard, l'homme qui gagne est celui qui pense qu'il peut. | Vince Lombardi
Ne soyez pas un spectateur, ne laissez pas la vie vous échapper. | Lou Holtz
La vie est un territoire inexploré. Elle révèle son histoire un moment à la fois. | Leo Buscaglia
Avoir de l'intégrité, c'est aussi avoir du caractère, ce qui est aussi le moyen le plus simple de se heurter à ceux qui n'ont ni l'un ni l'autre. | Byron Pulsifer
Ayez le courage de dire non. Ayez le courage de faire face à la vérité. Faites ce qu'il faut parce que c'est bien. Ce sont les clés magiques pour vivre votre vie avec intégrité. | Mark Twain
Il peut être difficile de maintenir son intégrité dans un monde qui exige que vous changiez avec le vent. | Byron Pulsifer
L'intégrité, c'est ce que nous faisons, ce que nous disons et ce que nous disons que nous faisons. | Don Galer
Aimez tout le monde, faites confiance à quelques-uns, ne faites de mal à personne. | William Shakespeare
Avoir de l'intégrité signifie que vous n'êtes pas d'accord avec tout le monde que vous rencontrez, ni ne cédez à la pression d'être quelque chose qui est en conflit direct avec vos principes de base. | Byron Pulsifer
Le caractère est supérieur à l'intellect. | Ralph Waldo Emerson
Mon grand-père m'a dit un jour qu'il y a deux sortes de personnes : celles qui travaillent et celles qui prennent le crédit. Il m'a dit d'essayer d'être dans le premier groupe ; il y avait moins de concurrence là-bas. | Indira Gandhi
Mais qu'est-ce que le bonheur sinon la simple harmonie entre un homme et la vie qu'il mène ? | Albert Camus
Il n'y a qu'un seul coin de l'univers que vous pouvez être certain d'améliorer, et c'est votre propre personne. | Aldous Huxley
Nous ne devons pas nous laisser devenir comme le système que nous opposons. | Bishop Desmond Tutu
L'intégrité sans connaissance est faible et inutile, et la connaissance sans intégrité est dangereuse et redoutable. | Samuel Johnson
Nous devons souligner que l'intégrité personnelle est aussi importante que les compétences exécutives dans les affaires. | Russell E. Palmer
Quel que soit le moment de la journée, peu importe qui regarde et quelle que soit la situation, l'intégrité personnelle ne prend pas de vacances. | Byron Pulsifer
La sagesse consiste à savoir quoi faire ensuite ; la vertu consiste à le faire. | David Star Jordan
Le caractère consiste à faire ce qu'il faut quand personne ne regarde. Il y a trop de gens qui pensent que la seule chose qui est bien est de s'en sortir, et la seule chose qui est mal est de se faire prendre. | J.C. Watts
Vous ne pouvez pas toujours faire ce qu'il faut, mais vous pouvez toujours faire tout ce que vous faites avec intégrité. | Byron Pulsifer
Ne laissez jamais votre sens moral vous empêcher de faire ce qui est juste. | Isaac Asimov
L'intégrité consiste à conformer la réalité à nos paroles - en d'autres termes, à tenir ses promesses et à remplir ses attentes. | Stephen R. Covey
Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez. | Albert Schweitzer
Vous ne serez jamais heureux si vous continuez à chercher ce qu'est le bonheur. Vous ne vivrez jamais si vous cherchez le sens de la vie. | Albert Camus
La Constitution ne garantit aux Américains que le droit de poursuivre le bonheur. Vous devez l'attraper vous-même. | Benjamin Franklin
Aucune société ne peut sûrement prospérer et être heureuse, dont la plus grande partie des membres est pauvre et misérable. | Adam Smith
Le bonheur est un état d'esprit, pas ce qui est dans votre portefeuille. | Byron Pulsifer
Si vous voulez être heureux, soyez. | Leo Tolstoy
Soyons reconnaissants envers les personnes qui nous rendent heureux ; ce sont les charmants jardiniers qui font fleurir nos âmes. | Marcel Proust
L'homme qui fait dépendre son bonheur de lui-même, et non des autres hommes, a adopté le meilleur plan pour vivre heureux. | Plato
Croyez en vous ! Ayez foi en vos capacités ! Sans une confiance humble mais raisonnable en vos propres pouvoirs, vous ne pouvez pas réussir ou être heureux. | Norman Vincent Peale
Être privé de certaines des choses que vous voulez est une partie indispensable du bonheur. | Bertrand Russell
Mais qu'est-ce que le bonheur sinon la simple harmonie entre un homme et la vie qu'il mène ? | Albert Camus
L'action ne mène pas toujours au bonheur ; mais il n'y a pas de bonheur sans action. | Benjamin Disraeli
La plupart des gens préfèrent être sûrs d'être misérables plutôt que de risquer d'être heureux. | Robert Anthony
Si seulement nous arrêtions d'essayer d'être heureux, nous pourrions passer un bon moment. | Edith Wharton
Que peut-on ajouter au bonheur d'un homme qui est en bonne santé, sans dettes et a la conscience tranquille ? | Adam Smith
L'expérience n'est pas ce qui arrive à un homme. C'est ce que fait un homme avec ce qui lui arrive. | Aldous Leonard Huxley
Le bon jugement vient de l'expérience, et souvent l'expérience vient du mauvais jugement. | Rita Mae Brown
Un esprit qui est étiré par une nouvelle expérience ne peut jamais revenir à ses anciennes dimensions. | Oliver Wendell Holmes, Jr.
Parfois, vous devez faire beaucoup de choses pour déterminer ce que vous ne voulez pas faire. En chemin, vous accumulez beaucoup d'expérience. | Wally Amos
Un homme ne peut pas prendre sa retraite de son expérience. Il doit l'utiliser. L'expérience réalise plus avec moins d'énergie et de temps. | Bernard M. Baruch
La réponse à 'La Plus Grande Génération' et aux livres qui ont suivi a été l'une des expériences les plus satisfaisantes de ma vie. | Tom Brokaw
La célébrité s'en ira, et tant pis, je vous ai eu, la célébrité. Si elle s'en va, j'ai toujours su qu'elle était capricieuse. Donc, au moins, c'est quelque chose que j'ai vécu, mais ce n'est pas là où je vis. | Marilyn Monroe
L'expérience est l'enfant de la pensée, et la pensée est l'enfant de l'action. | Benjamin Disraeli
Je préfère avoir beaucoup de talent et peu d'expérience plutôt que beaucoup d'expérience et peu de talent. | John Wooden
Ne devenez jamais un expert au point d'arrêter d'acquérir de l'expertise. Considérez la vie comme une expérience d'apprentissage continu. | Denis Waitley
La chose la plus belle que nous puissions vivre est le mystérieux. Il est la source de toute véritable art et science. | Albert Einstein
L'expérience n'est pas ce qui vous arrive. C'est ce que vous faites avec ce qui vous arrive. | Aldous Huxley
Avec chaque expérience, vous seul peignez votre propre toile, pensée par pensée, choix par choix. | Oprah Winfrey
En tant que femme, j'ai toujours pensé qu'en vieillissant, nous nous améliorons. Vous vous réconciliez avec vous-même, grâce à des expériences émotionnelles et à la simple sagesse qui vient avec l'âge. | Linda Evans
Nous ne devrions pas regarder en arrière, sauf pour tirer des leçons utiles des erreurs passées, et dans le but de profiter de l'expérience chèrement acquise. | George Washington
La chose la plus douloureuse à vivre n'est pas la défaite mais le regret. | Leo Buscaglia
Aucun homme n'a jamais été aussi complètement habile dans la conduite de la vie, au point de ne pas recevoir de nouvelles informations avec l'âge et l'expérience. | Jonathan Swift
L'art n'est pas un artisanat, c'est la transmission du sentiment que l'artiste a vécu. | Leo Tolstoy
Je pense que tout le monde devrait connaître la défaite au moins une fois dans sa carrière. On en apprend beaucoup. | Lou Holtz
Le secret d'une vie riche est d'avoir plus de commencements que de fins. | Dave Weinbaum
Toutes les choses difficiles ont leur origine dans ce qui est facile, et les grandes choses dans ce qui est petit. | Lao-Tzu
Presque tout vient de rien. | Henry F. Amiel
La nécessité, qui est la mère de l'invention. | Plato
La distance n'est rien ; c'est seulement la première étape qui est difficile. | Marquise du Deffand
Les débuts ne sont difficiles qu'en l'absence d'action. | Byron Pulsifer
Les petites opportunités sont souvent le début de grandes entreprises. | Demosthenes
Un début difficile fait une bonne fin. | John Heywood
Vous n'avez pas besoin d'être génial pour commencer, mais vous devez commencer pour être génial. | Joe Sabah
Beaucoup de gens recherchant de nouveaux débuts n'ont jamais fini avec le passé. | Byron Pulsifer
Chaque jour est un nouveau départ. Traitez-le comme tel. Éloignez-vous de ce qui aurait pu être, et regardez ce qui peut être. | Marsha Petrie Sue
Ce n'est pas la fin. Ce n'est même pas le début de la fin. Mais c'est, peut-être, la fin du début. | Winston Churchill
Quoi que vous fassiez, ou rêviez de faire, commencez-le. La hardiesse a du génie, de la puissance et de la magie en elle. | Goethe
Sauter sur plusieurs petites opportunités peut nous y mener plus rapidement que d'attendre qu'une grande vienne. | Hugh Allen
Il est souvent difficile de distinguer les coups durs de la vie de ceux des opportunités. | Frederick Phillips
La capacité compte peu sans opportunité. | Napoleon
Le secret du succès dans la vie est qu'un homme soit prêt pour son opportunité quand elle se présente. | Benjamin Disraeli
Les opportunités ne sont jamais perdues ; quelqu'un prendra celle que vous manquez. |
Chaque jour est une opportunité de créer une nouvelle fin heureuse. |
Tout ce qui est précieux dans la société humaine dépend de l'opportunité de développement accordée à l'individu. | Albert Einstein
Un pessimiste voit la difficulté dans chaque opportunité ; un optimiste voit l'opportunité dans chaque difficulté. | Winston Churchill
La vie est un cadeau, et elle nous offre le privilège, l'opportunité et la responsabilité de donner quelque chose en retour en devenant plus. | Tony Robbins
L'échelle du succès est mieux gravie en montant les échelons de l'opportunité. | Ayn Rand
La capacité n'est rien sans opportunité. | Napoleon Bonaparte
Votre grande opportunité peut se trouver là où vous êtes maintenant. | Napoleon Hill
Les opportunités viennent dans ma vie et je réponds à celles qui m'attirent. | Wally Amos
Les hommes ne gémissent jamais des opportunités perdues pour faire le bien, seulement des opportunités de faire le mal. | Proverbe grec
Edison a échoué 10 000 fois avant de créer la lumière électrique. Ne soyez pas découragé si vous échouez quelques fois. | Napoleon Hill
Combien de temps devriez-vous essayer ? Jusqu'à. | Jim Rohn
La patience et la persévérance ont un effet magique devant lequel les difficultés disparaissent et les obstacles s'évanouissent. | John Quincy Adams
Par la persévérance, beaucoup de gens remportent le succès de ce qui semblait destiné à être un échec certain. | Benjamin Disraeli
Essayez et échouez, mais n'échouez pas à essayer. | Stephen Kaggwa
Si vous souhaitez réussir dans la vie, faites de la persévérance votre amie intime, de l'expérience votre conseiller avisé, de la prudence votre frère aîné et de l'espoir votre génie gardien. | Joseph Addison
Les grandes œuvres sont accomplies, non par la force, mais par la persévérance. | Samuel Johnson
Je ne pense pas qu'il existe d'autre qualité aussi essentielle au succès de quelque nature que ce soit que la qualité de la persévérance. Elle surmonte presque tout, même la nature. | John D. Rockefeller
Il n'y a pas d'échec sauf dans l'arrêt d'essayer. | Elbert Hubbard
La persistance et la détermination seules sont omnipotentes. Le slogan persévérer a résolu et résoudra toujours les problèmes de la race humaine. | Calvin Coolidge
La victoire appartient à ceux qui persévèrent le plus. | Napoleon Bonaparte
Suivez vos rêves d'un monde meilleur et continuez d'essayer, même lorsqu'il semble y avoir peu d'espoir, car c'est la bonne chose à faire. | Robert Alan
Le génie est la persévérance divine. Je ne peux pas prétendre au génie ni même à une grande intelligence, mais tout le monde peut avoir de la persévérance. | Woodrow Wilson
Dans la confrontation entre le ruisseau et le rocher, le ruisseau gagne toujours - non pas par la force mais par la persévérance. | H. Jackson Brown
La persévérance est plus prévalente que la violence et beaucoup de choses qui ne peuvent être surmontées ensemble cèdent lorsqu'elles sont prises petit à petit. | Plutarch
La persévérance n'est pas une course longue ; ce sont de nombreuses petites courses l'une après l'autre. | Walter Elliot
Les meilleurs d'entre nous ne sont pas plus doués que les autres. Ils font juste de petits pas chaque jour en marchant vers leur plus grande vie. | Robin Sharma, The Greatness Guide
Associez-vous à des hommes de bonne qualité si vous estimez votre propre réputation. Il vaut mieux être seul que mal accompagné. | George Washington
La qualité n'est pas un acte, c'est une habitude. | Aristotle
Si votre niveau de vie est votre principal objectif, la qualité de vie ne s'améliore presque jamais, mais si la qualité de vie est votre objectif numéro un, votre niveau de vie s'améliore presque toujours. | Zig Ziglar
La qualité est une caractéristique souvent abusée par ceux qui cherchent à tromper. | Byron Pulsifer
La qualité signifie bien faire les choses quand personne ne regarde. | Henry Ford
Si vous n'êtes pas sûr de la qualité de votre travail, vous devez d'abord comprendre ce qu'est la qualité. | Byron Pulsifer
La qualité n'est jamais un accident ; elle est toujours le résultat d'un effort intelligent. | John Ruskin
C'est la qualité de notre travail qui plaira à Dieu, pas la quantité. | Mahatma Gandhi
La qualité de la vie d'une personne est en proportion directe avec son engagement envers l'excellence, quelle que soit sa branche d'activité choisie. | Vince Lombardi
La qualité, pas la longévité, de la vie est ce qui est important. | Martin Luther King
Personne ne peut réaliser un succès réel et durable ou "devenir riche" en affaires en étant conformiste. | J. P. Getty
Pour gravir des collines escarpées, il faut d'abord un rythme lent. | William Shakespeare
Il n'y a pas de secret sur le succès. Avez-vous déjà connu un homme réussi qui ne vous en parle pas ? | Kin Hubbard
Le secret du succès de l'homme réside dans sa perspicacité sur les humeurs des gens et sa tactique pour traiter avec eux. | Josiah Gilbert Holland
Il n'y a aucune passion à trouver en jouant petit - en se contentant d'une vie inférieure à celle que vous êtes capable de vivre. | Nelson Mandela
Les objectifs ont fait une différence énorme dans ma vie. Ils m'ont permis de réussir et d'accomplir ce que j'avais auparavant seulement rêvé ou souhaité. | Catherine Pulsifer
Ne confondez jamais mouvement et action. | Ernest Hemmingway
Le succès, c'est obtenir ce que vous voulez. Le bonheur, c'est vouloir ce que vous obtenez. | Dale Carnegie
Dans tout ce que nous faisons, nos propres pensées peuvent nous aider à réussir ou à échouer. Maintenez une attitude positive. | Catherine Pulsifer
La plupart des personnes que j'ai connues qui ont réussi sont celles qui écoutent plus qu'elles ne parlent. | Bernard M. Baruch
Faire un succès du travail en cours est la meilleure étape vers le genre de travail que vous voulez. | Bernard M. Baruch
Vous ne pouvez pas mesurer un homme par ses échecs. Vous devez savoir quel usage il en fait. Que signifiaient-ils pour lui. Qu'en a-t-il tiré. | Orison Swett Marden
Si l'on avance avec confiance dans la direction de son rêve et s'efforce de vivre la vie qu'il a imaginée, il rencontrera un succès inattendu dans des heures ordinaires. | Henry David Thoreau
Le temps est la chose la plus précieuse qu'un homme puisse dépenser. | Theophrastus
Vous avez dû être mis en garde contre le fait de laisser filer les heures dorées ; mais certaines d'entre elles ne sont dorées que parce que nous les laissons filer. | James Matthew Barrie
Si vous voulez que le travail soit bien fait, choisissez un homme occupé, l'autre type n'a pas de temps. | Elbert Hubbard
Le temps est le conseiller le plus sage de tous. | Pericles
Tout ce qui nous appartient vraiment, c'est le temps ; même celui qui n'a rien d'autre en a. | Baltasar Gracian
Le temps est la plus longue distance entre deux endroits. | Tennessee Williams
Rien n'est une perte de temps si vous utilisez l'expérience à bon escient. | Rodin
Nous devons utiliser le temps comme un outil, pas comme une béquille. | John F. Kennedy
Le temps et les mots ne peuvent être rappelés, même s'ils n'étaient qu'hier. | Proverbe yiddish
Le regret des choses que nous avons faites peut être tempéré par le temps ; c'est le regret des choses que nous n'avons pas faites qui est inconsolable. | Sydney J. Harris
Mais quels minutes ! Comptez-les par sensation, et non par calendriers, et chaque moment est un jour. | Benjamin Disraeli
Le temps est la monnaie de votre vie. C'est la seule monnaie que vous avez, et vous seul pouvez déterminer comment elle sera dépensée. Faites attention de ne pas laisser d'autres personnes la dépenser pour vous. | Carl Sandburg
Vous ne trouverez jamais de temps pour quoi que ce soit. Si vous voulez du temps, vous devez le créer. | Charles Buxton
Mieux vaut trois heures trop tôt qu'une minute trop tard. | William Shakespeare
Le temps perdu ne se retrouve jamais. | Benjamin Franklin
Les heures de folie sont mesurées par l'horloge ; mais de la sagesse, aucune horloge ne peut mesurer. | William Blake
Vous ne vous fatiguez jamais à moins de vous arrêter et de prendre le temps pour cela. | Bob Hope
Le temps est le conseiller le plus sage. | Pericles
J'ai perdu du temps, et maintenant le temps me perd. | William Shakespeare
Votre plus grand atout est votre capacité à gagner. Votre plus grande ressource est votre temps. | Brian Tracy
Nous devons utiliser le temps à bon escient et réaliser toujours que le moment est toujours propice pour faire ce qui est juste. | Nelson Mandela
La vie n'est pas mesurée par le nombre de respirations que nous prenons, mais par les moments qui nous coupent le souffle. |
Le meilleur moyen de réaliser vos rêves est de vous réveiller. | Paul Valery
L'une des choses que j'ai apprise à la dure, c'est que ça ne vaut pas la peine de se décourager. | Lucille Ball
L'important est ceci : être capable à tout moment de sacrifier ce que nous sommes ; pour ce que nous pourrions devenir. | Charles Dubois
Tous les conseils du monde ne vous aideront jamais tant que vous ne vous aiderez pas vous-même. | Fred Van Amburgh
Aimer abondamment, c'est vivre abondamment, et aimer pour toujours, c'est vivre pour toujours. | Henry Drummond
Comment vous pensez à un problème est plus important que le problème lui-même. Alors pensez toujours positivement. | Norman Vincent Peale
Oubliez les erreurs passées. Oubliez les échecs. Oubliez tout sauf ce que vous allez faire maintenant et faites-le. | William Durant
Vous pouvez en dire plus sur une personne par ce qu'elle dit des autres que par ce que les autres disent d'elle. | Leo Aikman
Rêvez de grands rêves, puis enfilez votre salopette et allez faire en sorte que les rêves se réalisent. | Fred Van Amburgh
Le mystère de la vie n'est pas un problème à résoudre ; c'est une réalité à vivre. | Aart van der Leenw
Il n'y a qu'un seul coin de l'univers que vous pouvez être certain d'améliorer, et c'est votre propre personne. | Aldous Huxley
La bonne vie est un processus, non un état d'être. C'est une direction, non une destination. | Carl Rogers
Nous sommes ce que nous faisons à plusieurs reprises. L'excellence, alors, n'est pas un acte, mais une habitude. | Aristotle
Lisez non pour contredire et confondre, non pour croire et prendre pour acquis, non pour trouver matière à discussion, mais pour peser et considérer. | Francis Bacon
Une des meilleures façons de persuader les autres est avec vos oreilles, en les écoutant. | Dean Rusk
Si vous avez un ou deux amis avec qui vous pouvez partager vos plus hautes aspirations, vous devez vous considérer comme richement béni. | J. Donald Waters
Plutôt que de souhaiter le changement, vous devez d'abord être prêt à changer. | Catherine Pulsifer
Tout le monde pense à changer le monde, mais personne ne pense à se changer soi-même. | Léon Tolstoï
Le changement est aussi inexorable que le temps, pourtant rien ne rencontre plus de résistance. | Benjamin Disraeli
Seuls les plus sages et les plus stupides des hommes ne changent jamais. | Confucius
Ne cessez jamais d'apprendre, comme ne cessez jamais de changer et de grandir dans votre vie - l'apprentissage vous aide à vous adapter au changement plus facilement. | Citations sur l'apprentissage
Ce que nous pensons détermine ce qui nous arrive, donc si nous voulons changer nos vies, nous devons étirer nos esprits. | Wayne Dyer
Vous ne pouvez pas changer votre destination du jour au lendemain, mais vous pouvez changer de direction du jour au lendemain. | Jim Rohn
Nous sommes souvent déçus à cause de nos attentes. Ce n'est que lorsque vous apprenez à voir les circonstances telles qu'elles sont réellement que vous pouvez devenir l'architecte de l'amélioration. | Greg Henry Quinn
Le seul homme que je connais qui se comporte de manière sensée est mon tailleur ; il prend mes mesures à nouveau chaque fois qu'il me voit. Les autres continuent avec leurs anciennes mesures et s'attendent à ce que je m'y adapte. | George Bernard Shaw
Pas d'action, pas de changement. Action limitée, changement limité. Beaucoup d'action - le changement se produit. | Catherine Pulsifer
Vous êtes toujours libre de changer d'avis et de choisir un avenir différent, ou un passé différent. | Richard Bach
Ne laissez pas les autres changer votre vie, soyez votre propre agent de changement et mettez en œuvre les changements que vous voulez ! Et si un changement inattendu survient dans votre vie, trouvez le positif en lui. | Catherine Pulsifer
Le changement est inévitable. Le changement est constant. | Benjamin Disraeli
Si vous vous sentez déprimé, ne désespérez pas. Le soleil a un sort de coucher chaque nuit, mais il revient chaque matin. Comme je le vois, si vous voulez l'arc-en-ciel, vous devez supporter la pluie. | Dolly Parton
Être testé est bon. La vie mise à l'épreuve peut être le meilleur thérapeute. | Gail Sheehy
Ce ne sont pas les montagnes devant lesquelles vous devez grimper qui vous épuisent ; c'est le caillou dans votre chaussure. | Muhammad Ali
Allez avec ce qui se passe et laissez votre esprit être libre. Restez centré en acceptant ce que vous faites. C'est l'ultime. | Chuang Tzu
Vous n'êtes peut-être pas responsable de vous faire renverser, mais vous êtes certainement responsable de vous relever. | Wally Amos
Je m'efforce d'être sage quand je ne peux pas être joyeux, d'être à l'aise quand je ne peux pas être content, de me contenter de ce qui ne peut pas être réparé et d'être patient quand il n'y a pas de recours. | Elizabeth Montagu
Les mauvaises choses ne sont pas les pires choses qui peuvent nous arriver. "Rien" est la pire chose qui peut nous arriver ! | Richard Bach
La partie ne peut jamais être bien à moins que le tout soit bien. | Platon
Les montagnes ne peuvent être surmontées que par des chemins sinueux. | Johann Wolfgang Von Goethe
Ne sous-estimez jamais votre problème ou votre capacité à y faire face. | Robert H. Schuller
Chaque demain a deux poignées. Nous pouvons le saisir par la poignée de l'anxiété ou la poignée de la foi. | Henry Ward Beecher
Les impossibilités ne sont que des choses que nous n'avons pas encore apprises. | Charles W. Chesnutt
Quand le destin nous donne un citron, essayons de faire de la limonade. | Dale Carnegie
Vous ne le réaliserez peut-être pas quand cela se produit, mais un coup de pied dans les dents peut être la meilleure chose au monde pour vous. | Walt Disney
La grandeur ne réside pas dans la force, mais dans la bonne utilisation de la force. | Henry Ward Beecher
N'ayez pas peur de la grandeur : certains naissent grands, certains atteignent la grandeur, et certains ont la grandeur imposée. | William Shakespeare
Le grand accomplissement naît généralement d'un grand sacrifice, et n'est jamais le résultat de l'égoïsme. | Napoleon Hill
Pour devenir vraiment grand, il faut se tenir avec les gens, pas au-dessus d'eux. | Charles de Montesquieu
Une grande photographie est celle qui exprime pleinement ce que l'on ressent, au plus profond, à propos de ce qui est photographié. | Ansel Adams
Les sommets atteints et gardés par de grands hommes n'ont pas été atteints par un vol soudain mais, tandis que leurs compagnons dormaient, ils peinaient la nuit. | Henry Wadsworth Longfellow
C'est sous la plus grande adversité qu'il existe le plus grand potentiel pour faire du bien, à la fois pour soi-même et pour les autres. | Dalai Lama
Une des plus grandes découvertes qu'un homme fait, l'une de ses grandes surprises, est de découvrir qu'il peut faire ce qu'il avait peur de ne pas pouvoir faire. | Henry Ford
La responsabilité est le prix de la grandeur. | Winston Churchill
La plupart des grandes personnes ont atteint leur plus grand succès juste un pas au-delà de leur plus grand échec. | Napoleon Hill
Aucun grand homme ne se plaint jamais du manque d'opportunités. | Ralph Waldo Emerson
Nourrissez votre esprit de grandes pensées ; croire en l'héroïsme fait des héros. | Benjamin Disraeli
Un grand effort jaillit naturellement d'une grande attitude. | Pat Riley
Risquez plus que les autres ne pensent être sûr. Prenez soin de plus que les autres ne pensent être sage. Rêvez plus que les autres ne pensent être pratique. Attendez plus que les autres ne pensent être possible. | Cadet Maxim
Faites une chose chaque jour qui vous effraie. | Eleanor Roosevelt
Faites confiance à votre propre instinct. Vos erreurs pourraient bien être les vôtres, plutôt que celles de quelqu'un d'autre. | Billy Wilder
Vivre à risque, c'est sauter du haut de la falaise et construire ses ailes en descendant. | Ray Bradbury
On ne découvre pas de nouvelles terres sans consentir à perdre de vue le rivage pendant très longtemps. | André Gide
Attention à ne pas manquer les occasions ; sinon, il pourrait être trop tard un jour. | Franz Liszt
Ceux qui font confiance au hasard doivent se conformer aux résultats du hasard. | Calvin Coolidge
Vous ne vous cognerez jamais les orteils en restant immobile. Plus vous avancez vite, plus il y a de chances de vous cogner les orteils, mais plus vous avez de chances d'arriver quelque part. | Charles F. Kettering
De loin le meilleur prix que la vie ait à offrir est la chance de travailler dur à un travail qui vaut la peine. | Theodore Roosevelt
À mon époque, nous n'avions pas d'estime de soi, nous avions du respect de soi, et pas plus que ce que nous avions gagné. | Jane Haddam
Celui qui se respecte est à l'abri des autres ; il porte une cotte de mailles que personne ne peut percer. | Henry Wadsworth Longfellow
Les personnes que je respecte le plus se comportent comme si elles étaient immortelles et comme si la société était éternelle. | E. M. Forster
Si vous n'avez aucun respect pour vos propres valeurs, comment pouvez-vous être digne de respect des autres. | Byron Pulsifer
Un homme peut supporter beaucoup tant qu'il peut se supporter lui-même. | Axel Munthe
Le respect n'est pas quelque chose que vous pouvez demander, acheter ou emprunter. Le respect est ce que vous gagnez de chaque personne, quel que soit leur milieu ou leur statut. | Byron Pulsifer
Je préfère être vrai avec moi-même, même au risque d'encourir le ridicule des autres, plutôt que d'être faux, et d'encourir ma propre abhorrence. | Frederick Douglass
Si l'on est étranger à soi-même, on est aussi étranger aux autres. Si l'on est hors de contact avec soi-même, alors on ne peut pas toucher les autres. | Anne Morrow Lindbergh
Ils ne peuvent pas enlever notre respect de nous-mêmes si nous ne leur donnons pas. | Mahatma Gandhi
Chaque individu a une place à remplir dans le monde et est important à certains égards, qu'il choisisse de l'être ou non. | Nathaniel Hawthorne
La tragédie est que tant de gens cherchent la confiance en soi et le respect de soi partout sauf en eux-mêmes, et échouent ainsi dans leur recherche. | Nathaniel Branden
Le respect et la confiance ne peuvent jamais être pris pour acquis. Ce sont des attributs qui doivent être prouvés. Ils sont également directement réciproques au comportement des autres. | Elaine Sihera
Regardez tout comme si vous le voyiez pour la première ou la dernière fois. Alors votre temps sur terre sera rempli de gloire. | Betty Smith
Les hommes sages parlent parce qu'ils ont quelque chose à dire ; les fous, parce qu'ils ont à dire quelque chose. | Platon
Quand vous voyez un homme de valeur, pensez à comment vous pouvez l'imiter. Quand vous voyez un homme indigne, examinez-vous. | Confucius
Il y a un appel en chacun de nous, un appel à faire quelque chose, peu importe à quel point c'est impopulaire ou inaperçu, pour rendre le monde meilleur. | Robert K. Cooper
Rien n'est prédestiné : les obstacles de votre passé peuvent devenir les portes qui mènent à de nouveaux commencements. | Ralph Blum
Pouvoir donner des richesses est obligatoire si vous souhaitez les posséder. C'est la seule façon dont vous serez vraiment riche. | Muhammad Ali
Les gens empruntent des routes différentes pour chercher l'épanouissement et le bonheur. Juste parce qu'ils ne sont pas sur votre route ne signifie pas qu'ils se sont perdus. | Dalai Lama
J'ai beaucoup plus de respect pour la personne avec une seule idée qui y arrive que pour la personne avec mille idées qui ne fait rien. | Thomas Edison
Travail et jeu sont des mots utilisés pour décrire la même chose dans des conditions différentes. | Mark Twain
L'homme est le plus riche dont les plaisirs sont les moins chers. | Henry David Thoreau
Vous ne pouvez pas serrer la main avec un poing fermé. | Gandhi
Il faut aimer les gens et leur faire confiance si on ne veut pas faire un gâchis de la vie. | E.M. Forster
Vous ne pouvez pas faire confiance sans risque, mais vous ne pouvez pas non plus vivre dans un cocon. | Byron Pulsifer
Vous pouvez être trompé si vous faites trop confiance, mais vous vivrez dans le tourment à moins de faire suffisamment confiance. | Frank Crane
Nous naissons tous courageux, confiants et gourmands, et la plupart d'entre nous restent gourmands. | Mignon McLaughlin
Qu'y a-t-il dans la politique qui semble ignorer la confiance, sauf au moment des élections ? | Byron Pulsifer
Je dois suivre les gens. Ne suis-je pas leur leader ? | Benjamin Disraeli
Celui qui ne peut obéir, ne peut commander. | Benjamin Franklin
Un bon leader ne peut pas être trop en avance sur ses suiveurs. | Theodore Roosevelt
Le leadership est l'art de faire faire à quelqu'un d'autre ce que vous voulez parce qu'il veut le faire. | Dwight Eisenhower
La clé du leadership réussi aujourd'hui est l'influence, pas l'autorité. | Kenneth Blanchard
Il y a un nombre énorme de gestionnaires qui ont pris leur retraite sur le tas. | Peter F. Drucker
Un bon leader prend un peu plus que sa part du blâme, un peu moins que sa part du crédit. | Arnold H. Glasgow
La gestion, c'est faire les choses correctement ; le leadership, c'est faire les bonnes choses. | Peter F. Drucker
Il n'est pas juste de demander aux autres ce que vous ne voulez pas faire vous-même. | Eleanor Roosevelt
Les leaders ne créent pas des suiveurs, ils créent plus de leaders. | Tom Peters
Le plus grand bien que vous pouvez faire pour un autre n'est pas seulement de partager vos richesses, mais de leur révéler les leurs. | Benjamin Disraeli
On ne dirige pas en frappant les gens sur la tête - c'est une agression, pas du leadership. | Dwight Eisenhower
Un bon objectif de leadership est d'aider ceux qui échouent à réussir et d'aider ceux qui réussissent à réussir encore mieux. | Jim Rohn
Les leaders exceptionnels se démènent pour rehausser l'estime de soi de leur personnel. Si les gens croient en eux-mêmes, c'est incroyable ce qu'ils peuvent accomplir. | Sam Walton
Trop de leaders agissent comme si les moutons... leur peuple... étaient là pour le bénéfice du berger, et non que le berger a la responsabilité des moutons. | Kenneth Blanchard
Le médiocre enseignant raconte. Le bon enseignant explique. Le supérieur enseignant démontre. Le grand enseignant inspire. | William Arthur Ward
Dans le passé, un leader était un patron. Les leaders d'aujourd'hui doivent être des partenaires avec leur peuple... ils ne peuvent plus diriger uniquement sur la base du pouvoir positionnel. | Kenneth Blanchard
La gentillesse est le langage que les sourds peuvent entendre et que les aveugles peuvent voir. | Mark Twain
Vous ne pouvez pas faire une gentillesse trop tôt, car vous ne savez jamais à quel point il sera bientôt trop tard. | Ralph Waldo Emerson
Ma religion est très simple. Ma religion est la gentillesse. | Dalai Lama
S'il y a une gentillesse que je peux montrer, ou une bonne chose que je peux faire pour tout être humain, laissez-moi la faire maintenant, et ne pas la différer ou la négliger, car je ne passerai plus jamais par ici. | William Penn
Vous n'avez pas vécu une journée parfaite, à moins que vous n'ayez fait quelque chose pour quelqu'un qui ne pourra jamais vous le rendre. | Ruth Smeltzer
Quelle sagesse pouvez-vous trouver qui soit plus grande que la gentillesse ? | Jean Jacques Rousseau
Ainsi brille une bonne action dans un monde fatigué. | William Shakespeare
Nos actes nous déterminent, autant que nous déterminons nos actes. | George Eliot
Soyez gentil, car tout le monde que vous rencontrez mène un dur combat. | Platon
Celui qui attend de faire un grand bien d'un seul coup, ne fera jamais rien. | Samuel Johnson
La gentillesse est le soleil sous lequel la vertu pousse. | Robert Green Ingersoll
Visez toujours l'harmonie complète de la pensée, de la parole et de l'acte. Visez toujours à purifier vos pensées et tout ira bien. | Mohandas Gandhi
Celui qui vous a rendu une gentillesse sera plus prêt à vous en faire une autre, que celui que vous avez vous-même obligé. | Benjamin Franklin
La bonté est sans incident. Elle ne scintille pas, elle brille. | David Grayson
Rappelons-nous que, tout comme il nous a été beaucoup donné, il nous sera beaucoup demandé, et que le véritable hommage vient du cœur ainsi que des lèvres, et se montre dans les actes. | Theodore Roosevelt
Une gentillesse offerte spontanément à celui qui en a besoin, est doublement gratifiante. | Jonathan Swift
C'est lorsque vous donnez de vous-même que vous donnez vraiment. | Kahlil Gibran
Faites plus que d'appartenir : participez. Faites plus que vous soucier : aidez. Faites plus que croire : pratiquez. Faites plus que d'être juste : soyez gentil. Faites plus que pardonner : oubliez. Faites plus que rêver : travaillez. | William Arthur Ward
La gentillesse est la chaîne dorée par laquelle la société est liée ensemble. | Johann Wolfgang Von Goethe
La plus petite bonne action vaut mieux que la plus grande intention. | Proverbe japonais
Il n'y a pas de meilleur exercice pour votre cœur que de se pencher et d'aider à soulever quelqu'un. | Bernard Meltzer
La gentillesse peut devenir sa propre motivation. Nous sommes rendus gentils en étant gentils. | Eric Hoffer
La gentillesse engendre la gentillesse. | Proverbe grec
Un cœur gentil est une fontaine de joie, rendant tout ce qui est à sa proximité plus frais en sourires. | Washington Irving
Soyez gentil avec ceux que vous rencontrez en montant, vous pourriez les croiser à nouveau en descendant. | Proverbe irlandais
La possession complète n'est prouvée que par le don. Tout ce que vous ne pouvez pas donner vous possède. | André Gide
Un mot gentil peut réchauffer trois mois d'hiver. | Proverbe japonais
Chaque fois que vous devez faire quelque chose, même si cela ne peut être connu que de vous-même, demandez-vous comment vous agiriez si tout le monde vous regardait et agissez en conséquence. | Thomas Jefferson
La question la plus persistante et urgente de la vie est, Que faites-vous pour les autres ? | Martin Luther King, Jr.
Partout où il y a un être humain, il y a une opportunité de gentillesse. | Sénèque
Les mots gentils peuvent être courts et faciles à dire mais leurs échos sont vraiment infinis. | Mère Teresa
Pouvoir sous toutes les circonstances pratiquer cinq choses constitue la vertu parfaite ; ces cinq choses sont la gravité, la générosité de l'âme, la sincérité, l'ardeur et la gentillesse. | Confucius
Faisons une nouvelle règle de vie à partir de ce soir - essayons toujours d'être un peu plus gentils que nécessaire. | Sir James M. Barrie
Les bonnes actions nous ennoblissent, nous sommes les fils de nos propres actes. | Jean Paul Richter
Si vous n'avez pas de charité dans votre cœur, vous avez le pire genre de problème cardiaque. | Bob Hope
Les mots gentils ouvriront une porte de fer. | Proverbe turc
Cultiver la gentillesse est une partie précieuse des affaires de la vie. | Samuel Johnson
Nous pouvons être rancuniers de notre âge, ou nous pouvons être reconnaissants de l'avoir atteint. | William Arthur Ward
Si vous ne vous contentez de rien de moins que votre meilleur, vous serez étonné de ce que vous pouvez accomplir dans vos vies. | Vince Lombardi
Les grandes esprits ont des objectifs ; les petites esprits ont des souhaits. Les petites esprits sont subjuguées par les malheurs ; les grandes esprits les surmontent. | Washington Irving
Aucun homme ne peut éviter d'être né moyen, mais aucun homme ne doit être commun. | Satchel Paige
Croyez profondément dans votre cœur que vous êtes destiné à accomplir de grandes choses. | Joe Paterno
Nous ne devrions pas regarder en arrière sauf pour tirer des leçons utiles des erreurs passées, et dans le but de profiter de l'expérience chèrement achetée. | George Washington
La terre est remplie de Ciel. | Elizabeth Barrett Browning
Rappelez-vous, l'inspiration suit l'action et non l'inverse. | Aronson, Eric, Dash.
Rappelez-vous que ne pas obtenir ce que vous voulez est parfois un coup de chance merveilleux. | Dalai Lama
Tout arrive à point à qui sait attendre. | Henry Wadsworth Longfellow
Vous voyez, dans la vie, beaucoup de gens savent quoi faire, mais peu de gens font réellement ce qu'ils savent. Savoir ne suffit pas ! Vous devez passer à l'action. | Anthony Robbins
J'aime toujours regarder le côté optimiste de la vie, mais je suis assez réaliste pour savoir que la vie est une affaire complexe. | Walt Disney
Nous nous retrouvons tous dans des situations qui semblent parfois désespérées. Et, nous avons tous le choix de ne rien faire ou d'agir. | Catherine Pulsifer
L'honnêteté est la richesse la plus rare que quelqu'un puisse posséder, et pourtant toute l'honnêteté du monde n'est pas un argent légal pour un pain. | Josh Billings
Oh, quel enchevêtrement nous tissons, lorsque nous pratiquons pour la première fois de tromper ! | Sir Walter Scott
Presque toute la vérité honnête dans le monde est dite par des enfants. | Oliver Wendell Holmes, Jr.
Il est difficile de croire qu'un homme dit la vérité quand vous savez que vous mentiriez si vous étiez à sa place. | Henry Louis Mencken
Nos vies s'améliorent seulement lorsque nous prenons des risques - et le premier et le plus difficile risque que nous pouvons prendre est d'être honnête avec nous-mêmes. | Walter Anderson
Élevons un standard auquel les sages et honnêtes peuvent se réparer ; le reste est entre les mains de Dieu. | George Washington
Aucun héritage n'est aussi riche que l'honnêteté. | William Shakespeare
La meilleure mesure de l'honnêteté d'un homme n'est pas sa déclaration de revenus. C'est le zéro ajustement sur sa balance de salle de bain. | Arthur C. Clarke
L'une des valeurs fondamentales les plus basiques est l'honnêteté. | Catherine Pulsifer
Les pierres de fondation d'un succès équilibré sont l'honnêteté, le caractère, l'intégrité, la foi, l'amour et la loyauté. | Zig Ziglar
La malhonnêteté mettra l'honnêteté en déroute n'importe quel jour de la semaine, s'il y a quelque chose à en tirer. | Charles Dickens
L'honnêteté est le premier chapitre du livre de la sagesse. | Thomas Jefferson
L'intégrité, c'est me dire la vérité. Et l'honnêteté, c'est dire la vérité aux autres. | Spencer Johnson
Soyez préparé et soyez honnête. | John Wooden
Il n'y a pas de zone grise de l'honnêteté dans les affaires. Une chose est soit juste, soit c'est mal. C'est noir ou c'est blanc. | John F. Dodge
Aucun homme n'a une mémoire assez bonne pour faire un menteur réussi. | Abraham Lincoln
Mettez-vous à niveau avec votre enfant en étant honnête. Personne ne repère plus rapidement un faux qu'un enfant. | Mary MacCracken
Soyez idiot. Soyez honnête. Soyez gentil. | Ralph Waldo Emerson
Comme je l'ai dit, la première chose est d'être honnête avec vous-même. | Nelson Mandela
L'honnêteté, c'est craindre une réponse négative et dire la vérité quand même. | Michelle C. Ustaszeski
La concentration est ma devise - d'abord l'honnêteté, puis l'industrie, puis la concentration. | Andrew Carnegie
Un désaccord honnête est souvent un bon signe de progrès. | Gandhi
Le doute, choyé et entretenu, est en danger de devenir un déni ; mais s'il est honnête et orienté vers une enquête approfondie, il peut bientôt mener à une pleine établissement de la vérité. | Ambrose Bierce
