Tutte le realizzazioni, tutte le ricchezze guadagnate, hanno il loro inizio in un'idea. | Napoleon Hill
Non confondere mai l'attività con il risultato. | John Wooden
Il successo deriva dal lavoro che realizza l'ambizione. | Adam Ant
Le realizzazioni più complicate del pensiero sono possibili senza l'assistenza della coscienza. | Sigmund Freud
Il grande successo nasce solitamente da grandi sacrifici, e non è mai il risultato dell'egoismo. | Napoleon Hill
La morte viene per tutti, ma i grandi successi costruiscono un monumento che durerà fino a quando il sole diventerà freddo. | Ralph Waldo Emerson
Coltiva le tue visioni e i tuoi sogni poiché sono i figli della tua anima; i progetti delle tue realizzazioni finali. | Napoleon Hill
Devi imparare le regole del gioco. E poi devi giocare meglio di chiunque altro. | Albert Einstein
Sono felice di averlo fatto, in parte perché ne valeva la pena, ma soprattutto perché non dovrò mai più farlo. | Mark Twain
Non è la montagna che conquisteremo ma noi stessi. | Edmund Hillary
Il nostro compito deve essere quello di liberarci da questa prigione ampliando i nostri circoli di compassione per abbracciare tutte le creature viventi e l'intera natura nella sua bellezza. | Albert Einstein
Il grande successo si verifica sempre nel contesto di alte aspettative. | Charles F. Kettering
Puoi avere tutto ciò che vuoi nella vita, se aiuti le altre persone a ottenere ciò che vogliono. | Zig Ziglar
Il grande impegno nasce naturalmente da un grande atteggiamento. | Pat Riley
Il tuo atteggiamento, non la tua attitudine, determinerà la tua altitudine. | Zig Ziglar
Puoi adottare l'atteggiamento che non c'è nulla che puoi fare, oppure puoi vedere la sfida come il tuo invito all'azione. | Catherine Pulsifer
Un ottimista è una persona che vede una luce verde ovunque, mentre il pessimista vede solo il semaforo rosso - La persona veramente saggia è daltonica. | Albert Schweitzer
Il pensiero positivo ti permetterà di fare tutto meglio del pensiero negativo. | Zig Ziglar
Non puoi controllare ciò che ti accade, ma puoi controllare il tuo atteggiamento verso ciò che ti accade, e in questo modo, dominerai il cambiamento piuttosto che permettergli di dominarti. | Brian Tracy
Puoi farcela se credi di poterci riuscire! | Napoleon Hill
Se non stabilisci uno standard di base per ciò che accetterai nella vita, scoprirai che è facile scivolare in comportamenti e atteggiamenti o in una qualità della vita che è molto al di sotto di ciò che meriti. | Anthony Robbins
Se non ti piace qualcosa, cambiala. Se non puoi cambiarla, cambia il tuo atteggiamento. Non lamentarti. | Maya Angelou
La persona che invia pensieri positivi attiva il mondo intorno a lui in modo positivo e attira a sé risultati positivi. | Norman Vincent Peale
Se la tua felicità dipende da ciò che fa qualcun altro, suppongo che tu abbia un problema. | Richard Bach
Provare pena per te stesso e per la tua condizione attuale non è solo uno spreco di energia, ma il peggior abitudine che potresti mai avere. | Dale Carnegie
Chiunque può fare praticamente qualsiasi cosa con se stesso se lo vuole veramente e si decide a farlo. Siamo capaci di cose più grandi di quanto realizziamo. | Norman Vincent Peale
Ci sono due scelte principali nella vita: accettare le condizioni come esistono, o accettare la responsabilità di cambiarle. | Denis Waitley
La vita è come suonare un violino in pubblico e imparare a suonare mentre si procede. | Samuel Butler
Il primo passo per ottenere ciò che desideri dalla vita è questo: Decidi cosa vuoi. | Ben Stein
La vita è ciò che ti accade mentre sei occupato a fare altri progetti. | John Lennon
Dove finisci non è la cosa più importante. È il cammino che fai per arrivarci. Il cammino che fai è ciò a cui guarderai indietro e chiamerai la tua vita. | Tim Wiley
Ci sono solo due modi per vivere la tua vita. Uno è come se nulla fosse un miracolo. L'altro è come se tutto fosse un miracolo. | Albert Einstein
La qualità della vita di una persona è direttamente proporzionale al suo impegno per l'eccellenza, indipendentemente dal campo di attività scelto. | Vince Lombardi
La vita è solo uno specchio, e ciò che vedi là fuori, devi prima vederlo dentro di te. | Wally Amos
Riempi la tua vita di tutto ciò che c'è; passi solo una volta da questa parte! Siediti e pensa a cosa ti piace. Segui corsi, leggi libri, trova la tua passione. | Catherine Pulsifer
Il grande segreto della vita è che non c'è nessun grande segreto. Qualunque sia il tuo obiettivo, puoi raggiungerlo se sei disposto a lavorare. | Oprah Winfrey
La vita deve essere vissuta e la curiosità mantenuta viva. Non bisogna mai, per nessun motivo, voltare le spalle alla vita. | Eleanor Roosevelt
Sapere che almeno una vita ha respirato più facilmente perché tu hai vissuto. Questo è successo. | Ralph Waldo Emerson
Le battaglie della vita non vanno sempre all'uomo più forte o più veloce. Ma prima o poi l'uomo che vince è quello che pensa di poterci riuscire. | Vince Lombardi
Non essere uno spettatore, non lasciare che la vita ti passi accanto. | Lou Holtz
La vita è territorio inesplorato. Rivela la sua storia un momento alla volta. | Leo Buscaglia
Avere integrità significa anche avere carattere, il che è anche il modo più semplice per entrare in conflitto con coloro che non hanno né l'uno né l'altro. | Byron Pulsifer
Abbi il coraggio di dire di no. Abbi il coraggio di affrontare la verità. Fai la cosa giusta perché è giusta. Questi sono i tasti magici per vivere la tua vita con integrità. | Mark Twain
L'integrità può essere difficile da mantenere in un mondo che ti chiede di cambiare con il vento. | Byron Pulsifer
L'integrità è ciò che facciamo, ciò che diciamo e ciò che diciamo di fare. | Don Galer
Ama tutti, fidati di pochi, non fare del male a nessuno. | William Shakespeare
Avere integrità significa che non sei d'accordo con tutti quelli che incontri, né cedi alla pressione di essere qualcosa che è in diretto conflitto con i tuoi principi etici. | Byron Pulsifer
Il carattere è superiore all'intelletto. | Ralph Waldo Emerson
Mio nonno una volta mi disse che ci sono due tipi di persone: quelli che lavorano e quelli che prendono il merito. Mi disse di cercare di essere nel primo gruppo; c'era meno competizione lì. | Indira Gandhi
Ma cos'è la felicità se non la semplice armonia tra un uomo e la vita che conduce? | Albert Camus
C'è solo un angolo dell'universo che puoi essere certo di migliorare, ed è il tuo stesso io. | Aldous Huxley
Non dobbiamo permettere a noi stessi di diventare come il sistema che opponiamo. | Vescovo Desmond Tutu
L'integrità senza conoscenza è debole e inutile, e la conoscenza senza integrità è pericolosa e terribile. | Samuel Johnson
Dobbiamo sottolineare che l'integrità personale è importante quanto l'abilità esecutiva negli affari. | Russell E. Palmer
Indipendentemente dall'ora del giorno, indipendentemente da chi sta guardando e indipendentemente dalla situazione, l'integrità personale non va in vacanza. | Byron Pulsifer
La saggezza è sapere cosa fare dopo; la virtù è farlo. | David Star Jordan
Il carattere è fare la cosa giusta quando nessuno guarda. Ci sono troppe persone che pensano che l'unica cosa giusta sia cavarsela, e l'unica cosa sbagliata è essere catturati. | J.C. Watts
Non puoi sempre fare la cosa giusta, ma puoi sempre fare qualsiasi cosa tu faccia con integrità. | Byron Pulsifer
Non lasciare mai che il tuo senso morale ti impedisca di fare ciò che è giusto. | Isaac Asimov
L'integrità è conformare la realtà alle nostre parole - in altre parole, mantenere le promesse e soddisfare le aspettative. | Stephen R. Covey
Il successo non è la chiave della felicità. La felicità è la chiave del successo. Se ami quello che fai, avrai successo. | Albert Schweitzer
Non sarai mai felice se continui a cercare in cosa consiste la felicità. Non vivrai mai se cerchi il significato della vita. | Albert Camus
La Costituzione garantisce solo al popolo americano il diritto di perseguire la felicità. Devi catturarla da solo. | Benjamin Franklin
Nessuna società può certamente prosperare e essere felice, di cui la maggior parte dei membri è povera e miserabile. | Adam Smith
La felicità è uno stato mentale, non quello che c'è nel portafoglio. | Byron Pulsifer
Se vuoi essere felice, sii. | Lev Tolstoj
Sii grato alle persone che ti rendono felice; sono i giardinieri affascinanti che fanno fiorire la tua anima. | Marcel Proust
L'uomo che fa dipendere tutto ciò che porta alla felicità da se stesso, e non dagli altri uomini, ha adottato il piano migliore per vivere felicemente. | Platone
Credi in te stesso! Abbi fiducia nelle tue capacità! Senza una fiducia umile ma ragionevole nelle proprie capacità non si può essere di successo né felici. | Norman Vincent Peale
Essere senza alcune delle cose che desideri è una parte indispensabile della felicità. | Bertrand Russell
Ma cos'è la felicità se non la semplice armonia tra un uomo e la vita che conduce? | Albert Camus
L'azione può non portare sempre la felicità; ma non c'è felicità senza azione. | Benjamin Disraeli
La maggior parte delle persone preferirebbe essere sicura di essere infelice piuttosto che rischiare di essere felice. | Robert Anthony
Se solo smettessimo di cercare di essere felici potremmo passare un bel po' di tempo. | Edith Wharton
Cosa può essere aggiunto alla felicità di un uomo che è in salute, senza debiti e ha una coscienza pulita? | Adam Smith
L'esperienza non è ciò che accade a un uomo. È ciò che un uomo fa con ciò che gli accade. | Aldous Leonard Huxley
Il buon giudizio deriva dall'esperienza, e spesso l'esperienza deriva da un cattivo giudizio. | Rita Mae Brown
Una mente che si allunga con una nuova esperienza non può mai tornare alle sue vecchie dimensioni. | Oliver Wendell Holmes, Jr.
A volte devi fare molte cose per determinare cosa è che non vuoi fare. Lungo la strada raccogli molte esperienze. | Wally Amos
Un uomo non può ritirare la sua esperienza. Deve usarla. L'esperienza raggiunge di più con meno energia e tempo. | Bernard M. Baruch
La risposta a 'La Generazione Più Grande' e ai libri che seguirono è stata una delle esperienze più gratificanti della mia vita. | Tom Brokaw
La fama passerà e, addio, ti ho avuto, fama. Se passa, ho sempre saputo che era incostante. Quindi almeno è qualcosa che ho sperimentato, ma non è dove vivo. | Marilyn Monroe
L'esperienza è il figlio del pensiero, e il pensiero è il figlio dell'azione. | Benjamin Disraeli
Preferirei avere molto talento e poca esperienza che molta esperienza e poco talento. | John Wooden
Non diventare mai così esperto da smettere di acquisire competenze. Guarda la vita come un'esperienza di apprendimento continuo. | Denis Waitley
La cosa più bella che possiamo sperimentare è il misterioso. È la fonte di tutta la vera arte e scienza. | Albert Einstein
L'esperienza non è ciò che ti accade. È ciò che fai con ciò che ti accade. | Aldous Huxley
Con ogni esperienza, stai dipingendo la tua tela, pensiero dopo pensiero, scelta dopo scelta. | Oprah Winfrey
Come donna, ho sempre sentito che invecchiando miglioriamo. Veniamo a patti con noi stesse, attraverso esperienze emotive e la semplice saggezza che viene con l'età. | Linda Evans
Non dovremmo guardare indietro se non per trarre lezioni utili dagli errori passati, e per il fine di trarre profitto dall'esperienza pagata a caro prezzo. | George Washington
La cosa più dolorosa da sperimentare non è la sconfitta ma il rimpianto. | Leo Buscaglia
Nessun uomo è mai stato così completamente abile nella conduzione della vita, da non ricevere nuove informazioni dall'età e dall'esperienza. | Jonathan Swift
L'arte non è un mestiere, è la trasmissione del sentimento che l'artista ha vissuto. | Lev Tolstoj
Penso che tutti dovrebbero sperimentare la sconfitta almeno una volta nella loro carriera. Impari molto da essa. | Lou Holtz
Il segreto di una vita ricca è avere più inizi che finali. | Dave Weinbaum
Tutte le cose difficili hanno la loro origine in ciò che è facile, e le grandi cose in ciò che è piccolo. | Lao-Tzu
Quasi tutto viene dal nulla. | Henry F. Amiel
La necessità è la madre dell'invenzione. | Platone
La distanza è nulla; è solo il primo passo che è difficile. | Marquise du Deffand
Gli inizi sono difficili solo senza alcuna azione. | Byron Pulsifer
Le piccole opportunità sono spesso l'inizio di grandi imprese. | Demostene
Un inizio difficile fa un buon finale. | John Heywood
Non devi essere grande per iniziare, ma devi iniziare per essere grande. | Joe Sabah
Molte persone in cerca di nuovi inizi non hanno mai chiuso col passato. | Byron Pulsifer
Ogni giorno è un nuovo inizio. Trattalo in questo modo. Stai lontano da ciò che avrebbe potuto essere, e guarda a ciò che può essere. | Marsha Petrie Sue
Questo non è la fine. Non è nemmeno l'inizio della fine. Ma è, forse, la fine dell'inizio. | Winston Churchill
Qualunque cosa tu faccia, o sogni di poter fare, cominciala. L'audacia ha genio, potere e magia in sé. | Goethe
Saltare su diverse piccole opportunità può portarci lì più rapidamente che aspettare che ne arrivi una grande. | Hugh Allen
Spesso è difficile distinguere tra i colpi duri della vita e quelli delle opportunità. | Frederick Phillips
L'abilità ha poco valore senza opportunità. | Napoleone
Il segreto del successo nella vita è essere pronti per l'opportunità quando arriva. | Benjamin Disraeli
Le opportunità non sono mai perse; qualcuno prenderà quella che hai perso tu. |
Ogni giorno è un'opportunità per fare un nuovo lieto fine. |
Tutto ciò che è prezioso nella società umana dipende dall'opportunità di sviluppo concessa all'individuo. | Albert Einstein
Un pessimista vede la difficoltà in ogni opportunità; un ottimista vede l'opportunità in ogni difficoltà. | Winston Churchill
La vita è un dono, e ci offre il privilegio, l'opportunità e la responsabilità di restituire qualcosa diventando di più. | Tony Robbins
La scala del successo si scala meglio salendo sui gradini delle opportunità. | Ayn Rand
L'abilità non è nulla senza opportunità. | Napoleone Bonaparte
La tua grande opportunità può essere proprio dove sei ora. | Napoleon Hill
Le opportunità entrano nella mia vita e rispondo a quelle che mi attraggono. | Wally Amos
Gli uomini non si lamentano mai delle opportunità perse per fare del bene, solo delle opportunità per essere cattivi. | Proverbio greco
Edison fallì 10.000 volte prima di inventare la luce elettrica. Non scoraggiarti se fallisci qualche volta. | Napoleon Hill
Per quanto tempo dovresti provare? Finché. | Jim Rohn
La pazienza e la perseveranza hanno un effetto magico davanti al quale le difficoltà scompaiono e gli ostacoli svaniscono. | John Quincy Adams
Attraverso la perseveranza molte persone ottengono il successo da ciò che sembrava destinato a essere un fallimento certo. | Benjamin Disraeli
Prova e fallisci, ma non smettere di provare. | Stephen Kaggwa
Se desideri il successo nella vita, fai della perseveranza il tuo amico del cuore, dell'esperienza il tuo consigliere saggio, della prudenza il tuo fratello maggiore e della speranza il tuo genio guardiano. | Joseph Addison
Le grandi opere non sono realizzate con la forza, ma con la perseveranza. | Samuel Johnson
Non credo che ci sia altra qualità così essenziale al successo di qualsiasi tipo come la qualità della perseveranza. Supera quasi tutto, persino la natura. | John D. Rockefeller
Non c'è fallimento se non nel non provare più. | Elbert Hubbard
La persistenza e la determinazione da sole sono onnipotenti. Lo slogan "continua" ha risolto e risolverà sempre i problemi della razza umana. | Calvin Coolidge
La vittoria appartiene a chi persevera di più. | Napoleone Bonaparte
Segui i tuoi sogni di un mondo migliore, e continua a provare, anche quando sembra esserci poca speranza, perché è la cosa giusta da fare. | Robert Alan
Il genio è divina perseveranza. Non posso vantare il genio né una luminosità eccezionale, ma la perseveranza tutti possono averla. | Woodrow Wilson
Nello scontro tra il torrente e la roccia, il torrente vince sempre - non attraverso la forza ma attraverso la perseveranza. | H. Jackson Brown
La perseveranza è più prevalente della violenza e molte cose che non possono essere superate quando sono insieme si arrendono quando vengono prese poco a poco. | Plutarco
La perseveranza non è una lunga corsa; è molte brevi corse una dopo l'altra. | Walter Elliot
I migliori tra noi non sono più dotati degli altri. Fanno solo piccoli passi ogni giorno mentre avanzano verso la loro vita più grande. | Robin Sharma, The Greatness Guide
Associa te stesso con uomini di buona qualità se stimi la tua reputazione. È meglio essere soli che in cattiva compagnia. | George Washington
La qualità non è un atto, è un'abitudine. | Aristotele
Se lo standard di vita è il tuo obiettivo principale, la qualità della vita quasi mai migliora, ma se la qualità della vita è il tuo obiettivo numero uno, il tuo standard di vita quasi sempre migliora. | Zig Ziglar
La qualità è un attributo abbastanza spesso abusato da coloro che cercano di ingannare. | Byron Pulsifer
La qualità significa fare bene quando nessuno guarda. | Henry Ford
Se non sei sicuro della qualità del tuo lavoro, devi prima capire cosa sia la qualità. | Byron Pulsifer
La qualità non è mai un caso; è sempre il risultato di uno sforzo intelligente. | John Ruskin
È la qualità del nostro lavoro che piacerà a Dio, non la quantità. | Mahatma Gandhi
La qualità della vita di una persona è direttamente proporzionale al suo impegno per l'eccellenza, indipendentemente dal campo di attività scelto. | Vince Lombardi
La qualità, non la longevità, della vita di una persona è ciò che è importante. | Martin Luther King
Nessuno può ottenere un vero successo duraturo o "arricchirsi" negli affari essendo un conformista. | J. P. Getty
Scalare colline ripide richiede un ritmo lento all'inizio. | William Shakespeare
Non c'è segreto sul successo. Hai mai conosciuto un uomo di successo che non ti raccontasse di esso? | Kin Hubbard
Il segreto del successo di un uomo risiede nella sua capacità di capire gli umori delle persone e nella sua tattica nel trattare con loro. | Josiah Gilbert Holland
Non c'è passione nel giocare piccolo - nell'accontentarsi di una vita che è meno di quella che sei capace di vivere. | Nelson Mandela
Gli obiettivi hanno fatto una differenza enorme nella mia vita. Mi hanno permesso di raggiungere il successo, e di realizzare ciò che avevo precedentemente solo sognato, o desiderato. | Catherine Pulsifer
Non confondere mai il movimento con l'azione. | Ernest Hemmingway
Il successo è ottenere ciò che vuoi. La felicità è volere ciò che ottieni. | Dale Carnegie
In tutto ciò che facciamo, i nostri stessi pensieri possono aiutarci a riuscire, o possono aiutarci a fallire. Mantieni un atteggiamento positivo. | Catherine Pulsifer
La maggior parte delle persone di successo che ho conosciuto sono quelle che ascoltano di più di quanto parlino. | Bernard M. Baruch
Fare un successo del lavoro che hai in mano è il miglior passo verso quello che desideri. | Bernard M. Baruch
Non puoi misurare un uomo dai suoi fallimenti. Devi sapere che uso ne fa. Cosa significano per lui. Cosa ne ha ricavato. | Orison Swett Marden
Se uno avanza con fiducia nella direzione del suo sogno, e si sforza di vivere la vita che ha immaginato, incontrerà un successo inaspettato nelle ore comuni. | Henry David Thoreau
Il tempo è la cosa più preziosa che un uomo può spendere. | Teofrasto
Devi essere stato avvertito contro lasciare scivolare via le ore d'oro; ma alcune di esse sono d'oro solo perché le lasciamo scivolare via. | James Matthew Barrie
Se vuoi un lavoro ben fatto, scegli un uomo occupato, l'altro tipo non ha tempo. | Elbert Hubbard
Il tempo è il più saggio consigliere di tutti. | Pericle
Tutto ciò che veramente ci appartiene è il tempo; anche chi non ha altro ha quello. | Baltasar Gracián
Il tempo è la distanza più lunga tra due luoghi. | Tennessee Williams
Nulla è una perdita di tempo se usi saggiamente l'esperienza. | Rodin
Dobbiamo usare il tempo come uno strumento, non come una stampella. | John F. Kennedy
Il tempo e le parole non possono essere richiamati, anche se era solo ieri. | Proverbio Yiddish
Il rimpianto per le cose che abbiamo fatto può essere temperato dal tempo; è il rimpianto per le cose che non abbiamo fatto che è inconsolabile. | Sydney J. Harris
Ma che minuti! Contali per sensazione, e non per calendari, e ogni momento è un giorno. | Benjamin Disraeli
Il tempo è la moneta della tua vita. È l'unica moneta che hai, e solo tu puoi determinare come verrà spesa. Fai attenzione che altre persone non la spendano per te. | Carl Sandburg
Non troverai mai il tempo per nulla. Se vuoi tempo, devi farlo. | Charles Buxton
Meglio tre ore troppo presto che un minuto troppo tardi. | William Shakespeare
Il tempo perso non si trova mai più. | Benjamin Franklin
Le ore di follia sono misurate dall'orologio; ma della saggezza, nessun orologio può misurare. | William Blake
Non ti stanchi mai a meno che tu non ti fermi e ti prenda il tempo per farlo. | Bob Hope
Il tempo è il più saggio consigliere. | Pericle
Ho sprecato tempo, e ora il tempo spreca me. | William Shakespeare
Il tuo più grande bene è la tua capacità di guadagno. La tua più grande risorsa è il tuo tempo. | Brian Tracy
Dobbiamo usare il tempo saggiamente e sempre rendersi conto che il momento è sempre maturo per fare la cosa giusta. | Nelson Mandela
La vita non è misurata dal numero di respiri che prendiamo, ma dai momenti che ci tolgono il respiro. |
Il modo migliore per realizzare i tuoi sogni è svegliarti. | Paul Valery
Una delle cose che ho imparato a caro prezzo è che non conviene scoraggiarsi. | Lucille Ball
La cosa importante è questa: essere in grado in qualsiasi momento di sacrificare ciò che siamo; per ciò che potremmo diventare. | Charles Dubois
Tutti i consigli del mondo non ti aiuteranno mai fino a quando non ti aiuterai tu stesso. | Fred Van Amburgh
Amare abbondantemente è vivere abbondantemente, e amare per sempre è vivere per sempre. | Henry Drummond
Il modo in cui pensi a un problema è più importante del problema stesso. Quindi pensa sempre positivamente. | Norman Vincent Peale
Dimentica gli errori del passato. Dimentica i fallimenti. Dimentica tutto tranne ciò che stai per fare ora e fallo. | William Durant
Puoi dire di più su una persona da ciò che dice degli altri che da ciò che gli altri dicono di lui. | Leo Aikman
Sogna grandi sogni, poi indossa la tua tuta da lavoro e vai a realizzare quei sogni. | Fred Van Amburgh
Il mistero della vita non è un problema da risolvere; è una realtà da vivere. | Aart van der Leenw
C'è solo un angolo dell'universo che puoi essere certo di migliorare, ed è il tuo stesso io. | Aldous Huxley
La buona vita è un processo, non uno stato dell'essere. È una direzione, non una destinazione. | Carl Rogers
Siamo ciò che facciamo ripetutamente. L'eccellenza, quindi, non è un atto, ma un'abitudine. | Aristotele
Leggi non per contraddire e confutare, non per credere e dare per scontato, non per trovare discussioni e discorsi, ma per pesare e considerare. | Francis Bacon
Uno dei modi migliori per persuadere gli altri è con le tue orecchie, ascoltandoli. | Dean Rusk
Se hai solo uno o due amici con cui puoi condividere le tue aspirazioni più alte, dovresti considerarti riccamente benedetto. | J. Donald Waters
Piuttosto che desiderare il cambiamento, devi prima essere disposto a cambiare. | Catherine Pulsifer
Tutti pensano di cambiare il mondo, ma nessuno pensa di cambiare se stesso. | Lev Tolstoj
Il cambiamento è inesorabile come il tempo, ma niente incontra più resistenza. | Benjamin Disraeli
Solo i più saggi e i più sciocchi degli uomini non cambiano mai. | Confucio
Non smettere mai di imparare, come non smettere mai di cambiare e crescere nella tua vita - l'apprendimento ti aiuta ad adattarti al cambiamento più facilmente. | Citazioni di apprendimento
Ciò che pensiamo determina ciò che ci accade, quindi se vogliamo cambiare le nostre vite, dobbiamo allungare le nostre menti. | Wayne Dyer
Non puoi cambiare la tua destinazione da un giorno all'altro, ma puoi cambiare la tua direzione da un giorno all'altro. | Jim Rohn
Spesso siamo delusi a causa delle nostre aspettative. Solo quando impari a vedere le circostanze per quello che sono veramente puoi diventare l'architetto del miglioramento. | Greg Henry Quinn
L'unico uomo che conosco che si comporta sensatamente è il mio sarto; prende le mie misure ogni volta che mi vede. Gli altri continuano con le loro vecchie misure e si aspettano che io mi adatti a loro. | George Bernard Shaw
Nessuna azione, nessun cambiamento. Azione limitata, cambiamento limitato. Tante azioni - Il cambiamento avviene. | Catherine Pulsifer
Sei sempre libero di cambiare idea e scegliere un futuro diverso, o un passato diverso. | Richard Bach
Non lasciare che gli altri cambino la tua vita, sii il tuo agente di cambiamento e implementa i cambiamenti che desideri! E se si verifica un cambiamento inaspettato nella tua vita, trova il lato positivo in esso. | Catherine Pulsifer
Il cambiamento è inevitabile. Il cambiamento è costante. | Benjamin Disraeli
Se ti senti giù, non disperare. Il sole ha un incantesimo ogni notte, ma torna su ogni mattina. Dal mio punto di vista, se vuoi l'arcobaleno, devi sopportare la pioggia. | Dolly Parton
Essere messi alla prova è positivo. La vita sfidante può essere il miglior terapeuta. | Gail Sheehy
Non sono le montagne davanti a noi da scalare che ci sfiniscono; è il sassolino nella scarpa. | Mahummad Ali
Fluisci con tutto ciò che sta accadendo e lascia che la tua mente sia libera. Resta centrato accettando qualunque cosa tu stia facendo. Questo è l'ultimo. | Chuang Tzu
Potresti non essere responsabile per essere abbattuto, ma sei certamente responsabile per rialzarti. | Wally Amos
Cerco di essere saggio quando non posso essere allegro, di essere sereno quando non posso essere felice, di essere contento di ciò che non può essere aggiustato e di essere paziente quando non c'è rimedio. | Elizabeth Montagu
Le cose brutte non sono le peggiori cose che ci possono accadere. "Nulla" è la peggior cosa che ci può accadere! | Richard Bach
La parte non può stare bene se il tutto non sta bene. | Platone
Le montagne non possono essere superate se non per sentieri tortuosi. | Johann Wolfgang Von Goethe
Non sottovalutare mai il tuo problema o la tua capacità di affrontarlo. | Robert H. Schuller
Ogni domani ha due manici. Possiamo afferrarlo con il manico dell'ansia o con il manico della fede. | Henry Ward Beecher
Le impossibilità sono solo cose che non abbiamo ancora imparato. | Charles W. Chesnutt
Quando il destino ci dà un limone, proviamo a fare la limonata. | Dale Carnegie
Potresti non rendertene conto quando accade, ma un calcio nei denti potrebbe essere la cosa migliore del mondo per te. | Walt Disney
La grandezza non risiede nell'essere forti, ma nell'uso corretto della forza. | Henry Ward Beecher
Non temere la grandezza: alcuni nascono grandi, alcuni raggiungono la grandezza e alcuni hanno la grandezza imposta su di loro. | William Shakespeare
Il grande successo nasce solitamente da grandi sacrifici, e non è mai il risultato dell'egoismo. | Napoleon Hill
Per diventare veramente grandi, bisogna stare con le persone, non al di sopra di loro. | Marleen Charles de Montesquieu
Una grande fotografia è quella che esprime completamente ciò che si sente, nel senso più profondo, riguardo a ciò che viene fotografato. | Ansel Adams
Le altezze raggiunte e mantenute da grandi uomini non sono state ottenute con un volo improvviso ma, mentre i loro compagni dormivano, stavano faticando verso l'alto nella notte. | Henry Wadsworth Longfellow
È nella più grande avversità che esiste il più grande potenziale per fare del bene, sia per se stessi che per gli altri. | Dalai Lama
Una delle più grandi scoperte che un uomo fa, una delle sue grandi sorprese, è scoprire che può fare ciò che temeva di non poter fare. | Henry Ford
La responsabilità è il prezzo della grandezza. | Winston Churchill
La maggior parte delle grandi persone ha raggiunto il loro più grande successo solo un passo oltre il loro più grande fallimento. | Napoleon Hill
Nessun grande uomo si lamenta mai della mancanza di opportunità. | Ralph Waldo Emerson
Nutri la tua mente con grandi pensieri; credere nell'eroico crea eroi. | Benjamin Disraeli
Il grande impegno nasce naturalmente da un grande atteggiamento. | Pat Riley
Rischia più di quanto gli altri pensano sia sicuro. Preoccupati più di quanto gli altri pensano sia saggio. Sogna più di quanto gli altri pensano sia pratico. Aspettati più di quanto gli altri pensano sia possibile. | Cadet Maxim
Fai una cosa ogni giorno che ti spaventa. | Eleanor Roosevelt
Fidati del tuo istinto. I tuoi errori potrebbero essere i tuoi, invece che di qualcun altro. | Billy Wilder
Vivere a rischio è saltare dal precipizio e costruire le ali durante la caduta. | Ray Bradbury
Non si scoprono nuove terre senza acconsentire a perdere di vista la riva per molto tempo. | André Gide
Attenzione a perdere occasioni; altrimenti potrebbe essere troppo tardi un giorno. | Franz Liszt
Chi si fida del caso deve sopportare i risultati del caso. | Calvin Coolidge
Non ti prenderai mai uno spigolo stando fermo. Più velocemente vai, più c'è la possibilità di prenderne uno, ma più c'è la possibilità di arrivare da qualche parte. | Charles F. Kettering
Di gran lunga il miglior premio che la vita ha da offrire è la possibilità di lavorare sodo a un lavoro che vale la pena fare. | Theodore Roosevelt
Ai miei tempi, non avevamo l'autostima, avevamo il rispetto per noi stessi, e non più di quanto ce ne fossimo guadagnati. | Jane Haddam
Chi rispetta se stesso è al sicuro dagli altri; indossa una cotta di maglia che nessuno può perforare. | Henry Wadsworth Longfellow
Le persone che rispetto di più si comportano come se fossero immortali e come se la società fosse eterna. | E. M. Forster
Se non rispetti i tuoi valori, come puoi essere degno di rispetto dagli altri. | Byron Pulsifer
Un uomo può sopportare molto finché può sopportare se stesso. | Axel Munthe
Il rispetto non è qualcosa che puoi chiedere, comprare o prendere in prestito. Il rispetto è ciò che guadagni da ogni persona indipendentemente dal loro background o status. | Byron Pulsifer
Preferisco essere fedele a me stesso, anche a rischio di incorrere nel ridicolo degli altri, piuttosto che essere falso e incorrere nella mia stessa ripugnanza. | Frederick Douglass
Se uno è estraniato da se stesso, allora è estraniato anche dagli altri. Se uno è fuori contatto con se stesso, allora non può toccare gli altri. | Anne Morrow Lindbergh
Non possono togliere il nostro rispetto per noi stessi se non lo diamo loro. | Mahatma Gandhi
Ogni individuo ha un posto nel mondo ed è importante in qualche misura, che lo scelga o no. | Nathaniel Hawthorne
La tragedia è che molte persone cercano fiducia in se stessi e rispetto per se stessi ovunque tranne che dentro di sé, e quindi falliscono nella loro ricerca. | Nathaniel Branden
Il rispetto e la fiducia non possono mai essere dati per scontati. Sono attributi che devono essere dimostrati. Sono anche direttamente reciproci al comportamento degli altri. | Elaine Sihera
Guarda tutto come se lo stessi vedendo per la prima o ultima volta. Allora il tuo tempo sulla terra sarà pieno di gloria. | Betty Smith
I saggi parlano perché hanno qualcosa da dire; gli sciocchi, perché devono dire qualcosa. | Platone
Quando vedi un uomo di valore, pensa a come puoi emularlo. Quando vedi uno indegno, esamina te stesso. | Confucio
C'è una chiamata dentro ognuno di noi, una chiamata a fare qualcosa, per quanto impopolare o inosservato, per rendere il mondo un posto migliore. | Robert K. Cooper
Nulla è predestinato: Gli ostacoli del tuo passato possono diventare le porte che portano a nuovi inizi. | Ralph Blum
Essere in grado di dare via le ricchezze è obbligatorio se desideri possederle. Questo è l'unico modo in cui sarai veramente ricco. | Mahummad Ali
Le persone percorrono strade diverse alla ricerca della realizzazione e della felicità. Solo perché non sono sulla tua strada non significa che si siano persi. | Dalai Lama
Ho molto più rispetto per la persona con un'idea singola che arriva lì che per la persona con mille idee che non fa nulla. | Thomas Edison
Lavoro e gioco sono parole usate per descrivere la stessa cosa in condizioni diverse. | Mark Twain
L'uomo è più ricco i cui piaceri sono più economici. | Henry David Thoreau
Non puoi stringere la mano con un pugno chiuso. | Gandhi
Bisogna essere affezionati alle persone e fidarsi di loro se non si vuole fare un pasticcio della vita. | E.M. Forster
Non puoi fidarti senza rischiare, ma non puoi neanche vivere in un bozzolo. | Byron Pulsifer
Potresti essere ingannato se ti fidi troppo, ma vivrai nel tormento se non ti fidi abbastanza. | Frank Crane
Siamo tutti nati coraggiosi, fiduciosi e avidi, e la maggior parte di noi rimane avida. | Mignon McLaughlin
Cosa c'è nella politica che sembra ignorare la fiducia tranne che al momento delle elezioni? | Byron Pulsifer
Devo seguire le persone. Non sono il loro leader? | Benjamin Disraeli
Chi non può obbedire, non può comandare. | Benjamin Franklin
Un buon leader non può andare troppo avanti rispetto ai suoi seguaci. | Theodore Roosevelt
La leadership è l'arte di far fare a qualcun altro qualcosa che tu vuoi fatto perché lui vuole farlo. | Dwight Eisenhower
La chiave per una leadership di successo oggi è l'influenza, non l'autorità. | Kenneth Blanchard
C'è un numero enorme di manager che sono andati in pensione sul lavoro. | Peter F. Drucker
Un buon leader prende un po' più della sua parte di colpa, un po' meno della sua parte di merito. | Arnold H. Glasgow
Il management è fare le cose bene; la leadership è fare le cose giuste. | Peter F. Drucker
Non è giusto chiedere agli altri ciò che non sei disposto a fare tu stesso. | Eleanor Roosevelt
I leader non creano seguaci, creano più leader. | Tom Peters
Il massimo bene che puoi fare per un altro non è solo condividere le tue ricchezze, ma rivelargli le sue proprie. | Benjamin Disraeli
Non guidi colpendo le persone sulla testa - questo è un assalto, non leadership. | Dwight Eisenhower
Un buon obiettivo della leadership è aiutare coloro che stanno andando male a fare bene e aiutare coloro che stanno andando bene a fare ancora meglio. | Jim Rohn
I leader eccezionali si sforzano di aumentare l'autostima del loro personale. Se le persone credono in se stesse, è sorprendente ciò che possono realizzare. | Sam Walton
Troppi leader agiscono come se le pecore... il loro popolo... fossero lì per il beneficio del pastore, non che il pastore abbia responsabilità per le pecore. | Kenneth Blanchard
L'insegnante mediocre racconta. L'insegnante buono spiega. L'insegnante superiore dimostra. L'insegnante grande ispira. | William Arthur Ward
In passato un leader era un capo. I leader di oggi devono essere partner con il loro popolo... non possono più guidare solo sulla base del potere di posizione. | Kenneth Blanchard
La gentilezza è la lingua che i sordi possono sentire e i ciechi possono vedere. | Mark Twain
Non puoi fare una gentilezza troppo presto, perché non sai mai quanto presto sarà troppo tardi. | Ralph Waldo Emerson
La mia religione è molto semplice. La mia religione è la gentilezza. | Dalai Lama
Se c'è qualche gentilezza che posso mostrare, o qualche buona cosa che posso fare a qualsiasi mio simile, lasciami farlo ora, e non rimandare o trascurare, poiché non passerò di nuovo da questa parte. | William Penn
Non hai vissuto una giornata perfetta, a meno che tu non abbia fatto qualcosa per qualcuno che non potrà mai ripagarti. | Ruth Smeltzer
Quale saggezza puoi trovare che è più grande della gentilezza? | Jean Jacques Rousseau
Così splende una buona azione in un mondo stanco. | William Shakespeare
Le nostre azioni ci determinano, tanto quanto noi determiniamo le nostre azioni. | George Eliot
Sii gentile, perché ognuno che incontri sta combattendo una dura battaglia. | Platone
Chi aspetta di fare un grande bene tutto in una volta, non farà mai nulla. | Samuel Johnson
La gentilezza è il sole in cui cresce la virtù. | Robert Green Ingersoll
Mira sempre alla completa armonia di pensiero, parola e azione. Mira sempre a purificare i tuoi pensieri e tutto andrà bene. | Mohandas Gandhi
Chi ti ha fatto un favore sarà più pronto a fartene un altro, rispetto a colui al quale hai fatto un favore tu stesso. | Benjamin Franklin
La bontà è priva di eventi. Non lampeggia, brilla. | David Grayson
Ricordiamo che, come molto ci è stato dato, molto sarà richiesto da noi, e che il vero omaggio viene dal cuore così come dalle labbra, e si manifesta nelle azioni. | Theodore Roosevelt
Una gentilezza spontaneamente offerta a chi ne ha bisogno, è doppiamente gratificante. | Jonathan Swift
È quando doni te stesso che doni veramente. | Kahlil Gibran
Fai più che appartenere: partecipa. Fai più che interessarti: aiuta. Fai più che credere: pratica. Fai più che essere equo: sii gentile. Fai più che perdonare: dimentica. Fai più che sognare: lavora. | William Arthur Ward
La gentilezza è la catena d'oro con cui la società è legata insieme. | Johann Wolfgang Von Goethe
Il più piccolo buon atto è meglio della più grande buona intenzione. | Proverbio giapponese
Non c'è miglior esercizio per il tuo cuore che raggiungere in basso e aiutare a sollevare qualcuno. | Bernard Meltzer
La gentilezza può diventare il suo stesso motivo. Siamo resi gentili essendo gentili. | Eric Hoffer
La gentilezza genera gentilezza. | Proverbio greco
Un cuore gentile è una fontana di gioia, che fa rifiorire tutto ciò che lo circonda in sorrisi. | Washington Irving
Sii gentile con coloro che incontri mentre sali, potresti rincontrarli quando scendi. | Proverbio irlandese
Il possesso completo è dimostrato solo dando. Tutto ciò che non sei in grado di dare ti possiede. | Andre Gide
Una parola gentile può scaldare tre mesi d'inverno. | Proverbio giapponese
Ogni volta che devi fare una cosa, anche se può essere conosciuta solo da te stesso, chiediti come agiresti se tutto il mondo ti stesse guardando e agisci di conseguenza. | Thomas Jefferson
La domanda più persistente e urgente della vita è: cosa stai facendo per gli altri? | Martin Luther King, Jr.
Ovunque ci sia un essere umano, c'è un'opportunità per la gentilezza. | Seneca
Le parole gentili possono essere brevi e facili da pronunciare, ma i loro echi sono davvero infiniti. | Madre Teresa
Essere in grado in tutte le circostanze di praticare cinque cose costituisce la virtù perfetta; queste cinque cose sono gravità, generosità d'animo, sincerità, serietà e gentilezza. | Confucio
Facciamo una nuova regola di vita da stasera: cerchiamo sempre di essere un po' più gentili di quanto sia necessario. | Sir James M. Barrie
Le buone azioni ci nobilitano, siamo figli delle nostre azioni. | Jean Paul Richter
Se non hai carità nel cuore, hai il peggior tipo di malattia del cuore. | Bob Hope
Le parole gentili apriranno una porta di ferro. | Proverbio turco
Coltivare la gentilezza è una parte preziosa degli affari della vita. | Samuel Johnson
Possiamo essere risentiti per la nostra età, o possiamo essere grati di averla raggiunta. | William Arthur Ward
Se non ti accontenterai di niente di meno del meglio, sarai stupito di ciò che puoi realizzare nella tua vita. | Vince Lombardi
Le grandi menti hanno scopi; le piccole menti hanno desideri. Le piccole menti sono sopraffatte dalle sventure; le grandi menti le superano. | Washington Irving
Non c'è uomo che possa evitare di nascere medio, ma non c'è uomo che debba essere comune. | Satchel Paige
Credi profondamente nel tuo cuore che sei destinato a fare grandi cose. | Joe Paterno
Non dovremmo guardare indietro se non per trarre lezioni utili dagli errori passati, e per il fine di trarre profitto dall'esperienza pagata a caro prezzo. | George Washington
La Terra è piena di Paradiso. | Elizabeth Barrett Browning
Ricorda, l'ispirazione segue l'azione e non viceversa. | Aronson, Eric, Dash.
Ricorda che non ottenere ciò che vuoi è a volte un meraviglioso colpo di fortuna. | Dalai Lama
Tutte le cose arrivano a colui che aspetta. | Henry Wadsworth Longfellow
Vedi, nella vita, molte persone sanno cosa fare, ma poche persone fanno effettivamente ciò che sanno. Sapere non è abbastanza! Devi agire. | Anthony Robbins
Mi piace sempre guardare il lato ottimista della vita, ma sono abbastanza realistico da sapere che la vita è una questione complessa. | Walt Disney
Ci troviamo tutti in situazioni che a volte sembrano senza speranza. E, tutti abbiamo la scelta di non fare nulla o di agire. | Catherine Pulsifer
L'onestà è la ricchezza più rara che qualcuno possa possedere, eppure tutta l'onestà nel mondo non è denaro legale per un pane. | Josh Billings
Oh, quale intricato intreccio tessiamo, quando iniziamo a praticare l'inganno! | Sir Walter Scott
Quasi tutta la verità onesta del mondo è detta dai bambini. | Oliver Wendell Holmes, Jr.
È difficile credere che un uomo stia dicendo la verità quando sai che mentiresti se fossi al suo posto. | Henry Louis Mencken
Le nostre vite migliorano solo quando prendiamo rischi - e il primo e più difficile rischio che possiamo prendere è essere onesti con noi stessi. | Walter Anderson
Alziamo uno standard a cui i saggi e onesti possono ricorrere; il resto è nelle mani di Dio. | George Washington
Nessuna eredità è così ricca come l'onestà. | William Shakespeare
La migliore misura dell'onestà di un uomo non è la sua dichiarazione dei redditi. È lo zero sull'aggiustamento della sua bilancia del bagno. | Arthur C. Clarke
Uno dei valori fondamentali più basilari è l'onestà. | Catherine Pulsifer
Le pietre angolari per un successo equilibrato sono l'onestà, il carattere, l'integrità, la fede, l'amore e la lealtà. | Zig Ziglar
La disonestà guarderà in faccia l'onestà ogni giorno della settimana, se c'è qualcosa da guadagnare. | Charles Dickens
L'onestà è il primo capitolo del libro della saggezza. | Thomas Jefferson
L'integrità è dire a me stesso la verità. E l'onestà è dire la verità agli altri. | Spencer Johnson
Sii preparato e sii onesto. | John Wooden
Non c'è zona d'ombra di onestà negli affari. Una cosa è giusta o è sbagliata. È bianco o è nero. | John F. Dodge
Nessun uomo ha una memoria abbastanza buona per essere un bugiardo di successo. | Abraham Lincoln
Sii franco con tuo figlio essendo onesto. Nessuno individua un falso più velocemente di un bambino. | Mary MacCracken
Sii sciocco. Sii onesto. Sii gentile. | Ralph Waldo Emerson
Come ho detto, la prima cosa è essere onesti con te stesso. | Nelson Mandela
L'onestà è temere una risposta negativa e dire comunque la verità. | Michelle C. Ustaszeski
La concentrazione è il mio motto - prima l'onestà, poi l'industria, poi la concentrazione. | Andrew Carnegie
Il disaccordo onesto è spesso un buon segno di progresso. | Gandhi
Il dubbio, indulgente e coltivato, è in pericolo di diventare negazione; ma se onesto e orientato a un'indagine approfondita, può presto portare alla piena affermazione della verità. | Ambrose Bierce
