Wszystkie osiągnięcia, wszystkie zdobyte bogactwa mają swój początek w idei. | Napoleon Hill
Nigdy nie myl aktywności z osiągnięciami. | John Wooden
Osiągnięcia wynikają z pracy realizującej ambicje. | Adam Ant
Najbardziej skomplikowane osiągnięcia myślowe są możliwe bez pomocy świadomości. | Sigmund Freud
Wielkie osiągnięcia rodzą się zazwyczaj z wielkiego poświęcenia i nigdy nie są wynikiem egoizmu. | Napoleon Hill
Śmierć przychodzi do wszystkich, ale wielkie osiągnięcia budują pomnik, który przetrwa, dopóki słońce nie ostygnie. | Ralph Waldo Emerson
Pielęgnuj swoje wizje i marzenia, ponieważ są one dziećmi Twojej duszy, planami Twoich ostatecznych osiągnięć. | Napoleon Hill
Musisz nauczyć się zasad gry. A potem musisz grać lepiej niż ktokolwiek inny. | Albert Einstein
Cieszę się, że to zrobiłem, częściowo dlatego, że było warto, ale przede wszystkim dlatego, że już nigdy nie będę musiał tego robić. | Mark Twain
Nie zdobywamy góry, lecz samych siebie. | Edmund Hillary
Naszym zadaniem musi być uwolnienie się z tego więzienia poprzez poszerzenie naszych kręgów współczucia, aby objąć wszystkie żywe istoty i całą naturę w jej pięknie. | Albert Einstein
Wysokie osiągnięcia zawsze mają miejsce w ramach wysokich oczekiwań. | Charles F. Kettering
Możesz mieć w życiu wszystko, czego pragniesz, jeśli tylko pomożesz innym ludziom zdobyć to, czego pragną. | Zig Ziglar
Wielki wysiłek rodzi się naturalnie z wielkiego nastawienia. | Pat Riley
Twoja postawa, a nie predyspozycje, określi twoją wysokość. | Zig Ziglar
Możesz przyjąć postawę, że nic nie możesz zrobić, albo możesz postrzegać wyzwanie jako wezwanie do działania. | Catherine Pulsifer
Optymista to osoba, która wszędzie widzi zielone światło, podczas gdy pesymista widzi tylko czerwone światło stopu - prawdziwie mądra osoba jest ślepa na kolory. | Albert Schweitzer
Pozytywne myślenie pozwoli Ci zrobić wszystko lepiej niż myślenie negatywne. | Zig Ziglar
Nie możesz kontrolować tego, co Ci się przytrafia, ale możesz kontrolować swoje nastawienie do tego, co Ci się przytrafia i w ten sposób będziesz panować nad zmianami, a nie pozwalać im panować nad Tobą. | Brian Tracy
Możesz to zrobić, jeśli wierzysz, że możesz! | Napoleon Hill
Jeśli nie ustalisz podstawowego standardu tego, co akceptujesz w życiu, łatwo jest popaść w zachowania i postawy lub jakość życia, które są znacznie poniżej tego, na co zasługujesz. | Anthony Robbins
Jeśli coś Ci się nie podoba, zmień to. Jeśli nie możesz tego zmienić, zmień swoje nastawienie. Nie narzekaj. | Maya Angelou
Osoba, która wysyła pozytywne myśli, aktywizuje pozytywnie świat wokół siebie i przyciąga do siebie pozytywne rezultaty. | Norman Vincent Peale
Jeśli Twoje szczęście zależy od tego, co robi ktoś inny, to chyba masz problem. | Richard Bach
Użalanie się nad sobą i swoim obecnym stanem jest nie tylko stratą energii, ale najgorszym nawykiem, jaki możesz mieć. | Dale Carnegie
Każdy może zrobić ze sobą wszystko, czego naprawdę chce i na co się zdecyduje. Jesteśmy zdolni do większych rzeczy, niż nam się wydaje. | Norman Vincent Peale
W życiu są dwa podstawowe wybory: zaakceptować warunki takimi, jakie są, lub przyjąć odpowiedzialność za ich zmianę. | Denis Waitley
Życie jest jak publiczne granie na skrzypcach i uczenie się tego instrumentu w miarę upływu czasu. | Samuel Butler
Pierwszym krokiem do osiągnięcia tego, czego chcesz od życia jest to: Zdecyduj, czego chcesz. | Ben Stein
Życie jest tym, co przytrafia się Tobie, kiedy jesteś zajęty robieniem innych planów. | John Lennon
To, gdzie skończysz, nie jest najważniejszą rzeczą. Ważna jest droga, którą podążasz, aby tam dotrzeć. Droga, którą podążasz jest tym, na co spojrzysz wstecz i nazwiesz swoim życiem. | Tim Wiley
Istnieją tylko dwa sposoby na przeżycie swojego życia. Jeden to taki, w którym nic nie jest cudem. Drugi to tak, jakby wszystko było cudem. | Albert Einstein
Jakość życia człowieka jest wprost proporcjonalna do jego zaangażowania w doskonałość, niezależnie od wybranej dziedziny. | Vince Lombardi
Życie jest tylko lustrem, a to, co widzisz na zewnątrz, musisz najpierw zobaczyć w sobie. | Wally Amos
Zapakuj w swoje życie wszystko, co w nim jest; przechodzisz tę drogę tylko raz! Usiądź wygodnie i zastanów się, co sprawia Ci przyjemność. Weź udział w kursach, czytaj książki, znajdź swoją pasję. | Catherine Pulsifer
Wielką tajemnicą w życiu jest to, że nie ma żadnej wielkiej tajemnicy. Niezależnie od tego, jaki jest Twój cel, możesz go osiągnąć, jeśli tylko będziesz chciał pracować. | Oprah Winfrey
Życie musi być przeżywane, a ciekawość utrzymywana przy życiu. Nigdy nie wolno, z jakiegokolwiek powodu, odwracać się od życia. | Eleanor Roosevelt
Wiedzieć, że choć jedno życie odetchnęło łatwiej dzięki temu, że żyłeś. To znaczy, że odniosłeś sukces. | Ralph Waldo Emerson
Bitwy życiowe nie zawsze kończą się zwycięstwem silniejszego lub szybszego człowieka. Ale prędzej czy później wygrywa ten, kto myśli, że jest w stanie. | Vince Lombardi
Nie bądź widzem, nie pozwól, aby życie przeszło Ci koło nosa. | Lou Holtz
Życie jest niezbadanym terytorium. Odkrywa swoją historię w jednej chwili. | Leo Buscaglia
Posiadanie uczciwości oznacza również posiadanie charakteru, co jest również najłatwiejszą drogą do popadnięcia w konflikt z tymi, którzy nie posiadają żadnego z nich.  | Byron Pulsifer
Miej odwagę powiedzieć "nie". Miej odwagę spojrzeć prawdzie w oczy. Rób to, co właściwe, ponieważ jest to właściwe. To są magiczne klucze do życia w uczciwości. | Mark Twain
Uczciwość może być trudna do utrzymania w świecie, który wymaga, abyś zmieniał się z wiatrem. | Byron Pulsifer
Uczciwość jest tym, co robimy, co mówimy i co mówimy, że robimy. | Don Galer
Kochaj wszystkich, ufaj niewielu, nie czyń zła żadnemu. | William Shakespeare
Uczciwość oznacza, że nie zgadzasz się z każdym, kogo spotykasz, ani nie ulegasz presji, aby być kimś, kto jest w bezpośrednim konflikcie z twoją podstawową etyką. | Byron Pulsifer
Charakter jest wyższy niż intelekt. | Ralph Waldo Emerson
Mój dziadek powiedział mi kiedyś, że są dwa rodzaje ludzi: ci, którzy pracują i ci, którzy przypisują sobie zasługi. Powiedział mi, żebym starała się być w tej pierwszej grupie; tam jest mniejsza konkurencja. | Indira Gandhi
Ale czym jest szczęście, oprócz prostej harmonii pomiędzy człowiekiem a życiem, które prowadzi? | Albert Camus
Jest tylko jeden zakątek wszechświata, którego poprawy możesz być pewien, a jest nim twoje własne ja. | Aldous Huxley
Nie możemy pozwolić, abyśmy stali się tacy jak system, któremu się sprzeciwiamy. | Biskup Desmond Tutu
Uczciwość bez wiedzy jest słaba i bezużyteczna, a wiedza bez uczciwości jest niebezpieczna i straszna. | Samuel Johnson
Musimy podkreślić, że osobista uczciwość jest tak samo ważna jak umiejętności kierownicze w kontaktach biznesowych. | Russell E. Palmer
Bez względu na porę dnia, bez względu na to, kto patrzy i bez względu na sytuację, osobista uczciwość nie bierze urlopu. | Byron Pulsifer
Mądrość to wiedzieć, co robić dalej; cnota to robić to. | David Star Jordan
Charakter to robienie właściwych rzeczy, kiedy nikt nie patrzy. Jest zbyt wielu ludzi, którzy myślą, że jedyną rzeczą, która jest właściwa jest przetrwać, a jedyną rzeczą, która jest zła jest zostać złapanym. | J.C. Watts
Nie zawsze możesz robić to, co właściwe, ale zawsze możesz robić to, co robisz z uczciwością. | Byron Pulsifer
Nigdy nie pozwól, aby twoje poczucie moralności powstrzymało cię od robienia tego, co słuszne. | Isaac Asimov
Uczciwość to zgodność rzeczywistości z naszymi słowami - innymi słowy, dotrzymywanie obietnic i spełnianie oczekiwań. | Stephen R. Covey
Sukces nie jest kluczem do szczęścia. Szczęście jest kluczem do sukcesu. Jeśli kochasz to, co robisz, osiągniesz sukces. | Albert Schweitzer
Nigdy nie będziesz szczęśliwy, jeśli wciąż będziesz szukał, na czym polega szczęście. Nigdy nie będziesz żył, jeśli będziesz szukał sensu życia. | Albert Camus
Konstytucja gwarantuje Amerykanom jedynie prawo do dążenia do szczęścia. Musisz sam je zdobyć. | Benjamin Franklin
Żadne społeczeństwo nie może być kwitnące i szczęśliwe, jeśli większa część jego członków jest biedna i nieszczęśliwa. | Adam Smith
Szczęście to stan umysłu, a nie to, co masz w portfelu. | Byron Pulsifer
Jeśli chcesz być szczęśliwy, bądź. | Lew Tołstoj
Bądźmy wdzięczni ludziom, którzy czynią nas szczęśliwymi; są oni czarującymi ogrodnikami, którzy sprawiają, że nasze dusze kwitną. | Marcel Proust
Człowiek, który sprawia, że wszystko, co prowadzi do szczęścia, zależy od niego samego, a nie od innych ludzi, przyjął najlepszy plan na szczęśliwe życie. | Platon
Uwierz w siebie! Miej wiarę w swoje możliwości! Bez pokornego, ale rozsądnego zaufania we własne siły nie można odnieść sukcesu ani być szczęśliwym. | Norman Vincent Peale
Być bez niektórych rzeczy, których pragniesz, jest nieodzowną częścią szczęścia. | Bertrand Russell
Ale czymże jest szczęście oprócz prostej harmonii między człowiekiem a życiem, które prowadzi? | Albert Camus
Działanie może nie zawsze przynosi szczęście, ale nie ma szczęścia bez działania. | Benjamin Disraeli
Większość ludzi woli być pewna, że są nieszczęśliwi, niż ryzykować, że będą szczęśliwi. | Robert Anthony
Jeśli tylko przestalibyśmy próbować być szczęśliwi, moglibyśmy się całkiem dobrze bawić. | Edith Wharton
Co może być dodane do szczęścia człowieka, który jest zdrowy, nie ma długów i ma czyste sumienie? | Adam Smith
Doświadczenie nie jest tym, co się człowiekowi przydarza. To jest to, co człowiek robi z tym, co mu się przydarza. | Aldous Leonard Huxley
Dobry osąd pochodzi z doświadczenia, a często doświadczenie pochodzi ze złego osądu. | Rita Mae Brown
Umysł, który jest rozciągnięty przez nowe doświadczenie, nigdy nie może powrócić do starych wymiarów. | Oliver Wendell Holmes, Jr.
Czasami musisz zrobić wiele rzeczy, aby dowiedzieć się, czego nie chcesz robić. Po drodze zdobywasz wiele doświadczeń. | Wally Amos
Człowiek nie może odłożyć swojego doświadczenia na emeryturę. Musi z niego korzystać. Doświadczenie pozwala osiągnąć więcej przy mniejszym nakładzie energii i czasu. | Bernard M. Baruch
Reakcja na 'The Greatest Generation' i książki, które po niej nastąpiły, była jednym z najbardziej satysfakcjonujących doświadczeń w moim życiu. | Tom Brokaw
Sława przeminie i, tak długo, miałem cię, sławo. Jeśli przeminie, zawsze wiedziałem, że jest kapryśna. Więc przynajmniej jest to coś, czego doświadczam, ale to nie jest miejsce, w którym żyję. | Marilyn Monroe
Doświadczenie jest dzieckiem myśli, a myśl jest dzieckiem działania. | Benjamin Disraeli
Wolałbym mieć dużo talentu i trochę doświadczenia, niż dużo doświadczenia i mało talentu. | John Wooden
Nigdy nie stań się tak wielkim ekspertem, abyś przestał zdobywać wiedzę. Postrzegaj życie jako ciągłe doświadczenie uczenia się. | Denis Waitley
Najpiękniejszą rzeczą, jakiej możemy doświadczyć, jest to, co tajemnicze. Jest ona źródłem prawdziwej sztuki i nauki. | Albert Einstein
Doświadczenie nie jest tym, co Ci się przydarza. To jest to, co robisz z tym, co ci się przydarza. | Aldous Huxley
Z każdym doświadczeniem, tylko Ty sam malujesz swoje płótno, myśl po myśli, wybór po wyborze. | Oprah Winfrey
Jako kobieta zawsze czułam, że z wiekiem stajemy się lepsi. Poprzez emocjonalne doświadczenia i prostą mądrość, która przychodzi z wiekiem, dochodzimy do porozumienia z samym sobą. | Linda Evans
Nie powinniśmy oglądać się za siebie, chyba że po to, aby wyciągnąć pożyteczne wnioski z błędów przeszłości i skorzystać z drogo kupionego doświadczenia. | George Washington
Najbardziej bolesną rzeczą, jakiej można doświadczyć, nie jest porażka, lecz żal. | Leo Buscaglia
Żaden człowiek nie był nigdy tak dobrze wyćwiczony w prowadzeniu życia, aby nie otrzymywać nowych informacji od wieku i doświadczenia. | Jonathan Swift
Sztuka nie jest rzemiosłem, jest przekazem uczuć, których doświadczył artysta. | Lew Tołstoj
Myślę, że każdy powinien doświadczyć porażki przynajmniej raz w swojej karierze. Można się z niej wiele nauczyć. | Lou Holtz
Sekret bogatego życia polega na tym, aby mieć więcej początków niż zakończeń. | Dave Weinbaum
Wszystkie trudne rzeczy mają swój początek w tym, co jest łatwe, a wielkie rzeczy w tym, co jest małe. | Lao-Tzu
Prawie wszystko bierze się z niczego. | Henry F. Amiel
Konieczność, która jest matką wynalazku. | Platon
Odległość nie jest niczym; trudny jest tylko pierwszy krok. | Marquise du Deffand
Początki są trudne tylko bez działania. | Byron Pulsifer
Małe możliwości są często początkiem wielkich przedsięwzięć. | Demostenes
Trudny początek czyni dobre zakończenie. | John Heywood
Nie trzeba być wielkim, aby zacząć, ale trzeba zacząć, aby być wielkim. | Joe Sabah
Wielu ludzi, którzy szukają nowych początków, nigdy nie skończyło z przeszłością. | Byron Pulsifer
Każdy dzień jest nowym początkiem. Traktuj go w ten sposób. Trzymaj się z dala od tego, co mogło być, a spójrz na to, co może być. | Marsha Petrie Sue
To nie jest koniec. To nie jest nawet początek końca. Ale jest to, być może, koniec początku. | Winston Churchill
Cokolwiek robisz, lub o czymkolwiek marzysz, zacznij to. Śmiałość ma w sobie geniusz, moc i magię. | Goethe
Wykorzystanie kilku małych okazji może doprowadzić nas do celu szybciej niż czekanie na jedną dużą. | Hugh Allen
Często trudno jest odróżnić twarde uderzenia w życiu od tych, które wynikają z okazji. | Frederick Phillips
Umiejętności są mało ważne bez okazji. | Napoleon
Sekretem sukcesu w życiu jest to, aby człowiek był gotowy na swoją szansę, kiedy ona nadejdzie. | Benjamin Disraeli
Okazje nigdy nie są stracone; ktoś wykorzysta tę, którą ty przegapisz. |
Każdy dzień jest okazją do stworzenia nowego, szczęśliwego zakończenia. |
Wszystko, co jest wartościowe w społeczeństwie ludzkim, zależy od szansy rozwoju danej jednostce. | Albert Einstein
Pesymista widzi trudności w każdej okazji; optymista widzi możliwości w każdej trudności. | Winston Churchill
Życie jest darem i oferuje nam przywilej, możliwość i odpowiedzialność, aby dać coś w zamian, stając się kimś więcej. | Tony Robbins
Na drabinę sukcesu najlepiej wspiąć się po szczeblach możliwości. | Ayn Rand
Umiejętności są niczym bez możliwości. | Napoleon Bonaparte
Twoja wielka szansa może być dokładnie tam, gdzie jesteś teraz. | Napoleon Hill
Okazje pojawiają się w moim życiu, a ja odpowiadam na te, które do mnie przemawiają. | Wally Amos
Ludzie nigdy nie jęczą z powodu straconych okazji do czynienia dobra, a jedynie z powodu straconych okazji do bycia złym. | Przysłowie greckie
Edison zawiódł 10 000 razy, zanim stworzył światło elektryczne. Nie zniechęcaj się, jeśli kilka razy Ci się nie uda. | Napoleon Hill
Jak długo powinieneś próbować? Do czasu. | Jim Rohn
Cierpliwość i wytrwałość mają magiczny efekt, przed którym znikają trudności i znikają przeszkody. | John Quincy Adams
Dzięki wytrwałości wielu ludzi osiąga sukces z tego, co wydawało się być skazane na pewną porażkę. | Benjamin Disraeli
Próbuj i ponoś porażkę, ale nie zaniedbuj prób. | Stephen Kaggwa
Jeśli chcesz osiągnąć sukces w życiu, uczyń wytrwałość swoim przyjacielem, doświadczenie swoim mądrym doradcą, ostrożność swoim starszym bratem, a nadzieję swoim geniuszem opiekuńczym. | Joseph Addison
Wielkie dzieła są dokonywane nie przez siłę, lecz przez wytrwałość. | Samuel Johnson
Nie sądzę, aby istniała jakakolwiek inna cecha tak niezbędna do osiągnięcia jakiegokolwiek sukcesu, jak cecha wytrwałości. Przezwycięża ona prawie wszystko, nawet naturę. | John D. Rockefeller
Nie ma porażki, chyba, że się już nie próbuje. | Elbert Hubbard
Tylko wytrwałość i determinacja są wszechmocne. Hasło "trzymaj się" rozwiązywało i zawsze będzie rozwiązywać problemy rasy ludzkiej. | Calvin Coolidge
Zwycięstwo należy do najbardziej wytrwałych. | Napoleon Bonaparte
Podążaj za swoimi marzeniami o lepszym świecie i próbuj dalej, nawet gdy wydaje się, że nie ma nadziei, ponieważ jest to właściwe postępowanie. | Robert Alan
Geniusz to boska wytrwałość. Geniuszu nie mogę przypisać sobie, ani nawet dodatkowej jasności, ale wytrwałość wszyscy mogą mieć. | Woodrow Wilson
W konfrontacji pomiędzy strumieniem a skałą, strumień zawsze wygrywa - nie dzięki sile, ale dzięki wytrwałości. | H. Jackson Brown
Wytrwałość jest bardziej zwycięska niż przemoc i wiele rzeczy, które nie mogą być przezwyciężone, gdy są razem, poddają się, gdy są podejmowane krok po kroku. | Plutarch
Wytrwałość nie jest długim wyścigiem; jest to wiele krótkich wyścigów jeden po drugim. | Walter Elliot
Najlepsi wśród nas nie są bardziej utalentowani niż pozostali. Oni po prostu stawiają małe kroki każdego dnia, maszerując w kierunku swojego największego życia. | Robin Sharma, Przewodnik po wielkości
Jeśli cenisz swoją własną reputację, wiąż się z ludźmi dobrej jakości. Lepiej być samemu niż w złym towarzystwie. | George Washington
Jakość nie jest czynem, jest nawykiem. | Arystoteles
Jeśli standard życia jest Twoim głównym celem, jakość życia prawie nigdy się nie poprawia, ale jeśli jakość życia jest Twoim celem numer jeden, standard życia prawie zawsze się poprawia. | Zig Ziglar
Jakość jest atrybutem dość powszechnie nadużywanym przez tych, którzy chcą wprowadzić w błąd. | Byron Pulsifer
Jakość oznacza robienie tego dobrze, kiedy nikt nie patrzy. | Henry Ford
Jeśli nie jesteś pewien jakości swojej pracy, musisz najpierw zrozumieć, czym jest jakość. | Byron Pulsifer
Jakość nigdy nie jest przypadkiem; zawsze jest wynikiem inteligentnego wysiłku. | John Ruskin
To jakość naszej pracy zadowoli Boga, a nie jej ilość. | Mahatma Gandhi
Jakość życia człowieka jest wprost proporcjonalna do jego zaangażowania w doskonałość, bez względu na wybraną dziedzinę. | Vince Lombardi
Jakość, a nie długość życia jest tym, co jest ważne. | Martin Luther King
Nikt nie może osiągnąć prawdziwego i trwałego sukcesu ani wzbogacić się w biznesie będąc konformistą. | J.P. Getty
Wspinanie się na strome wzgórza wymaga początkowo wolnego tempa. | William Shakespeare
Sukces nie jest żadną tajemnicą. Czy znałeś kiedyś człowieka sukcesu, który Ci o tym nie powiedział? | Kin Hubbard
Tajemnica sukcesu człowieka tkwi w jego wglądzie w nastroje ludzi i takcie w postępowaniu z nimi. | Josiah Gilbert Holland
Nie ma pasji w graniu na małą skalę - w zadowalaniu się życiem, które jest mniejsze niż to, do którego jesteś zdolny. | Nelson Mandela
Cele zrobiły ogromną różnicę w moim życiu. Pozwoliły mi osiągnąć sukces i dokonać tego, o czym wcześniej tylko marzyłam lub czego pragnęłam. | Catherine Pulsifer
Nigdy nie należy mylić ruchu z działaniem. | Ernest Hemmingway
Sukces to dostać to, czego się chce. Szczęście to chcieć tego, co się dostaje. | Dale Carnegie
We wszystkim, co robimy, nasze własne myśli mogą pomóc nam odnieść sukces lub przyczynić się do porażki. Zachowaj pozytywne nastawienie. | Catherine Pulsifer
Większość ludzi sukcesu, których znałem, to ci, którzy więcej słuchają niż mówią. | Bernard M. Baruch
Odnoszenie sukcesów w pracy jest najlepszym krokiem w kierunku tego, czego pragniesz. | Bernard M. Baruch
Nie można oceniać człowieka po jego porażkach. Musisz wiedzieć, jaki użytek robi z nich. Co one dla niego oznaczają. Co z nich wyniósł. | Orison Swett Marden
Jeśli ktoś podąża pewnie w kierunku swoich marzeń i stara się żyć tak, jak sobie wyobraża, spotka się z sukcesem niespodziewanym w zwykłych godzinach. | Henry David Thoreau
Czas jest najcenniejszą rzeczą, jaką człowiek może spędzić. | Theophrastus
W ten sposób można osiągnąć sukces, którego nie da się przewidzieć. | James Matthew Barrie
Jeśli chcesz, aby praca była dobrze wykonana, wybierz człowieka zajętego, inni nie mają czasu. | Elbert Hubbard
Czas jest najmądrzejszym doradcą ze wszystkich. | Perykles
Wszystko, co naprawdę należy do nas, to czas; nawet ten, kto nie ma nic innego, ma to. | Baltasar Gracian
Czas to najdłuższa odległość między dwoma miejscami. | Tennessee Williams
Nic nie jest stratą czasu, jeśli mądrze wykorzystasz to doświadczenie. | Rodin
Musimy używać czasu jako narzędzia, a nie jako kuli. | John F. Kennedy
Czasu i słów nie da się cofnąć, nawet jeśli to było tylko wczoraj. | Przysłowie jidysz
Żal za rzeczy, które zrobiliśmy, może być złagodzony przez czas; to żal za rzeczy, których nie zrobiliśmy, jest nie do zniesienia. | Sydney J. Harris
Ale co za minuty! Liczymy je według wyczucia, a nie według kalendarza, a każda chwila jest dniem. | Benjamin Disraeli
Czas jest monetą Twojego życia. To jedyna moneta, jaką posiadasz i tylko Ty możesz zdecydować, jak ją wydasz. Uważaj, aby inni ludzie nie wydali go za Ciebie. | Carl Sandburg
Nigdy na nic nie znajdziesz czasu. Jeśli chcesz mieć czas, musisz go stworzyć. | Charles Buxton
Lepiej o trzy godziny za wcześnie niż o minutę za późno. | William Shakespeare
Straconego czasu nigdy się już nie znajdzie. | Benjamin Franklin
Godziny głupoty są odmierzane przez zegar; ale mądrości żaden zegar nie może odmierzyć. | William Blake
Nigdy się nie zmęczysz, jeśli nie zatrzymasz się i nie poświęcisz na to czasu. | Bob Hope
Czas jest najmądrzejszym doradcą. | Perykles
Ja zmarnowałem czas, a teraz czas marnuje mnie. | William Shakespeare
Twoim największym atutem jest zdolność do zarabiania. Twoim największym zasobem jest Twój czas. | Brian Tracy
Musimy mądrze wykorzystywać czas i zawsze zdawać sobie sprawę, że zawsze jest czas na zrobienie czegoś dobrego. | Nelson Mandela
Życie nie jest mierzone liczbą oddechów, które bierzemy, ale chwilami, które zapierają nam dech w piersiach. |
Najlepszym sposobem na spełnienie marzeń jest przebudzenie się. | Paul Valery
Jedną z rzeczy, których nauczyłam się w ciężki sposób jest to, że nie warto się zniechęcać. | Lucille Ball
Ważną rzeczą jest to, aby w każdej chwili móc poświęcić to, czym jesteśmy, dla tego, czym moglibyśmy się stać. | Charles Dubois
Wszystkie rady świata nigdy ci nie pomogą, dopóki sam sobie nie pomożesz. | Fred Van Amburgh
Kochać obficie, to żyć obficie, a kochać wiecznie, to żyć wiecznie. | Henry Drummond
To, jak myślisz o problemie, jest ważniejsze niż sam problem. Dlatego zawsze myśl pozytywnie. | Norman Vincent Peale
Zapomnij o błędach z przeszłości. Zapomnij o porażkach. Zapomnij o wszystkim oprócz tego, co masz zamiar zrobić teraz i zrób to. | William Durant
Możesz powiedzieć więcej o człowieku przez to, co on mówi o innych, niż przez to, co inni mówią o nim. | Leo Aikman
Marzenia są wielkie, a potem załóż kombinezon i wyjdź, aby je spełnić. | Fred Van Amburgh
Tajemnica życia nie jest problemem do rozwiązania; jest rzeczywistością, której należy doświadczyć. | Aart van der Leenw
Jest tylko jeden zakątek wszechświata, w którym można być pewnym poprawy, a jest nim własne ja. | Aldous Huxley
Dobre życie jest procesem, a nie stanem bycia. Jest kierunkiem, a nie celem. | Carl Rogers
Jesteśmy tym, co ciągle robimy. Doskonałość nie jest więc aktem, lecz nawykiem. | Arystoteles
Czytać nie po to, aby zaprzeczać i podważać, nie po to, aby wierzyć i przyjmować za pewnik, nie po to, aby znajdować rozmowy i dyskutować, ale aby ważyć i rozważać. | Francis Bacon
Jednym z najlepszych sposobów przekonywania innych jest słuchanie ich uszami. | Dean Rusk
Jeśli masz tylko jednego lub dwóch przyjaciół, z którymi możesz dzielić się swoimi najwyższymi aspiracjami, powinieneś uważać się za bogato błogosławionego. | J. Donald Waters
Zamiast pragnąć zmian, najpierw musisz być na nie przygotowany. | Catherine Pulsifer
Każdy myśli o zmianie świata, ale nikt nie myśli o zmianie samego siebie. | Lew Tołstoj
Zmiana jest tak nieubłagana jak czas, ale nic nie napotyka na większy opór. | Benjamin Disraeli
Tylko najmądrzejsi i najgłupsi z ludzi nigdy się nie zmieniają. | Konfucjusz
Nigdy nie przestawaj się uczyć, tak jak nigdy nie przestawaj się zmieniać i rozwijać w swoim życiu - nauka pomaga łatwiej przystosować się do zmian. | Uczenie się Cytaty
To, co myślimy, determinuje to, co się z nami dzieje, więc jeśli chcemy zmienić nasze życie, musimy wytężyć nasze umysły. | Wayne Dyer
Nie możesz zmienić swojego przeznaczenia w ciągu jednej nocy, ale możesz zmienić swój kierunek w ciągu jednej nocy. | Jim Rohn
Często jesteśmy rozczarowani z powodu naszych oczekiwań. Tylko wtedy, gdy nauczymy się widzieć okoliczności takimi, jakimi są naprawdę, możemy stać się architektem poprawy. | Greg Henry Quinn
Jedynym mężczyzną, jakiego znam, który zachowuje się rozsądnie, jest mój krawiec; mierzy mnie na nowo za każdym razem, gdy mnie widzi. Reszta idzie dalej ze swoimi starymi wymiarami i oczekuje, że ja je dopasuję. | George Bernard Shaw
Nie ma działania, nie ma zmiany. Ograniczone działanie, ograniczona zmiana. Dużo działania - zmiana następuje. | Catherine Pulsifer
Zawsze możesz zmienić zdanie i wybrać inną przyszłość lub inną przeszłość. | Richard Bach
Nie pozwól, aby inni zmieniali Twoje życie, bądź swoim własnym agentem zmian i wprowadzaj zmiany, których pragniesz! A jeśli w Twoim życiu pojawi się nieoczekiwana zmiana, znajdź w niej pozytywy. | Catherine Pulsifer
Zmiana jest nieunikniona. Zmiana jest stała. | Benjamin Disraeli
Jeśli czujesz się przygnębiony, nie rozpaczaj. Słońce każdej nocy tonie, ale każdego ranka wraca do góry. Jeśli chcesz zobaczyć tęczę, musisz znieść deszcz. | Dolly Parton
Bycie testowanym jest dobre. Życie pełne wyzwań może być najlepszym terapeutą. | Gail Sheehy
To nie góry, na które trzeba się wspiąć, męczą cię; to kamyk w twoim bucie. | Mahummad Ali
Podążaj za tym, co się dzieje i pozwól swojemu umysłowi być wolnym. Pozostań w centrum poprzez akceptację tego, co robisz. To jest ostateczność. | Chuang Tzu
Może nie jesteś odpowiedzialny za to, że zostałeś powalony, ale na pewno jesteś odpowiedzialny za to, że się podniosłeś. | Wally Amos
Staram się być mądra, kiedy nie mogę być wesoła, łatwa, kiedy nie mogę być szczęśliwa, zadowolona z tego, co nie może być naprawione i cierpliwa, kiedy nie ma zadośćuczynienia. | Elizabeth Montagu
Złe rzeczy nie są najgorszymi rzeczami, jakie mogą się nam przytrafić. "Nic" jest najgorszą rzeczą, jaka może się nam przytrafić! | Richard Bach
Część nigdy nie może być dobra, jeśli całość nie jest dobra. | Platon
Góry nie mogą być pokonane inaczej niż krętymi ścieżkami. | Johann Wolfgang Von Goethe
Nigdy nie lekceważ swojego problemu ani swojej zdolności do radzenia sobie z nim. | Robert H. Schuller
Każde jutro ma dwa uchwyty. Możemy chwycić je za uchwyt lęku lub za uchwyt wiary. | Henry Ward Beecher
Niemożliwości są tylko rzeczami, których jeszcze się nie nauczyliśmy. | Charles W. Chesnutt
Kiedy los daje nam cytrynę, postarajmy się zrobić lemoniadę. | Dale Carnegie
Możesz nie zdawać sobie z tego sprawy, ale kopniak w zęby może być dla Ciebie najlepszą rzeczą na świecie. | Walt Disney
Wielkość nie polega na byciu silnym, ale na właściwym użyciu siły. | Henry Ward Beecher
Nie bój się wielkości: niektórzy rodzą się wielcy, inni osiągają wielkość, a jeszcze inni są do niej zmuszani. | William Shakespeare
Wielkie osiągnięcia rodzą się zazwyczaj z wielkiego poświęcenia i nigdy nie są wynikiem egoizmu. | Napoleon Hill
Aby stać się naprawdę wielkim, trzeba stać z ludźmi, a nie ponad nimi. | Marleen Charles de Montesquieu
Wspaniała fotografia to taka, która w pełni wyraża to, co czujemy, w najgłębszym sensie, do tego, co jest fotografowane. | Ansel Adams
Wysokość, którą osiągnęli i utrzymali wielcy ludzie, nie została zdobyta nagłą ucieczką, lecz podczas gdy ich towarzysze spali, oni pracowali w nocy w górę. | Henry Wadsworth Longfellow
To właśnie w największych przeciwnościach istnieje największy potencjał czynienia dobra, zarówno dla siebie, jak i dla innych. | Dalai Lama
Jednym z największych odkryć człowieka, jedną z największych niespodzianek, jest odkrycie, że może on zrobić to, czego obawiał się, że nie może zrobić. | Henry Ford
Odpowiedzialność jest ceną wielkości. | Winston Churchill
Większość wielkich ludzi osiągnęła swój największy sukces o krok od największej porażki. | Napoleon Hill
Żaden wielki człowiek nigdy nie narzeka na brak możliwości. | Ralph Waldo Emerson
Pielęgnuj swój umysł wielkimi myślami; wiara w to, co heroiczne, czyni bohaterów. | Benjamin Disraeli
Wielki wysiłek rodzi się naturalnie z wielkiego nastawienia. | Pat Riley
Ryzykuj więcej, niż inni uważają za bezpieczne. Troszcz się bardziej, niż inni uważają za mądre. Marz więcej, niż inni uważają za praktyczne. Oczekuj więcej niż inni myślą, że jest to możliwe. | Kadet Maxim
Codziennie zrób jedną rzecz, która Cię przeraża. | Eleanor Roosevelt
Zaufaj swojemu instynktowi. Równie dobrze Twoje błędy mogą być Twoje własne, a nie czyjeś. | Billy Wilder
Życie na granicy ryzyka to skakanie z klifu i budowanie skrzydeł po drodze w dół. | Ray Bradbury
Nie odkrywa się nowych lądów, nie godząc się na utratę brzegu z oczu na bardzo długi czas. | André Gide
Uważaj, aby nie przegapić szansy; w przeciwnym razie pewnego dnia może być już za późno. | Franciszek Liszt
Kto ufa przypadkowi, musi się pogodzić z jego skutkami. | Calvin Coolidge
Nigdy nie ukłujesz się w palec stojąc w miejscu. Im szybciej idziesz, tym większa szansa, że się ukłujesz, ale tym większa szansa, że gdzieś dojdziesz. | Charles F. Kettering
Najlepszą nagrodą, jaką życie ma do zaoferowania, jest możliwość ciężkiej pracy nad pracą, którą warto wykonać. | Theodore Roosevelt
W moich czasach nie mieliśmy poczucia własnej wartości, mieliśmy szacunek do samych siebie i nie więcej niż zasłużyliśmy. | Jane Haddam
Ten, kto szanuje siebie, jest bezpieczny od innych; nosi płaszcz z poczty, którego nikt nie może przebić. | Henry Wadsworth Longfellow
Ludzie, których najbardziej szanuję, zachowują się tak, jakby byli nieśmiertelni i jakby społeczeństwo było wieczne. | E. M. Forster
Jeśli nie masz szacunku dla swoich własnych wartości, jak możesz być godny szacunku innych. | Byron Pulsifer
Człowiek może znieść wiele tak długo, jak długo może znieść samego siebie. | Axel Munthe
Szacunek nie jest czymś, o co można prosić, co można kupić lub pożyczyć. Szacunek jest tym, na co zasługujesz od każdej osoby, bez względu na jej pochodzenie i status. | Byron Pulsifer
Wolę być wierny samemu sobie, nawet ryzykując narażenie się na śmieszność innych, niż być fałszywym i narażać się na własną odrazę. | Frederick Douglass
Jeśli ktoś jest wyobcowany z samego siebie, to jest też wyobcowany z innych. Jeśli ktoś nie ma kontaktu z samym sobą, nie może dotknąć innych. | Anne Morrow Lindbergh
Nie mogą odebrać nam szacunku do samych siebie, jeśli my im go nie damy. | Mahatma Gandhi
Każdy człowiek ma swoje miejsce do wypełnienia w świecie i jest ważny pod jakimś względem, czy tego chce, czy nie. | Nathaniel Hawthorne
Tragedia polega na tym, że tak wielu ludzi szuka pewności siebie i szacunku dla siebie wszędzie poza sobą i dlatego zawodzą w swoich poszukiwaniach. | Nathaniel Branden
Szacunek i zaufanie nigdy nie mogą być uważane za coś oczywistego. Są to cechy, które trzeba udowodnić. Są one również bezpośrednio odwzajemnione przez zachowanie innych. | Elaine Sihera
Patrz na wszystko tak, jakbyś widział to po raz pierwszy lub ostatni. Wtedy twój czas na ziemi będzie wypełniony chwałą. | Betty Smith
Mądrzy ludzie mówią, ponieważ mają coś do powiedzenia; głupcy, ponieważ muszą coś powiedzieć. | Platon
Kiedy widzisz człowieka wartościowego, pomyśl, jak możesz go naśladować. Kiedy widzisz kogoś, kto jest niegodny, zbadaj siebie. | Konfucjusz
W każdym z nas jest wezwanie do zrobienia czegoś, nawet jeśli jest to niepopularne lub niezauważone, aby uczynić świat lepszym. | Robert K. Cooper
Nic nie jest przesądzone: Przeszkody z Twojej przeszłości mogą stać się bramami, które prowadzą do nowych początków. | Ralph Blum
Umiejętność rozdawania bogactw jest obowiązkowa, jeśli chcesz je posiadać. To jest jedyny sposób, aby być naprawdę bogatym. | Mahummad Ali
Ludzie podążają różnymi drogami w poszukiwaniu spełnienia i szczęścia. To, że nie są na Twojej drodze, nie oznacza, że się zgubili. | Dalai Lama
Mam o wiele więcej szacunku dla osoby z jednym pomysłem, która osiąga cel, niż dla osoby z tysiącem pomysłów, która nie robi nic. | Thomas Edison
Praca i zabawa to słowa używane do opisania tej samej rzeczy w różnych warunkach. | Mark Twain
Najbogatszy jest ten człowiek, którego przyjemności są najtańsze. | Henry David Thoreau
Nie można podawać ręki z zaciśniętą pięścią. | Gandhi
Trzeba lubić ludzi i ufać im, jeśli nie chce się zrobić w życiu bałaganu. | E.M. Forster
Nie można ufać bez ryzyka, ale nie można też żyć w kokonie. | Byron Pulsifer
Możesz zostać oszukany, jeśli zaufasz za bardzo, ale będziesz żył w męczarniach, jeśli nie zaufasz wystarczająco. | Frank Crane
Wszyscy rodzimy się odważni, ufni i chciwi, a większość z nas pozostaje chciwa. | Mignon McLaughlin
Co jest takiego w polityce, że zdaje się ignorować zaufanie, chyba że w czasie wyborów? | Byron Pulsifer
Muszę podążać za ludźmi. Czy nie jestem ich przywódcą? | Benjamin Disraeli
Kto nie może być posłuszny, nie może dowodzić. | Benjamin Franklin
Dobry przywódca nie może zbytnio wyprzedzać swoich zwolenników. | Theodore Roosevelt
Przywództwo jest sztuką nakłaniania kogoś innego do zrobienia czegoś, co chcesz, aby zrobił, ponieważ on chce to zrobić. | Dwight Eisenhower
Kluczem do skutecznego przywództwa jest dziś wpływ, a nie władza. | Kenneth Blanchard
Istnieje ogromna liczba menedżerów, którzy odeszli na emeryturę w trakcie pracy. | Peter F. Drucker
Dobry lider bierze na siebie trochę więcej niż część winy, trochę mniej niż część zasług. | Arnold H. Glasgow
Zarządzanie to robienie rzeczy dobrze; przywództwo to robienie rzeczy dobrze. | Peter F. Drucker
Nie jest uczciwe wymagać od innych tego, czego samemu nie chce się zrobić. | Eleanor Roosevelt
Liderzy nie tworzą naśladowców, oni tworzą więcej liderów. | Tom Peters
Największym dobrem, jakie możesz uczynić dla innych, jest nie tylko dzielenie się swoim bogactwem, ale ujawnienie im ich własnego. | Benjamin Disraeli
Nie przewodzisz ludziom poprzez bicie ich po głowie - to jest napaść, a nie przywództwo. | Dwight Eisenhower
Dobrym celem przywództwa jest pomaganie tym, którzy radzą sobie słabo, aby radzili sobie dobrze i pomaganie tym, którzy radzą sobie dobrze, aby radzili sobie jeszcze lepiej. | Jim Rohn
Wybitni liderzy dokładają wszelkich starań, aby podnieść samoocenę swoich pracowników. Jeśli ludzie wierzą w siebie, to niesamowite jest to, co mogą osiągnąć. | Sam Walton
Zbyt wielu liderów zachowuje się tak, jakby owce... ich ludzie... byli tam dla dobra pasterza, a nie tak, jakby pasterz był odpowiedzialny za owce. | Kenneth Blanchard
Przeciętny nauczyciel opowiada. Dobry nauczyciel wyjaśnia. Doskonały nauczyciel demonstruje. Wielki nauczyciel inspiruje. | William Arthur Ward
W przeszłości lider był szefem. Dzisiejsi liderzy muszą być partnerami swoich ludzi... nie mogą już przewodzić wyłącznie w oparciu o władzę pozycyjną. | Kenneth Blanchard
Uprzejmość jest językiem, który głusi słyszą, a ślepi widzą. | Mark Twain
Nie możesz zrobić czegoś zbyt szybko, bo nigdy nie wiesz, jak szybko będzie za późno. | Ralph Waldo Emerson
Moja religia jest bardzo prosta. Moją religią jest dobroć. | Dalai Lama
Jeśli jest jakakolwiek dobroć, którą mogę okazać, lub jakąkolwiek dobrą rzecz, którą mogę zrobić dla jakiejkolwiek istoty, pozwól mi zrobić to teraz, a nie zniechęcać się lub zaniedbywać, ponieważ nie będę przechodził tą drogą ponownie. | William Penn
Nie przeżyłeś idealnego dnia, jeśli nie zrobiłeś czegoś dla kogoś, kto nigdy nie będzie w stanie ci się odwdzięczyć. | Ruth Smeltzer
Jaką mądrość możesz znaleźć większą niż dobroć? | Jean Jacques Rousseau
Tak błyszczy dobry uczynek w zmęczonym świecie. | William Shakespeare
Nasze czyny określają nas w takim samym stopniu, jak my określamy nasze czyny. | George Eliot
Bądź uprzejmy, bo każdy, kogo spotykasz, toczy ciężką walkę. | Platon
Ten, kto czeka, aby zrobić wiele dobrego na raz, nigdy nic nie zrobi. | Samuel Johnson
Uprzejmość jest słońcem, w którym rośnie cnota. | Robert Green Ingersoll
Zawsze dąż do pełnej harmonii myśli, słów i czynów. Zawsze staraj się oczyszczać swoje myśli, a wszystko będzie dobrze. | Mohandas Gandhi
Ten, kto wyświadczył ci przysługę, będzie bardziej gotów wyświadczyć ci inną, niż ten, kogo sam zobowiązałeś. | Benjamin Franklin
Dobroć jest niezauważalna. Nie błyska, lecz świeci. | David Grayson
Pamiętajmy, że tak jak wiele nam dano, tak wiele będzie się od nas oczekiwać i że prawdziwy hołd pochodzi zarówno z serca, jak i z ust, i przejawia się w czynach. | Theodore Roosevelt
Uprzejmość spontanicznie ofiarowana temu, kto jej potrzebuje, jest podwójnie satysfakcjonująca. | Jonathan Swift
Kiedy dajesz z siebie, dajesz naprawdę. | Kahil Gibran
Rób coś więcej niż przynależność: uczestnicz. Rób więcej niż troska: pomagaj. Rób więcej niż wierzyć: praktykuj. Rób więcej niż być sprawiedliwym: bądź uprzejmy. Rób więcej niż przebaczać: zapominaj. Rób więcej niż marzyć: pracuj. | William Arthur Ward
Życzliwość jest złotym łańcuchem, którym społeczeństwo jest związane. | Johann Wolfgang Von Goethe
Najmniejszy dobry uczynek jest lepszy niż najwspanialszy dobry zamiar. | Przysłowie japońskie
Nie ma lepszego ćwiczenia dla serca niż sięganie w dół i pomaganie komuś w podnoszeniu się. | Bernard Meltzer
Życzliwość może stać się własnym motywem. Jesteśmy życzliwi poprzez bycie życzliwym. | Eric Hoffer
Życzliwość rodzi życzliwość. | Przysłowie greckie
Życzliwe serce jest fontanną radości, która sprawia, że wszystko w jej pobliżu staje się uśmiechnięte. | Washington Irving
Bądź uprzejmy dla tych, którzy spotykają cię, gdy się podnosisz, a może miniesz ich ponownie, gdy upadasz. | Przysłowie irlandzkie
Całkowite posiadanie jest udowodnione tylko przez dawanie. Wszystko, czego nie jesteś w stanie dać, posiada ciebie. | Andre Gide
Jedno miłe słowo może ogrzać trzy zimowe miesiące. | Przysłowie japońskie
Zawsze, gdy masz coś zrobić, chociaż nie możesz tego wiedzieć tylko ty sam, zadaj sobie pytanie, jak byś się zachował, gdyby cały świat na ciebie patrzył i postępuj zgodnie z tym. | Thomas Jefferson
Najbardziej uporczywe i naglące pytanie w życiu brzmi: Co robisz dla innych? | Martin Luther King, Jr.
Gdziekolwiek jest człowiek, tam jest okazja do życzliwości. | Seneka
Uprzejme słowa mogą być krótkie i łatwe do wypowiedzenia, ale ich echo jest naprawdę nieskończone. | Matka Teresa
Umiejętność praktykowania pięciu rzeczy w każdych okolicznościach stanowi doskonałą cnotę; tymi pięcioma rzeczami są: powaga, szczodrość duszy, szczerość, gorliwość i życzliwość. | Konfucjusz
Czy powinniśmy wprowadzić nową zasadę życia od dziś - zawsze starać się być trochę bardziej uprzejmym niż to konieczne? | Sir James M. Barrie
Dobre uczynki uszlachetniają nas, jesteśmy synami naszych własnych czynów. | Jean Paul Richter
Jeśli nie masz w swoim sercu miłości, masz najgorszy rodzaj problemów z sercem. | Bob Hope
Miłe słowa otworzą żelazne drzwi. | Przysłowie tureckie
Kultywowanie życzliwości jest cenną częścią życia. | Samuel Johnson
Możemy mieć pretensje do naszego wieku, albo możemy być wdzięczni za to, że go osiągnęliśmy. | William Arthur Ward
Jeśli nie zadowolicie się niczym mniej niż tym, co macie najlepszego, będziecie zdumieni tym, co możecie osiągnąć w swoim życiu. | Vince Lombardi
Wielkie umysły mają cele, małe umysły mają życzenia. Małe umysły są przytłumione przez nieszczęścia; wielkie umysły wznoszą się ponad nie. | Washington Irving
Żaden człowiek nie może uniknąć urodzenia się przeciętnym, ale też żaden człowiek nie musi być zwyczajny. | Satchel Paige
Uwierz w głębi serca, że jesteś przeznaczony do robienia wielkich rzeczy. | Joe Paterno
Nie powinniśmy oglądać się za siebie, chyba że po to, aby wyciągnąć pożyteczne wnioski z błędów przeszłości i skorzystać z drogo kupionego doświadczenia. | George Washington
Ziemia jest przepełniona Niebem. | Elizabeth Barrett Browning
Pamiętaj, że inspiracja podąża za działaniem, a nie odwrotnie. | Aronson, Eric, Dash.
Pamiętaj, że nie otrzymanie tego, czego chcesz, jest czasami wspaniałym łutem szczęścia. | Dalai Lama
Wszystkie rzeczy przychodzą do tego, kto tylko czeka. | Henry Wadsworth Longfellow
Widzisz, w życiu wiele osób wie, co robić, ale niewiele osób robi to, co wie. Wiedza nie wystarczy! Musisz podjąć działanie. | Anthony Robbins
Zawsze lubię patrzeć na życie z optymistycznej strony, ale jestem na tyle realistą, aby wiedzieć, że życie jest skomplikowaną sprawą. | Walt Disney
Wszyscy znajdujemy się w sytuacjach, które czasami wydają się beznadziejne. I wszyscy mamy wybór: nie robić nic lub podjąć działanie. | Catherine Pulsifer
Uczciwość jest najrzadszym bogactwem, jakie można posiąść, a jednak uczciwość na świecie nie jest prawomocnym przetargiem na bochenek chleba. | Josh Billings
O, jakże splątaną sieć tka się, gdy najpierw ćwiczy się oszukiwanie! | Sir Walter Scott
Prawie cała uczciwa prawda, jaka istnieje na świecie, jest mówiona przez dzieci. | Oliver Wendell Holmes, Jr.
Trudno jest uwierzyć, że człowiek mówi prawdę, kiedy wiesz, że skłamałbyś, będąc na jego miejscu. | Henry Louis Mencken
Nasze życie staje się lepsze tylko wtedy, gdy podejmujemy ryzyko - a pierwszym i najtrudniejszym ryzykiem, jakie możemy podjąć, jest bycie szczerym wobec samego siebie. | Walter Anderson
Wznieśmy standard, do którego mądrzy i uczciwi mogą się dostosować; reszta jest w rękach Boga. | Jerzy Waszyngton
Żadne dziedzictwo nie jest tak bogate jak uczciwość. | William Shakespeare
Najlepszą miarą uczciwości człowieka nie jest jego zeznanie podatkowe. To zerowa wartość na jego wadze łazienkowej. | Arthur C. Clarke
Jedną z najbardziej podstawowych wartości jest uczciwość. | Catherine Pulsifer
Kamieniami węgielnymi dla zrównoważonego sukcesu są: uczciwość, charakter, prawość, wiara, miłość i lojalność. | Zig Ziglar
Nieuczciwość zignoruje uczciwość w każdym dniu tygodnia, jeśli tylko można na niej coś zyskać. | Charles Dickens
Uczciwość jest pierwszym rozdziałem księgi mądrości. | Thomas Jefferson
Uczciwość to mówienie sobie prawdy. A uczciwość to mówienie prawdy innym ludziom. | Spencer Johnson
Bądź przygotowany i bądź uczciwy. | John Wooden
W biznesie nie ma strefy zmierzchu uczciwości. Dana rzecz jest dobra lub zła. Jest czarna lub biała. | John F. Dodge
Żaden człowiek nie ma wystarczająco dobrej pamięci, aby stać się skutecznym kłamcą. | Abraham Lincoln
Zrównaj się z dzieckiem, będąc szczerym. Nikt nie rozpoznaje fałszu szybciej niż dziecko. | Mary MacCracken
Bądź głupi. Bądź szczery. Bądź uprzejmy. | Ralph Waldo Emerson
Jak już powiedziałem, pierwszą rzeczą jest bycie szczerym wobec siebie. | Nelson Mandela
Uczciwość to obawianie się negatywnej reakcji i mówienie prawdy mimo wszystko. | Michelle C. Ustaszeski
Koncentracja jest moim mottem - najpierw uczciwość, potem przemysł, potem koncentracja. | Andrew Carnegie
Szczera niezgoda jest często dobrym znakiem postępu. | Gandhi
Wątpliwości, pobłażane i pielęgnowane, mogą stać się zaprzeczeniem; ale jeśli są uczciwe i oparte na dokładnym badaniu, mogą wkrótce doprowadzić do pełnego ustalenia prawdy. | Ambrose Bierce
