<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'График за имейли';
$labels['email_schedule'] = 'График за имейли';
$labels['schedule'] = 'График';
$labels['scheduled'] = 'Планирано';
$labels['scheduled_messages'] = 'Планирани съобщения';
$labels['show_scheduled_messages'] = 'Показване на планирани съобщения.';
$labels['message_scheduled'] = 'Планирано съобщение.';
$labels['no_scheduled_messages'] = 'Няма съобщения в опашката на графика.';
$labels['warning_unsent_messages'] = 'Някои от планираните ви съобщения не са изпратени.';
$labels['message_delete_confirm'] = 'Искате ли да изтриете окончателно това съобщение?';

$labels['immediately'] = 'Незабавно';
$labels['in_5_minutes'] = 'За 5 минути';
$labels['in_10_minutes'] = 'За 10 минути';
$labels['in_15_minutes'] = 'За 15 минути';
$labels['in_30_minutes'] = 'За 30 минути';
$labels['in_1_hour'] = 'За 1 час';
$labels['in_2_hours'] = 'След 2 часа';
$labels['in_6_hours'] = 'След 6 часа';
$labels['at_a_specific_time'] = 'В определено време';

$labels['disabled'] = 'Планирането на съобщенията е деактивирано. Свържете се с администратора.';
$labels['draft_note'] = 'Това съобщение е запазено като чернова и е премахнато от опашката на графика. За да го планирате отново, щракнете върху бутона Планиране.';
$labels['error_editing'] = 'Не може да редактирате планираното съобщение; съобщението може да е изпратено или изтрито.';
$labels['error_deleting'] = 'Не може да преместите съобщението в кошчето; съобщението може да е изпратено, изтрито или пощенската кутия за боклук да не е налична.';

$labels['send_message'] = 'Изпрати съобщение';
$labels['setting_delay'] = 'Забавяне по подразбиране при изпращане на съобщения';
$labels['setting_highlight'] = 'Подчертаване на планираните съобщения, които предстои да бъдат изпратени';

$labels['email_being_sent'] = 'Изпращане на имейл';
$labels['send_now'] = 'Изпрати сега';
$labels['schedule_now'] = 'Планирайте сега';
$labels['cancel_sending'] = 'Отмяна на изпращането';
$labels['setting_countdown'] = 'Обратното броене преди изпращане на съобщения';
$labels['disable_countdown'] = 'Деактивиране на';
$labels['3_seconds'] = '3 секунди';
$labels['5_seconds'] = '5 секунди';
$labels['10_seconds'] = '10 секунди';
$labels['15_seconds'] = '15 секунди';

$labels['cannot_schedule_message'] = 'Не мога да планирам съобщение:';
$labels['time_has_already_passed'] = 'Планираното време вече е изтекло.';
$labels['invalid_time_format'] = 'Невалиден формат на времето.';
$labels['draft_folder_not_specified'] = 'Грешка при плъгина за график за имейл: Не е посочена папка за чернова.';
$labels['error'] = 'Грешка:';
$labels['attachment_tool_large'] = 'Конфигурацията на сървъра ограничава прикачените файлове към планираните съобщения до размер $.';
$labels['message_already_scheduled'] = 'Това съобщение вече е планирано.';

