<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'E-Mail-Zeitplaner';
$labels['email_schedule'] = 'E-Mail-Zeitplaner';
$labels['schedule'] = 'Nachricht geplant senden';
$labels['scheduled'] = 'Nachricht wurde zum geplanten Versand bereitgestellt';
$labels['scheduled_messages'] = 'Geplante Nachrichten';
$labels['show_scheduled_messages'] = 'Geplante Nachrichten anzeigen';
$labels['message_scheduled'] = 'Geplante Nachricht';
$labels['no_scheduled_messages'] = 'Es befinden keine geplanten Nachrichten in der Warteschlange.';
$labels['warning_unsent_messages'] = 'Eine oder mehrere geplante Nachrichten wurden nicht gesendet.';
$labels['message_delete_confirm'] = 'Möchten Sie diese Nachricht endgültig löschen?';

$labels['immediately'] = 'sofort';
$labels['in_5_minutes'] = 'in 5 Minuten';
$labels['in_10_minutes'] = 'in 10 Minuten';
$labels['in_15_minutes'] = 'in 15 Minuten';
$labels['in_30_minutes'] = 'in 30 Minuten';
$labels['in_1_hour'] = 'in 1 Stunde';
$labels['in_2_hours'] = 'in 2 Stunden';
$labels['in_6_hours'] = 'in 6 Stunden';
$labels['at_a_specific_time'] = 'Zu einer bestimmten Zeit';

$labels['disabled'] = 'Das Planen des Nachrichtenversands ist nicht aktiviert. Bitte nehmen Sie Kontakt mit dem Server-Administrator auf.';
$labels['draft_note'] = 'Diese Nachricht wurde aus der Warteschlange für geplante Nachrichten entfernt und als Entwurf gespeichert. Klicken Sie auf "Nachricht planen", um die Nachricht erneut zu versenden.';
$labels['error_editing'] = 'Die Nachricht kann nicht bearbeitet werden. Die Nachricht wurde bereits gesendet oder gelöscht.';
$labels['error_deleting'] = 'Die Nachricht kann nicht in den Papierkorb verschoben werden. Die Nachricht wurde bereits gesendet, gelöscht oder die gelöschten Objekte sind nicht verfügbar.';

$labels['send_message'] = 'Nachricht senden';
$labels['setting_delay'] = 'Nachrichten senden';
$labels['setting_highlight'] = 'Geplante Nachrichten hervorheben';

$labels['email_being_sent'] = 'Nachricht senden';
$labels['send_now'] = 'Jetzt senden';
$labels['schedule_now'] = 'Jetzt planen';
$labels['cancel_sending'] = 'Senden abbrechen';
$labels['setting_countdown'] = 'Countdown vor dem Senden der Nachrichten';
$labels['disable_countdown'] = 'Deaktivieren';
$labels['3_seconds'] = '3 Sekunden';
$labels['5_seconds'] = '5 Sekunden';
$labels['10_seconds'] = '10 Sekunden';
$labels['15_seconds'] = '15 Sekunden';

$labels['cannot_schedule_message'] = 'Nachricht kann nicht geplant werden:';
$labels['time_has_already_passed'] = 'Die geplante Zeit ist bereits verstrichen.';
$labels['invalid_time_format'] = 'Ungültiges Zeitformat.';
$labels['draft_folder_not_specified'] = 'Fehler im E-Mail-Zeitplan-Plugin: Entwurfsordner nicht angegeben.';
$labels['error'] = 'Fehler:';
$labels['attachment_tool_large'] = 'Die Serverkonfiguration begrenzt geplante Nachrichtenanhänge auf $size.';
$labels['message_already_scheduled'] = 'Diese Nachricht ist bereits geplant.';

