<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Προγραμματιστής email';
$labels['email_schedule'] = 'Προγραμματιστής email';
$labels['schedule'] = 'Πρόγραμμα';
$labels['scheduled'] = 'Προγραμματισμένο';
$labels['scheduled_messages'] = 'Προγραμματισμένα μηνύματα';
$labels['show_scheduled_messages'] = 'Εμφάνιση προγραμματισμένων μηνυμάτων.';
$labels['message_scheduled'] = 'Μήνυμα προγραμματισμένο.';
$labels['no_scheduled_messages'] = 'Δεν υπάρχουν μηνύματα στην ουρά χρονοδιαγράμματος.';
$labels['warning_unsent_messages'] = 'Κάποια από τα προγραμματισμένα μηνύματά σας δεν έχουν σταλεί.';
$labels['message_delete_confirm'] = 'Θέλετε να διαγράψετε οριστικά αυτό το μήνυμα;';

$labels['immediately'] = 'Αμέσως';
$labels['in_5_minutes'] = 'Σε 5 λεπτά';
$labels['in_10_minutes'] = 'Σε 10 λεπτά';
$labels['in_15_minutes'] = 'Σε 15 λεπτά';
$labels['in_30_minutes'] = 'Σε 30 λεπτά';
$labels['in_1_hour'] = 'Σε 1 ώρα';
$labels['in_2_hours'] = 'Σε 2 ώρες';
$labels['in_6_hours'] = 'Σε 6 ώρες';
$labels['at_a_specific_time'] = 'Σε συγκεκριμένη χρονική στιγμή';

$labels['disabled'] = 'Ο προγραμματισμός μηνυμάτων είναι απενεργοποιημένος. Επικοινωνήστε με το διαχειριστή.';
$labels['draft_note'] = 'Αυτό το μήνυμα αποθηκεύτηκε ως προσχέδιο και αφαιρέθηκε από την ουρά χρονοδιαγράμματος. Για να το προγραμματίσετε ξανά, κάντε κλικ στο κουμπί Προγραμματισμός.';
$labels['error_editing'] = 'Δεν είναι δυνατή η επεξεργασία του προγραμματισμένου μηνύματος- το μήνυμα ενδέχεται να έχει αποσταλεί ή διαγραφεί.';
$labels['error_deleting'] = 'Δεν είναι δυνατή η μεταφορά του μηνύματος στον κάδο απορριμμάτων- το μήνυμα μπορεί να έχει αποσταλεί, να έχει διαγραφεί ή το γραμματοκιβώτιο του κάδου απορριμμάτων να μην είναι διαθέσιμο.';

$labels['send_message'] = 'Αποστολή μηνύματος';
$labels['setting_delay'] = 'Προεπιλεγμένη καθυστέρηση για την αποστολή μηνυμάτων';
$labels['setting_highlight'] = 'Επισημάνετε τα προγραμματισμένα μηνύματα που πρόκειται να αποσταλούν';

$labels['email_being_sent'] = 'Αποστολή email';
$labels['send_now'] = 'Στείλτε τώρα';
$labels['schedule_now'] = 'Προγραμματισμός τώρα';
$labels['cancel_sending'] = 'Ακύρωση αποστολής';
$labels['setting_countdown'] = 'Αντίστροφη μέτρηση πριν από την αποστολή μηνυμάτων';
$labels['disable_countdown'] = 'Απενεργοποίηση';
$labels['3_seconds'] = '3 δευτερόλεπτα';
$labels['5_seconds'] = '5 δευτερόλεπτα';
$labels['10_seconds'] = '10 δευτερόλεπτα';
$labels['15_seconds'] = '15 δευτερόλεπτα';

$labels['cannot_schedule_message'] = 'Δεν μπορεί να προγραμματιστεί μήνυμα:';
$labels['time_has_already_passed'] = 'Ο προγραμματισμένος χρόνος έχει ήδη παρέλθει.';
$labels['invalid_time_format'] = 'Μη έγκυρη μορφή ώρας.';
$labels['draft_folder_not_specified'] = 'Σφάλμα του plugin για το χρονοδιάγραμμα ηλεκτρονικού ταχυδρομείου: Δεν έχει καθοριστεί φάκελος προσχεδίου.';
$labels['error'] = 'Σφάλμα:';
$labels['attachment_tool_large'] = 'Η ρύθμιση παραμέτρων του διακομιστή περιορίζει τα συνημμένα των προγραμματισμένων μηνυμάτων στο μέγεθος $size.';
$labels['message_already_scheduled'] = 'Αυτό το μήνυμα είναι ήδη προγραμματισμένο.';

