<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'E-posti ajaplaneerija';
$labels['email_schedule'] = 'E-posti ajaplaneerija';
$labels['schedule'] = 'Ajakava';
$labels['scheduled'] = 'Planeeritud';
$labels['scheduled_messages'] = 'Ajastatud sõnumid';
$labels['show_scheduled_messages'] = 'Näita plaanitud sõnumeid.';
$labels['message_scheduled'] = 'Sõnum kavandatud.';
$labels['no_scheduled_messages'] = 'Sõiduplaani järjekorras ei ole sõnumeid.';
$labels['warning_unsent_messages'] = 'Mõned teie kavandatud sõnumid ei ole saadetud.';
$labels['message_delete_confirm'] = 'Kas soovite selle sõnumi lõplikult kustutada?';

$labels['immediately'] = 'Kohe';
$labels['in_5_minutes'] = '5 minutiga';
$labels['in_10_minutes'] = '10 minutiga';
$labels['in_15_minutes'] = '15 minutiga';
$labels['in_30_minutes'] = '30 minutiga';
$labels['in_1_hour'] = '1 tunni jooksul';
$labels['in_2_hours'] = '2 tunni jooksul';
$labels['in_6_hours'] = '6 tunni jooksul';
$labels['at_a_specific_time'] = 'Konkreetsel ajal';

$labels['disabled'] = 'Sõnumite ajastamine on välja lülitatud. Võtke ühendust administraatoriga.';
$labels['draft_note'] = 'See sõnum salvestati eelnõuna ja eemaldati ajakava järjekorrast. Selle uuesti ajastamiseks klõpsake nupule Schedule (Ajastada).';
$labels['error_editing'] = 'Ajastatud sõnumit ei saa redigeerida; sõnum võib olla saadetud või kustutatud.';
$labels['error_deleting'] = 'Sõnumit ei saa prügikasti viia; sõnum võib olla saadetud, kustutatud või prügikast ei ole saadaval.';

$labels['send_message'] = 'Saada sõnum';
$labels['setting_delay'] = 'Sõnumite saatmise vaikimisi viivitus';
$labels['setting_highlight'] = 'Tähistab saadetavad plaanilised sõnumid, mida kavatsetakse saata';

$labels['email_being_sent'] = 'E-posti saatmine';
$labels['send_now'] = 'Saada nüüd';
$labels['schedule_now'] = 'Ajakava nüüd';
$labels['cancel_sending'] = 'Tühista saatmine';
$labels['setting_countdown'] = 'Tagasiarvestus enne sõnumite saatmist';
$labels['disable_countdown'] = 'Lülita välja';
$labels['3_seconds'] = '3 sekundit';
$labels['5_seconds'] = '5 sekundit';
$labels['10_seconds'] = '10 sekundit';
$labels['15_seconds'] = '15 sekundit';

$labels['cannot_schedule_message'] = 'Ei saa planeerida sõnumit:';
$labels['time_has_already_passed'] = 'Planeeritud aeg on juba möödas.';
$labels['invalid_time_format'] = 'Vale ajaformaat.';
$labels['draft_folder_not_specified'] = 'E-posti ajakava plugina viga: Eelnõu kaust ei ole määratud.';
$labels['error'] = 'Viga:';
$labels['attachment_tool_large'] = 'Serveri konfiguratsioon piirab planeeritud sõnumite manuseid $size.';
$labels['message_already_scheduled'] = 'See sõnum on juba planeeritud.';

