<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Sähköpostin ajastin';
$labels['email_schedule'] = 'Sähköpostin ajastin';
$labels['schedule'] = 'Aikataulu';
$labels['scheduled'] = 'Aikataulutettu';
$labels['scheduled_messages'] = 'Ajastetut viestit';
$labels['show_scheduled_messages'] = 'Näytä ajastetut viestit.';
$labels['message_scheduled'] = 'Viesti ajoitettu.';
$labels['no_scheduled_messages'] = 'Aikataulujonossa ei ole viestejä.';
$labels['warning_unsent_messages'] = 'Joitakin ajastettuja viestejäsi ei ole lähetetty.';
$labels['message_delete_confirm'] = 'Haluatko poistaa tämän viestin pysyvästi?';

$labels['immediately'] = 'Välittömästi';
$labels['in_5_minutes'] = '5 minuutissa';
$labels['in_10_minutes'] = '10 minuutissa';
$labels['in_15_minutes'] = '15 minuutissa';
$labels['in_30_minutes'] = '30 minuutissa';
$labels['in_1_hour'] = '1 tunnissa';
$labels['in_2_hours'] = '2 tunnin kuluttua';
$labels['in_6_hours'] = '6 tunnin kuluttua';
$labels['at_a_specific_time'] = 'Tiettynä ajankohtana';

$labels['disabled'] = 'Viestien aikataulutus on poistettu käytöstä. Ota yhteys järjestelmänvalvojaan.';
$labels['draft_note'] = 'Tämä viesti tallennettiin luonnoksena ja poistettiin aikataulujonosta. Voit ajoittaa sen uudelleen napsauttamalla Aikatauluta-painiketta.';
$labels['error_editing'] = 'Ajastettua viestiä ei voi muokata; viesti on ehkä lähetetty tai poistettu.';
$labels['error_deleting'] = 'Viestiä ei voi siirtää roskakoriin; viesti on ehkä lähetetty, poistettu tai roskapostilaatikko ei ole käytettävissä.';

$labels['send_message'] = 'Lähetä viesti';
$labels['setting_delay'] = 'Viestien lähettämisen oletusviive';
$labels['setting_highlight'] = 'Korosta pian lähetettävät ajastetut viestit';

$labels['email_being_sent'] = 'Sähköpostin lähettäminen';
$labels['send_now'] = 'Lähetä nyt';
$labels['schedule_now'] = 'Aikataulu nyt';
$labels['cancel_sending'] = 'Peruuta lähetys';
$labels['setting_countdown'] = 'Lähtölaskenta ennen viestien lähettämistä';
$labels['disable_countdown'] = 'Poista käytöstä';
$labels['3_seconds'] = '3 sekuntia';
$labels['5_seconds'] = '5 sekuntia';
$labels['10_seconds'] = '10 sekuntia';
$labels['15_seconds'] = '15 sekuntia';

$labels['cannot_schedule_message'] = 'Viestiä ei voi ajoittaa:';
$labels['time_has_already_passed'] = 'Aikataulun mukainen aika on jo kulunut.';
$labels['invalid_time_format'] = 'Virheellinen aikamuoto.';
$labels['draft_folder_not_specified'] = 'Sähköpostiaikataulun lisäosan virhe: Luonnoskansiota ei ole määritetty.';
$labels['error'] = 'Virhe:';
$labels['attachment_tool_large'] = 'Palvelimen asetukset rajoittavat ajastettujen viestien liitetiedostojen koon $size.';
$labels['message_already_scheduled'] = 'Tämä viesti on jo ajastettu.';

