<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'メールスケジューラー';
$labels['email_schedule'] = 'メールスケジューラー';
$labels['schedule'] = 'スケジュール';
$labels['scheduled'] = '予定';
$labels['scheduled_messages'] = 'スケジュールされたメッセージ';
$labels['show_scheduled_messages'] = 'スケジュールされたメッセージを表示する。';
$labels['message_scheduled'] = 'メッセージの予定';
$labels['no_scheduled_messages'] = 'スケジュール・キューにメッセージがない。';
$labels['warning_unsent_messages'] = '予約したメッセージの一部が送信されていません。';
$labels['message_delete_confirm'] = 'このメッセージを永久に削除しますか？';

$labels['immediately'] = '直ちに';
$labels['in_5_minutes'] = '5分以内';
$labels['in_10_minutes'] = '10分以内';
$labels['in_15_minutes'] = '15分以内';
$labels['in_30_minutes'] = '30分以内';
$labels['in_1_hour'] = '1時間以内';
$labels['in_2_hours'] = '2時間以内';
$labels['in_6_hours'] = '6時間以内';
$labels['at_a_specific_time'] = '特定の時間に';

$labels['disabled'] = 'メッセージのスケジューリングが無効になっている。管理者に連絡してください。';
$labels['draft_note'] = 'このメッセージは下書きとして保存され、スケジュールキューから削除されました。再度スケジュールするには、スケジュールボタンをクリックしてください。';
$labels['error_editing'] = 'メッセージが送信されたか削除された可能性があります。';
$labels['error_deleting'] = 'メッセージをゴミ箱に移動できません。メッセージが送信されたか、削除されたか、ゴミ箱メールボックスが利用できない可能性があります。';

$labels['send_message'] = 'メッセージを送る';
$labels['setting_delay'] = 'メッセージ送信のデフォルト遅延';
$labels['setting_highlight'] = '送信予定のメッセージをハイライト表示';

$labels['email_being_sent'] = '電子メールの送信';
$labels['send_now'] = '今すぐ送信';
$labels['schedule_now'] = 'スケジュール';
$labels['cancel_sending'] = '送信をキャンセルする';
$labels['setting_countdown'] = 'メッセージ送信前のカウントダウン';
$labels['disable_countdown'] = '無効';
$labels['3_seconds'] = '3秒';
$labels['5_seconds'] = '5秒';
$labels['10_seconds'] = '10秒';
$labels['15_seconds'] = '15秒';

$labels['cannot_schedule_message'] = 'メッセージをスケジュールできません：';
$labels['time_has_already_passed'] = '予定時間はすでに過ぎている。';
$labels['invalid_time_format'] = '無効な時間形式です。';
$labels['draft_folder_not_specified'] = 'メールスケジュールプラグインのエラー：下書きフォルダが指定されていません。';
$labels['error'] = 'エラー：';
$labels['attachment_tool_large'] = 'サーバー構成では、スケジュールされたメッセージの添付ファイルは$sizeに制限されています。';
$labels['message_already_scheduled'] = 'このメッセージはすでに予定されています。';

