<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'E-pasta plānotājs';
$labels['email_schedule'] = 'E-pasta plānotājs';
$labels['schedule'] = 'Grafiks';
$labels['scheduled'] = 'Plānotais';
$labels['scheduled_messages'] = 'Plānotie ziņojumi';
$labels['show_scheduled_messages'] = 'Rādīt plānotos ziņojumus.';
$labels['message_scheduled'] = 'Ziņojums ir plānots.';
$labels['no_scheduled_messages'] = 'Plāna rindā nav ziņojumu.';
$labels['warning_unsent_messages'] = 'Daži no jūsu plānotajiem ziņojumiem nav nosūtīti.';
$labels['message_delete_confirm'] = 'Vai vēlaties pastāvīgi dzēst šo ziņojumu?';

$labels['immediately'] = 'Uzreiz';
$labels['in_5_minutes'] = '5 minūšu laikā';
$labels['in_10_minutes'] = '10 minūšu laikā';
$labels['in_15_minutes'] = '15 minūšu laikā';
$labels['in_30_minutes'] = '30 minūšu laikā';
$labels['in_1_hour'] = '1 stundas laikā';
$labels['in_2_hours'] = 'Pēc 2 stundām';
$labels['in_6_hours'] = 'Pēc 6 stundām';
$labels['at_a_specific_time'] = 'Konkrētā laikā';

$labels['disabled'] = 'Ziņojumu plānošana ir atspējota. Sazinieties ar administratoru.';
$labels['draft_note'] = 'Šis ziņojums tika saglabāts kā melnraksts un noņemts no grafika rindas. Lai to atkal ieplānotu, noklikšķiniet uz pogas Plānot.';
$labels['error_editing'] = 'Nevar rediģēt ieplānoto ziņojumu; iespējams, ziņojums ir nosūtīts vai izdzēsts.';
$labels['error_deleting'] = 'Ziņu nevar pārvietot uz atkritumu urnu; iespējams, ziņa ir nosūtīta, izdzēsta vai atkritumu urna nav pieejama.';

$labels['send_message'] = 'Nosūtīt ziņojumu';
$labels['setting_delay'] = 'Noklusējuma ziņojumu nosūtīšanas aizkave';
$labels['setting_highlight'] = 'Izcelt plānotos ziņojumus, kas drīz tiks nosūtīti.';

$labels['email_being_sent'] = 'E-pasta sūtīšana';
$labels['send_now'] = 'Sūtīt tagad';
$labels['schedule_now'] = 'Plānojums tagad';
$labels['cancel_sending'] = 'Atcelt sūtīšanu';
$labels['setting_countdown'] = 'Atpakaļskaitīšana pirms ziņojumu nosūtīšanas';
$labels['disable_countdown'] = 'Atslēgt';
$labels['3_seconds'] = '3 sekundes';
$labels['5_seconds'] = '5 sekundes';
$labels['10_seconds'] = '10 sekundes';
$labels['15_seconds'] = '15 sekundes';

$labels['cannot_schedule_message'] = 'Nevar ieplānot ziņojumu:';
$labels['time_has_already_passed'] = 'Plānotais laiks jau ir pagājis.';
$labels['invalid_time_format'] = 'Nederīgs laika formāts.';
$labels['draft_folder_not_specified'] = 'E-pasta grafika spraudņa kļūda: Nav norādīta projekta mape.';
$labels['error'] = 'Kļūda:';
$labels['attachment_tool_large'] = 'Servera konfigurācija ierobežo plānoto ziņojumu pielikumus līdz $izmēram.';
$labels['message_already_scheduled'] = 'Šis ziņojums jau ir ieplānots.';

