<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Agendador de e-mail';
$labels['email_schedule'] = 'Agendador de e-mail';
$labels['schedule'] = 'Horário';
$labels['scheduled'] = 'Programado';
$labels['scheduled_messages'] = 'Mensagens programadas';
$labels['show_scheduled_messages'] = 'Mostrar mensagens programadas.';
$labels['message_scheduled'] = 'Mensagem programada.';
$labels['no_scheduled_messages'] = 'Não há mensagens na fila de programação.';
$labels['warning_unsent_messages'] = 'Algumas de suas mensagens programadas não foram enviadas.';
$labels['message_delete_confirm'] = 'Você quer apagar esta mensagem permanentemente?';

$labels['immediately'] = 'Imediatamente';
$labels['in_5_minutes'] = 'Em 5 minutos';
$labels['in_10_minutes'] = 'Em 10 minutos';
$labels['in_15_minutes'] = 'Em 15 minutos';
$labels['in_30_minutes'] = 'Em 30 minutos';
$labels['in_1_hour'] = 'Em 1 hora';
$labels['in_2_hours'] = 'Em 2 horas';
$labels['in_6_hours'] = 'Em 6 horas';
$labels['at_a_specific_time'] = 'Em um momento específico';

$labels['disabled'] = 'O agendamento de mensagens está desativado. Entre em contato com o administrador.';
$labels['draft_note'] = 'Esta mensagem foi salva como rascunho e removida da fila de programação. Para agendá-la novamente, clique no botão Agendar.';
$labels['error_editing'] = 'Não é possível editar a mensagem programada; a mensagem pode ter sido enviada ou excluída.';
$labels['error_deleting'] = 'Não é possível mover a mensagem para o lixo; a mensagem pode ter sido enviada, apagada ou a caixa de correio do lixo não está disponível.';

$labels['send_message'] = 'Enviar mensagem';
$labels['setting_delay'] = 'Atraso por defeito para o envio de mensagens';
$labels['setting_highlight'] = 'Destacar as mensagens programadas que estão prestes a serem enviadas';

$labels['email_being_sent'] = 'Envio de e-mail';
$labels['send_now'] = 'Enviar agora';
$labels['schedule_now'] = 'Programar agora';
$labels['cancel_sending'] = 'Cancelar o envio';
$labels['setting_countdown'] = 'Contagem regressiva antes de enviar mensagens';
$labels['disable_countdown'] = 'Desativar';
$labels['3_seconds'] = '3 segundos';
$labels['5_seconds'] = '5 segundos';
$labels['10_seconds'] = '10 segundos';
$labels['15_seconds'] = '15 segundos';

$labels['cannot_schedule_message'] = 'Não é possível agendar mensagem:';
$labels['time_has_already_passed'] = 'O tempo programado já passou.';
$labels['invalid_time_format'] = 'Formato de tempo inválido.';
$labels['draft_folder_not_specified'] = 'Erro no plugin de programação de e-mail: Pasta de rascunho não especificada.';
$labels['error'] = 'Erro:';
$labels['attachment_tool_large'] = 'A configuração do servidor limita os anexos de mensagens agendadas a $size.';
$labels['message_already_scheduled'] = 'Essa mensagem já está programada.';

