<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Programator e-mail';
$labels['email_schedule'] = 'Programator de e-mail';
$labels['schedule'] = 'Programare';
$labels['scheduled'] = 'Programat';
$labels['scheduled_messages'] = 'Mesaje programate';
$labels['show_scheduled_messages'] = 'Afișați mesajele programate.';
$labels['message_scheduled'] = 'Mesaj programat.';
$labels['no_scheduled_messages'] = 'Nu există mesaje în coada de așteptare a programării.';
$labels['warning_unsent_messages'] = 'Unele dintre mesajele dumneavoastră programate nu au fost trimise.';
$labels['message_delete_confirm'] = 'Doriți să ștergeți definitiv acest mesaj?';

$labels['immediately'] = 'Imediat';
$labels['in_5_minutes'] = 'În 5 minute';
$labels['in_10_minutes'] = 'În 10 minute';
$labels['in_15_minutes'] = 'În 15 minute';
$labels['in_30_minutes'] = 'În 30 de minute';
$labels['in_1_hour'] = 'În 1 oră';
$labels['in_2_hours'] = 'În 2 ore';
$labels['in_6_hours'] = 'În 6 ore';
$labels['at_a_specific_time'] = 'La un moment dat';

$labels['disabled'] = 'Programarea mesajelor este dezactivată. Contactați administratorul.';
$labels['draft_note'] = 'Acest mesaj a fost salvat ca proiect și eliminat din coada de programări. Pentru a-l programa din nou, faceți clic pe butonul Schedule (Programare).';
$labels['error_editing'] = 'Nu se poate edita mesajul programat; este posibil ca mesajul să fi fost trimis sau șters.';
$labels['error_deleting'] = 'Nu se poate muta mesajul în coșul de gunoi; este posibil ca mesajul să fi fost trimis, șters sau căsuța poștală pentru coșul de gunoi să nu fie disponibilă.';

$labels['send_message'] = 'Trimiteți un mesaj';
$labels['setting_delay'] = 'Întârziere implicită pentru trimiterea mesajelor';
$labels['setting_highlight'] = 'Evidențiați mesajele programate care urmează să fie trimise';

$labels['email_being_sent'] = 'Trimiterea de e-mail';
$labels['send_now'] = 'Trimiteți acum';
$labels['schedule_now'] = 'Programează-te acum';
$labels['cancel_sending'] = 'Anulează trimiterea';
$labels['setting_countdown'] = 'Numărătoarea inversă înainte de trimiterea mesajelor';
$labels['disable_countdown'] = 'Dezactivați';
$labels['3_seconds'] = '3 secunde';
$labels['5_seconds'] = '5 secunde';
$labels['10_seconds'] = '10 secunde';
$labels['15_seconds'] = '15 secunde';

$labels['cannot_schedule_message'] = 'Nu se poate programa mesajul:';
$labels['time_has_already_passed'] = 'Timpul programat a trecut deja.';
$labels['invalid_time_format'] = 'Formatul de timp invalid.';
$labels['draft_folder_not_specified'] = 'Eroare în pluginul de programare a e-mailurilor: Dosarul de redactare nu este specificat.';
$labels['error'] = 'Eroare:';
$labels['attachment_tool_large'] = 'Configurația serverului limitează atașamentele mesajelor programate la $size.';
$labels['message_already_scheduled'] = 'Acest mesaj este deja programat.';

