<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Plánovač e-mailov';
$labels['email_schedule'] = 'Plánovač e-mailov';
$labels['schedule'] = 'Plán';
$labels['scheduled'] = 'Plánované';
$labels['scheduled_messages'] = 'Naplánované správy';
$labels['show_scheduled_messages'] = 'Zobraziť naplánované správy.';
$labels['message_scheduled'] = 'Naplánovaná správa.';
$labels['no_scheduled_messages'] = 'Vo fronte plánovania nie sú žiadne správy.';
$labels['warning_unsent_messages'] = 'Niektoré z vašich naplánovaných správ neboli odoslané.';
$labels['message_delete_confirm'] = 'Chcete túto správu natrvalo vymazať?';

$labels['immediately'] = 'Okamžite';
$labels['in_5_minutes'] = 'Za 5 minút';
$labels['in_10_minutes'] = 'Za 10 minút';
$labels['in_15_minutes'] = 'Za 15 minút';
$labels['in_30_minutes'] = 'Za 30 minút';
$labels['in_1_hour'] = 'Za 1 hodinu';
$labels['in_2_hours'] = 'Za 2 hodiny';
$labels['in_6_hours'] = 'Za 6 hodín';
$labels['at_a_specific_time'] = 'V určitom čase';

$labels['disabled'] = 'Plánovanie správ je vypnuté. Kontaktujte správcu.';
$labels['draft_note'] = 'Táto správa bola uložená ako koncept a odstránená z frontu plánu. Ak ju chcete znova naplánovať, kliknite na tlačidlo Naplánovať.';
$labels['error_editing'] = 'Naplánovanú správu nemožno upraviť; správa mohla byť odoslaná alebo vymazaná.';
$labels['error_deleting'] = 'Správu nemožno presunúť do koša; správa mohla byť odoslaná, vymazaná alebo schránka koša nie je k dispozícii.';

$labels['send_message'] = 'Odoslať správu';
$labels['setting_delay'] = 'Predvolené oneskorenie odosielania správ';
$labels['setting_highlight'] = 'Zvýraznenie plánovaných správ, ktoré sa majú odoslať';

$labels['email_being_sent'] = 'Odosielanie e-mailov';
$labels['send_now'] = 'Odoslať teraz';
$labels['schedule_now'] = 'Naplánovať teraz';
$labels['cancel_sending'] = 'Zrušiť odosielanie';
$labels['setting_countdown'] = 'Odpočítavanie pred odoslaním správ';
$labels['disable_countdown'] = 'Zakázať';
$labels['3_seconds'] = '3 sekundy';
$labels['5_seconds'] = '5 sekúnd';
$labels['10_seconds'] = '10 sekúnd';
$labels['15_seconds'] = '15 sekúnd';

$labels['cannot_schedule_message'] = 'Nemožno naplánovať správu:';
$labels['time_has_already_passed'] = 'Plánovaný čas už uplynul.';
$labels['invalid_time_format'] = 'Nesprávny formát času.';
$labels['draft_folder_not_specified'] = 'Chyba zásuvného modulu plánu e-mailov: Nie je zadaný priečinok s návrhom.';
$labels['error'] = 'Chyba:';
$labels['attachment_tool_large'] = 'Konfigurácia servera obmedzuje veľkosť príloh plánovaných správ na $.';
$labels['message_already_scheduled'] = 'Táto správa je už naplánovaná.';

