<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Načrtovalec e-pošte';
$labels['email_schedule'] = 'Načrtovalec e-pošte';
$labels['schedule'] = 'Urnik';
$labels['scheduled'] = 'Načrtovani';
$labels['scheduled_messages'] = 'Načrtovana sporočila';
$labels['show_scheduled_messages'] = 'Prikaži načrtovana sporočila.';
$labels['message_scheduled'] = 'Sporočilo načrtovano.';
$labels['no_scheduled_messages'] = 'V čakalni vrsti urnika ni nobenih sporočil.';
$labels['warning_unsent_messages'] = 'Nekatera načrtovana sporočila niso bila poslana.';
$labels['message_delete_confirm'] = 'Ali želite trajno izbrisati to sporočilo?';

$labels['immediately'] = 'Takoj';
$labels['in_5_minutes'] = 'V 5 minutah';
$labels['in_10_minutes'] = 'V 10 minutah';
$labels['in_15_minutes'] = 'V 15 minutah';
$labels['in_30_minutes'] = 'V 30 minutah';
$labels['in_1_hour'] = 'V 1 uri';
$labels['in_2_hours'] = 'V 2 urah';
$labels['in_6_hours'] = 'V 6 urah';
$labels['at_a_specific_time'] = 'Ob določenem času';

$labels['disabled'] = 'Načrtovanje sporočil je onemogočeno. Obrnite se na skrbnika.';
$labels['draft_note'] = 'To sporočilo je bilo shranjeno kot osnutek in odstranjeno iz čakalne vrste. Če ga želite znova načrtovati, kliknite gumb Načrtovati.';
$labels['error_editing'] = 'Načrtovanega sporočila ni mogoče urejati; sporočilo je bilo morda poslano ali izbrisano.';
$labels['error_deleting'] = 'Sporočila ni mogoče premakniti v koš; sporočilo je bilo morda poslano, izbrisano ali pa poštni predal za koš ni na voljo.';

$labels['send_message'] = 'Pošlji sporočilo';
$labels['setting_delay'] = 'Privzeta zamuda za pošiljanje sporočil';
$labels['setting_highlight'] = 'Označite načrtovana sporočila, ki bodo kmalu poslana.';

$labels['email_being_sent'] = 'Pošiljanje e-pošte';
$labels['send_now'] = 'Pošlji zdaj';
$labels['schedule_now'] = 'Načrtujte zdaj';
$labels['cancel_sending'] = 'Prekliči pošiljanje';
$labels['setting_countdown'] = 'Odštevanje pred pošiljanjem sporočil';
$labels['disable_countdown'] = 'Onemogočite';
$labels['3_seconds'] = '3 sekunde';
$labels['5_seconds'] = '5 sekund';
$labels['10_seconds'] = '10 sekund';
$labels['15_seconds'] = '15 sekund';

$labels['cannot_schedule_message'] = 'Sporočila ni mogoče načrtovati:';
$labels['time_has_already_passed'] = 'Načrtovani čas je že potekel.';
$labels['invalid_time_format'] = 'Nepravilna časovna oblika.';
$labels['draft_folder_not_specified'] = 'Napaka vtičnika urnika e-pošte: mapo osnutka ni določena.';
$labels['error'] = 'Napaka:';
$labels['attachment_tool_large'] = 'Konfiguracija strežnika omejuje priponke načrtovanih sporočil na velikost $.';
$labels['message_already_scheduled'] = 'To sporočilo je že načrtovano.';

