<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Планувальник електронної пошти';
$labels['email_schedule'] = 'Розклад електронної пошти';
$labels['schedule'] = 'Запланувати';
$labels['scheduled'] = 'Заплановано';
$labels['scheduled_messages'] = 'Заплановані повідомлення';
$labels['show_scheduled_messages'] = 'Показати заплановані повідомлення.';
$labels['message_scheduled'] = 'Повідомлення заплановано.';
$labels['no_scheduled_messages'] = 'У черзі розкладу немає повідомлень.';
$labels['warning_unsent_messages'] = 'Деякі заплановані повідомлення не надіслано.';
$labels['message_delete_confirm'] = 'Ви хочете назавжди видалити це повідомлення?';

$labels['immediately'] = 'Негайно';
$labels['in_5_minutes'] = 'За 5 хвилин';
$labels['in_10_minutes'] = 'За 10 хвилин';
$labels['in_15_minutes'] = 'За 15 хвилин';
$labels['in_30_minutes'] = 'За 30 хвилин';
$labels['in_1_hour'] = 'За 1 годину';
$labels['in_2_hours'] = 'За 2 години';
$labels['in_6_hours'] = 'За 6 годин';
$labels['at_a_specific_time'] = 'У певний час';

$labels['disabled'] = 'Планування повідомлень вимкнено. Зверніться до адміністратора.';
$labels['draft_note'] = 'Це повідомлення було збережено як чернетку та видалено з черги розкладу. Щоб запланувати його знову, натисніть кнопку Розклад.';
$labels['error_editing'] = 'Неможливо редагувати заплановане повідомлення; повідомлення може бути надіслано або видалено.';
$labels['error_deleting'] = 'Не вдається перемістити повідомлення в кошик; повідомлення, можливо, було надіслано, видалено або поштова скринька сміття недоступна.';

$labels['send_message'] = 'Відправити повідомлення';
$labels['setting_delay'] = 'Надіслати повідомлення';
$labels['setting_highlight'] = 'Виділіть повідомлення, які мають бути надіслані';

$labels['email_being_sent'] = 'Надсилання електронної пошти';
$labels['send_now'] = 'Надішліть зараз';
$labels['schedule_now'] = 'Заплануйте зараз';
$labels['cancel_sending'] = 'Скасувати відправку';
$labels['setting_countdown'] = 'Зворотний відлік перед надсиланням повідомлень';
$labels['disable_countdown'] = 'Вимкнути';
$labels['3_seconds'] = '3 секунди.';
$labels['5_seconds'] = '5 секунд.';
$labels['10_seconds'] = '10 секунд';
$labels['15_seconds'] = '15 секунд.';

$labels['cannot_schedule_message'] = 'Неможливо запланувати повідомлення:';
$labels['time_has_already_passed'] = 'Запланований час вже минув.';
$labels['invalid_time_format'] = 'Неправильний формат часу.';
$labels['draft_folder_not_specified'] = 'Помилка плагіна розкладу електронної пошти: Не вказано папку для чернеток.';
$labels['error'] = 'Помилка:';
$labels['attachment_tool_large'] = 'Конфігурація сервера обмежує розмір вкладень запланованих повідомлень до $size.';
$labels['message_already_scheduled'] = 'Це повідомлення вже заплановано.';

