<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '电子邮件调度程序';
$labels['email_schedule'] = '电子邮件调度程序';
$labels['schedule'] = '时间安排';
$labels['scheduled'] = '计划';
$labels['scheduled_messages'] = '预定信息';
$labels['show_scheduled_messages'] = '显示计划信息';
$labels['message_scheduled'] = '信息已排定。';
$labels['no_scheduled_messages'] = '计划队列中没有信息。';
$labels['warning_unsent_messages'] = '您的某些预定信息尚未发送。';
$labels['message_delete_confirm'] = '您想永久删除这条信息吗？';

$labels['immediately'] = '立即';
$labels['in_5_minutes'] = '5 分钟内';
$labels['in_10_minutes'] = '10 分钟后';
$labels['in_15_minutes'] = '15 分钟后';
$labels['in_30_minutes'] = '30 分钟后';
$labels['in_1_hour'] = '1 小时后';
$labels['in_2_hours'] = '2 小时后';
$labels['in_6_hours'] = '6 小时后';
$labels['at_a_specific_time'] = '在特定时间';

$labels['disabled'] = '信息调度已禁用。请联系管理员。';
$labels['draft_note'] = '此信息已保存为草稿，并从计划队列中删除。要再次排程，请单击排程按钮。';
$labels['error_editing'] = '无法编辑预定信息；信息可能已发送或删除。';
$labels['error_deleting'] = '无法将邮件移至垃圾箱；邮件可能已发送、删除或垃圾箱不可用。';

$labels['send_message'] = '发送信息';
$labels['setting_delay'] = '发送信息的默认延迟时间';
$labels['setting_highlight'] = '突出显示即将发送的预定信息';

$labels['email_being_sent'] = '发送电子邮件';
$labels['send_now'] = '现在发送';
$labels['schedule_now'] = '现在安排';
$labels['cancel_sending'] = '取消发送';
$labels['setting_countdown'] = '发送信息前的倒计时';
$labels['disable_countdown'] = '禁用';
$labels['3_seconds'] = '3 秒钟';
$labels['5_seconds'] = '5 秒钟';
$labels['10_seconds'] = '10 秒钟';
$labels['15_seconds'] = '15 秒';

$labels['cannot_schedule_message'] = '无法安排信息：';
$labels['time_has_already_passed'] = '预定时间已过。';
$labels['invalid_time_format'] = '时间格式无效。';
$labels['draft_folder_not_specified'] = '电子邮件计划插件错误：未指定草稿文件夹。';
$labels['error'] = '错误：';
$labels['attachment_tool_large'] = '服务器配置将预定邮件附件限制为 $size。';
$labels['message_already_scheduled'] = '该信息已排定。';

