<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Poslední přihlášení';
$labels['setting_show_xlast_login'] = 'Zobrazit poslední přihlášení';
$labels['country'] = 'Země';
$labels['city'] = 'Město';
$labels['location'] = 'Umístění';
$labels['time'] = 'Čas';
$labels['map'] = 'Mapa';
$labels['more_data'] = 'Další údaje';
$labels['whats_this'] = 'Co je to?';
$labels['explanation'] = 'Toto pole zobrazuje místo posledního přihlášení k e-mailovému účtu. Pokud toto umístění nerozpoznáte, může mít vaše heslo k dispozici škodlivý uživatel. V takovém případě byste měli heslo okamžitě změnit.';
$labels['no_info'] = 'Nezobrazují se žádné informace o posledním přihlášení. Tyto informace budou k dispozici při příštím přihlášení k webové poště.';
