<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Sidste login';
$labels['setting_show_xlast_login'] = 'Vis sidste login';
$labels['country'] = 'Land';
$labels['city'] = 'By';
$labels['location'] = 'Placering';
$labels['time'] = 'Tid';
$labels['map'] = 'Kort';
$labels['more_data'] = 'Flere data';
$labels['whats_this'] = 'Hvad er det her?';
$labels['explanation'] = 'Denne boks viser placeringen af det seneste login til din e-mail-konto. Hvis du ikke kan genkende denne placering, kan en ondsindet bruger have din adgangskode. Du bør ændre din adgangskode med det samme, hvis dette sker.';
$labels['no_info'] = 'Der er ingen oplysninger om det seneste login, der skal vises. Oplysningerne vil være tilgængelige næste gang du logger ind på din webmail.';
