<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Utolsó bejelentkezés';
$labels['setting_show_xlast_login'] = 'Utolsó bejelentkezés megjelenítése';
$labels['country'] = 'Ország';
$labels['city'] = 'Város';
$labels['location'] = 'Helyszín';
$labels['time'] = 'Idő';
$labels['map'] = 'Térkép';
$labels['more_data'] = 'További adatok';
$labels['whats_this'] = 'Ez meg mi?';
$labels['explanation'] = 'Ebben a mezőben az e-mail fiókjába történő utolsó bejelentkezés helye látható. Ha nem ismeri fel ezt a helyet, akkor egy rosszindulatú felhasználó birtokában lehet a jelszava. Ha ez megtörténik, azonnal változtassa meg jelszavát.';
$labels['no_info'] = 'Nincs megjelenítendő utolsó bejelentkezési információ. Az információ a következő webmail bejelentkezéskor válik elérhetővé.';
