<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = '마지막 로그인';
$labels['setting_show_xlast_login'] = '마지막 로그인 표시';
$labels['country'] = '국가';
$labels['city'] = '도시';
$labels['location'] = '위치';
$labels['time'] = '시간';
$labels['map'] = '지도';
$labels['more_data'] = '더 많은 데이터';
$labels['whats_this'] = '이게 뭐죠?';
$labels['explanation'] = '이 상자에는 이메일 계정에 마지막으로 로그인한 위치가 표시됩니다. 이 위치를 알지 못하면 악의적인 사용자가 내 비밀번호를 알고 있을 수 있습니다. 이 경우 즉시 비밀번호를 변경해야 합니다.';
$labels['no_info'] = '표시할 마지막 로그인 정보가 없습니다. 이 정보는 다음에 웹메일에 로그인할 때 사용할 수 있습니다.';
