<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Último Login';
$labels['setting_show_xlast_login'] = 'Mostrar Último Login';
$labels['country'] = 'País';
$labels['city'] = 'Cidade';
$labels['location'] = 'Localização';
$labels['time'] = 'Hora';
$labels['map'] = 'Mapa';
$labels['more_data'] = 'Mais dados';
$labels['whats_this'] = 'O que é isso?';
$labels['explanation'] = 'Esta caixa mostra a localização do último login em sua conta de e-mail. Se você não reconhecer este local, um usuário malicioso pode ter sua senha. Você deve mudar sua senha imediatamente se isto acontecer.';
$labels['no_info'] = 'Não há nenhuma última informação de login a ser exibida. As informações ficarão disponíveis na próxima vez em que você acessar seu webmail.';
