<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Último login';
$labels['setting_show_xlast_login'] = 'Mostrar último login';
$labels['country'] = 'País';
$labels['city'] = 'Cidade';
$labels['location'] = 'Localização';
$labels['time'] = 'Tempo';
$labels['map'] = 'Mapa';
$labels['more_data'] = 'Mais dados';
$labels['whats_this'] = 'O que é que é isto?';
$labels['explanation'] = 'Esta caixa mostra a localização do último início de sessão na sua conta de correio eletrónico. Se não reconhecer esta localização, um utilizador malicioso pode ter a sua palavra-passe. Se isto acontecer, deve alterar imediatamente a sua palavra-passe.';
$labels['no_info'] = 'Não existem informações sobre o último início de sessão para apresentar. A informação estará disponível da próxima vez que iniciar sessão no seu webmail.';
