<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Zadnja prijava';
$labels['setting_show_xlast_login'] = 'Prikaži zadnjo prijavo';
$labels['country'] = 'Država';
$labels['city'] = 'Mesto';
$labels['location'] = 'Lokacija';
$labels['time'] = 'Čas';
$labels['map'] = 'Zemljevid';
$labels['more_data'] = 'Več podatkov';
$labels['whats_this'] = 'Kaj je to?';
$labels['explanation'] = 'To polje prikazuje lokacijo zadnje prijave v e-poštni račun. Če te lokacije ne prepoznate, ima morda vaše geslo zlonamerni uporabnik. Če se to zgodi, morate takoj spremeniti geslo.';
$labels['no_info'] = 'Informacij o zadnji prijavi ni mogoče prikazati. Informacije bodo na voljo ob naslednji prijavi v spletno pošto.';
