<?php
/**
 * Roundcube Plus Last Login plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];

$labels['last_login'] = 'Останній вхід';
$labels['setting_show_xlast_login'] = 'Показати останній вхід';
$labels['country'] = 'Країна';
$labels['city'] = 'Місто';
$labels['location'] = 'Локалізація';
$labels['time'] = 'Час';
$labels['map'] = 'Мапа';
$labels['more_data'] = 'Більше...';
$labels['whats_this'] = 'Що це?';
$labels['explanation'] = 'У цьому вікні показано місце останнього входу до облікового запису електронної пошти. Якщо це не ви, зловмисник може мати ваш пароль. Якщо це сталося, потрібно негайно змінити пароль.';
$labels['no_info'] = 'Немає останньої інформації для входу. Інформація стане доступною наступного разу, коли ви ввійдете в веб-пошту.';
