<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Weather';
$labels['weather'] = 'Weather';
$labels['setting_show_xweather'] = 'Show Weather';
$labels['description'] = 'Description';
$labels['humidity'] = 'Humidity';
$labels['pressure'] = 'Pressure';
$labels['clouds'] = 'Clouds';
$labels['wind'] = 'Wind';
$labels['sunrise'] = 'Sunrise';
$labels['sunset'] = 'Sunset';
$labels['more_data'] = 'More data';
$labels['display'] = 'Display';
$labels['options'] = 'Options';
$labels['setting_location_type'] = "Find location by";
$labels['setting_country_code'] = 'Country';
$labels['setting_city'] = 'City';
$labels['setting_latitude'] = "Latitude";
$labels['setting_longitude'] = "Longitude";
$labels['setting_units'] = 'Units';
$labels['setting_icons'] = 'Icons';
$labels['setting_show_description'] = 'Show description';
$labels['setting_show_pressure'] = 'Show pressure';
$labels['setting_show_humidity'] = 'Show humidity';
$labels['setting_show_clouds'] = 'Show clouds';
$labels['setting_show_wind'] = 'Show wind';
$labels['setting_show_sunrise'] = 'Show sunrise';
$labels['setting_show_sunset'] = 'Show sunset';
$labels['metric'] = 'Metric';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Icon preview';
$labels['icons_cutout'] = 'Cutout';
$labels['icons_glossy'] = 'Glossy';
$labels['icons_monochrome'] = 'Monochrome';
$labels['icons_moonlight'] = 'Moonlight';
$labels['icons_stickers'] = 'Stickers';
$labels['check_location'] = 'Check location';
$labels['location_found'] = 'Location found:';
$labels['location_not_found'] = 'Location not found.';
$labels['loading_error'] = 'There was an error while loading the weather data. Please check the country and city settings in the options.';
$labels['country_and_city'] = 'Country and city';
$labels['coordinates'] = 'Coordinates';
$labels['coordinates_link'] = 'Find your latitude and longitude.';
