<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Tiempo';
$labels['weather'] = 'Tiempo';
$labels['setting_show_xweather'] = 'Mostrar el tiempo';
$labels['description'] = 'Descripción';
$labels['humidity'] = 'Humedad';
$labels['pressure'] = 'Presión';
$labels['clouds'] = 'Nubes';
$labels['wind'] = 'Viento';
$labels['sunrise'] = 'Amanecer';
$labels['sunset'] = 'Puesta de sol';
$labels['more_data'] = 'Más datos';
$labels['display'] = 'Mostrar';
$labels['options'] = 'Opciones';
$labels['setting_location_type'] = 'Buscar ubicación por';
$labels['setting_country_code'] = 'País';
$labels['setting_city'] = 'Ciudad';
$labels['setting_latitude'] = 'Latitud';
$labels['setting_longitude'] = 'Longitud';
$labels['setting_units'] = 'Unidades';
$labels['setting_icons'] = 'Iconos';
$labels['setting_show_description'] = 'Mostrar descripción';
$labels['setting_show_pressure'] = 'Mostrar presión';
$labels['setting_show_humidity'] = 'Mostrar humedad';
$labels['setting_show_clouds'] = 'Mostrar nubes';
$labels['setting_show_wind'] = 'Mostrar viento';
$labels['setting_show_sunrise'] = 'Mostrar amanecer';
$labels['setting_show_sunset'] = 'Mostrar puesta de sol';
$labels['metric'] = 'Métrica';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Vista previa del icono';
$labels['icons_cutout'] = 'Recorte';
$labels['icons_glossy'] = 'Brillante';
$labels['icons_monochrome'] = 'Monocromo';
$labels['icons_moonlight'] = 'Luz de luna';
$labels['icons_stickers'] = 'Pegatinas';
$labels['check_location'] = 'Comprobar ubicación';
$labels['location_found'] = 'Ubicación encontrada:';
$labels['location_not_found'] = 'Ubicación no encontrada.';
$labels['loading_error'] = 'Se ha producido un error al cargar los datos meteorológicos. Comprueba los ajustes de país y ciudad en las opciones.';
$labels['country_and_city'] = 'País y ciudad';
$labels['coordinates'] = 'Coordenadas';
$labels['coordinates_link'] = 'Encuentra tu latitud y longitud.';
