<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Météo';
$labels['weather'] = 'Météo';
$labels['setting_show_xweather'] = 'Afficher la météo';
$labels['description'] = 'Description';
$labels['humidity'] = 'Humidité';
$labels['pressure'] = 'Pression';
$labels['clouds'] = 'Nuages';
$labels['wind'] = 'Vent';
$labels['sunrise'] = 'Lever du soleil';
$labels['sunset'] = 'Coucher du soleil';
$labels['more_data'] = 'Plus de données';
$labels['display'] = 'Afficher';
$labels['options'] = 'Options';
$labels['setting_location_type'] = 'Trouver l\'emplacement par';
$labels['setting_country_code'] = 'Pays';
$labels['setting_city'] = 'Ville';
$labels['setting_latitude'] = 'Latitude';
$labels['setting_longitude'] = 'Longitude';
$labels['setting_units'] = 'Unités';
$labels['setting_icons'] = 'Icônes';
$labels['setting_show_description'] = 'Afficher la description';
$labels['setting_show_pressure'] = 'Afficher la pression';
$labels['setting_show_humidity'] = 'Afficher le taux d\'humidité';
$labels['setting_show_clouds'] = 'Afficher la couverture nuageuse';
$labels['setting_show_wind'] = 'Afficher le vent';
$labels['setting_show_sunrise'] = 'Afficher le lever du soleil';
$labels['setting_show_sunset'] = 'Afficher le coucher du soleil';
$labels['metric'] = 'Métrique';
$labels['imperial'] = 'Impérial';
$labels['icon_preview'] = 'Aperçu de l\'icône';
$labels['icons_cutout'] = 'Cutout';
$labels['icons_glossy'] = 'Glossy';
$labels['icons_monochrome'] = 'Monochrome';
$labels['icons_moonlight'] = 'Moonlight';
$labels['icons_stickers'] = 'Stickers';
$labels['check_location'] = 'Vérifiez l\'emplacement';
$labels['location_found'] = 'Emplacement trouvé:';
$labels['location_not_found'] = 'Emplacement non trouvé';
$labels['loading_error'] = 'Une erreur s\'est produite lors du chargement des données météorologiques. Veuillez vérifier les paramètres de pays et de ville dans les options.';
$labels['country_and_city'] = 'Pays et ville';
$labels['coordinates'] = 'Coordonnées';
$labels['coordinates_link'] = 'Trouvez votre latitude et longitude.';
