<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Meteo';
$labels['weather'] = 'Meteo';
$labels['setting_show_xweather'] = 'Mostra meteo';
$labels['description'] = 'Descrizione';
$labels['humidity'] = 'Umidità';
$labels['pressure'] = 'Pressione';
$labels['clouds'] = 'Nuvole';
$labels['wind'] = 'Vento';
$labels['sunrise'] = 'Alba';
$labels['sunset'] = 'Tramonto';
$labels['more_data'] = 'Altri dati';
$labels['display'] = 'Visualizza';
$labels['options'] = 'Opzioni';
$labels['setting_location_type'] = 'Trova posizione per';
$labels['setting_country_code'] = 'Paese';
$labels['setting_city'] = 'Città';
$labels['setting_latitude'] = 'Latitudine';
$labels['setting_longitude'] = 'Longitudine';
$labels['setting_units'] = 'Unità';
$labels['setting_icons'] = 'Icone';
$labels['setting_show_description'] = 'Mostra descrizione';
$labels['setting_show_pressure'] = 'Mostra pressione';
$labels['setting_show_humidity'] = 'Mostra umidità';
$labels['setting_show_clouds'] = 'Mostra nuvole';
$labels['setting_show_wind'] = 'Mostra vento';
$labels['setting_show_sunrise'] = 'Mostra alba';
$labels['setting_show_sunset'] = 'Mostra tramonto';
$labels['metric'] = 'Metrico';
$labels['imperial'] = 'Imperiale';
$labels['icon_preview'] = 'Anteprima icona';
$labels['icons_cutout'] = 'Ritaglio';
$labels['icons_glossy'] = 'Lucido';
$labels['icons_monochrome'] = 'Monocromatico';
$labels['icons_moonlight'] = 'Chiaro di luna';
$labels['icons_stickers'] = 'Adesivi';
$labels['check_location'] = 'Controlla posizione';
$labels['location_found'] = 'Posizione trovata:';
$labels['location_not_found'] = 'Posizione non trovata.';
$labels['loading_error'] = 'Si è verificato un errore durante il caricamento dei dati meteo. Si prega di controllare le impostazioni del paese e della città nelle opzioni.';
$labels['country_and_city'] = 'Paese e città';
$labels['coordinates'] = 'Coordinate';
$labels['coordinates_link'] = 'Trova la tua latitudine e longitudine.';
