<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Laikapstākļi';
$labels['weather'] = 'Laikapstākļi';
$labels['setting_show_xweather'] = 'Rādīt laikapstākļus';
$labels['description'] = 'Apraksts';
$labels['humidity'] = 'Mitrums';
$labels['pressure'] = 'Spiediens';
$labels['clouds'] = 'Mākoņi';
$labels['wind'] = 'Vējš';
$labels['sunrise'] = 'Saullēkts';
$labels['sunset'] = 'Saulriets';
$labels['more_data'] = 'Vairāk datu';
$labels['display'] = 'Displejs';
$labels['options'] = 'Iespējas';
$labels['setting_location_type'] = 'Atrast atrašanās vietu pēc';
$labels['setting_country_code'] = 'Valsts';
$labels['setting_city'] = 'Pilsēta';
$labels['setting_latitude'] = 'Platums';
$labels['setting_longitude'] = 'Ģeogrāfiskais garums';
$labels['setting_units'] = 'Vienības';
$labels['setting_icons'] = 'Ikonas';
$labels['setting_show_description'] = 'Rādīt aprakstu';
$labels['setting_show_pressure'] = 'Parādīt spiedienu';
$labels['setting_show_humidity'] = 'Rādīt mitrumu';
$labels['setting_show_clouds'] = 'Rādīt mākoņus';
$labels['setting_show_wind'] = 'Rādīt vēju';
$labels['setting_show_sunrise'] = 'Rādīt saullēktu';
$labels['setting_show_sunset'] = 'Rādīt saulrietu';
$labels['metric'] = 'Metriskais';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Ikonas priekšskatījums';
$labels['icons_cutout'] = 'Izgriezums';
$labels['icons_glossy'] = 'Glancēts';
$labels['icons_monochrome'] = 'Vienkrāsains';
$labels['icons_moonlight'] = 'Mēness gaisma';
$labels['icons_stickers'] = 'Uzlīmes';
$labels['check_location'] = 'Pārbaudiet atrašanās vietu';
$labels['location_found'] = 'Atrastā atrašanās vieta:';
$labels['location_not_found'] = 'Atrašanās vieta nav atrasta.';
$labels['loading_error'] = 'Laikapstākļu datu ielādēšanas laikā tika pieļauta kļūda. Lūdzu, pārbaudiet valsts un pilsētas iestatījumus opcijās.';
$labels['country_and_city'] = 'Valsts un pilsēta';
$labels['coordinates'] = 'Koordinātas';
$labels['coordinates_link'] = 'Atrodiet savu ģeogrāfisko platumu un garumu.';
