<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Počasie';
$labels['weather'] = 'Počasie';
$labels['setting_show_xweather'] = 'Zobraziť počasie';
$labels['description'] = 'Popis';
$labels['humidity'] = 'Vlhkosť';
$labels['pressure'] = 'Tlak';
$labels['clouds'] = 'Oblaky';
$labels['wind'] = 'Vietor';
$labels['sunrise'] = 'Východ slnka';
$labels['sunset'] = 'Západ slnka';
$labels['more_data'] = 'Viac údajov';
$labels['display'] = 'Zobrazenie';
$labels['options'] = 'Možnosti';
$labels['setting_location_type'] = 'Vyhľadajte polohu podľa';
$labels['setting_country_code'] = 'Krajina';
$labels['setting_city'] = 'Mesto';
$labels['setting_latitude'] = 'Zemepisná šírka';
$labels['setting_longitude'] = 'Zemepisná dĺžka';
$labels['setting_units'] = 'Jednotky';
$labels['setting_icons'] = 'Ikony';
$labels['setting_show_description'] = 'Zobraziť popis';
$labels['setting_show_pressure'] = 'Zobraziť tlak';
$labels['setting_show_humidity'] = 'Zobraziť vlhkosť';
$labels['setting_show_clouds'] = 'Zobraziť mraky';
$labels['setting_show_wind'] = 'Zobraziť vietor';
$labels['setting_show_sunrise'] = 'Zobraziť východ slnka';
$labels['setting_show_sunset'] = 'Ukázať západ slnka';
$labels['metric'] = 'Metrické';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Náhľad ikony';
$labels['icons_cutout'] = 'Výrez';
$labels['icons_glossy'] = 'Lesklý';
$labels['icons_monochrome'] = 'Monochromatické';
$labels['icons_moonlight'] = 'Mesačný svit';
$labels['icons_stickers'] = 'Nálepky';
$labels['check_location'] = 'Skontrolujte umiestnenie';
$labels['location_found'] = 'Zistené miesto:';
$labels['location_not_found'] = 'Miesto nebolo nájdené.';
$labels['loading_error'] = 'Pri načítavaní údajov o počasí došlo k chybe. Skontrolujte nastavenia krajiny a mesta v možnostiach.';
$labels['country_and_city'] = 'Krajina a mesto';
$labels['coordinates'] = 'Súradnice';
$labels['coordinates_link'] = 'Zistite svoju zemepisnú šírku a dĺžku.';
