<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Vreme';
$labels['weather'] = 'Vreme';
$labels['setting_show_xweather'] = 'Prikaži vreme';
$labels['description'] = 'Opis';
$labels['humidity'] = 'Vlaga';
$labels['pressure'] = 'Tlak';
$labels['clouds'] = 'Oblaki';
$labels['wind'] = 'Veter';
$labels['sunrise'] = 'Sončni vzhod';
$labels['sunset'] = 'Sončni zahod';
$labels['more_data'] = 'Več podatkov';
$labels['display'] = 'Prikaz';
$labels['options'] = 'Možnosti';
$labels['setting_location_type'] = 'Poiščite lokacijo z';
$labels['setting_country_code'] = 'Država';
$labels['setting_city'] = 'Mesto';
$labels['setting_latitude'] = 'Zemljepisna širina';
$labels['setting_longitude'] = 'Zemljepisna dolžina';
$labels['setting_units'] = 'Enote';
$labels['setting_icons'] = 'Ikone';
$labels['setting_show_description'] = 'Prikaži opis';
$labels['setting_show_pressure'] = 'Prikaži pritisk';
$labels['setting_show_humidity'] = 'Pokaži vlažnost';
$labels['setting_show_clouds'] = 'Prikaži oblake';
$labels['setting_show_wind'] = 'Pokaži veter';
$labels['setting_show_sunrise'] = 'Prikaži sončni vzhod';
$labels['setting_show_sunset'] = 'Prikaži sončni zahod';
$labels['metric'] = 'Metrični';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Predogled ikone';
$labels['icons_cutout'] = 'Izrez';
$labels['icons_glossy'] = 'Glossy';
$labels['icons_monochrome'] = 'Enobarvni';
$labels['icons_moonlight'] = 'Moonlight';
$labels['icons_stickers'] = 'Nalepke';
$labels['check_location'] = 'Preverite lokacijo';
$labels['location_found'] = 'Najdena lokacija:';
$labels['location_not_found'] = 'Lokacija ni bila najdena.';
$labels['loading_error'] = 'Pri nalaganju vremenskih podatkov je prišlo do napake. Preverite nastavitve države in mesta v možnostih.';
$labels['country_and_city'] = 'Država in mesto';
$labels['coordinates'] = 'Koordinate';
$labels['coordinates_link'] = 'Poiščite svojo zemljepisno širino in dolžino.';
