<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Väder';
$labels['weather'] = 'Väder';
$labels['setting_show_xweather'] = 'Visa väder';
$labels['description'] = 'Beskrivning';
$labels['humidity'] = 'Luftfuktighet';
$labels['pressure'] = 'Tryck';
$labels['clouds'] = 'Moln';
$labels['wind'] = 'Vind';
$labels['sunrise'] = 'Soluppgång';
$labels['sunset'] = 'Solnedgång';
$labels['more_data'] = 'Mer data';
$labels['display'] = 'Display';
$labels['options'] = 'Alternativ';
$labels['setting_location_type'] = 'Hitta plats genom att';
$labels['setting_country_code'] = 'Land';
$labels['setting_city'] = 'Stad';
$labels['setting_latitude'] = 'Latitud';
$labels['setting_longitude'] = 'Longitud';
$labels['setting_units'] = 'Enheter';
$labels['setting_icons'] = 'Ikoner';
$labels['setting_show_description'] = 'Visa beskrivning';
$labels['setting_show_pressure'] = 'Visa tryck';
$labels['setting_show_humidity'] = 'Visa luftfuktighet';
$labels['setting_show_clouds'] = 'Visa moln';
$labels['setting_show_wind'] = 'Visa vind';
$labels['setting_show_sunrise'] = 'Visa soluppgång';
$labels['setting_show_sunset'] = 'Visa solnedgång';
$labels['metric'] = 'Metrisk';
$labels['imperial'] = 'Imperial';
$labels['icon_preview'] = 'Förhandsgranskning av ikoner';
$labels['icons_cutout'] = 'Utskärning';
$labels['icons_glossy'] = 'Glansig';
$labels['icons_monochrome'] = 'Monokrom';
$labels['icons_moonlight'] = 'Månsken';
$labels['icons_stickers'] = 'Klistermärken';
$labels['check_location'] = 'Kontrollera plats';
$labels['location_found'] = 'Plats funnen:';
$labels['location_not_found'] = 'Platsen hittades inte.';
$labels['loading_error'] = 'Det uppstod ett fel vid inläsningen av väderdata. Kontrollera inställningarna för land och stad i alternativen.';
$labels['country_and_city'] = 'Land och stad';
$labels['coordinates'] = 'Koordinater';
$labels['coordinates_link'] = 'Hitta din latitud och longitud.';
