<?php
/**
 * Roundcube Plus Weather plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Hava Durumu';
$labels['weather'] = 'Hava Durumu';
$labels['setting_show_xweather'] = 'Hava Durumunu Göster';
$labels['description'] = 'Açıklama';
$labels['humidity'] = 'Nem';
$labels['pressure'] = 'Basınç';
$labels['clouds'] = 'Bulutlar';
$labels['wind'] = 'Rüzgar';
$labels['sunrise'] = 'Gündoğumu';
$labels['sunset'] = 'Gün batımı';
$labels['more_data'] = 'Daha fazla veri';
$labels['display'] = 'Ekran';
$labels['options'] = 'Seçenekler';
$labels['setting_location_type'] = 'Konumu şu şekilde bulun';
$labels['setting_country_code'] = 'Ülke';
$labels['setting_city'] = 'Şehir';
$labels['setting_latitude'] = 'Enlem';
$labels['setting_longitude'] = 'Boylam';
$labels['setting_units'] = 'Birimler';
$labels['setting_icons'] = 'Simgeler';
$labels['setting_show_description'] = 'Açıklamayı göster';
$labels['setting_show_pressure'] = 'Basıncı göster';
$labels['setting_show_humidity'] = 'Nem oranını göster';
$labels['setting_show_clouds'] = 'Bulutları göster';
$labels['setting_show_wind'] = 'Rüzgarı göster';
$labels['setting_show_sunrise'] = 'Gün doğumunu göster';
$labels['setting_show_sunset'] = 'Gün batımını göster';
$labels['metric'] = 'Metrik';
$labels['imperial'] = 'İmparatorluk';
$labels['icon_preview'] = 'Simge önizlemesi';
$labels['icons_cutout'] = 'Kesme';
$labels['icons_glossy'] = 'Parlak';
$labels['icons_monochrome'] = 'Monokrom';
$labels['icons_moonlight'] = 'Ay Işığı';
$labels['icons_stickers'] = 'Çıkartmalar';
$labels['check_location'] = 'Konumu kontrol edin';
$labels['location_found'] = 'Bulunduğu yer:';
$labels['location_not_found'] = 'Konum bulunamadı.';
$labels['loading_error'] = 'Hava durumu verileri yüklenirken bir hata oluştu. Lütfen seçeneklerdeki ülke ve şehir ayarlarını kontrol edin.';
$labels['country_and_city'] = 'Ülke ve şehir';
$labels['coordinates'] = 'Koordinatlar';
$labels['coordinates_link'] = 'Enlem ve boylamınızı bulun.';
