<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Ταπετσαρία';
$labels['setting_compact'] = 'Εμφάνιση συμπαγούς λίστας μηνυμάτων';
$labels['with_vertical_preview'] = 'με κάθετη προεπισκόπηση';
$labels['setting_compose_plain_font_size'] = 'Προεπιλεγμένο μέγεθος γραμματοσειράς του μηνύματος απλού κειμένου';
$labels['background'] = 'Ιστορικό';
$labels['setting_image'] = 'Εικόνα φόντου';
$labels['setting_image_opacity'] = 'Αδιαφάνεια εικόνας';
$labels['setting_content_opacity'] = 'Αδιαφάνεια πλαισίου περιεχομένου';
$labels['more_background_options'] = 'Περισσότερες επιλογές φόντου...';
$labels['upload_image'] = 'Ανέβασμα εικόνας';
$labels['upload_background_image'] = 'Ανέβασμα εικόνας φόντου';
$labels['setting_placement'] = 'Τοποθέτηση εικόνας';
$labels['tile'] = 'Πλακάκια';
$labels['cover'] = 'Εξώφυλλο';
$labels['setting_text_color'] = 'Χρώμα κειμένου';
$labels['auto'] = 'Αυτόματο';
$labels['light'] = 'Φωτεινό';
$labels['dark'] = 'Σκούρο';
$labels['none'] = 'Κανένα';
$labels['setting_blur'] = 'Θόλωση εικόνας';
$labels['setting_gray'] = 'Μετατροπή σε γκρι';
$labels['placement_help'] = 'Καθορίζει εάν η εικόνα θα πρέπει να είναι σε μορφή πλακιδίων (επαναλαμβανόμενη) ή να καλύπτει ολόκληρο το φόντο.';
$labels['text_color_help'] = 'Καθορίζει εάν το χρώμα του κειμένου που εμφανίζεται απευθείας στην εικόνα φόντου θα είναι σκούρο ή ανοιχτό.';
