<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Tapeet';
$labels['setting_compact'] = 'Näita kompaktset sõnumite nimekirja';
$labels['with_vertical_preview'] = 'vertikaalse eelvaates';
$labels['setting_compose_plain_font_size'] = 'Tavalise tekstisõnumi vaikimisi kirjasuurus';
$labels['background'] = 'Taustaks';
$labels['setting_image'] = 'Taustapilt';
$labels['setting_image_opacity'] = 'Pildi läbipaistmatus';
$labels['setting_content_opacity'] = 'Sisu kasti läbipaistmatus';
$labels['more_background_options'] = 'Rohkem taustavõimalusi...';
$labels['upload_image'] = 'Pildi üleslaadimine';
$labels['upload_background_image'] = 'Taustapildi üleslaadimine';
$labels['setting_placement'] = 'Pildi paigutamine';
$labels['tile'] = 'Plaat';
$labels['cover'] = 'Kaane';
$labels['setting_text_color'] = 'Teksti värvus';
$labels['auto'] = 'Automaatne';
$labels['light'] = 'Bright';
$labels['dark'] = 'Tume';
$labels['none'] = 'Puudub';
$labels['setting_blur'] = 'Pildi hägusus';
$labels['setting_gray'] = 'Teisenda halliks';
$labels['placement_help'] = 'Määrab, kas pilt peaks olema plaaditud (korduv) või katma kogu tausta.';
$labels['text_color_help'] = 'Määrab, kas otse taustapildil kuvatava teksti värv peab olema tume või hele.';
