<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Carta da parati';
$labels['setting_compact'] = 'Visualizza elenco messaggi compatto';
$labels['with_vertical_preview'] = 'con anteprima verticale';
$labels['setting_compose_plain_font_size'] = 'Dimensione carattere predefinita del messaggio di testo';
$labels['background'] = 'Sfondo';
$labels['setting_image'] = 'Immagine di sfondo';
$labels['setting_image_opacity'] = 'Opacità immagine';
$labels['setting_content_opacity'] = 'Opacità riquadro contenuto';
$labels['more_background_options'] = 'Più opzioni di sfondo...';
$labels['upload_image'] = 'Carica immagine';
$labels['upload_background_image'] = 'Carica immagine di sfondo';
$labels['setting_placement'] = 'Posizionamento immagine';
$labels['tile'] = 'Affianca';
$labels['cover'] = 'Intero sfondo';
$labels['setting_text_color'] = 'Colore testo';
$labels['auto'] = 'Automatico';
$labels['light'] = 'Chiaro';
$labels['dark'] = 'Scuro';
$labels['none'] = 'Nessuno';
$labels['setting_blur'] = 'Sfocatura immagine';
$labels['setting_gray'] = 'Converti in grigio';
$labels['placement_help'] = 'Specifica se l\'immagine deve essere affiancata (ripetuta) o coprire l\'intero sfondo.';
$labels['text_color_help'] = 'Specifica se il colore del testo mostrato direttamente sull\'immagine di sfondo deve essere scuro o chiaro.';
