<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '배경 화면';
$labels['setting_compact'] = '간결한 메시지 목록 표시';
$labels['with_vertical_preview'] = '세로 미리보기 포함';
$labels['setting_compose_plain_font_size'] = '일반 텍스트 메시지의 기본 글꼴 크기';
$labels['background'] = '배경';
$labels['setting_image'] = '배경 이미지';
$labels['setting_image_opacity'] = '이미지 불투명도';
$labels['setting_content_opacity'] = '콘텐츠 상자 불투명도';
$labels['more_background_options'] = '더 많은 배경 옵션...';
$labels['upload_image'] = '이미지 업로드';
$labels['upload_background_image'] = '배경 이미지 업로드';
$labels['setting_placement'] = '이미지 배치';
$labels['tile'] = '타일';
$labels['cover'] = '커버';
$labels['setting_text_color'] = '텍스트 색상';
$labels['auto'] = '자동';
$labels['light'] = '밝음';
$labels['dark'] = 'Dark';
$labels['none'] = '없음';
$labels['setting_blur'] = '이미지 흐림';
$labels['setting_gray'] = '회색으로 변환';
$labels['placement_help'] = '이미지를 타일링(반복)할지 아니면 전체 배경을 덮을지 여부를 지정합니다.';
$labels['text_color_help'] = '배경 이미지에 직접 표시되는 텍스트의 색상을 어둡게 할지, 밝게 할지 지정합니다.';
