<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Tapetai';
$labels['setting_compact'] = 'Rodyti kompaktišką pranešimų sąrašą';
$labels['with_vertical_preview'] = 'su vertikalia peržiūra';
$labels['setting_compose_plain_font_size'] = 'Numatytasis paprasto teksto pranešimo šrifto dydis';
$labels['background'] = 'Pagrindinė informacija';
$labels['setting_image'] = 'Fono paveikslėlis';
$labels['setting_image_opacity'] = 'Vaizdo nepermatomumas';
$labels['setting_content_opacity'] = 'Turinio lauko neskaidrumas';
$labels['more_background_options'] = 'Daugiau fono parinkčių...';
$labels['upload_image'] = 'Įkelti paveikslėlį';
$labels['upload_background_image'] = 'Įkelti fono paveikslėlį';
$labels['setting_placement'] = 'Vaizdų talpinimas';
$labels['tile'] = 'Plytelės';
$labels['cover'] = 'Viršelis';
$labels['setting_text_color'] = 'Teksto spalva';
$labels['auto'] = 'Automatinis';
$labels['light'] = 'Ryškus';
$labels['dark'] = 'Tamsus';
$labels['none'] = 'Nėra';
$labels['setting_blur'] = 'Vaizdo suliejimas';
$labels['setting_gray'] = 'Konvertuoti į Pilka';
$labels['placement_help'] = 'Nurodoma, ar vaizdas turi būti išdėstytas plytelėmis (pasikartoti), ar užimti visą foną.';
$labels['text_color_help'] = 'Nurodo, ar teksto, rodomo tiesiai fono paveikslėlyje, spalva turi būti tamsi, ar šviesi.';
