<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Tapetes';
$labels['setting_compact'] = 'Kompaktā ziņojumu saraksta rādīšana';
$labels['with_vertical_preview'] = 'ar vertikālu priekšskatījumu';
$labels['setting_compose_plain_font_size'] = 'Parastā teksta ziņojuma noklusējuma fonta lielums';
$labels['background'] = 'Pamatinformācija';
$labels['setting_image'] = 'Fona attēls';
$labels['setting_image_opacity'] = 'Attēla necaurspīdīgums';
$labels['setting_content_opacity'] = 'Satura lauka necaurspīdīgums';
$labels['more_background_options'] = 'Vairāk fona iespēju...';
$labels['upload_image'] = 'Augšupielādēt attēlu';
$labels['upload_background_image'] = 'Fona attēla augšupielāde';
$labels['setting_placement'] = 'Attēlu izvietošana';
$labels['tile'] = 'Plāksnes';
$labels['cover'] = 'Vāks';
$labels['setting_text_color'] = 'Teksta krāsa';
$labels['auto'] = 'Automātiskais';
$labels['light'] = 'Bright';
$labels['dark'] = 'Tumšs';
$labels['none'] = 'Nav';
$labels['setting_blur'] = 'Attēlu izplūdums';
$labels['setting_gray'] = 'Konvertēt uz pelēks';
$labels['placement_help'] = 'Norāda, vai attēlam jābūt flīzētam (atkārtotam) vai jāpārklāj viss fons.';
$labels['text_color_help'] = 'Norāda, vai uz fona attēla tieši attēlotā teksta krāsai jābūt tumšai vai gaišai.';
