<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Papel de parede';
$labels['setting_compact'] = 'Apresentar uma lista compacta de mensagens';
$labels['with_vertical_preview'] = 'com pré-visualização vertical';
$labels['setting_compose_plain_font_size'] = 'Tamanho de letra predefinido da mensagem de texto simples';
$labels['background'] = 'Antecedentes';
$labels['setting_image'] = 'Imagem de fundo';
$labels['setting_image_opacity'] = 'Opacidade da imagem';
$labels['setting_content_opacity'] = 'Opacidade da caixa de conteúdo';
$labels['more_background_options'] = 'Mais opções de fundo...';
$labels['upload_image'] = 'Carregar imagem';
$labels['upload_background_image'] = 'Carregar imagem de fundo';
$labels['setting_placement'] = 'Colocação de imagens';
$labels['tile'] = 'Azulejo';
$labels['cover'] = 'Capa';
$labels['setting_text_color'] = 'Cor do texto';
$labels['auto'] = 'Automático';
$labels['light'] = 'Brilhante';
$labels['dark'] = 'Escuro';
$labels['none'] = 'Nenhum';
$labels['setting_blur'] = 'Desfoque de imagem';
$labels['setting_gray'] = 'Converter para cinzento';
$labels['placement_help'] = 'Especifica se a imagem deve ser colocada em mosaico (repetida) ou cobrir todo o fundo.';
$labels['text_color_help'] = 'Especifica se a cor do texto mostrado diretamente na imagem de fundo deve ser escura ou clara.';
