<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Wallpaper';
$labels['setting_compact'] = 'Afișarea listei de mesaje compacte';
$labels['with_vertical_preview'] = 'cu previzualizare verticală';
$labels['setting_compose_plain_font_size'] = 'Dimensiunea implicită a fontului din mesajul text simplu';
$labels['background'] = 'Fond';
$labels['setting_image'] = 'Imagine de fundal';
$labels['setting_image_opacity'] = 'Opacitatea imaginii';
$labels['setting_content_opacity'] = 'Opacitatea casetei de conținut';
$labels['more_background_options'] = 'Mai multe opțiuni de fundal...';
$labels['upload_image'] = 'Încărcați imaginea';
$labels['upload_background_image'] = 'Încărcați imaginea de fundal';
$labels['setting_placement'] = 'Plasarea imaginii';
$labels['tile'] = 'Țiglă';
$labels['cover'] = 'Coperta';
$labels['setting_text_color'] = 'Culoarea textului';
$labels['auto'] = 'Automat';
$labels['light'] = 'Strălucitoare';
$labels['dark'] = 'Întuneric';
$labels['none'] = 'Nici unul';
$labels['setting_blur'] = 'Ceață de imagine';
$labels['setting_gray'] = 'Conversia în gri';
$labels['placement_help'] = 'Precizează dacă imaginea trebuie să fie aranjată (repetată) sau să acopere întregul fundal.';
$labels['text_color_help'] = 'Specifică dacă culoarea textului afișat direct pe imaginea de fundal trebuie să fie închisă sau deschisă.';
