<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Обои';
$labels['setting_compact'] = 'Показать компактный список сообщений';
$labels['with_vertical_preview'] = 'с вертикальным просмотром';
$labels['setting_compose_plain_font_size'] = 'Размер шрифта по умолчанию для простого текстового сообщения';
$labels['background'] = 'Фон';
$labels['setting_image'] = 'Фоновое изображение';
$labels['setting_image_opacity'] = 'Прозрачность изображения';
$labels['setting_content_opacity'] = 'Прозрачность окна контента';
$labels['more_background_options'] = 'Больше вариантов фона...';
$labels['upload_image'] = 'Загрузить изображение';
$labels['upload_background_image'] = 'Загрузить фоновое изображение';
$labels['setting_placement'] = 'Размещение изображения';
$labels['tile'] = 'Плитка';
$labels['cover'] = 'Обложка';
$labels['setting_text_color'] = 'Цвет текста';
$labels['auto'] = 'Автоматически';
$labels['light'] = 'Светлый';
$labels['dark'] = 'Темный';
$labels['none'] = 'Нет';
$labels['setting_blur'] = 'Размытие изображения';
$labels['setting_gray'] = 'Преобразовать в серый';
$labels['placement_help'] = 'Укажите, изображение быть мозаичным (повторяющимся) или покрывать весь фон.';
$labels['text_color_help'] = 'Укажите, цвет текста, отображаемого на фоновом изображении должен быть темным или светлым.';
