Alle Errungenschaften, alle verdienten Reichtümer haben ihren Anfang in einer Idee. | Napoleon Hill
Verwechsle niemals Aktivität mit Leistung. | John Wooden
Erfolg resultiert aus Arbeit, die Ehrgeiz verwirklicht. | Adam Ant
Die kompliziertesten Leistungen des Denkens sind ohne die Hilfe des Bewusstseins möglich. | Sigmund Freud
Große Errungenschaften entstehen normalerweise aus großen Opfern und sind niemals das Ergebnis von Egoismus. | Napoleon Hill
Der Tod kommt zu allen, aber große Errungenschaften bauen ein Denkmal, das bestehen wird, bis die Sonne erkalten wird. | Ralph Waldo Emerson
Pflege deine Visionen und Träume, denn sie sind die Kinder deiner Seele; die Blaupausen deiner ultimativen Errungenschaften. | Napoleon Hill
Du musst die Regeln des Spiels lernen. Und dann musst du besser spielen als alle anderen. | Albert Einstein
Ich bin froh, dass ich es getan habe, teilweise weil es sich gelohnt hat, aber hauptsächlich, weil ich es nie wieder tun muss. | Mark Twain
Es ist nicht der Berg, den wir bezwingen, sondern wir selbst. | Edmund Hillary
Unsere Aufgabe muss es sein, uns aus diesem Gefängnis zu befreien, indem wir unsere Kreise des Mitgefühls erweitern, um alle lebenden Kreaturen und die ganze Natur in ihrer Schönheit zu umarmen. | Albert Einstein
Hohe Leistungen finden immer im Rahmen hoher Erwartungen statt. | Charles F. Kettering
Du kannst alles im Leben haben, was du willst, wenn du nur anderen Menschen hilfst, das zu bekommen, was sie wollen. | Zig Ziglar
Große Anstrengung entspringt natürlich aus einer großartigen Einstellung. | Pat Riley
Deine Einstellung, nicht deine Begabung, bestimmt deine Höhe. | Zig Ziglar
Du kannst die Einstellung annehmen, dass es nichts gibt, was du tun kannst, oder du kannst die Herausforderung als deinen Aufruf zum Handeln sehen. | Catherine Pulsifer
Ein Optimist ist eine Person, die überall grünes Licht sieht, während der Pessimist nur das rote Stoppschild sieht - der wirklich weise Mensch ist farbenblind. | Albert Schweitzer
Positives Denken lässt dich alles besser machen als negatives Denken. | Zig Ziglar
Du kannst nicht kontrollieren, was dir passiert, aber du kannst deine Einstellung dazu kontrollieren, was dir passiert, und darin wirst du die Veränderung meistern, anstatt es zuzulassen, dass sie dich meistert. | Brian Tracy
Du kannst es tun, wenn du glaubst, dass du es kannst! | Napoleon Hill
Wenn du keinen Basisstandard dafür setzt, was du im Leben akzeptieren wirst, wirst du feststellen, dass es leicht ist, in Verhaltensweisen und Einstellungen oder eine Lebensqualität abzugleiten, die weit unter dem liegt, was du verdienst. | Anthony Robbins
Wenn dir etwas nicht gefällt, ändere es. Wenn du es nicht ändern kannst, ändere deine Einstellung. Beschwere dich nicht. | Maya Angelou
Die Person, die positive Gedanken aussendet, aktiviert die Welt um sich herum positiv und zieht positive Ergebnisse zu sich zurück. | Norman Vincent Peale
Wenn dein Glück davon abhängt, was jemand anderes tut, hast du wohl ein Problem. | Richard Bach
Sich selbst und deinem gegenwärtigen Zustand leid zu tun, ist nicht nur Energieverschwendung, sondern die schlimmste Gewohnheit, die du haben könntest. | Dale Carnegie
Jeder kann so ziemlich alles mit sich selbst tun, was er wirklich will und sich vornimmt zu tun. Wir sind zu größeren Dingen fähig, als wir realisieren. | Norman Vincent Peale
Es gibt zwei Hauptentscheidungen im Leben: die Bedingungen so zu akzeptieren, wie sie sind, oder die Verantwortung dafür zu übernehmen, sie zu ändern. | Denis Waitley
Das Leben ist wie das Spielen einer Geige in der Öffentlichkeit und das Erlernen des Instruments, während man weitermacht. | Samuel Butler
Der erste Schritt, um die Dinge zu bekommen, die du im Leben willst, ist dieser: Entscheide, was du willst. | Ben Stein
Das Leben ist das, was passiert, während du beschäftigt bist, andere Pläne zu machen. | John Lennon
Wo du am Ende landest, ist nicht das Wichtigste. Es ist der Weg, den du dorthin nimmst. Der Weg, den du nimmst, ist das, worauf du zurückblicken und dein Leben nennen wirst. | Tim Wiley
Es gibt nur zwei Arten, dein Leben zu leben. Die eine ist, als ob nichts ein Wunder wäre. Die andere ist, als ob alles ein Wunder wäre. | Albert Einstein
Die Qualität eines Menschenlebens steht in direktem Verhältnis zu seinem Engagement für Exzellenz, unabhängig von seinem gewählten Betätigungsfeld. | Vince Lombardi
Das Leben ist nur ein Spiegel, und was du dort draußen siehst, musst du zuerst in dir selbst sehen. | Wally Amos
Packe alles in dein Leben; du kommst nur einmal vorbei! Setz dich hin und denke darüber nach, was dir Freude bereitet. Nimm Kurse, lies Bücher, finde deine Leidenschaft. | Catherine Pulsifer
Das große Geheimnis des Lebens ist, dass es kein großes Geheimnis gibt. Was auch immer dein Ziel ist, du kannst es erreichen, wenn du bereit bist zu arbeiten. | Oprah Winfrey
Das Leben muss gelebt und die Neugier am Leben gehalten werden. Man darf dem Leben niemals, aus welchem Grund auch immer, den Rücken kehren. | Eleanor Roosevelt
Zu wissen, dass auch nur ein Leben leichter geatmet hat, weil du gelebt hast. Das bedeutet, erfolgreich zu sein. | Ralph Waldo Emerson
Die Kämpfe des Lebens gehen nicht immer an den Stärkeren oder Schnelleren. Aber früher oder später gewinnt der Mensch, der glaubt, dass er es kann. | Vince Lombardi
Sei kein Zuschauer, lass das Leben nicht an dir vorbeiziehen. | Lou Holtz
Das Leben ist unerschlossenes Territorium. Es enthüllt seine Geschichte einen Moment nach dem anderen. | Leo Buscaglia
Integrität zu haben bedeutet auch, Charakter zu haben, was auch der einfachste Weg ist, in Konflikt mit denen zu geraten, die weder das eine noch das andere haben. | Byron Pulsifer
Habe den Mut, Nein zu sagen. Habe den Mut, der Wahrheit ins Auge zu sehen. Tue das Richtige, weil es richtig ist. Das sind die magischen Schlüssel, um dein Leben mit Integrität zu leben. | Mark Twain
Integrität kann schwierig zu bewahren sein in einer Welt, die verlangt, dass du dich mit dem Wind veränderst. | Byron Pulsifer
Integrität ist das, was wir tun, was wir sagen und was wir sagen, dass wir tun. | Don Galer
Liebe alle, vertraue wenigen, tue niemandem Unrecht. | William Shakespeare
Integrität zu haben bedeutet, dass du nicht mit jedem, den du triffst, übereinstimmst, noch dem Druck nachgibst, etwas zu sein, das in direktem Konflikt mit deinen Kernethiken steht. | Byron Pulsifer
Charakter ist höher als Intellekt. | Ralph Waldo Emerson
Mein Großvater sagte mir einmal, dass es zwei Arten von Menschen gibt: die, die arbeiten, und die, die den Kredit einstreichen. Er sagte mir, ich solle versuchen, zur ersten Gruppe zu gehören; dort gab es weniger Konkurrenz. | Indira Gandhi
Aber was ist Glück anderes als die einfache Harmonie zwischen einem Menschen und dem Leben, das er führt? | Albert Camus
Es gibt nur eine Ecke des Universums, die du mit Sicherheit verbessern kannst, und das ist dein eigenes Selbst. | Aldous Huxley
Wir dürfen nicht zulassen, dass wir wie das System werden, das wir bekämpfen. | Bischof Desmond Tutu
Integrität ohne Wissen ist schwach und nutzlos, und Wissen ohne Integrität ist gefährlich und schrecklich. | Samuel Johnson
Wir müssen betonen, dass persönliche Integrität ebenso wichtig ist wie exekutive Fähigkeiten in Geschäftstransaktionen. | Russell E. Palmer
Egal zu welcher Tageszeit, egal wer zuschaut und egal in welcher Situation, persönliche Integrität macht keine Ferien. | Byron Pulsifer
Weisheit ist zu wissen, was als Nächstes zu tun ist; Tugend ist, es zu tun. | David Star Jordan
Charakter ist, das Richtige zu tun, wenn niemand zusieht. Es gibt zu viele Menschen, die denken, dass das Einzige, was richtig ist, darin besteht, durchzukommen, und das Einzige, was falsch ist, erwischt zu werden. | J.C. Watts
Du kannst nicht immer das Richtige tun, aber du kannst immer das, was du tust, mit Integrität tun. | Byron Pulsifer
Lass niemals dein Moralempfinden dich davon abhalten, das Richtige zu tun. | Isaac Asimov
Integrität bedeutet, die Realität unseren Worten anzupassen - mit anderen Worten, Versprechen zu halten und Erwartungen zu erfüllen. | Stephen R. Covey
Erfolg ist nicht der Schlüssel zum Glück. Glück ist der Schlüssel zum Erfolg. Wenn du liebst, was du tust, wirst du erfolgreich sein. | Albert Schweitzer
Du wirst nie glücklich sein, wenn du weiterhin suchst, woraus Glück besteht. Du wirst nie leben, wenn du nach dem Sinn des Lebens suchst. | Albert Camus
Die Verfassung garantiert dem amerikanischen Volk nur das Recht, Glück zu verfolgen. Du musst es selbst fangen. | Benjamin Franklin
Keine Gesellschaft kann sicher blühen und glücklich sein, von der der weitaus größere Teil der Mitglieder arm und elend ist. | Adam Smith
Glück ist ein Geisteszustand, nicht das, was in deiner Brieftasche ist. | Byron Pulsifer
Wenn du glücklich sein willst, sei es. | Leo Tolstoi
Lass uns dankbar sein für die Menschen, die uns glücklich machen; sie sind die charmanten Gärtner, die unsere Seelen erblühen lassen. | Marcel Proust
Der Mensch, der alles, was zum Glück führt, von sich selbst abhängig macht und nicht von anderen Menschen, hat den besten Plan für ein glückliches Leben angenommen. | Plato
Glaube an dich selbst! Habe Vertrauen in deine Fähigkeiten! Ohne eine bescheidene, aber vernünftige Zuversicht in deine eigenen Kräfte kannst du weder erfolgreich noch glücklich sein. | Norman Vincent Peale
Ohne einige der Dinge zu sein, die du willst, ist ein unverzichtbarer Teil des Glücks. | Bertrand Russell
Aber was ist Glück anderes als die einfache Harmonie zwischen einem Menschen und dem Leben, das er führt? | Albert Camus
Handeln mag nicht immer Glück bringen; aber es gibt kein Glück ohne Handeln. | Benjamin Disraeli
Die meisten Menschen wären lieber sicher, dass sie unglücklich sind, als das Risiko einzugehen, glücklich zu sein. | Robert Anthony
Wenn wir nur aufhören würden, glücklich sein zu wollen, könnten wir eine ziemlich gute Zeit haben. | Edith Wharton
Was kann dem Glück eines Menschen hinzugefügt werden, der gesund ist, keine Schulden hat und ein reines Gewissen? | Adam Smith
Erfahrung ist nicht das, was einem Mann passiert. Es ist das, was ein Mann mit dem macht, was ihm passiert. | Aldous Leonard Huxley
Gutes Urteilsvermögen kommt aus Erfahrung, und oft kommt Erfahrung aus schlechtem Urteilsvermögen. | Rita Mae Brown
Ein Geist, der durch eine neue Erfahrung gestreckt wird, kann niemals zu seinen alten Dimensionen zurückkehren. | Oliver Wendell Holmes, Jr.
Manchmal musst du viele Dinge tun, um herauszufinden, was du nicht tun willst. Unterwegs sammelst du viele Erfahrungen. | Wally Amos
Ein Mann kann seine Erfahrung nicht in Rente schicken. Er muss sie nutzen. Erfahrung erreicht mehr mit weniger Energie und Zeit. | Bernard M. Baruch
Die Reaktion auf 'The Greatest Generation' und die folgenden Bücher war eine der befriedigendsten Erfahrungen meines Lebens. | Tom Brokaw
Ruhm wird vergehen und, so lange, ich habe dich, Ruhm. Wenn er vorbeigeht, wusste ich immer, dass er unbeständig war. Also ist es zumindest etwas, das ich erfahren habe, aber das ist nicht, wo ich lebe. | Marilyn Monroe
Erfahrung ist das Kind des Denkens, und Denken ist das Kind des Handelns. | Benjamin Disraeli
Ich habe lieber viel Talent und wenig Erfahrung als viel Erfahrung und wenig Talent. | John Wooden
Werde nie so sehr zum Experten, dass du aufhörst, Expertise zu gewinnen. Betrachte das Leben als eine kontinuierliche Lernerfahrung. | Denis Waitley
Das Schönste, was wir erleben können, ist das Geheimnisvolle. Es ist die Quelle aller wahren Kunst und Wissenschaft. | Albert Einstein
Erfahrung ist nicht das, was dir passiert. Es ist das, was du mit dem machst, was dir passiert. | Aldous Huxley
Mit jeder Erfahrung malst du alleine dein eigenes Bild, Gedanke für Gedanke, Wahl für Wahl. | Oprah Winfrey
Als Frau habe ich immer das Gefühl gehabt, dass wir mit zunehmendem Alter besser werden. Du kommst mit dir selbst ins Reine durch emotionale Erfahrungen und die einfache Weisheit, die mit dem Alter kommt. | Linda Evans
Wir sollten nicht zurückblicken, es sei denn, um nützliche Lektionen aus vergangenen Fehlern zu ziehen und um von teuer erkauften Erfahrungen zu profitieren. | George Washington
Das schmerzhafteste Erlebnis ist nicht die Niederlage, sondern das Bedauern. | Leo Buscaglia
Kein Mensch war jemals so vollständig in der Lebensführung geübt, dass er keine neuen Informationen aus Alter und Erfahrung erhalten hat. | Jonathan Swift
Kunst ist kein Handwerk, sie ist die Übertragung des Gefühls, das der Künstler erlebt hat. | Leo Tolstoi
Ich denke, jeder sollte mindestens einmal in seiner Karriere eine Niederlage erleben. Man lernt viel davon. | Lou Holtz
Das Geheimnis eines reichen Lebens ist, mehr Anfänge als Enden zu haben. | Dave Weinbaum
Alle schwierigen Dinge haben ihren Ursprung in dem, was leicht ist, und große Dinge in dem, was klein ist. | Lao-Tzu
Fast alles kommt aus dem Nichts. | Henry F. Amiel
Die Notwendigkeit ist die Mutter der Erfindung. | Plato
Die Entfernung ist nichts; es ist nur der erste Schritt, der schwierig ist. | Marquise du Deffand
Anfänge sind nur ohne Handeln schwierig. | Byron Pulsifer
Kleine Gelegenheiten sind oft der Beginn großer Unternehmungen. | Demosthenes
Ein harter Anfang macht ein gutes Ende. | John Heywood
Du musst nicht großartig sein, um anzufangen, aber du musst anfangen, um großartig zu sein. | Joe Sabah
Viele Menschen, die nach Neuanfängen suchen, haben nie mit der Vergangenheit abgeschlossen. | Byron Pulsifer
Jeder Tag ist ein neuer Anfang. Behandle ihn so. Bleib weg von dem, was hätte sein können, und schaue auf das, was sein kann. | Marsha Petrie Sue
Dies ist nicht das Ende. Es ist nicht einmal der Anfang vom Ende. Aber es ist vielleicht das Ende des Anfangs. | Winston Churchill
Was auch immer du tust oder träumst, dass du es kannst, beginne es. Kühnheit hat Genie, Macht und Magie in sich. | Goethe
Mehrere kleine Gelegenheiten zu ergreifen, kann uns schneller dorthin bringen, als auf eine große zu warten. | Hugh Allen
Es ist oft schwer zu unterscheiden zwischen den harten Schlägen des Lebens und denen der Gelegenheit. | Frederick Phillips
Fähigkeit ist ohne Gelegenheit wenig wert. | Napoleon
Das Geheimnis des Erfolgs im Leben besteht darin, dass ein Mann bereit ist für seine Gelegenheit, wenn sie kommt. | Benjamin Disraeli
Gelegenheiten gehen nie verloren; jemand wird diejenige nehmen, die du verpasst. |
Jeder Tag ist eine Gelegenheit, ein neues glückliches Ende zu machen. |
Alles, was in der menschlichen Gesellschaft wertvoll ist, hängt von der Gelegenheit zur Entwicklung ab, die dem Einzelnen gewährt wird. | Albert Einstein
Ein Pessimist sieht die Schwierigkeit in jeder Gelegenheit; ein Optimist sieht die Gelegenheit in jeder Schwierigkeit. | Winston Churchill
Das Leben ist ein Geschenk, und es bietet uns das Privileg, die Gelegenheit und die Verantwortung, etwas zurückzugeben, indem wir mehr werden. | Tony Robbins
Die Erfolgsleiter wird am besten erklommen, indem man auf den Sprossen der Gelegenheit tritt. | Ayn Rand
Fähigkeit ist nichts ohne Gelegenheit. | Napoleon Bonaparte
Deine große Chance könnte genau dort sein, wo du jetzt bist. | Napoleon Hill
Gelegenheiten kommen in mein Leben und ich reagiere auf diejenigen, die mich ansprechen. | Wally Amos
Männer jammern nie über die verlorenen Gelegenheiten, Gutes zu tun, nur über die Gelegenheiten, schlecht zu sein. | Griechisches Sprichwort
Edison scheiterte 10.000 Mal, bevor er das elektrische Licht erfand. Lass dich nicht entmutigen, wenn du ein paar Mal scheiterst. | Napoleon Hill
Wie lange solltest du es versuchen? Bis. | Jim Rohn
Geduld und Ausdauer haben eine magische Wirkung, vor der Schwierigkeiten verschwinden und Hindernisse verschwinden. | John Quincy Adams
Durch Ausdauer gewinnen viele Menschen Erfolg aus dem, was als sicherer Misserfolg bestimmt schien. | Benjamin Disraeli
Versuche und scheitere, aber versage nicht beim Versuch. | Stephen Kaggwa
Wenn du im Leben Erfolg haben willst, mach Ausdauer zu deinem Busenfreund, Erfahrung zu deinem weisen Berater, Vorsicht zu deinem älteren Bruder und Hoffnung zu deinem Schutzengel. | Joseph Addison
Große Werke werden nicht durch Stärke, sondern durch Ausdauer vollbracht. | Samuel Johnson
Ich glaube nicht, dass es irgendeine andere Eigenschaft gibt, die so wesentlich für den Erfolg jeglicher Art ist wie die Qualität der Ausdauer. Sie überwindet fast alles, sogar die Natur. | John D. Rockefeller
Es gibt kein Versagen außer im Nicht-mehr-Versuchen. | Elbert Hubbard
Beharrlichkeit und Entschlossenheit allein sind allmächtig. Der Slogan "Mach weiter" hat die Probleme der Menschheit gelöst und wird sie immer lösen. | Calvin Coolidge
Der Sieg gehört den Beharrlichsten. | Napoleon Bonaparte
Folge deinen Träumen von einer besseren Welt und gib nicht auf, auch wenn es wenig Hoffnung zu geben scheint, denn es ist das Richtige zu tun. | Robert Alan
Genie ist göttliche Ausdauer. Genie kann ich nicht beanspruchen, noch nicht einmal übermäßige Helligkeit, aber Ausdauer kann jeder haben. | Woodrow Wilson
Im Konflikt zwischen dem Strom und dem Felsen gewinnt immer der Strom - nicht durch Stärke, sondern durch Ausdauer. | H. Jackson Brown
Beharrlichkeit ist überwältigender als Gewalt, und viele Dinge, die nicht überwunden werden können, wenn sie zusammen sind, geben sich hin, wenn sie nach und nach genommen werden. | Plutarch Beharrlichkeit
ist kein langer Lauf; es sind viele kurze Läufe nacheinander. | Walter Elliot
Die Besten unter uns sind nicht begabter als der Rest. Sie machen nur jeden Tag kleine Schritte auf dem Weg zu ihrem größten Leben. | Robin Sharma, The Greatness Guide
Umgebe dich mit Männern von guter Qualität, wenn du deinen eigenen Ruf schätzt. Es ist besser, allein zu sein, als in schlechter Gesellschaft. | George Washington
Qualität ist keine Handlung, sondern eine Gewohnheit. | Aristoteles
Wenn dein Lebensstandard dein Hauptziel ist, verbessert sich die Lebensqualität fast nie, aber wenn die Lebensqualität dein Ziel Nummer eins ist, verbessert sich dein Lebensstandard fast immer. | Zig Ziglar
Qualität ist ein Attribut, das von denen, die irreführen wollen, ziemlich häufig missbraucht wird. | Byron Pulsifer
Qualität bedeutet, es richtig zu machen, wenn niemand zusieht. | Henry Ford
Wenn du dir über die Qualität deiner Arbeit unsicher bist, musst du zuerst verstehen, was Qualität ist. | Byron Pulsifer
Qualität ist niemals ein Zufall; sie ist immer das Ergebnis intelligenter Anstrengung. | John Ruskin
Es ist die Qualität unserer Arbeit, die Gott gefallen wird, nicht die Menge. | Mahatma Gandhi
Die Qualität des Lebens eines Menschen steht in direktem Verhältnis zu seinem Engagement für Exzellenz, unabhängig von seinem gewählten Tätigkeitsfeld. | Vince Lombardi
Die Qualität, nicht die Langlebigkeit, eines Lebens ist das, was zählt. | Martin Luther King
Niemand kann irgendeinen echten und dauerhaften Erfolg im Geschäft erzielen oder "reich werden", indem er ein Konformist ist. | J. P. Getty
Um steile Hügel zu erklimmen, ist zu Beginn ein langsames Tempo erforderlich. | William Shakespeare
Es gibt kein Geheimnis über den Erfolg. Kennst du einen erfolgreichen Mann, der dir nicht davon erzählt hat? | Kin Hubbard
Das Geheimnis des Erfolgs eines Menschen liegt in seiner Einsicht in die Stimmungen der Menschen und seiner Taktik im Umgang mit ihnen. | Josiah Gilbert Holland
Es gibt keine Leidenschaft darin, klein zu spielen - sich mit einem Leben zufrieden zu geben, das weniger ist als das, zu dem du fähig bist. | Nelson Mandela
Ziele haben einen enormen Unterschied in meinem Leben gemacht. Sie haben es mir ermöglicht, Erfolg zu erzielen und das zu erreichen, wovon ich zuvor nur geträumt oder gewünscht hatte. | Catherine Pulsifer
Verwechsle niemals Bewegung mit Handlung. | Ernest Hemmingway
Erfolg ist, das zu bekommen, was du willst. Glück ist, das zu wollen, was du bekommst. | Dale Carnegie
In allem, was wir tun, können unsere eigenen Gedanken uns helfen, erfolgreich zu sein, oder sie können uns helfen, zu scheitern. Behalte eine positive Einstellung. | Catherine Pulsifer
Die meisten erfolgreichen Menschen, die ich kenne, sind diejenigen, die mehr zuhören als reden. | Bernard M. Baruch
Den aktuellen Job erfolgreich zu machen, ist der beste Schritt in Richtung des Jobs, den du willst. | Bernard M. Baruch
Du kannst einen Mann nicht an seinen Misserfolgen messen. Du musst wissen, welchen Nutzen er daraus zieht. Was bedeuteten sie für ihn? Was hat er daraus gewonnen? | Orison Swett Marden
Wenn man selbstbewusst in die Richtung seines Traums geht und bestrebt ist, das Leben zu leben, das er sich vorgestellt hat, wird er in gewöhnlichen Stunden einen unerwarteten Erfolg haben. | Henry David Thoreau
Zeit ist das wertvollste, was ein Mensch ausgeben kann. | Theophrastus
Man hat dich sicher davor gewarnt, die goldenen Stunden verstreichen zu lassen; aber einige von ihnen sind nur deshalb golden, weil wir sie verstreichen lassen. | James Matthew Barrie
Wenn du gut gemachte Arbeit willst, wähle einen beschäftigten Mann aus, der andere hat keine Zeit. | Elbert Hubbard
Zeit ist der weiseste Ratgeber von allen. | Pericles
Alles, was wirklich zu uns gehört, ist die Zeit; selbst wer nichts anderes hat, hat das. | Baltasar Gracian
Zeit ist die längste Entfernung zwischen zwei Orten. | Tennessee Williams
Nichts ist eine Zeitverschwendung, wenn du die Erfahrung weise nutzt. | Rodin
Wir müssen die Zeit als Werkzeug nutzen, nicht als Krücke. | John F. Kennedy
Zeit und Worte können nicht zurückgerufen werden, selbst wenn es nur gestern war. | Jiddisches Sprichwort
Das Bedauern über die Dinge, die wir getan haben, kann durch die Zeit gemildert werden; das Bedauern über die Dinge, die wir nicht getan haben, ist untröstlich. | Sydney J. Harris
Aber was für Minuten! Zähle sie nach Empfindung und nicht nach Kalendern, und jeder Moment ist ein Tag. | Benjamin Disraeli
Zeit ist die Münze deines Lebens. Es ist die einzige Münze, die du hast, und nur du kannst bestimmen, wie sie ausgegeben wird. Sei vorsichtig, dass du nicht zulässt, dass andere Leute sie für dich ausgeben. | Carl Sandburg
Du wirst niemals Zeit für irgendetwas finden. Wenn du Zeit willst, musst du sie schaffen. | Charles Buxton
Besser drei Stunden zu früh als eine Minute zu spät. | William Shakespeare
Verlorene Zeit wird nie wieder gefunden. | Benjamin Franklin
Die Stunden des Unfugs werden von der Uhr gemessen; aber der Weisheit, keine Uhr kann messen. | William Blake
Du wirst nie müde, es sei denn, du hältst an und nimmst dir Zeit dafür. | Bob Hope
Zeit ist der weiseste Ratgeber. | Pericles
Ich habe Zeit verschwendet, und nun verschwendet die Zeit mich. | William Shakespeare
Dein größtes Kapital ist deine Erwerbsfähigkeit. Deine größte Ressource ist deine Zeit. | Brian Tracy
Wir müssen die Zeit weise nutzen und für immer erkennen, dass die Zeit immer reif ist, das Richtige zu tun. | Nelson Mandela
Das Leben wird nicht an der Anzahl der Atemzüge gemessen, die wir nehmen, sondern an den Momenten, die uns den Atem rauben. |
Der beste Weg, deine Träume wahr werden zu lassen, ist aufzuwachen. | Paul Valery
Eine der Lektionen, die ich auf die harte Tour gelernt habe, war, dass es sich nicht lohnt, entmutigt zu sein. | Lucille Ball
Das Wichtige ist: zu jedem Zeitpunkt in der Lage zu sein, das zu opfern, was wir sind; für das, was wir werden könnten. | Charles Dubois
Aller Rat der Welt wird dir nie helfen, bis du dir selbst hilfst. | Fred Van Amburgh
Reichlich zu lieben bedeutet, reichlich zu leben, und für immer zu lieben bedeutet, für immer zu leben. | Henry Drummond
Wie du über ein Problem denkst, ist wichtiger als das Problem selbst. Denke also immer positiv. | Norman Vincent Peale
Vergiss vergangene Fehler. Vergiss Misserfolge. Vergiss alles außer dem, was du jetzt tun wirst, und tue es. | William Durant
Man kann mehr über eine Person erfahren, indem man darauf achtet, was sie über andere sagt, als durch das, was andere über sie sagen. | Leo Aikman
Träume große Träume, ziehe dann deinen Overall an und gehe raus und lass die Träume wahr werden. | Fred Van Amburgh
Das Geheimnis des Lebens ist kein Problem, das gelöst werden muss; es ist eine Realität, die erlebt werden muss. | Aart van der Leenw
Es gibt nur eine Ecke des Universums, die du mit Sicherheit verbessern kannst, und das ist dein eigenes Selbst. | Aldous Huxley
Das gute Leben ist ein Prozess, kein Zustand des Seins. Es ist eine Richtung, kein Ziel. | Carl Rogers
Wir sind das, was wir wiederholt tun. Exzellenz ist dann keine Handlung, sondern eine Gewohnheit. | Aristoteles
Lies nicht, um zu widersprechen und zu widerlegen, nicht um zu glauben und als gegeben hinzunehmen, nicht um Gespräche und Diskurse zu finden, sondern um abzuwägen und zu überlegen. | Francis Bacon
Eine der besten Möglichkeiten, andere zu überzeugen, ist mit deinen Ohren, indem du ihnen zuhörst. | Dean Rusk
Wenn du nur einen oder zwei Freunde hast, mit denen du deine höchsten Bestrebungen teilen kannst, solltest du dich als reich gesegnet betrachten. | J. Donald Waters
Anstatt sich Veränderung zu wünschen, musst du zuerst bereit sein, dich zu verändern. | Catherine Pulsifer
Jeder denkt daran, die Welt zu verändern, aber niemand denkt daran, sich selbst zu verändern. | Leo Tolstoi
Veränderung ist so unausweichlich wie die Zeit, doch nichts stößt auf mehr Widerstand. | Benjamin Disraeli
Nur die Weisesten und Dümmsten der Menschen ändern sich nie. | Konfuzius
Hör niemals auf zu lernen, wie du niemals aufhörst, dich zu verändern und in deinem Leben zu wachsen - Lernen hilft dir, dich leichter an Veränderungen anzupassen. | Lernzitate
Was wir denken, bestimmt, was uns passiert, also wenn wir unser Leben verändern wollen, müssen wir unseren Geist dehnen. | Wayne Dyer
Du kannst dein Ziel nicht über Nacht ändern, aber du kannst über Nacht deine Richtung ändern. | Jim Rohn
Wir sind oft enttäuscht wegen unserer Erwartungen. Nur wenn du lernst, Umstände so zu sehen, wie sie wirklich sind, kannst du der Architekt der Verbesserung werden. | Greg Henry Quinn
Der einzige Mann, den ich kenne, der sich vernünftig verhält, ist mein Schneider; er nimmt bei jedem Treffen meine Maße neu. Die anderen fahren mit ihren alten Maßen fort und erwarten, dass ich ihnen entspreche. | George Bernard Shaw
Keine Aktion, keine Veränderung. Begrenzte Aktion, begrenzte Veränderung. Viel Aktion - Veränderung geschieht. | Catherine Pulsifer
Du bist immer frei, deine Meinung zu ändern und eine andere Zukunft oder eine andere Vergangenheit zu wählen. | Richard Bach
Lass nicht zu, dass andere dein Leben verändern, sei dein eigener Veränderungsagent und setze die Veränderungen um, die du willst! Und wenn eine unerwartete Veränderung in deinem Leben auftritt, finde das Positive daran. | Catherine Pulsifer
Veränderung ist unvermeidlich. Veränderung ist konstant. | Benjamin Disraeli
Wenn du dich niedergeschlagen fühlst, verzweifle nicht. Die Sonne hat jeden Abend einen Tiefstand, aber sie kommt jeden Morgen wieder hoch. So sehe ich es: Wenn du den Regenbogen willst, musst du den Regen ertragen. | Dolly Parton
Getestet zu werden ist gut. Das herausgeforderte Leben kann der beste Therapeut sein. | Gail Sheehy
Es sind nicht die Berge vor dir, die dich müde machen; es ist der Kieselstein in deinem Schuh. | Muhammad Ali
Fließe mit dem, was gerade passiert, und lass deinen Geist frei sein. Bleibe zentriert, indem du akzeptierst, was du tust. Das ist das Ultimative. | Chuang Tzu
Du magst nicht verantwortlich dafür sein, dass du niedergeschlagen wurdest, aber du bist sicherlich verantwortlich dafür, wieder aufzustehen. | Wally Amos
Ich bemühe mich, weise zu sein, wenn ich nicht fröhlich sein kann, leicht, wenn ich nicht froh sein kann, zufrieden mit dem, was nicht behoben werden kann, und geduldig, wenn es keinen Trost gibt. | Elizabeth Montagu
Schlechte Dinge sind nicht das Schlimmste, was uns passieren kann. "Nichts" ist das Schlimmste, was uns passieren kann! | Richard Bach
Das Teil kann nie gut sein, wenn das Ganze nicht gut ist. | Plato
Berge können nur durch gewundene Pfade bestiegen werden. | Johann Wolfgang von Goethe
Unterschätze niemals dein Problem oder deine Fähigkeit, damit umzugehen. | Robert H. Schuller
Jeder Morgen hat zwei Griffe. Wir können ihn mit dem Griff der Angst oder dem Griff des Glaubens ergreifen. | Henry Ward Beecher
Unmöglichkeiten sind lediglich Dinge, die wir noch nicht gelernt haben. | Charles W. Chesnutt
Wenn uns das Schicksal eine Zitrone reicht, versuchen wir, Limonade daraus zu machen. | Dale Carnegie
Du magst es nicht realisieren, wenn es passiert, aber ein Tritt in die Zähne kann das Beste sein, was dir auf der Welt passieren kann. | Walt Disney
Größe liegt nicht darin, stark zu sein, sondern in der richtigen Nutzung der Stärke. | Henry Ward Beecher
Fürchte dich nicht vor Größe: Einige sind von Geburt an groß, einige erreichen Größe, und einigen wird Größe aufgezwungen. | William Shakespeare
Große Errungenschaften entstehen normalerweise aus großen Opfern und sind niemals das Ergebnis von Egoismus. | Napoleon Hill
Um wirklich groß zu werden, muss man mit den Menschen stehen, nicht über ihnen. | Marleen Charles de Montesquieu
Ein großartiges Foto ist eines, das vollständig ausdrückt, was man in tiefstem Sinne über das, was fotografiert wird, fühlt. | Ansel Adams
Höhen, die von großen Männern erreicht und gehalten wurden, wurden nicht durch einen plötzlichen Flug erlangt, sondern während ihre Gefährten schliefen, mühten sie sich in der Nacht aufwärts. | Henry Wadsworth Longfellow
Es ist unter der größten Widrigkeit, dass das größte Potenzial besteht, Gutes zu tun, sowohl für sich selbst als auch für andere. | Dalai Lama
Eine der größten Entdeckungen eines Menschen, eine seiner großen Überraschungen, ist, zu finden, dass er tun kann, was er befürchtet, nicht tun zu können. | Henry Ford
Verantwortung ist der Preis der Größe. | Winston Churchill
Die meisten großen Menschen haben ihren größten Erfolg nur einen Schritt hinter ihrem größten Misserfolg erreicht. | Napoleon Hill
Kein großer Mensch beschwert sich jemals über Mangel an Gelegenheit. | Ralph Waldo Emerson
Ernähre deinen Geist mit großen Gedanken; an das Heroische zu glauben macht Helden. | Benjamin Disraeli
Große Anstrengung entspringt natürlich aus einer großartigen Einstellung. | Pat Riley
Riskiere mehr, als andere für sicher halten. Kümmere dich mehr, als andere für weise halten. Träume mehr, als andere für praktisch halten. Erwarte mehr, als andere für möglich halten. | Cadet Maxim
Tu jeden Tag eine Sache, die dir Angst macht. | Eleanor Roosevelt
Vertraue deinem eigenen Instinkt. Deine Fehler können ebenso gut deine eigenen sein, anstatt die von jemand anderem. | Billy Wilder
Ein risikoreiches Leben zu führen, bedeutet, von der Klippe zu springen und auf dem Weg nach unten deine Flügel zu bauen. | Ray Bradbury
Man entdeckt keine neuen Länder, ohne lange Zeit das Ufer aus den Augen zu verlieren. | André Gide
Hüte dich davor, Chancen zu verpassen; sonst ist es vielleicht eines Tages ganz zu spät. | Franz Liszt
Wer auf den Zufall vertraut, muss die Ergebnisse des Zufalls hinnehmen. | Calvin Coolidge
Du wirst dir nie den Zeh stoßen, wenn du still stehst. Je schneller du gehst, desto größer ist die Chance, dass du dir den Zeh stößt, aber desto größer ist die Chance, dass du irgendwohin kommst. | Charles F. Kettering
Weit und breit ist der beste Preis, den das Leben zu bieten hat, die Chance, hart an einer lohnenswerten Aufgabe zu arbeiten. | Theodore Roosevelt
Zu meiner Zeit hatten wir kein Selbstwertgefühl, wir hatten Selbstachtung, und nicht mehr davon, als wir uns verdient hatten. | Jane Haddam
Wer sich selbst achtet, ist vor anderen sicher; er trägt einen Mantel, den niemand durchdringen kann. | Henry Wadsworth Longfellow
Die Menschen, die ich am meisten respektiere, verhalten sich, als wären sie unsterblich und als wäre die Gesellschaft ewig. | E. M. Forster
Wenn du deine eigenen Werte nicht respektierst, wie kannst du dann respektwürdig sein für andere? | Byron Pulsifer
Ein Mensch kann viel ertragen, solange er sich selbst ertragen kann. | Axel Munthe
Respekt ist nichts, was du verlangen, kaufen oder leihen kannst. Respekt ist das, was du von jeder Person verdienst, unabhängig von ihrem Hintergrund oder Status. | Byron Pulsifer
Ich ziehe es vor, mir selbst treu zu sein, auch auf die Gefahr hin, das Gespött anderer zu ernten, anstatt falsch zu sein und meinen eigenen Abscheu zu erleiden. | Frederick Douglass
Wenn man von sich selbst entfremdet ist, dann ist man auch von anderen entfremdet. Wenn man nicht in Kontakt mit sich selbst ist, dann kann man andere nicht berühren. | Anne Morrow Lindbergh
Sie können uns unseren Selbstrespekt nicht nehmen, wenn wir ihn ihnen nicht geben. | Mahatma Gandhi
Jeder Mensch hat einen Platz in der Welt und ist in gewisser Weise wichtig, ob er es will oder nicht. | Nathaniel Hawthorne
Die Tragödie ist, dass so viele Menschen Selbstvertrauen und Selbstachtung überall suchen, außer in sich selbst, und so scheitern sie bei ihrer Suche. | Nathaniel Branden
Respekt und Vertrauen können niemals als selbstverständlich angesehen werden. Sie sind Attribute, die bewiesen werden müssen. Sie sind auch direkt proportional zum Verhalten anderer. | Elaine Sihera
Betrachte alles, als würdest du es entweder zum ersten oder letzten Mal sehen. Dann wird deine Zeit auf Erden mit Herrlichkeit erfüllt sein. | Betty Smith
Weise Männer sprechen, weil sie etwas zu sagen haben; Narren, weil sie etwas sagen müssen. | Plato
Wenn du einen wertvollen Mann siehst, denke daran, wie du ihn nachahmen kannst. Wenn du einen unwürdigen siehst, prüfe dich selbst. | Konfuzius
In jedem von uns gibt es einen Ruf, etwas zu tun, sei es noch so unbeliebt oder unbeachtet, um die Welt zu einem besseren Ort zu machen. | Robert K. Cooper
Nichts ist vorherbestimmt: Die Hindernisse deiner Vergangenheit können zu Toren werden, die zu neuen Anfängen führen. | Ralph Blum
Um Reichtum wegzugeben, ist obligatorisch, wenn du ihn besitzen möchtest. Dies ist der einzige Weg, wie du wirklich reich sein wirst. | Muhammad Ali
Menschen nehmen unterschiedliche Wege, um Erfüllung und Glück zu suchen. Nur weil sie nicht auf deinem Weg sind, bedeutet das nicht, dass sie sich verirrt haben. | Dalai Lama
Ich habe viel mehr Respekt vor der Person mit einer einzigen Idee, die dorthin gelangt, als vor der Person mit tausend Ideen, die nichts tut. | Thomas Edison
Arbeit und Spiel sind Wörter, die dasselbe unter unterschiedlichen Bedingungen beschreiben. | Mark Twain
Der reichste Mensch ist der, dessen Freuden am günstigsten sind. | Henry David Thoreau
Du kannst nicht mit einer geballten Faust die Hand schütteln. | Gandhi
Man muss Menschen mögen und ihnen vertrauen, wenn man das Leben nicht vermasseln will. | E.M. Forster
Man kann nicht vertrauen, ohne Risiken einzugehen, aber man kann auch nicht in einem Kokon leben. | Byron Pulsifer
Du magst getäuscht werden, wenn du zu viel vertraust, aber du wirst in Qualen leben, wenn du nicht genug vertraust. | Frank Crane
Wir werden alle mutig, vertrauensvoll und gierig geboren, und die meisten von uns bleiben gierig. | Mignon McLaughlin
Was ist es an der Politik, das Vertrauen ignoriert, es sei denn, es ist Wahlzeit? | Byron Pulsifer
Ich muss den Menschen folgen. Bin ich nicht ihr Anführer? | Benjamin Disraeli
Wer nicht gehorchen kann, kann nicht befehlen. | Benjamin Franklin
Ein guter Führer kann nicht zu weit vor seinen Anhängern sein. | Theodore Roosevelt
Führung ist die Kunst, jemanden dazu zu bringen, etwas zu tun, was du getan haben möchtest, weil er es selbst tun möchte. | Dwight Eisenhower
Der Schlüssel zu erfolgreicher Führung heute ist Einfluss, nicht Autorität. | Kenneth Blanchard
Es gibt eine enorme Anzahl von Managern, die im Job in Rente gegangen sind. | Peter F. Drucker
Ein guter Führer nimmt etwas mehr als seinen Anteil an der Schuld, etwas weniger als seinen Anteil an der Anerkennung. | Arnold H. Glasgow
Management bedeutet, die Dinge richtig zu tun; Führung bedeutet, die richtigen Dinge zu tun. | Peter F. Drucker
Es ist nicht fair, von anderen zu verlangen, was du selbst nicht bereit bist zu tun. | Eleanor Roosevelt
Führer schaffen keine Anhänger, sie schaffen mehr Führer. | Tom Peters
Das größte Gute, das du für einen anderen tun kannst, besteht nicht nur darin, deinen Reichtum zu teilen, sondern ihm seine eigenen aufzuzeigen. | Benjamin Disraeli
Man führt nicht, indem man Menschen auf den Kopf schlägt - das ist Übergriff, keine Führung. | Dwight Eisenhower
Ein gutes Ziel der Führung besteht darin, denen, die schlecht abschneiden, zu helfen, gut abzuschneiden, und denen, die gut abschneiden, noch besser zu werden. | Jim Rohn
Hervorragende Führer gehen aus dem Weg, um das Selbstwertgefühl ihres Personals zu steigern. Wenn Menschen an sich selbst glauben, ist es erstaunlich, was sie erreichen können. | Sam Walton
Zu viele Führer verhalten sich, als ob die Schafe ... ihre Leute ... zum Vorteil des Hirten da sind, nicht dass der Hirte Verantwortung für die Schafe hat. | Kenneth Blanchard
Der mittelmäßige Lehrer erzählt. Der gute Lehrer erklärt. Der überlegene Lehrer demonstriert. Der große Lehrer inspiriert. | William Arthur Ward
Früher war ein Führer ein Boss. Die heutigen Führer müssen Partner mit ihren Leuten sein ... sie können nicht länger ausschließlich aufgrund von Positionsmacht führen. | Kenneth Blanchard
Freundlichkeit ist die Sprache, die die Tauben hören und die Blinden sehen können. | Mark Twain
Du kannst nicht zu früh freundlich sein, denn du weißt nie, wie bald es zu spät sein wird. | Ralph Waldo Emerson
Meine Religion ist sehr einfach. Meine Religion ist Freundlichkeit. | Dalai Lama
Wenn es irgendeine Freundlichkeit gibt, die ich zeigen kann, oder irgendeine gute Sache, die ich einem Mitmenschen tun kann, lass mich es jetzt tun und nicht verschieben oder vernachlässigen, da ich diesen Weg nicht noch einmal gehen werde. | William Penn
Du hast keinen perfekten Tag gelebt, es sei denn, du hast etwas für jemanden getan, der niemals in der Lage sein wird, es dir zurückzuzahlen. | Ruth Smeltzer
Welche Weisheit kannst du finden, die größer ist als Freundlichkeit? | Jean Jacques Rousseau
So leuchtet eine gute Tat in einer müden Welt. | William Shakespeare
Unsere Taten bestimmen uns ebenso sehr, wie wir unsere Taten bestimmen. | George Eliot
Sei freundlich, denn jeder, den du triffst, kämpft einen harten Kampf. | Plato
Wer wartet, um auf einmal viel Gutes zu tun, wird nie etwas tun. | Samuel Johnson
Freundlichkeit ist der Sonnenschein, in dem Tugend gedeiht. | Robert Green Ingersoll
Strebe immer nach vollständiger Harmonie von Gedanke, Wort und Tat. Strebe immer danach, deine Gedanken zu reinigen und alles wird gut. | Mohandas Gandhi
Wer dir eine Freundlichkeit erwiesen hat, wird eher bereit sein, dir eine weitere zu tun, als derjenige, den du selbst verpflichtet hast. | Benjamin Franklin
Güte ist ereignislos. Sie blitzt nicht auf, sie glüht. | David Grayson
Lass uns daran denken, dass uns viel gegeben wurde, viel von uns erwartet wird und dass wahrer Tribut aus dem Herzen sowie von den Lippen kommt und sich in Taten zeigt. | Theodore Roosevelt
Eine spontan angebotene Freundlichkeit für jemanden, der sie braucht, ist doppelt erfreulich. | Jonathan Swift
Es ist, wenn du von dir selbst gibst, dass du wirklich gibst. | Kahil Gibran
Tue mehr als nur dazugehören: Nimm teil. Tue mehr als nur sorgen: Hilf. Tue mehr als nur glauben: Übe. Tue mehr als nur fair sein: Sei freundlich. Tue mehr als nur vergeben: Vergiss. Tue mehr als nur träumen: Arbeite. | William Arthur Ward
Freundlichkeit ist die goldene Kette, die die Gesellschaft zusammenhält. | Johann Wolfgang von Goethe
Die kleinste gute Tat ist besser als die größte gute Absicht. | Japanisches Sprichwort
Es gibt keine bessere Übung für dein Herz, als hinunterzureichen und jemandem aufzuhelfen. | Bernard Meltzer
Freundlichkeit kann zum eigenen Motiv werden. Wir werden freundlich, indem wir freundlich sind. | Eric Hoffer
Freundlichkeit erzeugt Freundlichkeit. | Griechisches Sprichwort
Ein freundliches Herz ist ein Brunnen der Freude, der alles in seiner Umgebung in Lächeln verwandelt. | Washington Irving
Sei freundlich zu denen, die du beim Aufstieg triffst, du könntest ihnen wieder begegnen, wenn du fällst. | Irisches Sprichwort
Vollständiger Besitz wird nur durch Geben bewiesen. Alles, was du nicht geben kannst, besitzt dich. | Andre Gide
Ein freundliches Wort kann drei Wintermonate erwärmen. | Japanisches Sprichwort
Wann immer du etwas tun sollst, obwohl es nur dir selbst bekannt sein kann, frage dich, wie du handeln würdest, wenn die ganze Welt zuschauen würde, und handle entsprechend. | Thomas Jefferson
Die hartnäckigste und dringlichste Frage des Lebens lautet: Was tust du für andere? | Martin Luther King, Jr.
Wo immer es einen Menschen gibt, gibt es eine Gelegenheit zur Freundlichkeit. | Seneca
Freundliche Worte können kurz und leicht zu sprechen sein, aber ihre Echos sind wahrlich endlos. | Mutter Teresa
Um unter allen Umständen fünf Dinge zu üben, bildet vollkommene Tugend; diese fünf Dinge sind Schwere, Großzügigkeit der Seele, Aufrichtigkeit, Ernsthaftigkeit und Freundlichkeit. | Konfuzius
Sollen wir ein neues Lebensmotto machen, ab heute Abend - immer versuchen, ein wenig freundlicher zu sein, als notwendig ist. | Sir James M. Barrie
Gute Taten adeln uns, wir sind die Söhne unserer eigenen Taten. | Jean Paul Richter
Wenn du keine Nächstenliebe in deinem Herzen hast, hast du die schlimmste Art von Herzproblemen. | Bob Hope
Freundliche Worte werden ein Eisentor aufschließen. | Türkisches Sprichwort
Freundlichkeit zu kultivieren ist ein wertvoller Teil des Lebensgeschäfts. | Samuel Johnson
Wir können unser Alter entweder bedauern oder dankbar sein, dass wir es erreicht haben. | William Arthur Ward
Wenn du dich mit nichts weniger als deinem Besten zufriedengibst, wirst du erstaunt sein, was du in deinem Leben erreichen kannst. | Vince Lombardi
Große Geister haben Ziele; kleine Geister haben Wünsche. Kleine Geister werden von Missgeschicken überwältigt; große Geister erheben sich über sie. | Washington Irving
Kein Mensch kann vermeiden, durchschnittlich geboren zu werden, aber kein Mensch muss gewöhnlich sein. | Satchel Paige
Glaube tief in deinem Herzen, dass du dazu bestimmt bist, großartige Dinge zu tun. | Joe Paterno
Wir sollten nicht zurückblicken, es sei denn, um nützliche Lektionen aus vergangenen Fehlern zu ziehen und um von teuer erkauften Erfahrungen zu profitieren. | George Washington
Die Erde ist mit Himmel überfüllt. | Elizabeth Barrett Browning
Erinnere dich, die Inspiration folgt der Handlung und nicht umgekehrt. | Aronson, Eric, Dash
Erinnere dich, dass es manchmal ein wunderbarer Glücksfall ist, nicht zu bekommen, was du willst. | Dalai Lama
Alles kommt zu dem, der nur wartet. | Henry Wadsworth Longfellow
Siehst du, im Leben wissen viele Menschen, was zu tun ist, aber nur wenige tun tatsächlich das, was sie wissen. Wissen ist nicht genug! Du musst handeln. | Anthony Robbins
Ich sehe das Leben immer gerne von der optimistischen Seite, aber ich bin realistisch genug, um zu wissen, dass das Leben eine komplexe Angelegenheit ist. | Walt Disney
Wir alle finden uns manchmal in Situationen, die hoffnungslos erscheinen. Und wir alle haben die Wahl, nichts zu tun oder zu handeln. | Catherine Pulsifer
Ehrlichkeit ist der seltenste Reichtum, den jemand besitzen kann, und doch ist alle Ehrlichkeit der Welt kein gesetzliches Zahlungsmittel für ein Brot. | Josh Billings
Oh, welch ein Gewirr wir weben, wenn wir zum ersten Mal Täuschung üben! | Sir Walter Scott
So ziemlich alle ehrlichen Wahrheiten der Welt werden von Kindern gesagt. | Oliver Wendell Holmes, Jr.
Es ist schwer zu glauben, dass ein Mann die Wahrheit sagt, wenn du weißt, dass du lügen würdest, wenn du an seiner Stelle wärst. | Henry Louis Mencken
Unser Leben verbessert sich nur, wenn wir Chancen ergreifen - und die erste und schwierigste Chance, die wir ergreifen können, ist, ehrlich zu uns selbst zu sein. | Walter Anderson
Lass uns einen Standard setzen, zu dem die Weisen und Ehrlichen zurückkehren können; der Rest liegt in den Händen Gottes. | George Washington
Kein Vermächtnis ist so reich wie Ehrlichkeit. | William Shakespeare
Das beste Maß für die Ehrlichkeit eines Mannes ist nicht seine Steuererklärung. Es ist der Nullabgleich seiner Waage im Badezimmer. | Arthur C. Clarke
Eine der grundlegendsten Kernwerte ist Ehrlichkeit. | Catherine Pulsifer
Die Grundsteine für einen ausgewogenen Erfolg sind Ehrlichkeit, Charakter, Integrität, Glaube, Liebe und Loyalität. | Zig Ziglar
Unehrlichkeit wird die Ehrlichkeit jede Woche aus dem Konzept bringen, wenn es etwas zu gewinnen gibt. | Charles Dickens
Ehrlichkeit ist das erste Kapitel im Buch der Weisheit. | Thomas Jefferson
Integrität bedeutet, sich selbst die Wahrheit zu sagen. Und Ehrlichkeit bedeutet, anderen die Wahrheit zu sagen. | Spencer Johnson
Sei vorbereitet und sei ehrlich. | John Wooden
Es gibt keine Grauzone der Ehrlichkeit im Geschäft. Eine Sache ist richtig oder falsch. Es ist schwarz oder weiß. | John F. Dodge
Kein Mensch hat ein gutes Gedächtnis, um ein erfolgreicher Lügner zu sein. | Abraham Lincoln
Sei ehrlich zu deinem Kind. Niemand erkennt einen Phony schneller als ein Kind. | Mary MacCracken
Sei albern. Sei ehrlich. Sei freundlich. | Ralph Waldo Emerson
Wie ich bereits sagte, das Erste ist, ehrlich zu sich selbst zu sein. | Nelson Mandela
Ehrlichkeit bedeutet, eine negative Reaktion zu fürchten und trotzdem die Wahrheit zu sagen. | Michelle C. Ustaszeski
Konzentration ist mein Motto - zuerst Ehrlichkeit, dann Fleiß, dann Konzentration. | Andrew Carnegie
Ehrliche Meinungsverschiedenheit ist oft ein gutes Zeichen für Fortschritt. | Gandhi
Zweifel, der gehegt und gepflegt wird, läuft Gefahr, zur Verleugnung zu werden; aber wenn er ehrlich ist und auf gründliche Untersuchung aus ist, kann er bald zur vollen Feststellung der Wahrheit führen. | Ambrose Bierce
