All achievements, all earned riches, have their beginning in an idea. | Napoleon Hill
Never mistake activity for achievement. | John Wooden
Achievement results from work realizing ambition. | Adam Ant
The most complicated achievements of thought are possible without the assistance of consciousness. | Sigmund Freud
Great achievement is usually born of great sacrifice, and is never the result of selfishness. | Napoleon Hill
Death comes to all, but great achievements build a monument which shall endure until the sun grows cold. | Ralph Waldo Emerson
Cherish your visions and your dreams as they are the children of your soul; the blueprints of your ultimate achievements. | Napoleon Hill
You have to learn the rules of the game. And then you have to play better than anyone else. | Albert Einstein
I'm glad I did it, partly because it was worth it, but mostly because I shall never have to do it again. | Mark Twain
It is not the mountain we conquer but ourselves. | Edmund Hillary
Our task must be to free ourselves from this prison by widening our circles of compassion to embrace all living creatures and the whole of nature in its beauty. | Albert Einstein
High achievement always takes place in the framework of high expectation. | Charles F. Kettering
You can have everything in life you want, if you will just help other people get what they want. | Zig Ziglar
Great effort springs naturally from a great attitude. | Pat Riley
Your attitude, not your aptitude, will determine your altitude. | Zig Ziglar
You can adopt the attitude there is nothing you can do, or you can see the challenge as your call to action. | Catherine Pulsifer
An optimist is a person who sees a green light everywhere, while the pessimist sees only the red stoplight - The truly wise person is colorblind. |  Albert Schweitzer
Positive thinking will let you do everything better than negative thinking will. | Zig Ziglar
You cannot control what happens to you, but you can control your attitude toward what happens to you, and in that, you will be mastering change rather than allowing it to master you. | Brian Tracy
You can do it if you believe you can! | Napoleon Hill
If you don't set a baseline standard for what you'll accept in life, you'll find it's easy to slip into behaviors and attitudes or a quality of life that's far below what you deserve. | Anthony Robbins
If you don't like something, change it. If you can't change it, change your attitude. Don't complain. | Maya Angelou
The person who sends out positive thoughts activates the world around him positively and draws back to himself positive results. | Norman Vincent Peale
If your happiness depends on what somebody else does, I guess you do have a problem. | Richard Bach
Feeling sorry for yourself, and your present condition, is not only a waste of energy but the worst habit you could possibly have. | Dale Carnegie
Anybody can do just about anything with himself that he really wants to and makes up his mind to do. We are capable of greater things than we realize. | Norman Vincent Peale
There are two primary choices in life: to accept conditions as they exist, or accept the responsibility for changing them. | Denis Waitley
Life is like playing a violin in public and learning the instrument as one goes on. | Samuel Butler
The first step to getting the things you want out of life is this: Decide what you want. | Ben Stein
Life is what happens to you while you're busy making other plans. | John Lennon
Where you end up isn't the most important thing. It's the road you take to get there. The road you take is what you'll look back on and call your life. | Tim Wiley
There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. | Albert Einstein
The quality of a person's life is in direct proportion to their commitment to excellence, regardless of their chosen field of endeavor. | Vince Lombardi
Life is just a mirror, and what you see out there, you must first see inside of you. | Wally Amos
Pack all there is into your life; you only pass this way once! Sit back and think what is it you enjoy. Take courses, read books, find your passion. | Catherine Pulsifer
The big secret in life is that there is no big secret. Whatever your goal, you can get there if you're willing to work. | Oprah Winfrey
Life must be lived and curiosity kept alive. One must never, for whatever reason, turn his back on life. | Eleanor Roosevelt
To know even one life has breathed easier because you have lived. This is to have succeeded. | Ralph Waldo Emerson
Life's battles don't always go to the stronger or faster man. But sooner or later the man who wins, is the man who thinks he can. | Vince Lombardi
Don't be a spectator, don't let life pass you by. | Lou Holtz
Life is uncharted territory. It reveals its story one moment at a time. | Leo Buscaglia
To have integrity is also to have character which is also the easiest way to run into conflict with those without either.  | Byron Pulsifer
Have the courage to say no. Have the courage to face the truth. Do the right thing because it is right. These are the magic keys to living your life with integrity. | Mark Twain
Integrity can be difficult to maintain in a world that demands you change with the wind. | Byron Pulsifer
Integrity is what we do, what we say, and what we say we do. | Don Galer
Love all, trust a few, do wrong to none. | William Shakespeare
To have integrity means that you don't agree with everyone you meet, nor do you succumb to pressure to be something that is in direct conflict with your core ethics. | Byron Pulsifer
Character is higher than intellect. | Ralph Waldo Emerson
My grandfather once told me that there are two kinds of people: those who work and those who take the credit. He told me to try to be in the first group; there was less competition there. | Indira Gandhi
But what is happiness except the simple harmony between a man and the life he leads? | Albert Camus
There's only one corner of the universe you can be certain of improving, and that's your own self. | Aldous Huxley
We must not allow ourselves to become like the system we oppose. | Bishop Desmond Tutu
Integrity without knowledge is weak and useless, and knowledge without integrity is dangerous and dreadful. | Samuel Johnson
We need to stress that personal integrity is as important as executive skill in business dealings.. | Russell E. Palmer
No matter the time of day, no matter who is watching and no matter the situation, personal integrity doesn't take a holiday. | Byron Pulsifer
Wisdom is knowing what to do next; virtue is doing it. | David Star Jordan
Character is doing the right thing when nobody's looking. There are too many people who think that the only thing that's right is to get by, and the only thing that's wrong is to get caught. | J.C. Watts
You cannot always do the right thing but you can always do whatever you do with integrity. | Byron Pulsifer
Never let your sense of morals prevent you from doing what's right. | Isaac Asimov
Integrity is conforming reality to our words - in other words, keeping promises and fulfilling expectations. | Stephen R. Covey
Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. | Albert Schweitzer
You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life. | Albert Camus
The Constitution only guarantees the American people the right to pursue happiness. You have to catch it yourself. | Benjamin Franklin
No society can surely be flourishing and happy, of which the far greater part of the members are poor and miserable. | Adam Smith
Happiness is a state of mind not what's in your wallet. | Byron Pulsifer
If you want to be happy, be. | Leo Tolstoy
Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom. | Marcel Proust
The man who makes everything that leads to happiness depend upon himself, and not upon other men, has adopted the very best plan for living happily. | Plato
Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy. | Norman Vincent Peale
To be without some of the things you want is an indispensable part of happiness. | Bertrand Russell
But what is happiness except the simple harmony between a man and the life he leads? | Albert Camus
Action may not always bring happiness; but there is no happiness without action. | Benjamin Disraeli
Most people would rather be certain they're miserable, than risk being happy. | Robert Anthony
If only we'd stop trying to be happy we could have a pretty good time. | Edith Wharton
What can be added to the happiness of a man who is in health, out of debt, and has a clear conscience? | Adam Smith
Experience is not what happens to a man. It is what a man does with what happens to him. | Aldous Leonard Huxley
Good judgment comes from experience, and often experience comes from bad judgment. | Rita Mae Brown
A mind that is stretched by a new experience can never go back to its old dimensions. | Oliver Wendell Holmes, Jr.
Sometimes you have to do a lot of things to determine what it is you don't want to do. Along the way you pick up a lot of experience. | Wally Amos
A man can't retire his experience. He must use it. Experience achieves more with less energy and time. | Bernard M. Baruch
The response to 'The Greatest Generation' and the books that followed has been one of the most satisfying experiences of my life. | Tom Brokaw
Fame will go by and, so long, I've had you, fame. If it goes by, I've always known it was fickle. So at least it's something I experience, but that's not where I live. | Marilyn Monroe
Experience is the child of thought, and thought is the child of action. | Benjamin Disraeli
I'd rather have a lot of talent and a little experience than a lot of experience and a little talent. | John Wooden
Never become so much of an expert that you stop gaining expertise. View life as a continuous learning experience. | Denis Waitley
The most beautiful thing we can experience is the mysterious. It is the source of all true art and science. | Albert Einstein
Experience is not what happens to you. It is what you do with what happens to you. | Aldous Huxley
With every experience, you alone are painting your own canvas, thought by thought, choice by choice. | Oprah Winfrey
As a woman I've always felt that as we get older we get better. You come to terms with yourself, through emotional experiences and the simple wisdom that comes with age. | Linda Evans
We should not look back unless it is to derive useful lessons from past errors, and for the purpose of profiting by dearly bought experience. | George Washington
The most painful thing to experience is not defeat but regret. | Leo Buscaglia
No man was ever so completely skilled in the conduct of life, as not to receive new information from age and experience. | Jonathan Swift
Art is not a handicraft, it is the transmission of feeling the artist has experienced. | Leo Tolstoy
I think everyone should experience defeat at least once during their career. You learn a lot from it. | Lou Holtz
The secret to a rich life is to have more beginnings than endings. | Dave Weinbaum
All difficult things have their origin in that which is easy, and great things in that which is small. | Lao-Tzu
Almost everything comes from nothing. | Henry F. Amiel
Necessity, who is the mother of invention. | Plato
The distance is nothing; it's only the first step that is difficult. | Marquise du Deffand
Beginnings are only difficult without any action. | Byron Pulsifer
Small opportunities are often the beginning of great enterprises. | Demosthenes
A hard beginning maketh a good ending. | John Heywood
You don't have to be great to start, but you have to start to be great. | Joe Sabah
A lot of people seeking new beginnings have never finished with the past. | Byron Pulsifer
Every day is a new beginning. Treat it that way. Stay away from what might have been, and look at what can be. | Marsha Petrie Sue
This is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning. | Winston Churchill
Whatever you do, or dream you can, begin it. Boldness has genius and power and magic in it. | Goethe
Jumping at several small opportunities may get us there more quickly than waiting for one big one to come along. | Hugh Allen
It is often hard to distinguish between the hard knocks in life and those of opportunity. | Frederick Phillips
Ability is of little account without opportunity. | Napoleon
The secret of success in life is for a man to be ready for his opportunity when it comes. | Benjamin Disraeli
Opportunities are never lost; someone will take the one you miss. |
Every day is an opportunity to make a new happy ending. |
All that is valuable in human society depends upon the opportunity for development accorded the individual. | Albert Einstein
A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty. | Winston Churchill
Life is a gift, and it offers us the privilege, opportunity, and responsibility to give something back by becoming more. | Tony Robbins
The ladder of success is best climbed by stepping on the rungs of opportunity. | Ayn Rand
Ability is nothing without opportunity. | Napoleon Bonaparte
Your big opportunity may be right where you are now. | Napoleon Hill
Opportunities come into my life and I respond to those that appeal to me. | Wally Amos
Men never moan over the opportunities lost to do good, only the opportunities to be bad. | Greek Proverb
Edison failed 10, 000 times before he made the electric light. Do not be discouraged if you fail a few times. | Napoleon Hill
How long should you try? Until. | Jim Rohn
Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish. | John Quincy Adams
Through perseverance many people win success out of what seemed destined to be certain failure. | Benjamin Disraeli
Try and fail, but don't fail to try. | Stephen Kaggwa
If you wish success in life, make perseverance your bosom friend, experience your wise counselor, caution your elder brother and hope your guardian genius. | Joseph Addison
Great works are performed, not by strength, but by perseverance. | Samuel Johnson
I do not think there is any other quality so essential to success of any kind as the quality of perseverance. It overcomes almost everything, even nature. | John D. Rockefeller
There is no failure except in no longer trying. | Elbert Hubbard
Persistence and determination alone are omnipotent. The slogan press on has solved and always will solve the problems of the human race. | Calvin Coolidge
Victory belongs to the most persevering. | Napoleon Bonaparte
Follow your dreams of a better world, and keep on trying, even when there seems to be little hope, because it is the right thing to do. | Robert Alan
Genius is divine perseverance. Genius I cannot claim nor even extra brightness but perseverance all can have. | Woodrow Wilson
In the confrontation between the stream and the rock, the stream always wins- not through strength but by perseverance. | H. Jackson Brown
Perseverance is more prevailing than violence and many things which cannot be overcome when they are together yield themselves up when taken little by little. | Plutarch
Perseverance is not a long race; it is many short races one after the other. | Walter Elliot
The best among us are not more gifted than the rest. They just take little steps each day as they march toward their biggest life. | Robin Sharma,The Greatness Guide
Associate yourself with men of good quality if you esteem your own reputation. It is better be alone than in bad company. | George Washington
Quality is not an act, it is a habit. | Aristotle
If standard of living is your major objective, quality of life almost never improves, but if quality of life is your number one objective, your standard of living almost always improves. | Zig Ziglar
Quality is an attribute quite commonly abused by those who seek to mislead. | Byron Pulsifer
Quality means doing it right when no one is looking. | Henry Ford
If you are unsure about the quality of your work, you need to first understand what quality is. | Byron Pulsifer
Quality is never an accident; it is always the result of intelligent effort. | John Ruskin
It is the quality of our work which will please God, not the quantity. | Mahatma Gandhi
The quality of a person's life is in direct proportion to their commitment to excellence, regardless of their chosen field of endeavor. | Vince Lombardi
The quality, not the longevity, of one's life is what is important. | Martin Luther King
No one can possibly achieve any real and lasting success or 'get rich' in business by being a conformist. | J. P. Getty
To climb steep hills requires slow pace at first. | William Shakespeare
There's no secret about success. Did you ever know a successful man who didn't tell you about it? | Kin Hubbard
The secret of man's success resides in his insight into the moods of people, and his tact in dealing with them. | Josiah Gilbert Holland
There is no passion to be found playing small - in settling for a life that is less than the one you are capable of living. | Nelson Mandela
Goals have made a tremendous difference in my life. They have allowed me to achieve success, and to accomplish what I had previously only dreamed of, or wished for. | Catherine Pulsifer
Never confuse movement with action. | Ernest Hemmingway
Success is getting what you want. Happiness is wanting what you get. | Dale Carnegie
In everything we do, our own thoughts can help us succeed, or they can help us fail. Maintain a positive attitude. | Catherine Pulsifer
Most of the successful people I've known are the ones who do more listening than talking. | Bernard M. Baruch
Making a success of the job at hand is the best step toward the kind you want. | Bernard M. Baruch
You cannot measure a man by his failures. You must know what use he makes of them. What did they mean to him. What did he get out of them. | Orison Swett Marden
If one advances confidently in the direction of his dream, and endeavors to live the life which he had imagines, he will meet with a success unexpected in common hours. | Henry David Thoreau
Time is the most valuable thing a man can spend. | Theophrastus
You must have been warned against letting the golden hours slip by; but some of them are golden only because we let them slip by. | James Matthew Barrie
If you want work well done, select a busy man, the other kind has no time. | Elbert Hubbard
Time is the wisest counsellor of all. | Pericles
All that really belongs to us is time; even he who has nothing else has that. | Baltasar Gracian
Time is the longest distance between two places. | Tennessee Williams
Nothing is a waste of time if you use the experience wisely. | Rodin
We must use time as a tool, not as a crutch. | John F. Kennedy
Time and words can't be recalled, even if it was only yesterday. | Yiddish Proverb
Regret for the things we did can be tempered by time; it is regret for the things we did not do that is inconsolable. | Sydney J. Harris
But what minutes! Count them by sensation, and not by calendars, and each moment is a day. | Benjamin Disraeli
Time is the coin of your life. It is the only coin you have, and only you can determine how it will be spent. Be careful lest you let other people spend it for you. | Carl Sandburg
You will never find time for anything. If you want time you must make it. | Charles Buxton
Better three hours too soon than a minute too late. | William Shakespeare
Lost time is never found again. | Benjamin Franklin
The hours of folly are measured by the clock; but of wisdom, no clock can measure. | William Blake
You never get tired unless you stop and take time for it. | Bob Hope
Time is the wisest counsellor. | Pericles
I wasted time, and now doth time waste me. | William Shakespeare
Your greatest asset is your earning ability. Your greatest resource is your time. | Brian Tracy
We must use time wisely and forever realize that the time is always ripe to do right. | Nelson Mandela
Life is not measured by the number of breathes we take, but by the moments that take our breath away. |
The best way to make your dreams come true is to wake up. | Paul Valery
One of the things I learned the hard way was that it doesn't pay to get discouraged. | Lucille Ball
The important thing is this: to be able at any moment to sacrifice what we are; for what we could become. | Charles Dubois
All the advice in the world will never help you until you help yourself. | Fred Van Amburgh
To love abundantly is to live abundantly, and to love forever is to live forever. | Henry Drummond
How you think about a problem is more important than the problem itself. So always think positively. | Norman Vincent Peale
Forget past mistakes. Forget failures. Forget everything except what you're going to do now and do it. | William Durant
You can tell more about a person by what he says about others than you can by what others say about him. | Leo Aikman
Dream big dreams, then put on your overalls and go out and make the dreams come true. | Fred Van Amburgh
The mystery of life is not a problem to be solved; it is a reality to be experienced. | Aart van der Leenw
There is only one corner of the universe you can be certain of improving, and that's your own self. | Aldous Huxley
The good life is a process, not a state of being. It is a direction, not a destination. | Carl Rogers
We are what we repeatedly do. Excellence then, is not an act, but a habit. | Aristotle
Read not to contradict and confute, not to believe and take for granted, not to find talk and discourse, but to weigh and consider. | Francis Bacon
One of the best ways to persuade others is with your ears, by listening to them. | Dean Rusk
If you have just one or two friends with whom you can share your highest aspirations, you should consider yourself richly blessed. | J. Donald Waters
Rather than wishing for change, you first must be prepared to change. | Catherine Pulsifer
Everyone thinks of changing the world, but no one thinks of changing himself. | Leo Tolstoy
Change is as inexorable as time, yet nothing meets with more resistance. | Benjamin Disraeli
Only the wisest and stupidest of men never change. | Confucius
Never stop learning, like never stop changing and growing in your life - learning helps you adapt to change more easily. | Learning Quotes
What we think determines what happens to us, so if we want to change our lives, we need to stretch our minds. | Wayne Dyer
You cannot change your destination overnight, but you can change your direction overnight. | Jim Rohn
We are often disappointed because of our expectations. Only when you learn to see circumstances as they truly are can you become the architect of improvement. | Greg Henry Quinn
The only man I know who behaves sensibly is my tailor; he takes my measurements anew each time he sees me. The rest go on with their old measurements and expect me to fit them. | George Bernard Shaw
No action, no change. Limited action, limited change. Lots of action - Change occurs. | Catherine Pulsifer
You are always free to change your mind and choose a different future, or a different past. | Richard Bach
Don't let others change your life, be your own change agent and implement the changes you want! And if an unexpected change occurs in your life, find the positive in it. | Catherine Pulsifer
Change is inevitable. Change is constant. | Benjamin Disraeli
If you're feeling low, don't despair. The sun has a sinking spell every night, but it comes back up every morning. The way I see it, if you want the rainbow, you gotta put up with the rain. | Dolly Parton
To be tested is good. The challenged life may be the best therapist. | Gail Sheehy
It isn't the mountains ahead to climb that wear you out; it's the pebble in your shoe. | Mahummad Ali
Flow with whatever is happening and let your mind be free. Stay centered by accepting whatever you are doing. This is the ultimate. | Chuang Tzu
You may not be responsible for getting knocked down, but you're certainly responsible for getting back up. | Wally Amos
I endeavor to be wise when I cannot be merry, easy when I cannot be glad, content with what cannot be mended and patient when there is no redress. | Elizabeth Montagu
Bad things are not the worst things that can happen to us. "Nothing" is the worst thing that can happen to us! | Richard Bach
The part can never be well unless the whole is well. | Plato
Mountains cannot be surmounted except by winding paths. | Johann Wolfgang Von Goethe
Never underestimate your problem or your ability to deal with it. | Robert H. Schuller
Every tomorrow has two handles. We can take hold of it with the handle of anxiety or the handle of faith. | Henry Ward Beecher
Impossibilities are merely things which we have not yet learned. | Charles W. Chesnutt
When fate hands us a lemon, let's try to make lemonade. | Dale Carnegie
You may not realize it when it happens, but a kick in the teeth may be the best thing in the world for you. | Walt Disney
Greatness lies not in being strong, but in the right use of strength. | Henry Ward Beecher
Be not afraid of greatness: some are born great, some achieve greatness, and some have greatness thrust upon them. | William Shakespeare
Great achievement is usually born of great sacrifice, and is never the result of selfishness. | Napoleon Hill
To become truly great, one has to stand with people, not above them. | Marleen Charles de Montesquieu
A great photograph is one that fully expresses what one feels, in the deepest sense, about what is being photographed. | Ansel Adams
Heights by great men reached and kept were not obtained by sudden flight but, while their companions slept, they were toiling upward in the night. | Henry Wadsworth Longfellow
It is under the greatest adversity that there exists the greatest potential for doing good, both for oneself and others. | Dalai Lama
One of the greatest discoveries a man makes, one of his great surprises, is to find he can do what he was afraid he couldn't do. | Henry Ford
Responsibility is the price of greatness. | Winston Churchill
Most great people have attained their greatest success just one step beyond their greatest failure. | Napoleon Hill
No great man ever complains of want of opportunity. | Ralph Waldo Emerson
Nurture your mind with great thoughts; to believe in the heroic makes heroes. | Benjamin Disraeli
Great effort springs naturally from a great attitude. | Pat Riley
Risk more than others think is safe. Care more than others think is wise. Dream more than others think is practical. Expect more than others think is possible. | Cadet Maxim
Do one thing every day that scares you. | Eleanor Roosevelt
Trust your own instinct. Your mistakes might as well be your own, instead of someone else's. | Billy Wilder
Living at risk is jumping off the cliff and building your wings on the way down. | Ray Bradbury
One does not discover new lands without consenting to lose sight of the shore for a very long time. | André Gide
Beware of missing chances; otherwise it may be altogether too late some day. | Franz Liszt
Those who trust to chance must abide by the results of chance. | Calvin Coolidge
You will never stub your toe standing still. The faster you go, the more chance there is of stubbing your toe, but the more chance you have of getting somewhere. | Charles F. Kettering
Far and away the best prize that life has to offer is the chance to work hard at work worth doing. | Theodore Roosevelt
In my day, we didn't have self-esteem, we had self-respect, and no more of it than we had earned. | Jane Haddam
He that respects himself is safe from others; he wears a coat of mail that none can pierce. | Henry Wadsworth Longfellow
The people I respect most behave as if they were immortal and as if society was eternal. | E. M. Forster
If you have no respect for your own values how can you be worthy of respect from others. | Byron Pulsifer
A man can stand a lot as long as he can stand himself. | Axel Munthe
Respect is not something that you can ask for, buy or borrow. Respect is what you earn from each person no matter their background or status. | Byron Pulsifer
I prefer to be true to myself, even at the hazard of incurring the ridicule of others, rather than to be false, and to incur my own abhorrence. | Frederick Douglass
If one is estranged from oneself, then one is estranged from others too. If one is out of touch with oneself, then one cannot touch others. | Anne Morrow Lindbergh
They cannot take away our self-respect if we do not give it to them. | Mahatma Gandhi
Every individual has a place to fill in the world and is important in some respect whether he chooses to be so or not. | Nathaniel Hawthorne
The tragedy is that so many people look for self-confidence and self-respect everywhere except within themselves, and so they fail in their search. | Nathaniel Branden
Respect and trust can never be taken for granted. They are attributes that have to be proven. They are also directly reciprocal to the behaviour of others. | Elaine Sihera
Look at everything as though you were seeing it either for the first or last time. Then your time on earth will be filled with glory. | Betty Smith
Wise men talk because they have something to say; fools, because they have to say something. | Plato
When you see a man of worth, think of how you may emulate him. When you see one who is unworthy, examine yourself. | Confucius
There is a call within every one of us, a call to do something, however unpopular or unnoticed, to make the world a better place. | Robert K. Cooper
Nothing is predestined: The obstacles of your past can become the gateways that lead to new beginnings. | Ralph Blum
To be able to give away riches is mandatory if you wish to possess them. This is the only way that you will be truly rich. | Mahummad Ali
People take different roads seeking fulfillment and happiness. Just because they're not on your road doesn't mean they've gotten lost. | Dalai Lama
I have far more respect for the person with a single idea who gets there than for the person with a thousand ideas who does nothing. | Thomas Edison
Work and play are words used to describe the same thing under differing conditions. | Mark Twain
The man is richest whose pleasures are cheapest. | Henry David Thoreau
You can't shake hands with a clenched fist. | Gandhi
One must be fond of people and trust them if one is not to make a mess of life. | E.M. Forster
You can't trust without risk but neither can you live in a cocoon. | Byron Pulsifer
You may be deceived if you trust too much, but you will live in torment unless you trust enough. | Frank Crane
We're all born brave, trusting, and greedy, and most of us remain greedy. | Mignon McLaughlin
What is it about politics that seems to ignore trust unless at election time? | Byron Pulsifer
I must follow the people. Am I not their leader? | Benjamin Disraeli
He that cannot obey, cannot command. | Benjamin Franklin
A good leader can't get too far ahead of his followers. | Theodore Roosevelt
Leadership is the art of getting someone else to do something you want done because he wants to do it. | Dwight Eisenhower
The key to successful leadership today is influence, not authority. | Kenneth Blanchard
There is an enormous number of managers who have retired on the job. | Peter F. Drucker
A good leader takes a little more than his share of the blame, a little less than his share of the credit. | Arnold H. Glasgow
Management is doing things right; leadership is doing the right things. | Peter F. Drucker
It is not fair to ask of others what you are unwilling to do yourself. | Eleanor Roosevelt
Leaders don't create followers, they create more leaders. | Tom Peters
The greatest good you can do for another is not just share your riches, but reveal to them their own. | Benjamin Disraeli
You do not lead by hitting people over the head - that's assault, not leadership. | Dwight Eisenhower
A good objective of leadership is to help those who are doing poorly to do well and to help those who are doing well to do even better. | Jim Rohn
Outstanding leaders go out of their way to boost the self-esteem of their personnel. If people believe in themselves, it's amazing what they can accomplish. | Sam Walton
Too many leaders act as if the sheep... their people... are there for the benefit of the shepherd, not that the shepherd has responsibility for the sheep. | Kenneth Blanchard
The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires. | William Arthur Ward
In the past a leader was a boss. Today's leaders must be partners with their people... they no longer can lead solely based on positional power. | Kenneth Blanchard
Kindness is the language which the deaf can hear and the blind can see. | Mark Twain
You cannot do a kindness too soon, for you never know how soon it will be too late. | Ralph Waldo Emerson
My religion is very simple. My religion is kindness. | Dalai Lama
If there is any kindness I can show, or any good thing I can do to any fellow being, let me do it now, and not deter or neglect it, as I shall not pass this way again. | William Penn
You have not lived a perfect day, unless you have done something for someone who will never be able to repay you. | Ruth Smeltzer
What wisdom can you find that is greater than kindness? | Jean Jacques Rousseau
So shines a good deed in a weary world. | William Shakespeare
Our deeds determine us, as much as we determine our deeds. | George Eliot
Be kind, for everyone you meet is fighting a hard battle. | Plato
He who waits to do a great deal of good at once, will never do anything. | Samuel Johnson
Kindness is the sunshine in which virtue grows. | Robert Green Ingersoll
Always aim at complete harmony of thought and word and deed. Always aim at purifying your thoughts and everything will be well. | Mohandas Gandhi
He that has done you a kindness will be more ready to do you another, than he whom you yourself have obliged. | Benjamin Franklin
Goodness is uneventful. It does not flash, it glows. | David Grayson
Let us remember that, as much has been given us, much will be expected from us, and that true homage comes from the heart as well as from the lips, and shows itself in deeds. | Theodore Roosevelt
A kindness spontaneously offered to him who needs it, is doubly gratifying. | Jonathan Swift
It is when you give of yourself that you truly give. | Kahil Gibran
Do more than belong: participate. Do more than care: help. Do more than believe: practice. Do more than be fair: be kind. Do more than forgive: forgett. Do more than dream: work. | William Arthur Ward
Kindness is the golden chain by which society is bound together. | Johann Wolfgang Von Goethe
The smallest good deed is better than the grandest good intention. | Japanese Proverb
There is no better exercise for your heart than reaching down and helping to lift someone up. | Bernard Meltzer
Kindness can become its own motive. We are made kind by being kind. | Eric Hoffer
Kindness begets kindness. | Greek Proverb
A kind heart is a fountain of gladness, making everything in its vicinity freshen into smiles. | Washington Irving
Be kind to those that meet you as you rise, you may pass them again as you fall. | Irish Proverb
Complete possession is proved only by giving. All you are unable to give possesses you. | Andre Gide
One kind word can warm three winter months. | Japanese Proverb
Whenever you are to do a thing, though it can never be known but to yourself, ask yourself how you would act were all the world looking at you and act accordingly. | Thomas Jefferson
Life's most persistent and urgent question is, What are you doing for others? | Martin Luther King, Jr.
Wherever there is a human being there is an opportunity for kindness. | Seneca
Kind words can be short and easy to speak but their echoes are truly endless. | Mother Teresa
To be able under all circumstances to practice five things constitutes perfect virtue; these five things are gravity, generosity of soul, sincerity, earnestness and kindness. | Confucius
Shall we make a new rule of life from tonight - always try to be a little kinder than is necessary. | Sir James M. Barrie
Good actions ennoble us, we are the sons of our own deeds. | Jean Paul Richter
If you haven't any charity in your heart, you have the worst kind of heart trouble. | Bob Hope
Kind words will unlock an iron door. | Turkish Proverb
To cultivate kindness is a valuable part of the business of life. | Samuel Johnson
We can be resentful of our age, or we can be grateful for having attained it. | William Arthur Ward
If you'll not settle for anything less than your best, you will be amazed at what you can accomplish in your lives. | Vince Lombardi
Great minds have purposes; little minds have wishes. Little minds are subdued by misfortunes; great minds rise above them. | Washington Irving
Ain't no man can avoid being born average, but there ain't no man got to be common. | Satchel Paige
Believe deep down in your heart that you're destined to do great things. | Joe Paterno
We should not look back unless it is to derive useful lessons from past errors, and for the purpose of profiting by dearly bought experience. | George Washington
Earth is crammed with Heaven. | Elizabeth Barrett Browning
Remember, the inspiration follows action and not vice versa. | Aronson, Eric, Dash.
Remember that not getting what you want is sometimes a wonderful stroke of luck. | Dalai Lama
All things come round to him who will but wait. | Henry Wadsworth Longfellow
You see, in life, lots of people know what to do, but few people actually do what they know. Knowing is not enough! You must take action. | Anthony Robbins
I always like to look on the optimistic side of life, but I am realistic enough to know that life is a complex matter. | Walt Disney
We all find ourselves in situations that at times seem hopeless. And, we all have the choice to do nothing or take action. | Catherine Pulsifer
Honesty is the rarest wealth anyone can possess, and yet all the honesty in the world ain't lawful tender for a loaf of bread. | Josh Billings
Oh, what a tangled web we weave, when first we practice to deceive! | Sir Walter Scott
Pretty much all the honest truth-telling there is in the world is done by children. | Oliver Wendell Holmes, Jr.
It is hard to believe that a man is telling the truth when you know that you would lie if you were in his place. | Henry Louis Mencken
Our lives improve only when we take chances - and the first and most difficult risk we can take is to be honest with ourselves. | Walter Anderson
Let us raise a standard to which the wise and honest can repair; the rest is in the hands of God. | George Washington
No legacy is so rich as honesty. | William Shakespeare
The best measure of a man's honesty isn't his income tax return. It's the zero adjust on his bathroom scale. | Arthur C. Clarke
One of the most basic core values is honesty. | Catherine Pulsifer
The foundation stones for a balanced success are honesty, character, integrity, faith, love and loyalty. | Zig Ziglar
Dishonesty will stare honesty out of countenance any day in the week, if there is anything to be got by it. | Charles Dickens
Honesty is the first chapter of the book of wisdom. | Thomas Jefferson
Integrity is telling myself the truth. And honesty is telling the truth to other people. | Spencer Johnson
Be prepared and be honest. | John Wooden
There is no twilight zone of honesty in business. A thing is right or it's wrong. It's black or it's white. | John F. Dodge
No man has a good enough memory to make a successful liar. | Abraham Lincoln
Level with your child by being honest. Nobody spots a phony quicker than a child. | Mary MacCracken
Be Silly. Be honest. Be kind. | Ralph Waldo Emerson
As I have said, the first thing is to be honest with yourself. | Nelson Mandela
Honesty is fearing a negative response and telling the truth anyway. | Michelle C. Ustaszeski
Concentration is my motto - first honesty, then industry, then concentration. | Andrew Carnegie
Honest disagreement is often a good sign of progress. | Gandhi
Doubt, indulged and cherished, is in danger of becoming denial; but if honest, and bent on thorough investigation, it may soon lead to full establishment of the truth. | Ambrose Bierce
