Alle prestaties, alle verdiende rijkdommen, hebben hun begin in een idee. | Napoleon Hill
Verwar nooit activiteit met prestatie. | John Wooden
Prestatie is het resultaat van werk dat ambitie realiseert. | Adam Ant
De meest gecompliceerde prestaties van denken zijn mogelijk zonder de hulp van bewustzijn. | Sigmund Freud
Grote prestaties worden meestal geboren uit grote offers, en zijn nooit het resultaat van egoïsme. | Napoleon Hill
De dood komt voor iedereen, maar grote prestaties bouwen een monument dat zal blijven bestaan totdat de zon koud wordt. | Ralph Waldo Emerson
Koester je visies en je dromen, want zij zijn de kinderen van je ziel; de blauwdrukken van je ultieme prestaties. | Napoleon Hill
Je moet de regels van het spel leren. En dan moet je beter spelen dan wie dan ook. | Albert Einstein
Ik ben blij dat ik het heb gedaan, deels omdat het de moeite waard was, maar vooral omdat ik het nooit meer hoef te doen. | Mark Twain
Het is niet de berg die we overwinnen, maar onszelf. | Edmund Hillary
Onze taak moet zijn om onszelf te bevrijden uit deze gevangenis door onze cirkels van mededogen te verbreden om alle levende wezens en de hele natuur in haar schoonheid te omarmen. | Albert Einstein
Hoge prestaties vinden altijd plaats binnen het kader van hoge verwachtingen. | Charles F. Kettering
Je kunt alles in het leven hebben wat je wilt, als je andere mensen gewoon helpt te krijgen wat zij willen. | Zig Ziglar
Grote inspanning komt vanzelf voort uit een geweldige houding. | Pat Riley
Je houding, niet je bekwaamheid, bepaalt je hoogte. | Zig Ziglar
Je kunt de houding aannemen dat er niets is wat je kunt doen, of je kunt de uitdaging zien als je oproep tot actie. | Catherine Pulsifer
Een optimist is een persoon die overal een groen licht ziet, terwijl de pessimist alleen het rode stoplicht ziet - de werkelijk wijze persoon is kleurenblind. | Albert Schweitzer
Positief denken laat je alles beter doen dan negatief denken. | Zig Ziglar
Je kunt niet beheersen wat er met je gebeurt, maar je kunt je houding bepalen ten opzichte van wat er met je gebeurt, en daarmee beheer je de verandering in plaats van dat de verandering jou beheerst. | Brian Tracy
Je kunt het doen als je gelooft dat je het kunt! | Napoleon Hill
Als je geen basisstandaard stelt voor wat je in het leven accepteert, zul je merken dat het gemakkelijk is om te vervallen in gedrag en attitudes of een levenskwaliteit die ver onder wat je verdient ligt. | Anthony Robbins
Als je iets niet leuk vindt, verander het dan. Als je het niet kunt veranderen, verander dan je houding. Niet klagen. | Maya Angelou
De persoon die positieve gedachten uitzendt, activeert de wereld om hem heen positief en trekt positieve resultaten naar zichzelf toe. | Norman Vincent Peale
Als je geluk afhangt van wat iemand anders doet, dan heb je inderdaad een probleem. | Richard Bach
Medelijden hebben met jezelf en je huidige toestand is niet alleen een verspilling van energie, maar de slechtste gewoonte die je mogelijk kunt hebben. | Dale Carnegie
Iedereen kan vrijwel alles met zichzelf doen wat hij echt wil en besluit te doen. We zijn tot grotere dingen in staat dan we ons realiseren. | Norman Vincent Peale
Er zijn twee primaire keuzes in het leven: de omstandigheden accepteren zoals ze zijn, of de verantwoordelijkheid accepteren om ze te veranderen. | Denis Waitley
Het leven is als het bespelen van een viool in het openbaar en het leren van het instrument terwijl je doorgaat. | Samuel Butler
De eerste stap om de dingen te krijgen die je uit het leven wilt, is dit: Bepaal wat je wilt. | Ben Stein
Het leven is wat er met je gebeurt terwijl je bezig bent andere plannen te maken. | John Lennon
Waar je eindigt, is niet het belangrijkste. Het is de weg die je neemt om daar te komen. De weg die je neemt, is wat je zult terugkijken en je leven noemen. | Tim Wiley
Er zijn maar twee manieren om je leven te leven. De ene is alsof niets een wonder is. De andere is alsof alles een wonder is. | Albert Einstein
De kwaliteit van iemands leven is recht evenredig met hun toewijding aan excellentie, ongeacht hun gekozen werkgebied. | Vince Lombardi
Het leven is slechts een spiegel, en wat je daarbuiten ziet, moet je eerst binnenin jezelf zien. | Wally Amos
Stop alles wat er is in je leven; je komt hier maar één keer langs! Ga zitten en denk na over wat je leuk vindt. Volg cursussen, lees boeken, vind je passie. | Catherine Pulsifer
Het grote geheim van het leven is dat er geen groot geheim is. Wat je doel ook is, je kunt het bereiken als je bereid bent om te werken. | Oprah Winfrey
Het leven moet geleefd worden en nieuwsgierigheid moet levend worden gehouden. Men moet nooit, om welke reden dan ook, zijn rug naar het leven keren. | Eleanor Roosevelt
Weten dat zelfs één leven gemakkelijker heeft kunnen ademen omdat jij hebt geleefd. Dit is succes hebben. | Ralph Waldo Emerson
De veldslagen van het leven gaan niet altijd naar de sterkere of snellere man. Maar vroeg of laat wint de man die denkt dat hij kan winnen. | Vince Lombardi
Wees geen toeschouwer, laat het leven niet aan je voorbijgaan. | Lou Holtz
Het leven is onbekend terrein. Het onthult zijn verhaal moment per moment. | Leo Buscaglia
Integriteit hebben betekent ook karakter hebben, wat ook de gemakkelijkste manier is om in conflict te komen met degenen die geen van beide hebben. | Byron Pulsifer
Heb de moed om nee te zeggen. Heb de moed om de waarheid onder ogen te zien. Doe het juiste omdat het juist is. Dit zijn de magische sleutels om je leven met integriteit te leven. | Mark Twain
Integriteit kan moeilijk te handhaven zijn in een wereld die van je vraagt te veranderen met de wind. | Byron Pulsifer
Integriteit is wat we doen, wat we zeggen, en wat we zeggen dat we doen. | Don Galer
Heb iedereen lief, vertrouw enkelen, doe niemand kwaad. | William Shakespeare
Integriteit hebben betekent dat je het niet met iedereen eens bent die je ontmoet, noch bezwijk je voor de druk om iets te zijn dat in direct conflict is met je kernwaarden. | Byron Pulsifer
Karakter staat hoger dan intellect. | Ralph Waldo Emerson
Mijn grootvader vertelde me ooit dat er twee soorten mensen zijn: degenen die werken en degenen die de eer opeisen. Hij vertelde me te proberen in de eerste groep te zitten; daar was minder concurrentie. | Indira Gandhi
Maar wat is geluk behalve de eenvoudige harmonie tussen een man en het leven dat hij leidt? | Albert Camus
Er is maar één hoek van het universum waarvan je zeker kunt zijn dat je die kunt verbeteren, en dat is jezelf. | Aldous Huxley
We mogen niet toestaan dat we worden zoals het systeem dat we bestrijden. | Bisschop Desmond Tutu
Integriteit zonder kennis is zwak en nutteloos, en kennis zonder integriteit is gevaarlijk en vreselijk. | Samuel Johnson
We moeten benadrukken dat persoonlijke integriteit net zo belangrijk is als executive vaardigheden in zakelijke transacties. | Russell E. Palmer
Het maakt niet uit welk tijdstip van de dag, wie er ook kijkt en wat de situatie ook is, persoonlijke integriteit neemt nooit een vakantie. | Byron Pulsifer
Wijsheid is weten wat te doen; deugd is het doen. | David Star Jordan
Karakter is het juiste doen wanneer niemand kijkt. Er zijn te veel mensen die denken dat het enige dat juist is, er mee wegkomen is, en het enige dat fout is, betrapt worden. | J.C. Watts
Je kunt niet altijd het juiste doen, maar je kunt altijd alles doen met integriteit. | Byron Pulsifer
Laat je moreel besef nooit voorkomen dat je doet wat juist is. | Isaac Asimov
Integriteit is de werkelijkheid conform onze woorden - met andere woorden, het nakomen van beloften en het voldoen aan verwachtingen. | Stephen R. Covey
Succes is niet de sleutel tot geluk. Geluk is de sleutel tot succes. Als je houdt van wat je doet, zul je succesvol zijn. | Albert Schweitzer
Je zult nooit gelukkig zijn als je blijft zoeken naar waaruit geluk bestaat. Je zult nooit leven als je blijft zoeken naar de betekenis van het leven. | Albert Camus
De Grondwet garandeert de Amerikaanse bevolking alleen het recht om geluk na te streven. Je moet het zelf vangen. | Benjamin Franklin
Geen enkele samenleving kan zeker bloeiend en gelukkig zijn, waarvan het grootste deel van de leden arm en ellendig is. | Adam Smith
Geluk is een gemoedstoestand, niet wat er in je portemonnee zit. | Byron Pulsifer
Als je gelukkig wilt zijn, wees dan gelukkig. | Leo Tolstoy
Laten we dankbaar zijn voor mensen die ons gelukkig maken; zij zijn de charmante tuiniers die onze ziel laten bloeien. | Marcel Proust
De man die alles wat leidt tot geluk van zichzelf laat afhangen, en niet van andere mannen, heeft het beste plan aangenomen om gelukkig te leven. | Plato
Geloof in jezelf! Heb vertrouwen in je capaciteiten! Zonder een bescheiden maar redelijke zelfverzekerdheid in je eigen krachten kun je niet succesvol of gelukkig zijn. | Norman Vincent Peale
Zonder enkele van de dingen die je wilt zijn, is een onmisbaar onderdeel van geluk. | Bertrand Russell
Maar wat is geluk behalve de eenvoudige harmonie tussen een man en het leven dat hij leidt? | Albert Camus
Actie brengt misschien niet altijd geluk; maar er is geen geluk zonder actie. | Benjamin Disraeli
De meeste mensen zouden liever zeker zijn dat ze ongelukkig zijn, dan het risico lopen gelukkig te zijn. | Robert Anthony
Als we maar zouden stoppen met proberen gelukkig te zijn, zouden we een vrij goede tijd kunnen hebben. | Edith Wharton
Wat kan worden toegevoegd aan het geluk van een man die gezond is, schuldenvrij is en een zuiver geweten heeft? | Adam Smith
Ervaring is niet wat er met een man gebeurt. Het is wat een man doet met wat er met hem gebeurt. | Aldous Leonard Huxley
Goed oordeel komt voort uit ervaring, en vaak komt ervaring voort uit slecht oordeel. | Rita Mae Brown
Een geest die wordt uitgerekt door een nieuwe ervaring, kan nooit terugkeren naar zijn oude dimensies. | Oliver Wendell Holmes, Jr.
Soms moet je veel dingen doen om te bepalen wat je niet wilt doen. Onderweg verzamel je veel ervaring. | Wally Amos
Een man kan zijn ervaring niet met pensioen sturen. Hij moet het gebruiken. Ervaring bereikt meer met minder energie en tijd. | Bernard M. Baruch
De respons op 'The Greatest Generation' en de boeken die daarop volgden, was een van de meest bevredigende ervaringen van mijn leven. | Tom Brokaw
Roem zal voorbijgaan en, zo lang, ik heb je gehad, roem. Als het voorbijgaat, heb ik altijd geweten dat het grillig was. Dus het is in ieder geval iets dat ik ervaar, maar dat is niet waar ik leef. | Marilyn Monroe
Ervaring is het kind van gedachte, en gedachte is het kind van actie. | Benjamin Disraeli
Ik heb liever veel talent en weinig ervaring dan veel ervaring en weinig talent. | John Wooden
Word nooit zo'n expert dat je stopt met het opdoen van expertise. Zie het leven als een continu leerproces. | Denis Waitley
Het mooiste wat we kunnen ervaren, is het mysterieuze. Het is de bron van alle ware kunst en wetenschap. | Albert Einstein
Ervaring is niet wat er met je gebeurt. Het is wat je doet met wat er met je gebeurt. | Aldous Huxley
Met elke ervaring schilder je alleen je eigen canvas, gedachte na gedachte, keuze na keuze. | Oprah Winfrey
Als vrouw heb ik altijd het gevoel gehad dat we beter worden naarmate we ouder worden. Je komt tot jezelf, door emotionele ervaringen en de eenvoudige wijsheid die met de leeftijd komt. | Linda Evans
We moeten niet terugkijken, tenzij het is om nuttige lessen te trekken uit fouten uit het verleden, en met het doel te profiteren van duur betaalde ervaring. | George Washington
Het pijnlijkste om te ervaren is niet nederlaag maar spijt. | Leo Buscaglia
Geen man was ooit zo volledig bedreven in het leiden van het leven, dat hij geen nieuwe informatie ontving door leeftijd en ervaring. | Jonathan Swift
Kunst is geen handwerk, het is de overdracht van gevoel dat de kunstenaar heeft ervaren. | Leo Tolstoy
Ik denk dat iedereen minstens één keer in zijn carrière nederlaag moet ervaren. Je leert er veel van. | Lou Holtz
Het geheim van een rijk leven is om meer begin dan eindes te hebben. | Dave Weinbaum
Alle moeilijke dingen hebben hun oorsprong in dat wat gemakkelijk is, en grote dingen in dat wat klein is. | Lao-Tzu
Bijna alles komt uit niets. | Henry F. Amiel
Noodzaak, die de moeder van uitvinding is. | Plato
De afstand is niets; alleen de eerste stap is moeilijk. | Marquise du Deffand
Beginnen is alleen moeilijk zonder enige actie. | Byron Pulsifer
Kleine kansen zijn vaak het begin van grote ondernemingen. | Demosthenes
Een moeilijke start maakt een goed einde. | John Heywood
Je hoeft niet geweldig te zijn om te beginnen, maar je moet beginnen om geweldig te zijn. | Joe Sabah
Veel mensen die naar een nieuw begin zoeken, hebben nooit met het verleden afgerekend. | Byron Pulsifer
Elke dag is een nieuw begin. Behandel het zo. Blijf weg van wat had kunnen zijn, en kijk naar wat kan zijn. | Marsha Petrie Sue
Dit is niet het einde. Het is zelfs niet het begin van het einde. Maar het is misschien wel het einde van het begin. | Winston Churchill
Wat je ook doet, of droomt dat je kunt doen, begin het. Moed heeft genialiteit en kracht en magie in zich. | Goethe
Door op verschillende kleine kansen te springen, kunnen we daar sneller komen dan door te wachten op één grote kans die voorbij komt. | Hugh Allen
Het is vaak moeilijk om onderscheid te maken tussen de harde klappen in het leven en die van de kans. | Frederick Phillips
Bekwaamheid is van weinig belang zonder kans. | Napoleon
Het geheim van succes in het leven is dat een man klaar is voor zijn kans als die komt. | Benjamin Disraeli
Kansen gaan nooit verloren; iemand zal degene nemen die je mist. |
Elke dag is een kans om een nieuw gelukkig einde te maken. |
Alles wat waardevol is in de menselijke samenleving hangt af van de mogelijkheid voor ontwikkeling die aan het individu wordt gegeven. | Albert Einstein
Een pessimist ziet de moeilijkheid in elke kans; een optimist ziet de kans in elke moeilijkheid. | Winston Churchill
Het leven is een geschenk, en het biedt ons het voorrecht, de kans en de verantwoordelijkheid om iets terug te geven door meer te worden. | Tony Robbins
De ladder van succes wordt het best beklommen door op de treden van kans te stappen. | Ayn Rand
Bekwaamheid is niets zonder kans. | Napoleon Bonaparte
Je grote kans kan precies zijn waar je nu bent. | Napoleon Hill
Kansen komen in mijn leven en ik reageer op diegenen die mij aanspreken. | Wally Amos
Mannen klagen nooit over de gemiste kansen om goed te doen, alleen over de gemiste kansen om slecht te zijn. | Grieks Proverb
Edison faalde 10.000 keer voordat hij het elektrische licht maakte. Wees niet ontmoedigd als je een paar keer faalt. | Napoleon Hill
Hoe lang moet je het proberen? Totdat. | Jim Rohn
Geduld en doorzettingsvermogen hebben een magisch effect waardoor moeilijkheden verdwijnen en obstakels verdwijnen. | John Quincy Adams
Door doorzettingsvermogen winnen veel mensen succes uit wat leek voorbestemd te zijn tot zekere mislukking. | Benjamin Disraeli
Probeer en faal, maar faal niet om te proberen. | Stephen Kaggwa
Als je succes in het leven wenst, maak dan doorzettingsvermogen je beste vriend, ervaring je wijze raadgever, voorzichtigheid je oudere broer en hoop je beschermende genie. | Joseph Addison
Grote werken worden uitgevoerd, niet door kracht, maar door doorzettingsvermogen. | Samuel Johnson
Ik denk niet dat er een andere eigenschap is die zo essentieel is voor succes van welke aard dan ook als de kwaliteit van doorzettingsvermogen. Het overwint bijna alles, zelfs de natuur. | John D. Rockefeller
Er is geen mislukking, behalve in het niet langer proberen. | Elbert Hubbard
Volharding en vastberadenheid alleen zijn almachtig. De slogan 'doorgaan' heeft en zal altijd de problemen van de mensheid oplossen. | Calvin Coolidge
Overwinning behoort toe aan de meest volhardende. | Napoleon Bonaparte
Volg je dromen van een betere wereld en blijf proberen, zelfs wanneer er weinig hoop lijkt te zijn, omdat het de juiste is om te doen. | Robert Alan
Genius is goddelijke volharding. Genie kan ik niet claimen, noch zelfs extra helderheid, maar volharding kunnen we allemaal hebben. | Woodrow Wilson
In de confrontatie tussen de stroom en de rots wint de stroom altijd - niet door kracht maar door volharding. | H. Jackson Brown
Volharding is meer overwinnend dan geweld en veel dingen die niet overwonnen kunnen worden wanneer ze samen zijn, geven zich over wanneer ze beetje bij beetje worden genomen. | Plutarch
Volharding is geen lange race; het zijn veel korte races de een na de ander. | Walter Elliot
De besten onder ons zijn niet meer begaafd dan de rest. Ze nemen gewoon elke dag kleine stapjes terwijl ze marcheren naar hun grootste leven. | Robin Sharma, The Greatness Guide
Verbind jezelf met mannen van goede kwaliteit als je je eigen reputatie waardeert. Het is beter alleen te zijn dan in slecht gezelschap. | George Washington
Kwaliteit is geen handeling, het is een gewoonte. | Aristotle
Als levensstandaard je belangrijkste doel is, verbetert de kwaliteit van leven bijna nooit, maar als kwaliteit van leven je nummer één doel is, verbetert je levensstandaard bijna altijd. | Zig Ziglar
Kwaliteit is een attribuut dat vaak wordt misbruikt door degenen die willen misleiden. | Byron Pulsifer
Kwaliteit betekent het goed doen wanneer niemand kijkt. | Henry Ford
Als je onzeker bent over de kwaliteit van je werk, moet je eerst begrijpen wat kwaliteit is. | Byron Pulsifer
Kwaliteit is nooit een ongeluk; het is altijd het resultaat van intelligente inspanning. | John Ruskin
Het is de kwaliteit van ons werk die God zal behagen, niet de hoeveelheid. | Mahatma Gandhi
De kwaliteit van iemands leven is recht evenredig met hun toewijding aan excellentie, ongeacht hun gekozen werkgebied. | Vince Lombardi
De kwaliteit, niet de levensduur, van iemands leven is wat belangrijk is. | Martin Luther King
Niemand kan ooit echt en blijvend succes behalen of 'rijk worden' in zaken door een conformist te zijn. | J. P. Getty
Om steile heuvels te beklimmen, is het eerst nodig om langzaam te beginnen. | William Shakespeare
Er is geen geheim over succes. Heb je ooit een succesvolle man gekend die je er niet over vertelde? | Kin Hubbard
Het geheim van het succes van een man ligt in zijn inzicht in de stemmingen van mensen en zijn tact in het omgaan met hen. | Josiah Gilbert Holland
Er is geen passie te vinden in het klein spelen - in het genoegen nemen met een leven dat minder is dan het leven waartoe je in staat bent. | Nelson Mandela
Doelen hebben een enorm verschil gemaakt in mijn leven. Ze hebben me in staat gesteld om succes te behalen en te bereiken wat ik eerder alleen maar had gedroomd of gewenst. | Catherine Pulsifer
Verwar beweging nooit met actie. | Ernest Hemmingway
Succes is krijgen wat je wilt. Geluk is willen wat je krijgt. | Dale Carnegie
In alles wat we doen, kunnen onze eigen gedachten ons helpen slagen, of ze kunnen ons helpen falen. Behoud een positieve houding. | Catherine Pulsifer
De meeste succesvolle mensen die ik heb gekend, zijn degenen die meer luisteren dan praten. | Bernard M. Baruch
Het succesvol maken van het werk dat je doet, is de beste stap naar het soort werk dat je wilt. | Bernard M. Baruch
Je kunt een man niet beoordelen op zijn mislukkingen. Je moet weten wat hij ermee heeft gedaan. Wat betekenden ze voor hem? Wat heeft hij eruit gehaald? | Orison Swett Marden
Als iemand vol vertrouwen voortgaat in de richting van zijn droom en probeert het leven te leven dat hij heeft voorgesteld, zal hij onverwacht succes ontmoeten in gewone uren. | Henry David Thoreau
Tijd is het meest waardevolle dat een man kan besteden. | Theophrastus
Je moet gewaarschuwd zijn tegen het laten glippen van de gouden uren; maar sommige ervan zijn alleen goud omdat we ze laten glippen. | James Matthew Barrie
Als je wilt dat werk goed wordt gedaan, kies dan een druk man, het andere type heeft geen tijd. | Elbert Hubbard
Tijd is de wijste raadgever van allemaal. | Pericles
Alles wat echt van ons is, is tijd; zelfs hij die niets anders heeft, heeft dat. | Baltasar Gracian
Tijd is de langste afstand tussen twee plaatsen. | Tennessee Williams
Niets is een verspilling van tijd als je de ervaring wijs gebruikt. | Rodin
We moeten tijd gebruiken als een gereedschap, niet als een kruk. | John F. Kennedy
Tijd en woorden kunnen niet worden teruggeroepen, zelfs als het maar gisteren was. | Jiddisch Proverb
Spijt van de dingen die we hebben gedaan, kan door de tijd worden getemperd; het is spijt van de dingen die we niet hebben gedaan die troosteloos is. | Sydney J. Harris
Maar wat een minuten! Tel ze door sensatie, en niet door kalenders, en elk moment is een dag. | Benjamin Disraeli
Tijd is de munt van je leven. Het is de enige munt die je hebt, en alleen jij kunt bepalen hoe deze wordt besteed. Wees voorzichtig zodat je niet laat dat andere mensen het voor je uitgeven. | Carl Sandburg
Je zult nooit tijd vinden voor iets. Als je tijd wilt, moet je het maken. | Charles Buxton
Beter drie uur te vroeg dan een minuut te laat. | William Shakespeare
Verloren tijd wordt nooit meer gevonden. | Benjamin Franklin
De uren van dwaasheid worden gemeten door de klok; maar van wijsheid, geen klok kan meten. | William Blake
Je wordt nooit moe tenzij je stopt en er tijd voor neemt. | Bob Hope
Tijd is de wijste raadgever. | Pericles
Ik heb tijd verspild, en nu verspil ik tijd. | William Shakespeare
Je grootste bezit is je verdienvermogen. Je grootste hulpbron is je tijd. | Brian Tracy
We moeten tijd wijs gebruiken en voor altijd beseffen dat het altijd het juiste moment is om het juiste te doen. | Nelson Mandela
Het leven wordt niet gemeten door het aantal ademhalingen dat we nemen, maar door de momenten die onze adem benemen. |
De beste manier om je dromen waar te maken, is wakker worden. | Paul Valery
Een van de dingen die ik op de harde manier heb geleerd, is dat het niet loont om ontmoedigd te raken. | Lucille Ball
Het belangrijkste is dit: in staat zijn om op elk moment op te offeren wat we zijn; voor wat we zouden kunnen worden. | Charles Dubois
Al het advies in de wereld zal je nooit helpen totdat je jezelf helpt. | Fred Van Amburgh
Overvloedig liefhebben is overvloedig leven, en voor altijd liefhebben is voor altijd leven. | Henry Drummond
Hoe je over een probleem denkt, is belangrijker dan het probleem zelf. Dus denk altijd positief. | Norman Vincent Peale
Vergeet de fouten uit het verleden. Vergeet mislukkingen. Vergeet alles behalve wat je nu gaat doen en doe het. | William Durant
Je kunt meer over een persoon te weten komen door wat hij zegt over anderen dan door wat anderen over hem zeggen. | Leo Aikman
Droom grote dromen, trek dan je overall aan en ga naar buiten en maak de dromen waar. | Fred Van Amburgh
Het mysterie van het leven is geen probleem om op te lossen; het is een realiteit om te ervaren. | Aart van der Leenw
Er is maar één hoek van het universum waarvan je zeker kunt zijn dat je die kunt verbeteren, en dat is jezelf. | Aldous Huxley
Het goede leven is een proces, geen toestand van zijn. Het is een richting, geen bestemming. | Carl Rogers
Wij zijn wat we herhaaldelijk doen. Excellentie dan, is geen handeling, maar een gewoonte. | Aristotle
Lees niet om te weerleggen en te weerleggen, niet om te geloven en voor vanzelfsprekend aan te nemen, niet om te praten en te discussiëren, maar om te wegen en te overwegen. | Francis Bacon
Een van de beste manieren om anderen te overtuigen is met je oren, door naar hen te luisteren. | Dean Rusk
Als je slechts één of twee vrienden hebt met wie je je hoogste aspiraties kunt delen, moet je jezelf rijkelijk gezegend beschouwen. | J. Donald Waters
In plaats van te wensen voor verandering, moet je eerst bereid zijn om te veranderen. | Catherine Pulsifer
Iedereen denkt eraan de wereld te veranderen, maar niemand denkt eraan zichzelf te veranderen. | Leo Tolstoy
Verandering is net zo onvermijdelijk als tijd, toch niets ontmoet meer weerstand. | Benjamin Disraeli
Alleen de wijste en domste mannen veranderen nooit. | Confucius
Stop nooit met leren, net zoals je nooit moet stoppen met veranderen en groeien in je leven - leren helpt je gemakkelijker aan te passen aan verandering. | Learning Quotes
Wat we denken, bepaalt wat er met ons gebeurt, dus als we ons leven willen veranderen, moeten we onze geest stretchen. | Wayne Dyer
Je kunt je bestemming niet van de ene op de andere dag veranderen, maar je kunt wel van de ene op de andere nacht je richting veranderen. | Jim Rohn
We zijn vaak teleurgesteld vanwege onze verwachtingen. Alleen wanneer je leert de omstandigheden te zien zoals ze werkelijk zijn, kun je de architect van verbetering worden. | Greg Henry Quinn
De enige man die ik ken die zich verstandig gedraagt, is mijn kleermaker; hij neemt mijn maten opnieuw op elke keer dat hij me ziet. De rest gaat verder met hun oude maten en verwacht dat ik erin pas. | George Bernard Shaw
Geen actie, geen verandering. Beperkte actie, beperkte verandering. Veel actie - Verandering vindt plaats. | Catherine Pulsifer
Je bent altijd vrij om van gedachten te veranderen en te kiezen voor een andere toekomst, of een ander verleden. | Richard Bach
Laat anderen je leven niet veranderen, wees je eigen veranderingsagent en implementeer de veranderingen die je wilt! En als er een onverwachte verandering in je leven plaatsvindt, vind dan het positieve erin. | Catherine Pulsifer
Verandering is onvermijdelijk. Verandering is constant. | Benjamin Disraeli
Als je je somber voelt, wanhoop dan niet. De zon heeft elke nacht een inzinking, maar komt elke ochtend weer op. Zoals ik het zie, als je de regenboog wilt, moet je de regen accepteren. | Dolly Parton
Getest worden is goed. Het uitgedaagde leven kan de beste therapeut zijn. | Gail Sheehy
Het zijn niet de bergen voor ons die ons uitputten; het is de kiezel in je schoen. | Mahummad Ali
Stroom mee met wat er ook gebeurt en laat je geest vrij zijn. Blijf gecentreerd door te accepteren wat je ook doet. Dit is het ultieme. | Chuang Tzu
Je bent misschien niet verantwoordelijk voor het neergeslagen worden, maar je bent zeker verantwoordelijk voor het weer opstaan. | Wally Amos
Ik probeer wijs te zijn wanneer ik niet vrolijk kan zijn, gemakkelijk wanneer ik niet blij kan zijn, tevreden met wat niet gerepareerd kan worden en geduldig wanneer er geen verhaal is. | Elizabeth Montagu
Slechte dingen zijn niet het ergste dat ons kan overkomen. "Niets" is het ergste dat ons kan overkomen! | Richard Bach
Het deel kan nooit goed zijn, tenzij het geheel goed is. | Plato
Bergen kunnen niet worden beklommen, behalve door kronkelende paden. | Johann Wolfgang Von Goethe
Onderschat nooit je probleem of je vermogen om ermee om te gaan. | Robert H. Schuller
Elke morgen heeft twee handvatten. We kunnen het vastpakken met het handvat van angst of het handvat van vertrouwen. | Henry Ward Beecher
Onmogelijkheden zijn slechts dingen die we nog niet hebben geleerd. | Charles W. Chesnutt
Als het lot ons een citroen geeft, laten we proberen limonade te maken. | Dale Carnegie
Je realiseert je misschien niet wanneer het gebeurt, maar een schop in de tanden kan het beste ter wereld voor je zijn. | Walt Disney
Grootheid ligt niet in sterk zijn, maar in het juiste gebruik van kracht. | Henry Ward Beecher
Wees niet bang voor grootsheid: sommigen worden groot geboren, sommigen bereiken grootheid, en sommigen hebben grootheid opgedrongen gekregen. | William Shakespeare
Grote prestaties worden meestal geboren uit grote offers, en zijn nooit het resultaat van egoïsme. | Napoleon Hill
Om echt groot te worden, moet men met mensen staan, niet boven hen. | Marleen Charles de Montesquieu
Een geweldige foto is er een die volledig uitdrukt wat men voelt, in de diepste zin, over wat er wordt gefotografeerd. | Ansel Adams
Hoogtes die door grote mannen werden bereikt en behouden, werden niet door een plotselinge vlucht verkregen, maar terwijl hun metgezellen sliepen, waren zij 's nachts naar boven aan het zwoegen. | Henry Wadsworth Longfellow
Het is onder de grootste tegenspoed dat het grootste potentieel voor het doen van goed bestaat, zowel voor zichzelf als voor anderen. | Dalai Lama
Een van de grootste ontdekkingen die een man doet, een van zijn grote verrassingen, is dat hij kan doen waarvan hij bang was dat hij het niet kon doen. | Henry Ford
Verantwoordelijkheid is de prijs van grootheid. | Winston Churchill
De meeste grote mensen hebben hun grootste succes behaald net één stap voorbij hun grootste mislukking. | Napoleon Hill
Geen groot man klaagt ooit over gebrek aan kansen. | Ralph Waldo Emerson
Voed je geest met grote gedachten; geloven in het heroïsche maakt helden. | Benjamin Disraeli
Grote inspanning komt vanzelf voort uit een geweldige houding. | Pat Riley
Riskeer meer dan anderen veilig vinden. Zorg meer dan anderen wijs vinden. Droom meer dan anderen praktisch vinden. Verwacht meer dan anderen mogelijk vinden. | Cadet Maxim
Doe elke dag één ding dat je bang maakt. | Eleanor Roosevelt
Vertrouw op je eigen instinct. Je fouten zijn misschien net zo goed van jezelf, in plaats van van iemand anders. | Billy Wilder
Leven met risico is van een klif springen en je vleugels bouwen terwijl je naar beneden gaat. | Ray Bradbury
Men ontdekt geen nieuwe landen zonder ermee in te stemmen het zicht op de kust voor een zeer lange tijd te verliezen. | André Gide
Pas op voor het missen van kansen; anders kan het op een dag helemaal te laat zijn. | Franz Liszt
Degenen die op het toeval vertrouwen, moeten de resultaten van het toeval accepteren. | Calvin Coolidge
Je zult je teen nooit stoten als je stil blijft staan. Hoe sneller je gaat, hoe meer kans je hebt om je teen te stoten, maar hoe meer kans je hebt om ergens te komen. | Charles F. Kettering
Veruit de beste prijs die het leven te bieden heeft, is de kans om hard te werken aan werk dat de moeite waard is om te doen. | Theodore Roosevelt
In mijn tijd hadden we geen zelfrespect, we hadden zelfrespect, en niet meer dan we hadden verdiend. | Jane Haddam
Hij die zichzelf respecteert, is veilig voor anderen; hij draagt een maliënkolder die niemand kan doorboren. | Henry Wadsworth Longfellow
De mensen die ik het meest respecteer, gedragen zich alsof ze onsterfelijk waren en alsof de samenleving eeuwig was. | E. M. Forster
Als je geen respect hebt voor je eigen waarden, hoe kun je dan waardig zijn voor respect van anderen. | Byron Pulsifer
Een man kan veel verdragen zolang hij zichzelf kan verdragen. | Axel Munthe
Respect is niet iets dat je kunt vragen, kopen of lenen. Respect is wat je verdient van elke persoon, ongeacht hun achtergrond of status. | Byron Pulsifer
Ik geef er de voorkeur aan trouw te zijn aan mezelf, zelfs met het risico de spot van anderen op te lopen, in plaats van vals te zijn en mijn eigen afschuw op te lopen. | Frederick Douglass
Als iemand van zichzelf vervreemd is, dan is hij ook van anderen vervreemd. Als iemand niet in contact is met zichzelf, kan hij anderen niet aanraken. | Anne Morrow Lindbergh
Ze kunnen ons zelfrespect niet wegnemen als we het niet aan hen geven. | Mahatma Gandhi
Elke persoon heeft een plaats in de wereld en is belangrijk in enig opzicht, of hij ervoor kiest om dat te zijn of niet. | Nathaniel Hawthorne
De tragedie is dat zoveel mensen zelfvertrouwen en zelfrespect overal zoeken, behalve in zichzelf, en daardoor falen in hun zoektocht. | Nathaniel Branden
Respect en vertrouwen kunnen nooit als vanzelfsprekend worden beschouwd. Het zijn eigenschappen die bewezen moeten worden. Ze zijn ook direct wederkerig aan het gedrag van anderen. | Elaine Sihera
Kijk naar alles alsof je het voor de eerste of laatste keer ziet. Dan zal je tijd op aarde gevuld zijn met glorie. | Betty Smith
Wijze mannen praten omdat ze iets te zeggen hebben; dwazen, omdat ze iets moeten zeggen. | Plato
Als je een man van waarde ziet, denk dan na over hoe je hem kunt navolgen. Als je iemand ziet die onwaardig is, onderzoek dan jezelf. | Confucius
Er is een roep in ieder van ons, een roep om iets te doen, hoe onpopulair of onopgemerkt ook, om de wereld een betere plek te maken. | Robert K. Cooper
Niets is voorbestemd: de obstakels van je verleden kunnen de poorten worden die leiden naar nieuwe beginnen. | Ralph Blum
Om in staat te zijn rijkdom weg te geven is verplicht als je ze wilt bezitten. Dit is de enige manier waarop je echt rijk zult zijn. | Mahummad Ali
Mensen nemen verschillende wegen op zoek naar vervulling en geluk. Alleen omdat ze niet op jouw weg zijn, betekent niet dat ze verdwaald zijn. | Dalai Lama
Ik heb veel meer respect voor de persoon met één enkel idee die daar aankomt dan voor de persoon met duizend ideeën die niets doet. | Thomas Edison
Werk en spel zijn woorden die worden gebruikt om dezelfde dingen te beschrijven onder verschillende omstandigheden. | Mark Twain
De man is het rijkst wiens plezier het goedkoopst is. | Henry David Thoreau
Je kunt geen handen schudden met een gebalde vuist. | Gandhi
Je moet van mensen houden en ze vertrouwen als je geen puinhoop van het leven wilt maken. | E.M. Forster
Je kunt niet vertrouwen zonder risico, maar je kunt ook niet leven in een cocon. | Byron Pulsifer
Je kunt worden misleid als je te veel vertrouwt, maar je zult in kwelling leven tenzij je genoeg vertrouwt. | Frank Crane
We worden allemaal dapper, vertrouwend en hebberig geboren, en de meesten van ons blijven hebberig. | Mignon McLaughlin
Wat is het aan politiek dat vertrouwen lijkt te negeren, behalve tijdens verkiezingstijd? | Byron Pulsifer
Ik moet de mensen volgen. Ben ik niet hun leider? | Benjamin Disraeli
Hij die niet kan gehoorzamen, kan niet bevelen. | Benjamin Franklin
Een goede leider kan zijn volgelingen niet te ver vooruit lopen. | Theodore Roosevelt
Leiderschap is de kunst om iemand anders iets te laten doen wat jij gedaan wilt hebben omdat hij het zelf wil doen. | Dwight Eisenhower
De sleutel tot succesvol leiderschap vandaag de dag is invloed, niet autoriteit. | Kenneth Blanchard
Er is een enorm aantal managers die met pensioen zijn gegaan op hun werk. | Peter F. Drucker
Een goede leider neemt iets meer dan zijn deel van de schuld, iets minder dan zijn deel van de eer. | Arnold H. Glasgow
Management is dingen goed doen; leiderschap is de juiste dingen doen. | Peter F. Drucker
Het is niet eerlijk om van anderen te vragen wat je zelf niet wilt doen. | Eleanor Roosevelt
Leiders creëren geen volgers, ze creëren meer leiders. | Tom Peters
Het grootste goed dat je voor een ander kunt doen, is niet alleen je rijkdom delen, maar hen hun eigen rijkdom onthullen. | Benjamin Disraeli
Je leidt niet door mensen op het hoofd te slaan - dat is mishandeling, geen leiderschap. | Dwight Eisenhower
Een goed doel van leiderschap is om degenen die het slecht doen te helpen om het goed te doen en om degenen die het goed doen, het nog beter te laten doen. | Jim Rohn
Uitstekende leiders gaan uit hun weg om het zelfvertrouwen van hun personeel te versterken. Als mensen in zichzelf geloven, is het verbazingwekkend wat ze kunnen bereiken. | Sam Walton
Te veel leiders handelen alsof de schapen... hun mensen... er zijn voor het welzijn van de herder, niet dat de herder verantwoordelijkheid heeft voor de schapen. | Kenneth Blanchard
De middelmatige leraar vertelt. De goede leraar legt uit. De superieure leraar demonstreert. De grote leraar inspireert. | William Arthur Ward
In het verleden was een leider een baas. Tegenwoordig moeten leiders partners zijn met hun mensen... ze kunnen niet langer uitsluitend leiden op basis van positie. | Kenneth Blanchard
Vriendelijkheid is de taal die de doven kunnen horen en de blinden kunnen zien. | Mark Twain
Je kunt nooit te vroeg vriendelijk zijn, want je weet nooit hoe snel het te laat zal zijn. | Ralph Waldo Emerson
Mijn religie is heel eenvoudig. Mijn religie is vriendelijkheid. | Dalai Lama
Als er enige vriendelijkheid is die ik kan tonen, of iets goeds dat ik kan doen voor een medemens, laat mij het nu doen, en niet uitstellen of verwaarlozen, want ik zal deze weg niet nogmaals passeren. | William Penn
Je hebt geen perfecte dag geleefd, tenzij je iets hebt gedaan voor iemand die nooit in staat zal zijn om je terug te betalen. | Ruth Smeltzer
Welke wijsheid kun je vinden die groter is dan vriendelijkheid? | Jean Jacques Rousseau
Zo schittert een goede daad in een vermoeide wereld. | William Shakespeare
Onze daden bepalen ons, net zoals wij onze daden bepalen. | George Eliot
Wees vriendelijk, want iedereen die je ontmoet, vecht een harde strijd. | Plato
Hij die wacht om in één keer veel goeds te doen, zal nooit iets doen. | Samuel Johnson
Vriendelijkheid is de zonneschijn waarin deugd groeit. | Robert Green Ingersoll
Richt altijd op volledige harmonie van gedachte en woord en daad. Richt altijd op het zuiveren van je gedachten en alles zal goed komen. | Mohandas Gandhi
Hij die je een vriendelijkheid heeft gedaan, zal eerder bereid zijn je nog een vriendelijkheid te doen, dan degene die jij zelf hebt verplicht. | Benjamin Franklin
Goedheid is ongewoon. Het flitst niet, het gloeit. | David Grayson
Laten we ons herinneren dat, zoals ons veel is gegeven, er veel van ons zal worden verwacht, en dat ware eerbetoon uit het hart komt net zo goed als uit de lippen, en zich toont in daden. | Theodore Roosevelt
Een vriendelijkheid die spontaan wordt aangeboden aan iemand die het nodig heeft, is dubbel bevredigend. | Jonathan Swift
Het is wanneer je jezelf geeft dat je echt geeft. | Kahil Gibran
Doe meer dan behoren: neem deel. Doe meer dan zorgen: help. Doe meer dan geloven: oefen. Doe meer dan eerlijk zijn: wees vriendelijk. Doe meer dan vergeven: vergeet. Doe meer dan dromen: werk. | William Arthur Ward
Vriendelijkheid is de gouden ketting waarmee de samenleving samen wordt gebonden. | Johann Wolfgang Von Goethe
De kleinste goede daad is beter dan de grootste goede bedoeling. | Japans Proverb
Er is geen betere oefening voor je hart dan naar beneden reiken en iemand op te helpen. | Bernard Meltzer
Vriendelijkheid kan zijn eigen motivatie worden. We worden vriendelijk door vriendelijk te zijn. | Eric Hoffer
Vriendelijkheid wekt vriendelijkheid op. | Grieks Proverb
Een vriendelijk hart is een bron van vreugde, die alles in zijn omgeving laat opbloeien in glimlachen. | Washington Irving
Wees vriendelijk tegen degenen die je ontmoet als je opstaat, je kunt ze weer tegenkomen als je valt. | Iers Proverb
Volledig bezit wordt alleen bewezen door te geven. Alles wat je niet kunt geven, bezit jou. | Andre Gide
Eén vriendelijk woord kan drie wintermaanden verwarmen. | Japans Proverb
Wanneer je iets moet doen, ook al kan het alleen aan jezelf bekend zijn, vraag jezelf dan hoe je zou handelen als de hele wereld naar je keek en handel dienovereenkomstig. | Thomas Jefferson
De meest aanhoudende en dringende vraag van het leven is: Wat doe je voor anderen? | Martin Luther King, Jr.
Waar er ook een mens is, is er een kans voor vriendelijkheid. | Seneca
Vriendelijke woorden kunnen kort en gemakkelijk te spreken zijn, maar hun echo's zijn echt eindeloos. | Moeder Teresa
In staat zijn om onder alle omstandigheden vijf dingen te beoefenen, vormt volmaakte deugd; deze vijf dingen zijn ernst, grootmoedigheid, oprechtheid, ernst en vriendelijkheid. | Confucius
Zullen we vanaf vanavond een nieuwe levensregel maken - probeer altijd een beetje vriendelijker te zijn dan nodig is. | Sir James M. Barrie
Goede daden veredelen ons, wij zijn de zonen van onze eigen daden. | Jean Paul Richter
Als je geen liefde in je hart hebt, heb je de ergste soort hartproblemen. | Bob Hope
Vriendelijke woorden zullen een ijzeren deur openen. | Turks Proverb
Vriendelijkheid cultiveren is een waardevol onderdeel van het leven. | Samuel Johnson
We kunnen boos zijn over onze leeftijd, of we kunnen dankbaar zijn dat we deze hebben bereikt. | William Arthur Ward
Als je niets minder accepteert dan je best, zul je verbaasd zijn over wat je in je leven kunt bereiken. | Vince Lombardi
Grote geesten hebben doelen; kleine geesten hebben wensen. Kleine geesten worden overweldigd door tegenslagen; grote geesten stijgen erboven. | Washington Irving
Er is geen man die kan voorkomen dat hij gemiddeld wordt geboren, maar er is geen man die gemeen moet zijn. | Satchel Paige
Geloof diep in je hart dat je voorbestemd bent om geweldige dingen te doen. | Joe Paterno
We moeten niet terugkijken, tenzij het is om nuttige lessen te trekken uit fouten uit het verleden, en met het doel te profiteren van duur betaalde ervaring. | George Washington
De aarde is volgepropt met de hemel. | Elizabeth Barrett Browning
Onthoud, de inspiratie volgt actie en niet andersom. | Aronson, Eric, Dash.
Onthoud dat het soms een prachtige meevaller is om niet te krijgen wat je wilt. | Dalai Lama
Alle dingen komen rond naar hem die maar wacht. | Henry Wadsworth Longfellow
Je ziet, in het leven weten veel mensen wat ze moeten doen, maar weinig mensen doen wat ze weten. Weten is niet genoeg! Je moet actie ondernemen. | Anthony Robbins
Ik kijk altijd graag naar de optimistische kant van het leven, maar ik ben realistisch genoeg om te weten dat het leven een complex iets is. | Walt Disney
We bevinden ons allemaal in situaties die soms hopeloos lijken. En we hebben allemaal de keuze om niets te doen of actie te ondernemen. | Catherine Pulsifer
Eerlijkheid is de zeldzaamste rijkdom die iemand kan bezitten, en toch is alle eerlijkheid in de wereld geen wettig betaalmiddel voor een brood. | Josh Billings
Oh, wat een ingewikkeld web we weven, wanneer we eerst oefenen om te bedriegen! | Sir Walter Scott
Vrijwel alle eerlijke waarheidsvertelling die er in de wereld is, wordt gedaan door kinderen. | Oliver Wendell Holmes, Jr.
Het is moeilijk te geloven dat een man de waarheid vertelt wanneer je weet dat je zou liegen als je in zijn plaats was. | Henry Louis Mencken
Onze levens verbeteren alleen als we risico's nemen - en het eerste en moeilijkste risico dat we kunnen nemen is om eerlijk te zijn tegen onszelf. | Walter Anderson
Laten we een standaard oprichten waarop de wijze en eerlijke zich kunnen herstellen; de rest ligt in de handen van God. | George Washington
Geen nalatenschap is zo rijk als eerlijkheid. | William Shakespeare
De beste maatstaf voor de eerlijkheid van een man is niet zijn belastingaangifte. Het is de nul-instelling op zijn weegschaal in de badkamer. | Arthur C. Clarke
Een van de meest basale kernwaarden is eerlijkheid. | Catherine Pulsifer
De fundamentele stenen voor een gebalanceerd succes zijn eerlijkheid, karakter, integriteit, geloof, liefde en loyaliteit. | Zig Ziglar
Oneerlijkheid zal eerlijkheid elke dag van de week uit het veld slaan, als er iets te halen valt. | Charles Dickens
Eerlijkheid is het eerste hoofdstuk van het boek van wijsheid. | Thomas Jefferson
Integriteit is mezelf de waarheid vertellen. En eerlijkheid is de waarheid aan andere mensen vertellen. | Spencer Johnson
Wees voorbereid en wees eerlijk. | John Wooden
Er is geen schemerzone van eerlijkheid in zaken. Een ding is juist of het is verkeerd. Het is zwart of het is wit. | John F. Dodge
Geen man heeft een goed genoeg geheugen om een succesvolle leugenaar te zijn. | Abraham Lincoln
Wees eerlijk tegen je kind. Niemand spot sneller een nepperd dan een kind. | Mary MacCracken
Wees gek. Wees eerlijk. Wees vriendelijk. | Ralph Waldo Emerson
Zoals ik al zei, het eerste is eerlijk zijn tegen jezelf. | Nelson Mandela
Eerlijkheid is bang zijn voor een negatieve reactie en toch de waarheid vertellen. | Michelle C. Ustaszeski
Concentratie is mijn motto - eerst eerlijkheid, dan industrie, dan concentratie. | Andrew Carnegie
Eerlijk meningsverschil is vaak een goed teken van vooruitgang. | Gandhi
Twijfel, gekoesterd en gekoesterd, loopt gevaar in ontkenning te veranderen; maar als het eerlijk is en gericht op grondig onderzoek, kan het snel leiden tot volledige vaststelling van de waarheid. | Ambrose Bierce
