Todas as conquistas, todas as riquezas adquiridas, têm seu início em uma ideia. | Napoleon Hill
Nunca confunda atividade com realização. | John Wooden
A realização resulta do trabalho realizando a ambição. | Adam Ant
As realizações mais complicadas do pensamento são possíveis sem a assistência da consciência. | Sigmund Freud
A grande realização geralmente nasce de grande sacrifício, e nunca é o resultado do egoísmo. | Napoleon Hill
A morte vem para todos, mas grandes realizações constroem um monumento que perdurará até o sol esfriar. | Ralph Waldo Emerson
Valorize suas visões e seus sonhos, pois eles são os filhos da sua alma; os projetos de suas realizações finais. | Napoleon Hill
Você tem que aprender as regras do jogo. E então você tem que jogar melhor do que qualquer outra pessoa. | Albert Einstein
Estou feliz por ter feito isso, em parte porque valeu a pena, mas principalmente porque nunca terei que fazer isso de novo. | Mark Twain
Não é a montanha que conquistamos, mas nós mesmos. | Edmund Hillary
Nosso trabalho deve ser libertar-nos desta prisão, ampliando nossos círculos de compaixão para abranger todas as criaturas vivas e toda a natureza em sua beleza. | Albert Einstein
A alta realização sempre ocorre no contexto de alta expectativa. | Charles F. Kettering
Você pode ter tudo o que deseja na vida, se ajudar outras pessoas a conseguirem o que elas querem. | Zig Ziglar
O grande esforço surge naturalmente de uma grande atitude. | Pat Riley
Sua atitude, não sua aptidão, determinará sua altitude. | Zig Ziglar
Você pode adotar a atitude de que não há nada que você possa fazer, ou pode ver o desafio como seu chamado à ação. | Catherine Pulsifer
Um otimista é uma pessoa que vê um sinal verde em todos os lugares, enquanto o pessimista vê apenas a luz vermelha de parada - A pessoa verdadeiramente sábia é daltônica. | Albert Schweitzer
O pensamento positivo permitirá que você faça tudo melhor do que o pensamento negativo. | Zig Ziglar
Você não pode controlar o que acontece com você, mas pode controlar sua atitude em relação ao que acontece com você, e nisso, você estará dominando a mudança em vez de permitir que ela o domine. | Brian Tracy
Você pode fazer isso se acreditar que pode! | Napoleon Hill
Se você não estabelecer um padrão básico para o que aceitará na vida, achará fácil escorregar para comportamentos e atitudes ou um nível de vida muito abaixo do que você merece. | Anthony Robbins
Se você não gosta de algo, mude-o. Se não pode mudá-lo, mude sua atitude. Não reclame. | Maya Angelou
A pessoa que emite pensamentos positivos ativa o mundo ao seu redor positivamente e atrai de volta para si resultados positivos. | Norman Vincent Peale
Se sua felicidade depende do que outra pessoa faz, acho que você tem um problema. | Richard Bach
Sentir pena de si mesmo e de sua condição atual não é apenas uma perda de energia, mas o pior hábito que você pode ter. | Dale Carnegie
Qualquer um pode fazer quase qualquer coisa consigo mesmo que realmente queira e decida fazer. Somos capazes de coisas maiores do que imaginamos. | Norman Vincent Peale
Há duas escolhas primárias na vida: aceitar as condições como existem ou aceitar a responsabilidade de mudá-las. | Denis Waitley
A vida é como tocar violino em público e aprender o instrumento à medida que se avança. | Samuel Butler
O primeiro passo para conseguir as coisas que você quer na vida é este: Decida o que você quer. | Ben Stein
A vida é o que acontece com você enquanto está ocupado fazendo outros planos. | John Lennon
Onde você acaba não é o mais importante. É o caminho que você percorre para chegar lá. O caminho que você percorre é o que você olhará para trás e chamará de sua vida. | Tim Wiley
Há apenas duas maneiras de viver sua vida. Uma é como se nada fosse um milagre. A outra é como se tudo fosse um milagre. | Albert Einstein
A qualidade de vida de uma pessoa é proporcional ao seu compromisso com a excelência, independentemente do campo de atuação escolhido. | Vince Lombardi
A vida é apenas um espelho, e o que você vê lá fora, você deve primeiro ver dentro de você. | Wally Amos
Coloque tudo o que há na sua vida; você só passa por este caminho uma vez! Sente-se e pense no que você gosta. Faça cursos, leia livros, encontre sua paixão. | Catherine Pulsifer
O grande segredo da vida é que não há grande segredo. Qualquer que seja o seu objetivo, você pode alcançá-lo se estiver disposto a trabalhar. | Oprah Winfrey
A vida deve ser vivida e a curiosidade mantida viva. Nunca se deve, por qualquer motivo, virar as costas para a vida. | Eleanor Roosevelt
Saber que ao menos uma vida respirou mais fácil porque você viveu. Isso é ter sucesso. | Ralph Waldo Emerson
As batalhas da vida nem sempre vão para o homem mais forte ou mais rápido. Mas mais cedo ou mais tarde o homem que vence é aquele que pensa que pode. | Vince Lombardi
Não seja um espectador, não deixe a vida passar por você. | Lou Holtz
A vida é um território desconhecido. Ela revela sua história um momento de cada vez. | Leo Buscaglia
Ter integridade é também ter caráter, que é a maneira mais fácil de entrar em conflito com aqueles que não possuem nenhum dos dois. | Byron Pulsifer
Tenha a coragem de dizer não. Tenha a coragem de enfrentar a verdade. Faça a coisa certa porque é a coisa certa a fazer. Estas são as chaves mágicas para viver sua vida com integridade. | Mark Twain
A integridade pode ser difícil de manter em um mundo que exige que você mude com o vento. | Byron Pulsifer
Integridade é o que fazemos, o que dizemos e o que dizemos que fazemos. | Don Galer
Ame a todos, confie em poucos, não faça mal a ninguém. | William Shakespeare
Ter integridade significa que você não concorda com todos que encontra, nem sucumbe à pressão para ser algo que está em conflito direto com sua ética central. | Byron Pulsifer
O caráter está acima do intelecto. | Ralph Waldo Emerson
Meu avô uma vez me disse que existem dois tipos de pessoas: aquelas que trabalham e aquelas que levam o crédito. Ele me disse para tentar estar no primeiro grupo; havia menos competição lá. | Indira Gandhi
Mas o que é a felicidade senão a simples harmonia entre um homem e a vida que ele leva? | Albert Camus
Há apenas um canto do universo que você pode ter certeza de melhorar, e esse é você mesmo. | Aldous Huxley
Não devemos nos permitir tornar-nos como o sistema que combatemos. | Bispo Desmond Tutu
Integridade sem conhecimento é fraca e inútil, e conhecimento sem integridade é perigoso e terrível. | Samuel Johnson
Precisamos enfatizar que a integridade pessoal é tão importante quanto a habilidade executiva nos negócios. | Russell E. Palmer
Não importa a hora do dia, não importa quem está assistindo e não importa a situação, a integridade pessoal não tira férias. | Byron Pulsifer
Sabedoria é saber o que fazer em seguida; virtude é fazer isso. | David Star Jordan
Caráter é fazer a coisa certa quando ninguém está olhando. Há muitas pessoas que pensam que a única coisa certa é passar despercebido, e a única coisa errada é ser pego. | J.C. Watts
Você nem sempre pode fazer a coisa certa, mas pode sempre fazer o que faz com integridade. | Byron Pulsifer
Nunca deixe seu senso de moral impedir você de fazer o que é certo. | Isaac Asimov
Integridade é conformar a realidade com nossas palavras - em outras palavras, manter promessas e cumprir expectativas. | Stephen R. Covey
Sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso. Se você ama o que está fazendo, você será bem-sucedido. | Albert Schweitzer
Você nunca será feliz se continuar procurando o que consiste a felicidade. Você nunca viverá se estiver procurando o significado da vida. | Albert Camus
A Constituição só garante ao povo americano o direito de buscar a felicidade. Você tem que alcançá-la sozinho. | Benjamin Franklin
Nenhuma sociedade pode certamente ser próspera e feliz, da qual a maior parte dos membros é pobre e miserável. | Adam Smith
A felicidade é um estado de espírito, não o que está na sua carteira. | Byron Pulsifer
Se você quer ser feliz, seja. | Leo Tolstoy
Sejamos gratos às pessoas que nos fazem felizes; elas são os jardineiros encantadores que fazem nossas almas florescerem. | Marcel Proust
O homem que faz tudo o que leva à felicidade depender de si mesmo, e não dos outros, adotou o melhor plano para viver feliz. | Platão
Acredite em você mesmo! Tenha fé nas suas habilidades! Sem uma confiança humilde mas razoável em seus próprios poderes, você não pode ser bem-sucedido ou feliz. | Norman Vincent Peale
Estar sem algumas das coisas que você quer é uma parte indispensável da felicidade. | Bertrand Russell
Mas o que é a felicidade senão a simples harmonia entre um homem e a vida que ele leva? | Albert Camus
A ação pode nem sempre trazer felicidade; mas não há felicidade sem ação. | Benjamin Disraeli
A maioria das pessoas preferiria ter certeza de que são miseráveis do que arriscar serem felizes. | Robert Anthony
Se apenas parássemos de tentar ser felizes, poderíamos ter um bom tempo. | Edith Wharton
O que pode ser adicionado à felicidade de um homem que está com saúde, sem dívidas e tem a consciência limpa? | Adam Smith
Experiência não é o que acontece com um homem. É o que um homem faz com o que lhe acontece. | Aldous Leonard Huxley
O bom julgamento vem da experiência, e muitas vezes a experiência vem do mau julgamento. | Rita Mae Brown
Uma mente que é esticada por uma nova experiência nunca volta às suas dimensões antigas. | Oliver Wendell Holmes, Jr.
Às vezes você tem que fazer muitas coisas para determinar o que não quer fazer. Ao longo do caminho, você adquire muita experiência. | Wally Amos
Um homem não pode aposentar sua experiência. Ele deve usá-la. A experiência realiza mais com menos energia e tempo. | Bernard M. Baruch
A resposta a 'A Maior Geração' e aos livros que se seguiram tem sido uma das experiências mais satisfatórias da minha vida. | Tom Brokaw
A fama passará e, assim, eu tive você, fama. Se ela passar, sempre soube que era inconstante. Então, pelo menos, é algo que experimentei, mas não é onde vivo. | Marilyn Monroe
Experiência é o filho do pensamento, e o pensamento é o filho da ação. | Benjamin Disraeli
Prefiro ter muito talento e pouca experiência do que muita experiência e pouco talento. | John Wooden
Nunca se torne tão especialista que pare de ganhar expertise. Encare a vida como uma experiência contínua de aprendizado. | Denis Waitley
A coisa mais bela que podemos experimentar é o misterioso. É a fonte de toda verdadeira arte e ciência. | Albert Einstein
Experiência não é o que acontece com você. É o que você faz com o que acontece com você. | Aldous Huxley
Com cada experiência, você sozinho está pintando sua própria tela, pensamento por pensamento, escolha por escolha. | Oprah Winfrey
Como mulher, sempre senti que à medida que envelhecemos, ficamos melhores. Você se reconcilia consigo mesma, através de experiências emocionais e da simples sabedoria que vem com a idade. | Linda Evans
Não devemos olhar para trás a menos que seja para tirar lições úteis dos erros passados e para o propósito de lucrar com a experiência comprada a caro preço. | George Washington
A coisa mais dolorosa de se experimentar não é a derrota, mas o arrependimento. | Leo Buscaglia
Nenhum homem foi tão completamente habilidoso na condução da vida a ponto de não receber novas informações da idade e da experiência. | Jonathan Swift
Arte não é um artesanato, é a transmissão do sentimento que o artista experimentou. | Leo Tolstoy
Acho que todos deveriam experimentar a derrota pelo menos uma vez durante sua carreira. Você aprende muito com isso. | Lou Holtz
O segredo para uma vida rica é ter mais começos do que finais. | Dave Weinbaum
Todas as coisas difíceis têm sua origem naquilo que é fácil, e grandes coisas naquilo que é pequeno. | Lao-Tzu
Quase tudo vem do nada. | Henry F. Amiel
Necessidade, que é a mãe da invenção. | Platão
A distância não é nada; é apenas o primeiro passo que é difícil. | Marquise du Deffand
Os começos são difíceis apenas sem nenhuma ação. | Byron Pulsifer
Pequenas oportunidades são frequentemente o início de grandes empreendimentos. | Demóstenes
Um começo difícil faz um bom final. | John Heywood
Você não precisa ser grande para começar, mas precisa começar para ser grande. | Joe Sabah
Muitas pessoas que buscam novos começos nunca terminaram com o passado. | Byron Pulsifer
Cada dia é um novo começo. Trate-o dessa forma. Fique longe do que poderia ter sido e olhe para o que pode ser. | Marsha Petrie Sue
Isso não é o fim. Não é nem o começo do fim. Mas é, talvez, o fim do começo. | Winston Churchill
Seja o que for que você faça, ou sonhe que pode, comece. A ousadia tem genialidade, poder e magia nela. | Goethe
Aproveitar várias pequenas oportunidades pode nos levar lá mais rapidamente do que esperar por uma grande oportunidade. | Hugh Allen
Freqüentemente é difícil distinguir entre os golpes duros da vida e os da oportunidade. | Frederick Phillips
Habilidade tem pouca importância sem oportunidade. | Napoleão
O segredo do sucesso na vida é estar preparado para a oportunidade quando ela vier. | Benjamin Disraeli
As oportunidades nunca se perdem; alguém aproveitará a que você perdeu. |
Cada dia é uma oportunidade de fazer um novo final feliz. |
Tudo o que é valioso na sociedade humana depende da oportunidade de desenvolvimento concedida ao indivíduo. | Albert Einstein
Um pessimista vê a dificuldade em cada oportunidade; um otimista vê a oportunidade em cada dificuldade. | Winston Churchill
A vida é um presente, e ela nos oferece o privilégio, oportunidade e responsabilidade de retribuir tornando-nos mais. | Tony Robbins
A escada do sucesso é melhor escalada pisando nos degraus da oportunidade. | Ayn Rand
Habilidade não é nada sem oportunidade. | Napoleão Bonaparte
Sua grande oportunidade pode estar exatamente onde você está agora. | Napoleon Hill
As oportunidades entram na minha vida e eu respondo àquelas que me atraem. | Wally Amos
Os homens nunca lamentam as oportunidades perdidas para fazer o bem, apenas as oportunidades para fazer o mal. | Provérbio Grego
Edison falhou 10.000 vezes antes de inventar a lâmpada elétrica. Não desanime se falhar algumas vezes. | Napoleon Hill
Por quanto tempo você deve tentar? Até. | Jim Rohn
Paciência e perseverança têm um efeito mágico diante do qual as dificuldades desaparecem e os obstáculos somem. | John Quincy Adams
Através da perseverança, muitas pessoas alcançam o sucesso a partir do que parecia ser um fracasso certo. | Benjamin Disraeli
Tente e falhe, mas não falhe em tentar. | Stephen Kaggwa
Se você deseja sucesso na vida, faça da perseverança sua amiga do peito, da experiência seu sábio conselheiro, da cautela seu irmão mais velho e da esperança seu gênio guardião. | Joseph Addison
Grandes obras são realizadas, não pela força, mas pela perseverança. | Samuel Johnson
Não acho que haja outra qualidade tão essencial para o sucesso de qualquer tipo quanto a qualidade da perseverança. Ela supera quase tudo, até mesmo a natureza. | John D. Rockefeller
Não há fracasso exceto em não tentar mais. | Elbert Hubbard
Persistência e determinação sozinhas são onipotentes. O slogan continue em frente resolveu e sempre resolverá os problemas da raça humana. | Calvin Coolidge
A vitória pertence ao mais perseverante. | Napoleão Bonaparte
Siga seus sonhos de um mundo melhor e continue tentando, mesmo quando parecer haver pouca esperança, porque é a coisa certa a fazer. | Robert Alan
Genialidade é perseverança divina. Genialidade eu não posso reivindicar nem mesmo um brilho extra, mas perseverança todos podem ter. | Woodrow Wilson
Na confrontação entre o riacho e a rocha, o riacho sempre vence - não pela força, mas pela perseverança. | H. Jackson Brown
A perseverança é mais eficaz do que a violência e muitas coisas que não podem ser superadas quando estão juntas se rendem quando tomadas pouco a pouco. | Plutarco
Perseverança não é uma corrida longa; é muitas corridas curtas uma após a outra. | Walter Elliot
Os melhores entre nós não são mais talentosos do que os outros. Eles apenas dão pequenos passos todos os dias enquanto marcham em direção à sua maior vida. | Robin Sharma, The Greatness Guide
Associe-se a homens de boa qualidade se estima sua própria reputação. É melhor estar sozinho do que em má companhia. | George Washington
Qualidade não é um ato, é um hábito. | Aristóteles
Se o padrão de vida é seu principal objetivo, a qualidade de vida quase nunca melhora, mas se a qualidade de vida é seu objetivo número um, seu padrão de vida quase sempre melhora. | Zig Ziglar
Qualidade é um atributo bastante comumente abusado por aqueles que buscam enganar. | Byron Pulsifer
Qualidade é fazer certo quando ninguém está olhando. | Henry Ford
Se você está inseguro sobre a qualidade do seu trabalho, precisa primeiro entender o que é qualidade. | Byron Pulsifer
Qualidade nunca é um acidente; é sempre o resultado de esforço inteligente. | John Ruskin
É a qualidade do nosso trabalho que agradará a Deus, não a quantidade. | Mahatma Gandhi
A qualidade de vida de uma pessoa é proporcional ao seu compromisso com a excelência, independentemente do campo de atuação escolhido. | Vince Lombardi
A qualidade, não a longevidade, da vida de uma pessoa é o que é importante. | Martin Luther King
Ninguém pode alcançar qualquer sucesso real e duradouro ou 'ficar rico' nos negócios sendo um conformista. | J. P. Getty
Subir colinas íngremes requer um ritmo lento no início. | William Shakespeare
Não há segredo sobre o sucesso. Você já conheceu um homem bem-sucedido que não lhe contou sobre isso? | Kin Hubbard
O segredo do sucesso de um homem reside em sua percepção dos humores das pessoas e em seu tato ao lidar com elas. | Josiah Gilbert Holland
Não há paixão a ser encontrada jogando pequeno - conformando-se com uma vida que é menos do que aquela que você é capaz de viver. | Nelson Mandela
Objetivos fizeram uma tremenda diferença na minha vida. Eles me permitiram alcançar o sucesso e realizar o que antes eu só tinha sonhado ou desejado. | Catherine Pulsifer
Nunca confunda movimento com ação. | Ernest Hemingway
Sucesso é conseguir o que você quer. Felicidade é querer o que você consegue. | Dale Carnegie
Em tudo o que fazemos, nossos próprios pensamentos podem nos ajudar a ter sucesso ou podem nos ajudar a falhar. Mantenha uma atitude positiva. | Catherine Pulsifer
A maioria das pessoas bem-sucedidas que conheci são aquelas que escutam mais do que falam. | Bernard M. Baruch
Fazer sucesso no trabalho em mãos é o melhor passo em direção ao tipo que você deseja. | Bernard M. Baruch
Você não pode medir um homem por suas falhas. Você deve saber o uso que ele faz delas. O que elas significaram para ele. O que ele tirou delas. | Orison Swett Marden
Se alguém avança confiante na direção de seu sonho e se esforça para viver a vida que imaginou, encontrará um sucesso inesperado em horas comuns. | Henry David Thoreau
O tempo é a coisa mais valiosa que um homem pode gastar. | Theophrastus
Você deve ter sido avisado contra deixar as horas douradas passarem; mas algumas delas são douradas apenas porque as deixamos passar. | James Matthew Barrie
Se você quer um trabalho bem feito, escolha um homem ocupado; o outro tipo não tem tempo. | Elbert Hubbard
O tempo é o conselheiro mais sábio de todos. | Péricles
Tudo o que realmente nos pertence é o tempo; mesmo quem não tem mais nada tem isso. | Baltasar Gracián
O tempo é a distância mais longa entre dois lugares. | Tennessee Williams
Nada é uma perda de tempo se você usa a experiência sabiamente. | Rodin
Devemos usar o tempo como uma ferramenta, não como uma muleta. | John F. Kennedy
Tempo e palavras não podem ser lembrados, mesmo que tenha sido ontem. | Provérbio Iídiche
O arrependimento pelas coisas que fizemos pode ser atenuado pelo tempo; é o arrependimento pelas coisas que não fizemos que é inconsolável. | Sydney J. Harris
Mas que minutos! Conte-os por sensação, e não por calendários, e cada momento é um dia. | Benjamin Disraeli
O tempo é a moeda da sua vida. É a única moeda que você tem, e só você pode determinar como será gasta. Cuidado para não deixar que outras pessoas a gastem por você. | Carl Sandburg
Você nunca encontrará tempo para nada. Se você quer tempo, deve fazê-lo. | Charles Buxton
Melhor três horas cedo demais do que um minuto tarde demais. | William Shakespeare
O tempo perdido nunca é encontrado novamente. | Benjamin Franklin
As horas de tolice são medidas pelo relógio; mas de sabedoria, nenhum relógio pode medir. | William Blake
Você nunca se cansa a menos que pare e tire um tempo para isso. | Bob Hope
O tempo é o conselheiro mais sábio. | Péricles
Eu desperdicei tempo, e agora o tempo me desperdiça. | William Shakespeare
Seu maior patrimônio é sua capacidade de ganho. Seu maior recurso é seu tempo. | Brian Tracy
Devemos usar o tempo sabiamente e sempre perceber que o tempo está sempre maduro para fazer o que é certo. | Nelson Mandela
A vida não é medida pelo número de respirações que damos, mas pelos momentos que tiram nosso fôlego. |
A melhor maneira de realizar seus sonhos é acordar. | Paul Valery
Uma das coisas que aprendi da maneira mais difícil foi que não vale a pena desanimar. | Lucille Ball
A coisa importante é esta: ser capaz a qualquer momento de sacrificar o que somos; pelo que podemos nos tornar. | Charles Dubois
Todo o conselho do mundo nunca ajudará você até que você ajude a si mesmo. | Fred Van Amburgh
Amar abundantemente é viver abundantemente, e amar para sempre é viver para sempre. | Henry Drummond
Como você pensa sobre um problema é mais importante do que o problema em si. Então, sempre pense positivamente. | Norman Vincent Peale
Esqueça os erros do passado. Esqueça as falhas. Esqueça tudo, exceto o que você vai fazer agora e faça. | William Durant
Você pode saber mais sobre uma pessoa pelo que ela diz sobre os outros do que pelo que os outros dizem sobre ela. | Leo Aikman
Sonhe grandes sonhos, então coloque seu macacão e vá fazer os sonhos se tornarem realidade. | Fred Van Amburgh
O mistério da vida não é um problema a ser resolvido; é uma realidade a ser experimentada. | Aart van der Leenw
Há apenas um canto do universo que você pode ter certeza de melhorar, e esse é você mesmo. | Aldous Huxley
A vida boa é um processo, não um estado de ser. É uma direção, não um destino. | Carl Rogers
Somos o que repetidamente fazemos. A excelência, então, não é um ato, mas um hábito. | Aristóteles
Leia não para contradizer e refutar, não para acreditar e tomar como certo, não para encontrar conversa e discurso, mas para pesar e considerar. | Francis Bacon
Uma das melhores maneiras de persuadir os outros é com seus ouvidos, ouvindo-os. | Dean Rusk
Se você tem apenas um ou dois amigos com quem pode compartilhar suas maiores aspirações, deve se considerar ricamente abençoado. | J. Donald Waters
Em vez de desejar a mudança, você deve primeiro estar preparado para mudar. | Catherine Pulsifer
Todos pensam em mudar o mundo, mas ninguém pensa em mudar a si mesmo. | Leo Tolstoy
A mudança é tão inexorável quanto o tempo, mas nada encontra mais resistência. | Benjamin Disraeli
Apenas os mais sábios e os mais tolos dos homens nunca mudam. | Confúcio
Nunca pare de aprender, assim como nunca pare de mudar e crescer em sua vida - aprender ajuda você a se adaptar à mudança mais facilmente. | Citações de Aprendizado
O que pensamos determina o que acontece conosco, então se queremos mudar nossas vidas, precisamos expandir nossas mentes. | Wayne Dyer
Você não pode mudar seu destino da noite para o dia, mas pode mudar sua direção da noite para o dia. | Jim Rohn
Frequentemente ficamos desapontados por causa de nossas expectativas. Só quando você aprende a ver as circunstâncias como realmente são, pode se tornar o arquiteto da melhoria. | Greg Henry Quinn
O único homem que conheço que se comporta de maneira sensata é meu alfaiate; ele tira minhas medidas de novo a cada vez que me vê. Os outros continuam com suas medidas antigas e esperam que eu me ajuste a elas. | George Bernard Shaw
Sem ação, sem mudança. Ação limitada, mudança limitada. Muita ação - A mudança ocorre. | Catherine Pulsifer
Você sempre é livre para mudar de ideia e escolher um futuro diferente, ou um passado diferente. | Richard Bach
Não deixe que outros mudem sua vida, seja seu próprio agente de mudança e implemente as mudanças que deseja! E se uma mudança inesperada ocorrer em sua vida, encontre o positivo nela. | Catherine Pulsifer
A mudança é inevitável. A mudança é constante. | Benjamin Disraeli
Se você está se sentindo para baixo, não desespere. O sol tem um feitiço de afundamento todas as noites, mas ele volta a nascer todas as manhãs. Do jeito que vejo, se você quer o arco-íris, tem que aguentar a chuva. | Dolly Parton
Ser testado é bom. A vida desafiada pode ser o melhor terapeuta. | Gail Sheehy
Não são as montanhas à frente que desgastam você; é o pedregulho no seu sapato. | Mahummad Ali
Flua com o que quer que esteja acontecendo e deixe sua mente estar livre. Mantenha-se centrado aceitando o que quer que esteja fazendo. Isso é o máximo. | Chuang Tzu
Você pode não ser responsável por ser derrubado, mas certamente é responsável por se levantar. | Wally Amos
Esforço-me para ser sábio quando não posso ser alegre, fácil quando não posso ser feliz, contente com o que não pode ser consertado e paciente quando não há recurso. | Elizabeth Montagu
Coisas ruins não são as piores coisas que podem nos acontecer. "Nada" é a pior coisa que pode nos acontecer! | Richard Bach
A parte nunca pode estar bem a menos que o todo esteja bem. | Platão
Montanhas não podem ser superadas exceto por caminhos sinuosos. | Johann Wolfgang Von Goethe
Nunca subestime seu problema ou sua capacidade de lidar com ele. | Robert H. Schuller
Cada amanhã tem duas alças. Podemos segurá-lo com a alça da ansiedade ou com a alça da fé. | Henry Ward Beecher
Impossibilidades são apenas coisas que ainda não aprendemos. | Charles W. Chesnutt
Quando o destino nos entrega um limão, vamos tentar fazer uma limonada. | Dale Carnegie
Você pode não perceber quando isso acontece, mas um chute nos dentes pode ser a melhor coisa do mundo para você. | Walt Disney
A grandeza não está em ser forte, mas no uso correto da força. | Henry Ward Beecher
Não tenha medo da grandeza: alguns nascem grandes, alguns alcançam a grandeza e alguns têm a grandeza imposta a eles. | William Shakespeare
A grande realização geralmente nasce de grande sacrifício, e nunca é o resultado do egoísmo. | Napoleon Hill
Para se tornar verdadeiramente grande, é preciso estar com as pessoas, não acima delas. | Marleen Charles de Montesquieu
Uma grande fotografia é aquela que expressa plenamente o que se sente, no sentido mais profundo, sobre o que está sendo fotografado. | Ansel Adams
Alturas alcançadas e mantidas por grandes homens não foram obtidas por um voo repentino, mas, enquanto seus companheiros dormiam, eles estavam trabalhando arduamente durante a noite. | Henry Wadsworth Longfellow
É sob a maior adversidade que existe o maior potencial para fazer o bem, tanto para si mesmo quanto para os outros. | Dalai Lama
Uma das maiores descobertas de um homem, uma de suas grandes surpresas, é descobrir que pode fazer o que temia não poder fazer. | Henry Ford
A responsabilidade é o preço da grandeza. | Winston Churchill
A maioria das grandes pessoas alcançou seu maior sucesso um passo além de seu maior fracasso. | Napoleon Hill
Nenhum grande homem jamais se queixa da falta de oportunidade. | Ralph Waldo Emerson
Nutra sua mente com grandes pensamentos; acreditar no heroico faz heróis. | Benjamin Disraeli
O grande esforço surge naturalmente de uma grande atitude. | Pat Riley
Arrisque mais do que os outros pensam ser seguro. Cuide mais do que os outros pensam ser sensato. Sonhe mais do que os outros pensam ser prático. Espere mais do que os outros pensam ser possível. | Cadet Maxim
Faça uma coisa todos os dias que te assusta. | Eleanor Roosevelt
Confie em seu próprio instinto. Seus erros podem muito bem ser seus, em vez dos de outra pessoa. | Billy Wilder
Viver em risco é pular do penhasco e construir suas asas no caminho para baixo. | Ray Bradbury
Não se descobrem novas terras sem consentir em perder de vista a costa por um longo tempo. | André Gide
Cuidado para não perder oportunidades; caso contrário, pode ser tarde demais um dia. | Franz Liszt
Aqueles que confiam na sorte devem aceitar os resultados da sorte. | Calvin Coolidge
Você nunca tropeça se estiver parado. Quanto mais rápido você vai, maior é a chance de tropeçar, mas maior é a chance de chegar a algum lugar. | Charles F. Kettering
De longe, o melhor prêmio que a vida tem a oferecer é a chance de trabalhar duro em um trabalho que vale a pena. | Theodore Roosevelt
No meu tempo, não tínhamos autoestima, tínhamos auto-respeito, e não mais do que merecíamos. | Jane Haddam
Aquele que respeita a si mesmo está seguro dos outros; ele veste uma armadura que ninguém pode perfurar. | Henry Wadsworth Longfellow
As pessoas que mais respeito se comportam como se fossem imortais e como se a sociedade fosse eterna. | E. M. Forster
Se você não tem respeito pelos seus próprios valores, como pode ser digno de respeito dos outros. | Byron Pulsifer
Um homem pode suportar muito desde que possa suportar a si mesmo. | Axel Munthe
Respeito não é algo que você pode pedir, comprar ou pegar emprestado. Respeito é o que você ganha de cada pessoa, independentemente de seu histórico ou status. | Byron Pulsifer
Prefiro ser fiel a mim mesmo, mesmo correndo o risco de incorrer no ridículo dos outros, do que ser falso e incorrer na minha própria aversão. | Frederick Douglass
Se alguém está afastado de si mesmo, então também está afastado dos outros. Se alguém está fora de contato consigo mesmo, então não pode tocar os outros. | Anne Morrow Lindbergh
Eles não podem tirar nosso respeito próprio se não o dermos a eles. | Mahatma Gandhi
Cada indivíduo tem um lugar a preencher no mundo e é importante em algum aspecto, quer ele escolha ser ou não. | Nathaniel Hawthorne
A tragédia é que tantas pessoas procuram autoconfiança e respeito próprio em todos os lugares, exceto dentro de si mesmas, e assim falham em sua busca. | Nathaniel Branden
Respeito e confiança nunca podem ser dados como certos. Eles são atributos que precisam ser comprovados. Eles também são diretamente recíprocos ao comportamento dos outros. | Elaine Sihera
Olhe para tudo como se estivesse vendo pela primeira ou última vez. Então seu tempo na terra estará cheio de glória. | Betty Smith
Homens sábios falam porque têm algo a dizer; tolos, porque têm que dizer algo. | Platão
Quando você vê um homem de valor, pense em como pode emulá-lo. Quando você vê um que é indigno, examine-se. | Confúcio
Há um chamado dentro de cada um de nós, um chamado para fazer algo, por mais impopular ou despercebido, para tornar o mundo um lugar melhor. | Robert K. Cooper
Nada está predestinado: Os obstáculos do seu passado podem se tornar os portões que levam a novos começos. | Ralph Blum
Ser capaz de doar riquezas é obrigatório se você deseja possuí-las. Esta é a única maneira de você ser realmente rico. | Mahummad Ali
As pessoas tomam caminhos diferentes em busca de realização e felicidade. Só porque não estão na sua estrada não significa que se perderam. | Dalai Lama
Tenho muito mais respeito pela pessoa com uma única ideia que chega lá do que pela pessoa com mil ideias que não faz nada. | Thomas Edison
Trabalho e lazer são palavras usadas para descrever a mesma coisa em condições diferentes. | Mark Twain
O homem é mais rico cujos prazeres são mais baratos. | Henry David Thoreau
Você não pode apertar as mãos com um punho cerrado. | Gandhi
É preciso gostar das pessoas e confiar nelas se não quiser fazer um estrago na vida. | E.M. Forster
Você não pode confiar sem risco, mas também não pode viver em um casulo. | Byron Pulsifer
Você pode ser enganado se confiar demais, mas viverá em tormento a menos que confie o suficiente. | Frank Crane
Todos nós nascemos corajosos, confiantes e gananciosos, e a maioria de nós permanece gananciosa. | Mignon McLaughlin
O que há na política que parece ignorar a confiança, exceto na época das eleições? | Byron Pulsifer
Eu devo seguir o povo. Não sou o líder deles? | Benjamin Disraeli
Aquele que não pode obedecer, não pode comandar. | Benjamin Franklin
Um bom líder não pode se distanciar muito de seus seguidores. | Theodore Roosevelt
Liderança é a arte de fazer com que outra pessoa faça algo que você quer porque ela quer fazer. | Dwight Eisenhower
A chave para a liderança bem-sucedida hoje é influência, não autoridade. | Kenneth Blanchard
Há um número enorme de gerentes que se aposentaram no trabalho. | Peter F. Drucker
Um bom líder assume um pouco mais do que sua parte da culpa, um pouco menos do que sua parte do crédito. | Arnold H. Glasgow
Gerenciamento é fazer as coisas direito; liderança é fazer as coisas certas. | Peter F. Drucker
Não é justo pedir aos outros o que você não está disposto a fazer sozinho. | Eleanor Roosevelt
Líderes não criam seguidores, eles criam mais líderes. | Tom Peters
O maior bem que você pode fazer por outro não é apenas compartilhar suas riquezas, mas revelá-las a elas mesmas. | Benjamin Disraeli
Você não lidera batendo nas pessoas - isso é agressão, não liderança. | Dwight Eisenhower
Um bom objetivo da liderança é ajudar aqueles que estão indo mal a se saírem bem e ajudar aqueles que estão indo bem a se saírem ainda melhor. | Jim Rohn
Líderes extraordinários fazem questão de aumentar a autoestima de seu pessoal. Se as pessoas acreditarem em si mesmas, é incrível o que podem alcançar. | Sam Walton
Muitos líderes agem como se as ovelhas... seu pessoal... estivessem lá para o benefício do pastor, não que o pastor tem responsabilidade pelas ovelhas. | Kenneth Blanchard
O professor medíocre conta. O bom professor explica. O professor superior demonstra. O grande professor inspira. | William Arthur Ward
No passado, um líder era um chefe. Os líderes de hoje devem ser parceiros com seu pessoal... eles não podem mais liderar apenas com base no poder posicional. | Kenneth Blanchard
A gentileza é a linguagem que os surdos podem ouvir e os cegos podem ver. | Mark Twain
Você não pode fazer uma gentileza cedo demais, pois nunca sabe quão cedo será tarde demais. | Ralph Waldo Emerson
Minha religião é muito simples. Minha religião é a bondade. | Dalai Lama
Se houver alguma gentileza que eu possa mostrar, ou qualquer coisa boa que eu possa fazer a qualquer ser humano, que eu o faça agora, e não adie ou negligencie, pois não passarei por este caminho novamente. | William Penn
Você não viveu um dia perfeito, a menos que tenha feito algo por alguém que nunca será capaz de retribuir. | Ruth Smeltzer
Que sabedoria você pode encontrar que seja maior do que a bondade? | Jean Jacques Rousseau
Assim brilha uma boa ação em um mundo cansado. | William Shakespeare
Nossos atos nos determinam, tanto quanto nós determinamos nossos atos. | George Eliot
Seja gentil, pois todos que você encontra estão lutando uma batalha difícil. | Platão
Aquele que espera fazer muito bem de uma só vez, nunca fará nada. | Samuel Johnson
A bondade é a luz do sol em que a virtude cresce. | Robert Green Ingersoll
Sempre busque a completa harmonia de pensamento, palavra e ação. Sempre busque purificar seus pensamentos e tudo ficará bem. | Mohandas Gandhi
Aquele que lhe fez uma gentileza estará mais pronto para lhe fazer outra, do que aquele a quem você mesmo obrigou. | Benjamin Franklin
A bondade é tranquila. Ela não brilha, ela resplandece. | David Grayson
Lembremos que, assim como muito nos foi dado, muito será esperado de nós, e que a verdadeira homenagem vem do coração, assim como dos lábios, e se mostra em ações. | Theodore Roosevelt
Uma bondade oferecida espontaneamente a quem precisa dela, é duplamente gratificante. | Jonathan Swift
É quando você se doa que você verdadeiramente dá. | Kahil Gibran
Faça mais do que pertencer: participe. Faça mais do que se importar: ajude. Faça mais do que acreditar: pratique. Faça mais do que ser justo: seja gentil. Faça mais do que perdoar: esqueça. Faça mais do que sonhar: trabalhe. | William Arthur Ward
A bondade é a corrente dourada pela qual a sociedade é unida. | Johann Wolfgang Von Goethe
O menor bom ato é melhor do que a maior boa intenção. | Provérbio Japonês
Não há melhor exercício para o coração do que alcançar e ajudar a levantar alguém. | Bernard Meltzer
A bondade pode se tornar seu próprio motivo. Tornamo-nos gentis ao sermos gentis. | Eric Hoffer
A bondade gera bondade. | Provérbio Grego
Um coração bondoso é uma fonte de alegria, fazendo tudo ao seu redor florescer em sorrisos. | Washington Irving
Seja gentil com aqueles que encontrar ao subir, você pode passar por eles novamente ao descer. | Provérbio Irlandês
Posse completa só é provada pela doação. Tudo o que você é incapaz de dar, possui você. | André Gide
Uma palavra gentil pode aquecer três meses de inverno. | Provérbio Japonês
Sempre que você estiver para fazer algo, embora só possa ser conhecido por você, pergunte a si mesmo como você agiria se todo o mundo estivesse olhando e aja de acordo. | Thomas Jefferson
A pergunta mais persistente e urgente da vida é: O que você está fazendo pelos outros? | Martin Luther King, Jr.
Onde quer que haja um ser humano, há uma oportunidade para a bondade. | Sêneca
Palavras gentis podem ser curtas e fáceis de falar, mas seus ecos são verdadeiramente infinitos. | Madre Teresa
Ser capaz de praticar sob todas as circunstâncias cinco coisas constitui a perfeita virtude; essas cinco coisas são gravidade, generosidade de alma, sinceridade, seriedade e bondade. | Confúcio
Vamos fazer uma nova regra de vida a partir de hoje à noite - sempre tente ser um pouco mais gentil do que o necessário. | Sir James M. Barrie
Boas ações nos enobrecem, somos filhos de nossos próprios atos. | Jean Paul Richter
Se você não tem caridade em seu coração, você tem o pior tipo de problema cardíaco. | Bob Hope
Palavras gentis abrirão uma porta de ferro. | Provérbio Turco
Cultivar a bondade é uma parte valiosa dos negócios da vida. | Samuel Johnson
Podemos ser ressentidos com nossa idade, ou podemos ser gratos por tê-la alcançado. | William Arthur Ward
Se você não se contentar com nada menos do que o seu melhor, ficará surpreso com o que pode realizar em sua vida. | Vince Lombardi
Grandes mentes têm propósitos; pequenas mentes têm desejos. Pequenas mentes são subjugadas por infortúnios; grandes mentes se elevam acima deles. | Washington Irving
Nenhum homem pode evitar nascer medíocre, mas nenhum homem precisa ser comum. | Satchel Paige
Acredite profundamente no seu coração que você está destinado a fazer grandes coisas. | Joe Paterno
Não devemos olhar para trás a menos que seja para tirar lições úteis dos erros passados e com o propósito de lucrar com a experiência comprada a caro preço. | George Washington
A Terra está cheia de Céu. | Elizabeth Barrett Browning
Lembre-se, a inspiração segue a ação e não vice-versa. | Aronson, Eric, Dash.
Lembre-se de que não conseguir o que você quer às vezes é um golpe de sorte maravilhoso. | Dalai Lama
Todas as coisas vêm para aquele que espera. | Henry Wadsworth Longfellow
Veja, na vida, muitas pessoas sabem o que fazer, mas poucas realmente fazem o que sabem. Saber não é o suficiente! Você deve agir. | Anthony Robbins
Eu sempre gosto de olhar para o lado otimista da vida, mas sou realista o suficiente para saber que a vida é uma questão complexa. | Walt Disney
Todos nós nos encontramos em situações que às vezes parecem desesperadoras. E todos nós temos a escolha de não fazer nada ou agir. | Catherine Pulsifer
A honestidade é a riqueza mais rara que alguém pode possuir, e ainda assim toda a honestidade do mundo não é dinheiro lícito para um pedaço de pão. | Josh Billings
Oh, que teia emaranhada tecemos, quando pela primeira vez praticamos enganar! | Sir Walter Scott
Praticamente toda a verdade honesta que existe no mundo é dita por crianças. | Oliver Wendell Holmes, Jr.
É difícil acreditar que um homem esteja dizendo a verdade quando você sabe que mentiria se estivesse no lugar dele. | Henry Louis Mencken
Nossas vidas melhoram apenas quando corremos riscos - e o primeiro e mais difícil risco que podemos correr é sermos honestos conosco mesmos. | Walter Anderson
Vamos levantar um padrão ao qual os sábios e honestos possam reparar; o resto está nas mãos de Deus. | George Washington
Nenhum legado é tão rico quanto a honestidade. | William Shakespeare
A melhor medida da honestidade de um homem não é sua declaração de imposto de renda. É o ajuste zero na balança de seu banheiro. | Arthur C. Clarke
Um dos valores centrais mais básicos é a honestidade. | Catherine Pulsifer
As pedras fundamentais para um sucesso equilibrado são honestidade, caráter, integridade, fé, amor e lealdade. | Zig Ziglar
A desonestidade desafiaria a honestidade a qualquer dia da semana, se houvesse algo a ser ganho com isso. | Charles Dickens
A honestidade é o primeiro capítulo do livro da sabedoria. | Thomas Jefferson
Integridade é dizer a mim mesmo a verdade. E a honestidade é dizer a verdade para outras pessoas. | Spencer Johnson
Esteja preparado e seja honesto. | John Wooden
Não há zona cinzenta de honestidade nos negócios. Uma coisa é certa ou errada. É preto ou branco. | John F. Dodge
Nenhum homem tem uma memória boa o suficiente para ser um mentiroso de sucesso. | Abraham Lincoln
Nivele-se com seu filho sendo honesto. Ninguém detecta um falso mais rápido do que uma criança. | Mary MacCracken
Seja bobo. Seja honesto. Seja gentil. | Ralph Waldo Emerson
Como eu disse, a primeira coisa é ser honesto consigo mesmo. | Nelson Mandela
A honestidade é temer uma resposta negativa e dizer a verdade mesmo assim. | Michelle C. Ustaszeski
Concentração é meu lema - primeiro honestidade, depois indústria, depois concentração. | Andrew Carnegie
Discordância honesta é frequentemente um bom sinal de progresso. | Gandhi
A dúvida, quando indulgente e acariciada, está em perigo de se tornar negação; mas se honesta, e empenhada em uma investigação completa, pode em breve levar ao pleno estabelecimento da verdade. | Ambrose Bierce
