<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Ροή ειδήσεων';
$labels['news_feed'] = 'Ροή ειδήσεων';
$labels['preview'] = 'Προεπισκόπηση';
$labels['test_settings'] = 'Δοκιμή ρυθμίσεων ροής ειδήσεων';
$labels['feed_error'] = 'Δεν μπορεί να φορτώσει ροή ειδήσεων.';
$labels['feed_error_url'] = 'Σφάλμα: URL.';
$labels['feed_error_content'] = 'Σφάλμα: Το περιεχόμενο που φορτώθηκε από την καθορισμένη διεύθυνση URL είναι κενό.';
$labels['setting_show_xnews_feed'] = 'Εμφάνιση ροής ειδήσεων';
$labels['setting_predefined'] = 'Προκαθορισμένες τροφοδοσίες';
$labels['setting_title'] = 'Τίτλος';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Αντικείμενα προς εμφάνιση';
