<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Noticias';
$labels['news_feed'] = 'Noticias';
$labels['preview'] = 'Vista previa';
$labels['test_settings'] = 'Probar la configuración del feed de noticias';
$labels['feed_error'] = 'No se pueden cargar las noticias.';
$labels['feed_error_url'] = 'Error: No se puede cargar la fuente de noticias de la URL especificada.';
$labels['feed_error_content'] = 'Error: El contenido cargado desde la URL especificada está vacío.';
$labels['setting_show_xnews_feed'] = 'Mostrar noticias';
$labels['setting_predefined'] = 'Alimentación predefinida';
$labels['setting_title'] = 'Título';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Elementos a mostrar';
