<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Umpan Berita';
$labels['news_feed'] = 'Umpan Berita';
$labels['preview'] = 'Pratinjau';
$labels['test_settings'] = 'Menguji pengaturan umpan berita';
$labels['feed_error'] = 'Tidak dapat memuat umpan berita.';
$labels['feed_error_url'] = 'Kesalahan: Tidak dapat memuat umpan berita dari URL yang ditentukan.';
$labels['feed_error_content'] = 'Kesalahan: Konten yang dimuat dari URL yang ditentukan kosong.';
$labels['setting_show_xnews_feed'] = 'Tampilkan Umpan Berita';
$labels['setting_predefined'] = 'Umpan yang telah ditentukan sebelumnya';
$labels['setting_title'] = 'Judul';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Item yang akan ditampilkan';
