<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Notizie';
$labels['news_feed'] = 'Notizie';
$labels['preview'] = 'Anteprima';
$labels['test_settings'] = 'Verifica le impostazioni del feed di notizie';
$labels['feed_error'] = 'Impossibile caricare il feed di notizie.';
$labels['feed_error_url'] = 'Errore: Impossibile caricare il feed di notizie dall\'URL specificato.';
$labels['feed_error_content'] = 'Errore: Il contenuto caricato dall\'URL specificato è vuoto.';
$labels['setting_show_xnews_feed'] = 'Mostra feed di notizie';
$labels['setting_predefined'] = 'Feed predefiniti';
$labels['setting_title'] = 'Titolo';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Elementi da mostrare';
