<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Ziņu plūsma';
$labels['news_feed'] = 'Ziņu plūsma';
$labels['preview'] = 'Priekšskatījums';
$labels['test_settings'] = 'Pārbaudīt ziņu plūsmas iestatījumus';
$labels['feed_error'] = 'Nevar ielādēt ziņu plūsmu.';
$labels['feed_error_url'] = 'Kļūda: Nevar ielādēt ziņu plūsmu no norādītā URL.';
$labels['feed_error_content'] = 'Kļūda: No norādītā URL ielādētais saturs ir tukšs.';
$labels['setting_show_xnews_feed'] = 'Rādīt jaunumu plūsmu';
$labels['setting_predefined'] = 'Iepriekš noteiktas plūsmas';
$labels['setting_title'] = 'Nosaukums';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Rādāmie priekšmeti';
