<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Flux de știri';
$labels['news_feed'] = 'Flux de știri';
$labels['preview'] = 'Previzualizare';
$labels['test_settings'] = 'Testați setările de alimentare cu știri';
$labels['feed_error'] = 'Nu se poate încărca fluxul de știri.';
$labels['feed_error_url'] = 'Eroare: Nu se poate încărca fluxul de știri de la URL-ul specificat.';
$labels['feed_error_content'] = 'Eroare: Conținutul încărcat de la URL-ul specificat este gol.';
$labels['setting_show_xnews_feed'] = 'Arată fluxul de știri';
$labels['setting_predefined'] = 'Fluxuri predefinite';
$labels['setting_title'] = 'Titlu';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Elemente de afișat';
