<?php
/**
 * Roundcube Plus Resell plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Haber Kaynağı';
$labels['news_feed'] = 'Haber Kaynağı';
$labels['preview'] = 'Önizleme';
$labels['test_settings'] = 'Haber akışı ayarlarını test edin';
$labels['feed_error'] = 'Haber akışı yüklenemiyor.';
$labels['feed_error_url'] = 'Hata oluştu: Belirtilen URL\'den haber akışı yüklenemiyor.';
$labels['feed_error_content'] = 'Hata oluştu: Belirtilen URL\'den yüklenen içerik boş.';
$labels['setting_show_xnews_feed'] = 'Haber Kaynağını Göster';
$labels['setting_predefined'] = 'Önceden tanımlanmış beslemeler';
$labels['setting_title'] = 'Başlık';
$labels['setting_url'] = 'URL';
$labels['setting_count'] = 'Gösterilecek öğeler';
