<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Programador de correo';
$labels['email_schedule'] = 'Programador de correo';
$labels['schedule'] = 'Horario';
$labels['scheduled'] = 'Programado';
$labels['scheduled_messages'] = 'Mensajes programados';
$labels['show_scheduled_messages'] = 'Mostrar mensajes programados.';
$labels['message_scheduled'] = 'Mensaje programado.';
$labels['no_scheduled_messages'] = 'No hay mensajes en la cola de programación.';
$labels['warning_unsent_messages'] = 'Algunos de tus mensajes programados no se han enviado.';
$labels['message_delete_confirm'] = '¿Quieres borrar definitivamente este mensaje?';

$labels['immediately'] = 'Inmediatamente';
$labels['in_5_minutes'] = 'En 5 minutos';
$labels['in_10_minutes'] = 'En 10 minutos';
$labels['in_15_minutes'] = 'En 15 minutos';
$labels['in_30_minutes'] = 'En 30 minutos';
$labels['in_1_hour'] = 'En 1 hora';
$labels['in_2_hours'] = 'En 2 horas';
$labels['in_6_hours'] = 'En 6 horas';
$labels['at_a_specific_time'] = 'En un momento determinado';

$labels['disabled'] = 'La programación de mensajes está desactivada. Póngase en contacto con el administrador.';
$labels['draft_note'] = 'Este mensaje se ha guardado como borrador y se ha eliminado de la cola de programación. Para volver a programarlo, haga clic en el botón Programar.';
$labels['error_editing'] = 'No se puede editar el mensaje programado; es posible que el mensaje se haya enviado o borrado.';
$labels['error_deleting'] = 'No se puede mover el mensaje a la papelera; es posible que el mensaje se haya enviado, borrado o que el buzón de la papelera no esté disponible.';

$labels['send_message'] = 'Enviar mensaje';
$labels['setting_delay'] = 'Retraso por defecto en el envío de mensajes';
$labels['setting_highlight'] = 'Resaltar los mensajes programados que están a punto de enviarse';

$labels['email_being_sent'] = 'Enviar correo electrónico';
$labels['send_now'] = 'Enviar ahora';
$labels['schedule_now'] = 'Programar ahora';
$labels['cancel_sending'] = 'Cancelar envío';
$labels['setting_countdown'] = 'Cuenta atrás antes de enviar mensajes';
$labels['disable_countdown'] = 'Desactivar';
$labels['3_seconds'] = '3 segundos';
$labels['5_seconds'] = '5 segundos';
$labels['10_seconds'] = '10 segundos';
$labels['15_seconds'] = '15 segundos';

$labels['cannot_schedule_message'] = 'No se puede programar el mensaje:';
$labels['time_has_already_passed'] = 'La hora prevista ya ha pasado.';
$labels['invalid_time_format'] = 'Formato de hora no válido.';
$labels['draft_folder_not_specified'] = 'Error del plugin de programación de correo electrónico: Carpeta de borradores no especificada.';
$labels['error'] = 'Error:';
$labels['attachment_tool_large'] = 'La configuración del servidor limita los archivos adjuntos de los mensajes programados a $tamaño.';
$labels['message_already_scheduled'] = 'Este mensaje ya está programado.';

