<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Email ütemező';
$labels['email_schedule'] = 'Email ütemező';
$labels['schedule'] = 'Ütemterv';
$labels['scheduled'] = 'Tervezett';
$labels['scheduled_messages'] = 'Ütemezett üzenetek';
$labels['show_scheduled_messages'] = 'Ütemezett üzenetek megjelenítése.';
$labels['message_scheduled'] = 'Üzenet ütemezve.';
$labels['no_scheduled_messages'] = 'Nincsenek üzenetek az ütemezési sorban.';
$labels['warning_unsent_messages'] = 'Néhány tervezett üzenete nem került elküldésre.';
$labels['message_delete_confirm'] = 'Szeretné véglegesen törölni ezt az üzenetet?';

$labels['immediately'] = 'Azonnal';
$labels['in_5_minutes'] = '5 perc alatt';
$labels['in_10_minutes'] = '10 perc alatt';
$labels['in_15_minutes'] = '15 perc múlva';
$labels['in_30_minutes'] = '30 perc múlva';
$labels['in_1_hour'] = '1 óra múlva';
$labels['in_2_hours'] = '2 óra múlva';
$labels['in_6_hours'] = '6 óra múlva';
$labels['at_a_specific_time'] = 'Egy adott időpontban';

$labels['disabled'] = 'Az üzenet ütemezése le van tiltva. Lépjen kapcsolatba a rendszergazdával.';
$labels['draft_note'] = 'Ezt az üzenetet tervezetként mentettük és eltávolítottuk a várólistáról. Újra ütemezéséhez kattintson az Ütemezés gombra.';
$labels['error_editing'] = 'Nem lehet szerkeszteni az ütemezett üzenetet; az üzenet lehet, hogy már elküldték vagy törölték.';
$labels['error_deleting'] = 'Az üzenetet nem lehet a szemetesbe helyezni; az üzenet lehet, hogy elküldték, törölték, vagy a szemetes postafiók nem elérhető.';

$labels['send_message'] = 'Üzenet küldése';
$labels['setting_delay'] = 'Üzenetek küldésének alapértelmezett késleltetése';
$labels['setting_highlight'] = 'Kiemeli az elküldésre váró ütemezett üzeneteket';

$labels['email_being_sent'] = 'E-mail küldése';
$labels['send_now'] = 'Küldj most';
$labels['schedule_now'] = 'Ütemezés most';
$labels['cancel_sending'] = 'Küldés törlése';
$labels['setting_countdown'] = 'Visszaszámlálás az üzenetek küldése előtt';
$labels['disable_countdown'] = 'A  letiltása';
$labels['3_seconds'] = '3 másodperc';
$labels['5_seconds'] = '5 másodperc';
$labels['10_seconds'] = '10 másodperc';
$labels['15_seconds'] = '15 másodperc';

$labels['cannot_schedule_message'] = 'Nem lehet ütemezni az üzenetet:';
$labels['time_has_already_passed'] = 'A tervezett idő már eltelt.';
$labels['invalid_time_format'] = 'Érvénytelen időformátum.';
$labels['draft_folder_not_specified'] = 'Email ütemezés plugin hiba: Draft folder not specified.';
$labels['error'] = 'Hiba:';
$labels['attachment_tool_large'] = 'A kiszolgáló konfigurációja az ütemezett üzenetek csatolmányait $méretre korlátozza.';
$labels['message_already_scheduled'] = 'Ez az üzenet már be van ütemezve.';

