<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Programmatore di e-mail';
$labels['email_schedule'] = 'Pianifica e-mail';
$labels['schedule'] = 'Pianifica';
$labels['scheduled'] = 'Pianificato';
$labels['scheduled_messages'] = 'Messaggi pianificati';
$labels['show_scheduled_messages'] = 'Mostra messaggi pianificati.';
$labels['message_scheduled'] = 'Messaggio pianificato.';
$labels['no_scheduled_messages'] = 'Non ci sono messaggi pianificati.';
$labels['warning_unsent_messages'] = 'Alcuni dei tuoi messaggi pianificati non sono stati inviati.';
$labels['message_delete_confirm'] = 'Vuoi eliminare definitivamente questo messaggio?';

$labels['immediately'] = 'Subito';
$labels['in_5_minutes'] = 'Tra 5 minuti';
$labels['in_10_minutes'] = 'Tra 10 minuti';
$labels['in_15_minutes'] = 'Tra 15 minuti';
$labels['in_30_minutes'] = 'Tra 30 minuti';
$labels['in_1_hour'] = 'Tra 1 ora';
$labels['in_2_hours'] = 'Tra 2 ore';
$labels['in_6_hours'] = 'Tra 6 ore';
$labels['at_a_specific_time'] = 'Ad un\'ora specifica';

$labels['disabled'] = 'La pianificazione dei messaggi è disabilitata. Contatta l\'amministratore.';
$labels['draft_note'] = 'Questo messaggio è stato salvato come bozza e rimosso dalla pianificazione. Per programmarlo di nuovo, fai clic sul pulsante Pianifica.';
$labels['error_editing'] = 'Impossibile modificare il messaggio pianificato; il messaggio potrebbe essere stato inviato o eliminato.';
$labels['error_deleting'] = 'Impossibile spostare il messaggio nel cestino; il messaggio potrebbe essere stato inviato, eliminato o la casella \'cestino\' non è disponibile.';

$labels['send_message'] = 'Invia messaggio';
$labels['setting_delay'] = 'Ritardo predefinito per l\'invio dei messaggi';
$labels['setting_highlight'] = 'Evidenzia i messaggi pianificati che stanno per essere inviati';

$labels['email_being_sent'] = 'Invio email';
$labels['send_now'] = 'Invia ora';
$labels['schedule_now'] = 'Pianifica ora';
$labels['cancel_sending'] = 'Annulla invio';
$labels['setting_countdown'] = 'Conto alla rovescia prima di inviare messaggi';
$labels['disable_countdown'] = 'Disabilita';
$labels['3_seconds'] = '3 secondi';
$labels['5_seconds'] = '5 secondi';
$labels['10_seconds'] = '10 secondi';
$labels['15_seconds'] = '15 secondi';

$labels['cannot_schedule_message'] = 'Impossibile pianificare il messaggio:';
$labels['time_has_already_passed'] = 'Il tempo pianificato è già trascorso.';
$labels['invalid_time_format'] = 'Formato dell\'ora non valido.';
$labels['draft_folder_not_specified'] = 'Errore plugin pianificazione email: cartella bozze non specificata.';
$labels['error'] = 'Errore:';
$labels['attachment_tool_large'] = 'La configurazione del server limita gli allegati dei messaggi pianificati a $size.';
$labels['message_already_scheduled'] = 'Questo messaggio è già programmato.';

