<?php
/**
 * Roundcube Plus Email Schedule plugin.
 *
 * Copyright 2018, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '電子郵件排程';
$labels['email_schedule'] = '電子郵件排程';
$labels['schedule'] = '時間表';
$labels['scheduled'] = '排程';
$labels['scheduled_messages'] = '排程訊息';
$labels['show_scheduled_messages'] = '顯示排程訊息。';
$labels['message_scheduled'] = '訊息排程。';
$labels['no_scheduled_messages'] = '排程佇列中沒有訊息。';
$labels['warning_unsent_messages'] = '您的某些排程訊息尚未傳送。';
$labels['message_delete_confirm'] = '您要永久刪除此訊息嗎？';

$labels['immediately'] = '立即';
$labels['in_5_minutes'] = '5 分鐘內';
$labels['in_10_minutes'] = '10 分鐘內';
$labels['in_15_minutes'] = '15 分鐘後';
$labels['in_30_minutes'] = '30 分鐘後';
$labels['in_1_hour'] = '1 小時內';
$labels['in_2_hours'] = '2 小時內';
$labels['in_6_hours'] = '6 小時內';
$labels['at_a_specific_time'] = '在特定時間';

$labels['disabled'] = '訊息排程已停用。請聯絡管理員。';
$labels['draft_note'] = '此訊息已儲存為草稿，並從排程佇列中移除。若要再次排程，請按一下排程按鈕。';
$labels['error_editing'] = '無法編輯排程訊息；訊息可能已傳送或刪除。';
$labels['error_deleting'] = '無法將訊息移至垃圾信箱；訊息可能已傳送、刪除或垃圾信箱不可用。';

$labels['send_message'] = '傳送訊息';
$labels['setting_delay'] = '傳送訊息的預設延遲';
$labels['setting_highlight'] = '高亮顯示即將傳送的排程訊息';

$labels['email_being_sent'] = '傳送電子郵件';
$labels['send_now'] = '立即發送';
$labels['schedule_now'] = '立即排程';
$labels['cancel_sending'] = '取消傳送';
$labels['setting_countdown'] = '傳送訊息前的倒數計時';
$labels['disable_countdown'] = '停用';
$labels['3_seconds'] = '3 秒';
$labels['5_seconds'] = '5 秒';
$labels['10_seconds'] = '10 秒';
$labels['15_seconds'] = '15 秒';

$labels['cannot_schedule_message'] = '無法排程訊息：';
$labels['time_has_already_passed'] = '預定時間已經過去。';
$labels['invalid_time_format'] = '無效的時間格式。';
$labels['draft_folder_not_specified'] = '電子郵件排程外掛程式錯誤：未指定草稿資料夾。';
$labels['error'] = '錯誤：';
$labels['attachment_tool_large'] = '伺服器設定將排程的訊息附件限制為 $size。';
$labels['message_already_scheduled'] = '此訊息已排程。';

