<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'ورق حائط';
$labels['setting_compact'] = 'عرض قائمة الرسائل المدمجة';
$labels['with_vertical_preview'] = 'مع معاينة رأسية';
$labels['setting_compose_plain_font_size'] = 'حجم الخط الافتراضي للرسالة النصية العادية';
$labels['background'] = 'الخلفية';
$labels['setting_image'] = 'صورة الخلفية';
$labels['setting_image_opacity'] = 'عتامة الصورة';
$labels['setting_content_opacity'] = 'عتامة مربع المحتوى';
$labels['more_background_options'] = 'المزيد من خيارات الخلفية...';
$labels['upload_image'] = 'تحميل الصورة';
$labels['upload_background_image'] = 'تحميل صورة الخلفية';
$labels['setting_placement'] = 'وضع الصورة';
$labels['tile'] = 'البلاط';
$labels['cover'] = 'الغلاف';
$labels['setting_text_color'] = 'لون النص';
$labels['auto'] = 'أوتوماتيكي';
$labels['light'] = 'مشرق';
$labels['dark'] = 'داكن';
$labels['none'] = 'لا يوجد';
$labels['setting_blur'] = 'ضبابية الصورة';
$labels['setting_gray'] = 'التحويل إلى اللون الرمادي';
$labels['placement_help'] = 'تحديد ما إذا كان ينبغي تجانب الصورة (مكررة) أو تغطية الخلفية بأكملها.';
$labels['text_color_help'] = 'يحدد ما إذا كان لون النص المعروض مباشرة على صورة الخلفية يجب أن يكون داكنًا أو فاتحًا.';
