<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Tapety';
$labels['setting_compact'] = 'Zobrazení kompaktního seznamu zpráv';
$labels['with_vertical_preview'] = 's vertikálním náhledem';
$labels['setting_compose_plain_font_size'] = 'Výchozí velikost písma prosté textové zprávy';
$labels['background'] = 'Pozadí';
$labels['setting_image'] = 'Obrázek na pozadí';
$labels['setting_image_opacity'] = 'Neprůhlednost obrázku';
$labels['setting_content_opacity'] = 'Neprůhlednost rámečku obsahu';
$labels['more_background_options'] = 'Další možnosti pozadí...';
$labels['upload_image'] = 'Nahrát obrázek';
$labels['upload_background_image'] = 'Nahrání obrázku na pozadí';
$labels['setting_placement'] = 'Umístění obrázku';
$labels['tile'] = 'Dlaždice';
$labels['cover'] = 'Obálka';
$labels['setting_text_color'] = 'Barva textu';
$labels['auto'] = 'Automatické';
$labels['light'] = 'Bright';
$labels['dark'] = 'Dark';
$labels['none'] = 'Žádné';
$labels['setting_blur'] = 'Rozmazání obrazu';
$labels['setting_gray'] = 'Převést na šedou';
$labels['placement_help'] = 'Určuje, zda má být obrázek dlaždicový (opakovaný) nebo zda má pokrývat celé pozadí.';
$labels['text_color_help'] = 'Určuje, zda má být barva textu zobrazeného přímo na obrázku na pozadí tmavá nebo světlá.';
