<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Baggrund';
$labels['setting_compact'] = 'Vis kompakt beskedliste';
$labels['with_vertical_preview'] = 'med lodret visning';
$labels['setting_compose_plain_font_size'] = 'Standardskriftstørrelse for almindelig tekstmeddelelse';
$labels['background'] = 'Baggrund';
$labels['setting_image'] = 'Baggrundsbillede';
$labels['setting_image_opacity'] = 'Billedets opacitet';
$labels['setting_content_opacity'] = 'Indholdsboksens opacitet';
$labels['more_background_options'] = 'Flere baggrundsmuligheder...';
$labels['upload_image'] = 'Upload billede';
$labels['upload_background_image'] = 'Upload baggrundsbillede';
$labels['setting_placement'] = 'Placering af billeder';
$labels['tile'] = 'Fliser';
$labels['cover'] = 'Cover';
$labels['setting_text_color'] = 'Tekstfarve';
$labels['auto'] = 'Automatisk';
$labels['light'] = 'Bright';
$labels['dark'] = 'Mørk';
$labels['none'] = 'Ingen';
$labels['setting_blur'] = 'Billede sløring';
$labels['setting_gray'] = 'Konverter til grå';
$labels['placement_help'] = 'Angiver, om billedet skal være flisebelagt (gentages) eller dække hele baggrunden.';
$labels['text_color_help'] = 'Angiver, om farven på den tekst, der vises direkte på baggrundsbilledet, skal være mørk eller lys.';
