<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Papel pintado';
$labels['setting_compact'] = 'Mostrar lista compacta de mensajes';
$labels['with_vertical_preview'] = 'con vista previa vertical';
$labels['setting_compose_plain_font_size'] = 'Tamaño de fuente por defecto del mensaje de texto sin formato';
$labels['background'] = 'Fondo';
$labels['setting_image'] = 'Imagen de fondo';
$labels['setting_image_opacity'] = 'Opacidad de la imagen';
$labels['setting_content_opacity'] = 'Opacidad del cuadro de contenido';
$labels['more_background_options'] = 'Más opciones de fondo...';
$labels['upload_image'] = 'Cargar imagen';
$labels['upload_background_image'] = 'Subir imagen de fondo';
$labels['setting_placement'] = 'Colocación de imágenes';
$labels['tile'] = 'Azulejos';
$labels['cover'] = 'Portada';
$labels['setting_text_color'] = 'Color del texto';
$labels['auto'] = 'Automático';
$labels['light'] = 'Brillante';
$labels['dark'] = 'Oscuro';
$labels['none'] = 'Ninguno';
$labels['setting_blur'] = 'Desenfoque de imagen';
$labels['setting_gray'] = 'Convertir a gris';
$labels['placement_help'] = 'Especifica si la imagen debe aparecer en mosaico (repetida) o cubrir todo el fondo.';
$labels['text_color_help'] = 'Especifica si el color del texto mostrado directamente sobre la imagen de fondo debe ser oscuro o claro.';
