<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Papier peint';
$labels['setting_compact'] = 'Afficher la liste de messages compacte';
$labels['with_vertical_preview'] = 'avec prévisualisation verticale';
$labels['setting_compose_plain_font_size'] = 'Taille de police par défaut du message en texte brut';
$labels['background'] = 'Arrière-plans';
$labels['setting_image'] = 'Image d\'arrière-plan';
$labels['setting_image_opacity'] = 'Opacité de l\'image';
$labels['setting_content_opacity'] = 'Opacité des zones de contenus';
$labels['more_background_options'] = 'Plus d\'arrière-plan ...';
$labels['upload_image'] = 'Charger une image';
$labels['upload_background_image'] = 'Charger une image d\'arrière-plan';
$labels['setting_placement'] = 'Position de l\'image';
$labels['tile'] = 'Titre';
$labels['cover'] = 'Couverture';
$labels['setting_text_color'] = 'Couleur du texte';
$labels['auto'] = 'Automatique';
$labels['light'] = 'Clair';
$labels['dark'] = 'Sombre';
$labels['none'] = 'Aucun';
$labels['setting_blur'] = 'Floutage de l\'image';
$labels['setting_gray'] = 'Convertir en niveau de gris';
$labels['placement_help'] = 'Préciser si l\'image doit être en mosaïque (répétée) ou couvrir tout l\'arrière-plan.';
$labels['text_color_help'] = 'Préciser si la couleur du texte affiché sur l\'image d\'arrière-plan doit être sombre ou claire.';
