<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Háttérkép';
$labels['setting_compact'] = 'Kompakt üzenetlista megjelenítése';
$labels['with_vertical_preview'] = 'függőleges előnézetben';
$labels['setting_compose_plain_font_size'] = 'A sima szöveges üzenet alapértelmezett betűmérete';
$labels['background'] = 'Háttér';
$labels['setting_image'] = 'Háttérkép';
$labels['setting_image_opacity'] = 'A kép átlátszatlansága';
$labels['setting_content_opacity'] = 'Tartalom doboz átlátszatlansága';
$labels['more_background_options'] = 'További háttér opciók...';
$labels['upload_image'] = 'Kép feltöltése';
$labels['upload_background_image'] = 'Háttérkép feltöltése';
$labels['setting_placement'] = 'Kép elhelyezése';
$labels['tile'] = 'Csempe';
$labels['cover'] = 'Borító';
$labels['setting_text_color'] = 'Szöveg színe';
$labels['auto'] = 'Automatikus';
$labels['light'] = 'Fényes';
$labels['dark'] = 'Sötét';
$labels['none'] = 'Nincs';
$labels['setting_blur'] = 'A kép elmosódása';
$labels['setting_gray'] = 'Szürkévé alakítani';
$labels['placement_help'] = 'Meghatározza, hogy a kép csempézett (ismétlődő) legyen, vagy a teljes hátteret fedje le.';
$labels['text_color_help'] = 'Meghatározza, hogy a közvetlenül a háttérképen megjelenített szöveg színe sötét vagy világos legyen.';
