<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = '壁紙';
$labels['setting_compact'] = 'コンパクトなメッセージリストを表示';
$labels['with_vertical_preview'] = '垂直プレビュー付き';
$labels['setting_compose_plain_font_size'] = 'プレーンテキストメッセージのデフォルトのフォントサイズ';
$labels['background'] = '背景';
$labels['setting_image'] = '背景画像';
$labels['setting_image_opacity'] = '画像の不透明度';
$labels['setting_content_opacity'] = 'コンテンツボックスの不透明度';
$labels['more_background_options'] = 'その他の背景オプション...';
$labels['upload_image'] = '画像のアップロード';
$labels['upload_background_image'] = '背景画像のアップロード';
$labels['setting_placement'] = '画像の配置';
$labels['tile'] = 'タイル';
$labels['cover'] = 'カバー';
$labels['setting_text_color'] = '文字色';
$labels['auto'] = '自動';
$labels['light'] = '明るい';
$labels['dark'] = '暗い';
$labels['none'] = 'なし';
$labels['setting_blur'] = 'イメージブラー';
$labels['setting_gray'] = 'グレーに変換';
$labels['placement_help'] = '画像をタイル状（繰り返し）にするか、背景全体を覆うかを指定します。';
$labels['text_color_help'] = '背景画像に直接表示されるテキストの色を濃くするか薄くするかを指定する。';
