<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Tapeta';
$labels['setting_compact'] = 'Wyświetl kompaktową listę wiadomości';
$labels['with_vertical_preview'] = 'z pionowym podglądem';
$labels['setting_compose_plain_font_size'] = 'Domyślny rozmiar zwykłego tekstu w wiadomości';
$labels['background'] = 'Tło';
$labels['setting_image'] = 'Obraz w tle';
$labels['setting_image_opacity'] = 'Widoczność obrazu';
$labels['setting_content_opacity'] = 'Widoczność zawartości';
$labels['more_background_options'] = 'Więcej opcji tła...';
$labels['upload_image'] = 'Prześlij obraz';
$labels['upload_background_image'] = 'Prześlij obraz na tło';
$labels['setting_placement'] = 'Położenie obrazu';
$labels['tile'] = 'Kafelek';
$labels['cover'] = 'Okładka';
$labels['setting_text_color'] = 'Kolor tekstu';
$labels['auto'] = 'Automatycznie';
$labels['light'] = 'Jasny';
$labels['dark'] = 'Ciemny';
$labels['none'] = 'Brak';
$labels['setting_blur'] = 'Rozmycie obrazu';
$labels['setting_gray'] = 'Konwertuj do szarości';
$labels['placement_help'] = 'Określa, czy obraz ma być kafelkowany (powtarzany w tle), czy zajmować całą przestrzeń tła.';
$labels['text_color_help'] = 'Określa, czy kolor tekstu wyświetlanego bezpośrednio na tle ma być jasny czy ciemny.';
