<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Ozadje';
$labels['setting_compact'] = 'Prikaz kompaktnega seznama sporočil';
$labels['with_vertical_preview'] = 'z navpičnim predogledom';
$labels['setting_compose_plain_font_size'] = 'Privzeta velikost pisave v navadnem besedilnem sporočilu';
$labels['background'] = 'Ozadje';
$labels['setting_image'] = 'Slika v ozadju';
$labels['setting_image_opacity'] = 'Motnost slike';
$labels['setting_content_opacity'] = 'Motnost polja vsebine';
$labels['more_background_options'] = 'Več možnosti ozadja...';
$labels['upload_image'] = 'Naloži sliko';
$labels['upload_background_image'] = 'Naložite sliko ozadja';
$labels['setting_placement'] = 'Umestitev slike';
$labels['tile'] = 'Ploščice';
$labels['cover'] = 'Pokrov';
$labels['setting_text_color'] = 'Barva besedila';
$labels['auto'] = 'Samodejno';
$labels['light'] = 'Bright';
$labels['dark'] = 'Dark';
$labels['none'] = 'Ni';
$labels['setting_blur'] = 'Zameglitev slike';
$labels['setting_gray'] = 'Pretvori v sivo';
$labels['placement_help'] = 'Določa, ali naj se slika ponovi ali prekrije celotno ozadje.';
$labels['text_color_help'] = 'Določa, ali naj bo barva besedila, prikazanega neposredno na sliki ozadja, temna ali svetla.';
