<?php
/**
 * Roundcube Plus Background plugin.
 *
 * Copyright 2016, Roundcubeplus.com.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = [];
$labels['app_menu_title'] = 'Bakgrund';
$labels['setting_compact'] = 'Visa kompakt meddelandelista';
$labels['with_vertical_preview'] = 'med vertikal förhandsgranskning';
$labels['setting_compose_plain_font_size'] = 'Standardstorlek på teckensnittet i ett vanligt textmeddelande';
$labels['background'] = 'Bakgrund';
$labels['setting_image'] = 'Bakgrundsbild';
$labels['setting_image_opacity'] = 'Bildens opacitet';
$labels['setting_content_opacity'] = 'Innehållsrutans opacitet';
$labels['more_background_options'] = 'Fler bakgrundsalternativ...';
$labels['upload_image'] = 'Ladda upp bild';
$labels['upload_background_image'] = 'Ladda upp bakgrundsbild';
$labels['setting_placement'] = 'Placering av bilder';
$labels['tile'] = 'Kakel';
$labels['cover'] = 'Omslag';
$labels['setting_text_color'] = 'Textfärg';
$labels['auto'] = 'Automatisk';
$labels['light'] = 'Ljus';
$labels['dark'] = 'Mörk';
$labels['none'] = 'Ingen';
$labels['setting_blur'] = 'Oskärpa i bilden';
$labels['setting_gray'] = 'Konvertera till grått';
$labels['placement_help'] = 'Anger om bilden ska vara "tiled" (upprepad) eller täcka hela bakgrunden.';
$labels['text_color_help'] = 'Anger om färgen på den text som visas direkt på bakgrundsbilden ska vara mörk eller ljus.';
