Todos los logros, todas las riquezas ganadas, tienen su comienzo en una idea. | Napoleon Hill
Nunca confundas la actividad con los logros. | John Wooden
Los logros son el resultado del trabajo que realiza la ambición. | Adam Ant
Los logros más complicados del pensamiento son posibles sin la ayuda de la conciencia. | Sigmund Freud
Los grandes logros suelen nacer de un gran sacrificio, y nunca son el resultado del egoísmo. | Napoleon Hill
La muerte llega a todos, pero los grandes logros construyen un monumento que perdurará hasta que el sol se enfríe. | Ralph Waldo Emerson
Aprecia tus visiones y tus sueños porque son los hijos de tu alma; los planos de tus logros finales. | Napoleon Hill
Tienes que aprender las reglas del juego. Y luego tienes que jugar mejor que nadie. | Albert Einstein
Me alegro de haberlo hecho, en parte porque ha merecido la pena, pero sobre todo porque nunca tendré que volver a hacerlo. | Mark Twain
No es la montaña lo que conquistamos, sino a nosotros mismos. | Edmund Hillary
Nuestra tarea debe ser liberarnos de esta prisión ampliando nuestros círculos de compasión para abarcar a todas las criaturas vivas y a toda la naturaleza en su belleza. | Albert Einstein
Los grandes logros siempre tienen lugar en el marco de una gran expectativa. | Charles F. Kettering
Puedes tener todo lo que quieres en la vida, si ayudas a otras personas a conseguir lo que quieren. | Zig Ziglar
Un gran esfuerzo surge naturalmente de una gran actitud. | Pat Riley
Tu actitud, no tu aptitud, determinará tu altitud. | Zig Ziglar
Puedes adoptar la actitud de que no hay nada que puedas hacer, o puedes ver el reto como tu llamada a la acción. | Catherine Pulsifer
Un optimista es una persona que ve la luz verde en todas partes, mientras que el pesimista sólo ve el semáforo en rojo - La persona verdaderamente sabia es daltónica. | Albert Schweitzer
El pensamiento positivo te permitirá hacer todo mejor que el pensamiento negativo. | Zig Ziglar
No puedes controlar lo que te sucede, pero puedes controlar tu actitud hacia lo que te sucede, y en eso, estarás dominando el cambio en lugar de permitir que te domine. | Brian Tracy
¡Puedes hacerlo si crees que puedes! | Napoleon Hill
Si no estableces un estándar de referencia para lo que aceptarás en la vida, descubrirás que es fácil caer en comportamientos y actitudes o en una calidad de vida que está muy por debajo de lo que mereces. | Anthony Robbins
Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud. No te quejes. | Maya Angelou
La persona que envía pensamientos positivos activa el mundo que le rodea positivamente y atrae hacia sí resultados positivos. | Norman Vincent Peale
Si tu felicidad depende de lo que haga otra persona, creo que tienes un problema. | Richard Bach
Sentir lástima por ti mismo, y por tu condición actual, no sólo es un desperdicio de energía sino el peor hábito que podrías tener. | Dale Carnegie
Cualquiera puede hacer consigo mismo todo lo que realmente quiera y se proponga. Somos capaces de cosas más grandes de lo que creemos. | Norman Vincent Peale
Hay dos opciones principales en la vida: aceptar las condiciones tal y como existen, o aceptar la responsabilidad de cambiarlas. | Denis Waitley
La vida es como tocar un violín en público y aprender el instrumento a medida que se avanza. | Samuel Butler
El primer paso para conseguir las cosas que quieres de la vida es éste: Decide lo que quieres. | Ben Stein
La vida es lo que te sucede mientras estás ocupado haciendo otros planes. | John Lennon
El lugar al que llegas no es lo más importante. Es el camino que tomas para llegar allí. El camino que tomes es lo que mirarás atrás y llamarás tu vida. | Tim Wiley
Sólo hay dos maneras de vivir la vida. Una es como si nada fuera un milagro. La otra es como si todo fuera un milagro. | Albert Einstein
La calidad de la vida de una persona está en proporción directa a su compromiso con la excelencia, independientemente del campo de trabajo que elija. | Vince Lombardi
La vida es sólo un espejo, y lo que ves ahí fuera, debes verlo primero dentro de ti. | Wally Amos
Empaca todo lo que hay en tu vida; ¡sólo pasas por aquí una vez! Siéntate y piensa qué es lo que te gusta. Haz cursos, lee libros, encuentra tu pasión. | Catherine Pulsifer
El gran secreto de la vida es que no hay ningún gran secreto. Sea cual sea tu objetivo, puedes conseguirlo si estás dispuesto a trabajar. | Oprah Winfrey
Hay que vivir la vida y mantener viva la curiosidad. Uno nunca debe, por la razón que sea, dar la espalda a la vida. | Eleanor Roosevelt
Saber que aunque sea una vida ha respirado mejor porque has vivido. Esto es haber triunfado. | Ralph Waldo Emerson
Las batallas de la vida no siempre son para el hombre más fuerte o más rápido. Pero tarde o temprano el hombre que gana, es el hombre que cree que puede. | Vince Lombardi
No seas un espectador, no dejes que la vida pase de largo. | Lou Holtz
La vida es un territorio desconocido. Revela su historia un momento a la vez. | Leo Buscaglia
Tener integridad es también tener carácter, que es también la forma más fácil de entrar en conflicto con quienes no tienen ninguna de las dos cosas.  | Byron Pulsifer
Ten el valor de decir no. Ten el valor de enfrentarte a la verdad. Haz lo correcto porque es lo correcto. Estas son las claves mágicas para vivir tu vida con integridad. | Mark Twain
La integridad puede ser difícil de mantener en un mundo que exige que cambies con el viento. | Byron Pulsifer
La integridad es lo que hacemos, lo que decimos y lo que decimos que hacemos. | Don Galer
Ama a todos, confía en unos pocos, no hagas mal a ninguno. | William Shakespeare
Tener integridad significa que no estás de acuerdo con todos los que conoces, ni sucumbes a la presión para ser algo que está en conflicto directo con tu ética principal. | Byron Pulsifer
El carácter está por encima del intelecto. | Ralph Waldo Emerson
Mi abuelo me dijo una vez que hay dos tipos de personas: las que trabajan y las que se llevan el mérito. Me dijo que intentara estar en el primer grupo; allí había menos competencia. | Indira Gandhi
¿Pero qué es la felicidad sino la simple armonía entre un hombre y la vida que lleva? | Albert Camus
Sólo hay un rincón del universo que puedes estar seguro de mejorar, y es tu propio yo. | Aldous Huxley
No debemos permitirnos ser como el sistema al que nos oponemos. | Obispo Desmond Tutu
La integridad sin conocimiento es débil e inútil, y el conocimiento sin integridad es peligroso y terrible. | Samuel Johnson
Tenemos que insistir en que la integridad personal es tan importante como la habilidad ejecutiva en los negocios.. | Russell E. Palmer
No importa la hora del día, no importa quién esté mirando y no importa la situación, la integridad personal no se toma vacaciones. | Byron Pulsifer
La sabiduría es saber qué hacer a continuación; la virtud es hacerlo. | David Star Jordan
El carácter es hacer lo correcto cuando nadie está mirando. Hay demasiada gente que piensa que lo único que está bien es salir adelante, y lo único que está mal es que te pillen. | J.C. Watts
No se puede hacer siempre lo correcto, pero siempre se puede hacer lo que se hace con integridad. | Byron Pulsifer
Nunca dejes que tu sentido de la moral te impida hacer lo correcto. | Isaac Asimov
La integridad es ajustar la realidad a nuestras palabras, es decir, mantener las promesas y cumplir las expectativas. | Stephen R. Covey
El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito. | Albert Schweitzer
Nunca serás feliz si sigues buscando en qué consiste la felicidad. Nunca vivirás si buscas el sentido de la vida. | Albert Camus
La Constitución sólo garantiza al pueblo estadounidense el derecho a buscar la felicidad. Tienes que alcanzarla tú mismo. | Benjamin Franklin
Ninguna sociedad puede ser seguramente floreciente y feliz, de la cual la mayor parte de sus miembros son pobres y miserables. | Adam Smith
La felicidad es un estado de ánimo, no lo que hay en la cartera. | Byron Pulsifer
Si quieres ser feliz, sé. | León Tolstoi
Agradezcamos a las personas que nos hacen felices; son los encantadores jardineros que hacen florecer nuestras almas. | Marcel Proust
El hombre que hace que todo lo que conduce a la felicidad dependa de sí mismo, y no de otros hombres, ha adoptado el mejor plan para vivir felizmente. | Platón
¡Cree en ti mismo! ¡Ten fe en tus capacidades! Sin una humilde pero razonable confianza en tus propios poderes no puedes tener éxito ni ser feliz. | Norman Vincent Peale
Estar sin algunas de las cosas que quieres es una parte indispensable de la felicidad. | Bertrand Russell
¿Pero qué es la felicidad sino la simple armonía entre un hombre y la vida que lleva? | Albert Camus
La acción puede no traer siempre la felicidad; pero no hay felicidad sin acción. | Benjamin Disraeli
La mayoría de la gente prefiere estar segura de ser miserable, que arriesgarse a ser feliz. | Robert Anthony
Si dejáramos de intentar ser felices, podríamos pasarlo bastante bien. | Edith Wharton
¿Qué se puede añadir a la felicidad de un hombre que tiene salud, no tiene deudas y tiene la conciencia tranquila? | Adam Smith
La experiencia no es lo que le sucede a un hombre. Es lo que un hombre hace con lo que le sucede. | Aldous Leonard Huxley
El buen juicio viene de la experiencia, y a menudo la experiencia viene del mal juicio. | Rita Mae Brown
Una mente que es estirada por una nueva experiencia nunca puede volver a sus antiguas dimensiones. | Oliver Wendell Holmes, Jr.
A veces tienes que hacer muchas cosas para determinar qué es lo que no quieres hacer. En el camino se adquiere mucha experiencia. | Wally Amos
Un hombre no puede jubilar su experiencia. Debe utilizarla. La experiencia consigue más con menos energía y tiempo. | Bernard M. Baruch
La respuesta a 'The Greatest Generation' y los libros que le siguieron ha sido una de las experiencias más satisfactorias de mi vida. | Tom Brokaw
La fama pasará y, hasta luego, te he tenido, fama. Si pasa, siempre he sabido que es voluble. Así que al menos es algo que experimento, pero no es donde vivo. | Marilyn Monroe
La experiencia es hija del pensamiento, y el pensamiento es hijo de la acción. | Benjamin Disraeli
Prefiero tener mucho talento y poca experiencia que mucha experiencia y poco talento. | John Wooden
Nunca te conviertas en un experto hasta el punto de dejar de ganar experiencia. Considera la vida como una experiencia de aprendizaje continuo. | Denis Waitley
Lo más hermoso que podemos experimentar es lo misterioso. Es la fuente de todo arte y ciencia verdaderos. | Albert Einstein
La experiencia no es lo que te ocurre. Es lo que haces con lo que te ocurre. | Aldous Huxley
Con cada experiencia, sólo tú estás pintando tu propio lienzo, pensamiento a pensamiento, elección a elección. | Oprah Winfrey
Como mujer siempre he sentido que a medida que envejecemos mejoramos. Te reconcilias contigo misma, a través de las experiencias emocionales y la simple sabiduría que viene con la edad. | Linda Evans
No debemos mirar hacia atrás a menos que sea para extraer lecciones útiles de los errores del pasado, y con el propósito de sacar provecho de la experiencia adquirida. | George Washington
Lo más doloroso de experimentar no es la derrota sino el arrepentimiento. | Leo Buscaglia
Ningún hombre fue jamás tan hábil en la conducción de la vida, como para no recibir nueva información de la edad y la experiencia. | Jonathan Swift
El arte no es una artesanía, es la transmisión del sentimiento que el artista ha experimentado. | León Tolstoi
Creo que todo el mundo debería experimentar la derrota al menos una vez durante su carrera. Se aprende mucho de ella. | Lou Holtz
El secreto de una vida rica es tener más principios que finales. | Dave Weinbaum
Todas las cosas difíciles tienen su origen en lo que es fácil, y las grandes cosas en lo que es pequeño. | Lao-Tzu
Casi todo viene de la nada. | Henry F. Amiel
La necesidad, que es la madre de la invención. | Platón
La distancia no es nada; lo difícil es sólo el primer paso. | Marquise du Deffand
Los comienzos sólo son difíciles sin ninguna acción. | Byron Pulsifer
Las pequeñas oportunidades suelen ser el comienzo de las grandes empresas. | Demóstenes
Un comienzo difícil hace un buen final. | John Heywood
No hay que ser grande para empezar, pero hay que empezar para ser grande. | Joe Sabah
Mucha gente que busca nuevos comienzos nunca ha terminado con el pasado. | Byron Pulsifer
Cada día es un nuevo comienzo. Trátalo así. Aléjate de lo que podría haber sido y mira lo que puede ser. | Marsha Petrie Sue
Esto no es el final. Ni siquiera es el principio del fin. Pero es, quizás, el final del principio. | Winston Churchill
Hagas lo que hagas, o sueñes que puedas, empieza. La audacia tiene genio, poder y magia. | Goethe
Aprovechar varias oportunidades pequeñas puede llevarnos más rápido que esperar a que aparezca una grande. | Hugh Allen
A menudo es difícil distinguir entre los golpes duros de la vida y los de la oportunidad. | Frederick Phillips
La habilidad tiene poca importancia sin la oportunidad. | Napoleón
El secreto del éxito en la vida es que un hombre esté preparado para su oportunidad cuando ésta llegue. | Benjamin Disraeli
Las oportunidades nunca se pierden; alguien tomará la que tú pierdes. |
Cada día es una oportunidad para hacer un nuevo final feliz. |
Todo lo que es valioso en la sociedad humana depende de la oportunidad de desarrollo que se le conceda al individuo. | Albert Einstein
Un pesimista ve la dificultad en cada oportunidad; un optimista ve la oportunidad en cada dificultad. | Winston Churchill
La vida es un regalo, y nos ofrece el privilegio, la oportunidad y la responsabilidad de dar algo a cambio convirtiéndonos en algo más. | Tony Robbins
La escalera del éxito se sube mejor pisando los peldaños de la oportunidad. | Ayn Rand
La habilidad no es nada sin la oportunidad. | Napoleón Bonaparte
Tu gran oportunidad puede estar justo donde estás ahora. | Napoleón Hill
Las oportunidades llegan a mi vida y respondo a las que me atraen. | Wally Amos
Los hombres nunca se quejan de las oportunidades perdidas para hacer el bien, sólo de las oportunidades para ser malos. | Proverbio griego
Edison fracasó 10.000 veces antes de crear la luz eléctrica. No te desanimes si fracasas algunas veces. | Napoleón Hill
¿Hasta cuándo hay que intentarlo? Hasta. | Jim Rohn
La paciencia y la perseverancia tienen un efecto mágico ante el cual las dificultades desaparecen y los obstáculos se desvanecen. | John Quincy Adams
A través de la perseverancia muchas personas obtienen el éxito de lo que parecía destinado a ser un fracaso seguro. | Benjamin Disraeli
Intenta y fracasa, pero no dejes de intentarlo. | Stephen Kaggwa
Si deseas tener éxito en la vida, haz de la perseverancia tu amigo íntimo, de la experiencia tu sabio consejero, de la precaución tu hermano mayor y de la esperanza tu genio guardián. | Joseph Addison
Las grandes obras se realizan, no por la fuerza, sino por la perseverancia. | Samuel Johnson
No creo que haya ninguna otra cualidad tan esencial para el éxito de cualquier tipo como la cualidad de la perseverancia. Supera casi todo, incluso la naturaleza. | John D. Rockefeller
No hay fracaso sino en dejar de intentarlo. | Elbert Hubbard
Sólo la perseverancia y la determinación son omnipotentes. La consigna de seguir adelante ha resuelto y siempre resolverá los problemas de la raza humana. | Calvin Coolidge
La victoria pertenece al más perseverante. | Napoleón Bonaparte
Sigue tus sueños de un mundo mejor, y sigue intentándolo, incluso cuando parezca que hay pocas esperanzas, porque es lo que hay que hacer. | Robert Alan
El genio es la perseverancia divina. Genio no puedo reclamar, ni siquiera brillo extra, pero perseverancia todos pueden tener. | Woodrow Wilson
En el enfrentamiento entre el arroyo y la roca, el arroyo siempre gana, no por la fuerza sino por la perseverancia. | H. Jackson Brown
La perseverancia es más imperante que la violencia y muchas cosas que no pueden ser vencidas cuando están juntas se rinden cuando se las toma poco a poco. | Plutarco
La perseverancia no es una carrera larga; son muchas carreras cortas una tras otra. | Walter Elliot
Los mejores entre nosotros no están más dotados que el resto. Sólo dan pequeños pasos cada día mientras marchan hacia su mayor vida. | Robin Sharma,La guía de la grandeza
Asóciate con hombres de buena calidad si estimas tu propia reputación. Es mejor estar solo que mal acompañado. | George Washington
La calidad no es un acto, es un hábito. | Aristóteles
Si el nivel de vida es tu objetivo principal, la calidad de vida casi nunca mejora, pero si la calidad de vida es tu objetivo número uno, tu nivel de vida casi siempre mejora. | Zig Ziglar
La calidad es un atributo del que suelen abusar los que buscan engañar. | Byron Pulsifer
La calidad significa hacerlo bien cuando nadie está mirando. | Henry Ford
Si no estás seguro de la calidad de tu trabajo, primero tienes que entender qué es la calidad. | Byron Pulsifer
La calidad nunca es un accidente; siempre es el resultado de un esfuerzo inteligente. | John Ruskin
Es la calidad de nuestro trabajo lo que complacerá a Dios, no la cantidad. | Mahatma Gandhi
La calidad de la vida de una persona está en proporción directa a su compromiso con la excelencia, independientemente del campo de trabajo que elija. | Vince Lombardi
Lo importante es la calidad, no la longevidad, de la vida. | Martin Luther King
Nadie puede lograr un éxito real y duradero o "hacerse rico" en los negocios siendo un conformista. | J. P. Getty
Subir colinas empinadas requiere un ritmo lento al principio. | William Shakespeare
El éxito no tiene ningún secreto. ¿Has conocido alguna vez a un hombre de éxito que no te lo haya contado? | Kin Hubbard
El secreto del éxito del hombre reside en su percepción de los estados de ánimo de la gente, y en su tacto para tratar con ellos. | Josiah Gilbert Holland
No hay pasión en jugar a lo pequeño, en conformarse con una vida inferior a la que uno es capaz de vivir. | Nelson Mandela
Los objetivos han marcado una enorme diferencia en mi vida. Me han permitido alcanzar el éxito y lograr lo que antes sólo había soñado o deseado. | Catherine Pulsifer
Nunca confundas el movimiento con la acción. | Ernest Hemmingway
El éxito es conseguir lo que quieres. La felicidad es querer lo que consigues. | Dale Carnegie
En todo lo que hacemos, nuestros propios pensamientos pueden ayudarnos a tener éxito, o pueden ayudarnos a fracasar. Mantén una actitud positiva. | Catherine Pulsifer
La mayoría de las personas de éxito que he conocido son las que hacen más por escuchar que por hablar. | Bernard M. Baruch
Tener éxito en el trabajo que se realiza es el mejor paso hacia el tipo que se desea. | Bernard M. Baruch
No se puede medir a un hombre por sus fracasos. Hay que saber qué uso hace de ellos. Qué significaron para él. Qué ha sacado de ellos. | Orison Swett Marden
Si uno avanza con confianza en la dirección de su sueño, y se esfuerza por vivir la vida que había imaginado, se encontrará con un éxito inesperado en las horas comunes. | Henry David Thoreau
El tiempo es lo más valioso que un hombre puede gastar. | Teofrasto
Te habrán advertido que no dejes pasar las horas doradas; pero algunas de ellas son doradas sólo porque las dejamos pasar. | James Matthew Barrie
Si quieres un trabajo bien hecho, elige un hombre ocupado, el otro tipo no tiene tiempo. | Elbert Hubbard
El tiempo es el consejero más sabio de todos. | Pericles
Todo lo que realmente nos pertenece es el tiempo; incluso el que no tiene nada más lo tiene. | Baltasar Gracián
El tiempo es la distancia más larga entre dos lugares. | Tennessee Williams
Nada es una pérdida de tiempo si usas la experiencia sabiamente. | Rodin
Debemos utilizar el tiempo como una herramienta, no como una muleta. | John F. Kennedy
El tiempo y las palabras no se pueden recordar, aunque sea ayer. | Proverbio Yiddish
El arrepentimiento por las cosas que hicimos puede ser atenuado por el tiempo; es el arrepentimiento por las cosas que no hicimos lo que es inconsolable. | Sydney J. Harris
Pero ¡qué minutos! Cuéntalos por sensaciones, y no por calendarios, y cada momento es un día. | Benjamin Disraeli
El tiempo es la moneda de tu vida. Es la única moneda que tienes, y sólo tú puedes determinar cómo se va a gastar. Ten cuidado de no dejar que otros lo gasten por ti. | Carl Sandburg
Nunca encontrarás tiempo para nada. Si quieres tiempo, debes crearlo. | Charles Buxton
Más vale tres horas de más que un minuto de más. | William Shakespeare
El tiempo perdido nunca se vuelve a encontrar. | Benjamin Franklin
Las horas de la locura son medidas por el reloj; pero las de la sabiduría, ningún reloj puede medirlas. | William Blake
Nunca te cansas a menos que te detengas y te tomes tiempo para ello. | Bob Hope
El tiempo es el consejero más sabio. | Pericles
Perdí el tiempo, y ahora el tiempo me pierde a mí. | William Shakespeare
Tu mayor activo es tu capacidad para ganar dinero. Tu mayor recurso es tu tiempo. | Brian Tracy
Debemos usar el tiempo sabiamente y siempre darnos cuenta de que el tiempo siempre está maduro para hacer lo correcto. | Nelson Mandela
La vida no se mide por el número de respiraciones que hacemos, sino por los momentos que nos dejan sin aliento. |
La mejor manera de hacer que tus sueños se hagan realidad es despertando. | Paul Valery
Una de las cosas que aprendí por las malas fue que no vale la pena desanimarse. | Lucille Ball
Lo importante es esto: ser capaces en cualquier momento de sacrificar lo que somos; por lo que podríamos llegar a ser. | Charles Dubois
Todos los consejos del mundo no te ayudarán hasta que te ayudes a ti mismo. | Fred Van Amburgh
Amar en abundancia es vivir en abundancia, y amar para siempre es vivir para siempre. | Henry Drummond
La forma de pensar sobre un problema es más importante que el propio problema. Así que piensa siempre en positivo. | Norman Vincent Peale
Olvida los errores del pasado. Olvida los fracasos. Olvida todo excepto lo que vas a hacer ahora y hazlo. | William Durant
Se puede saber más de una persona por lo que dice de los demás que por lo que los demás dicen de ella. | Leo Aikman
Sueña con grandes sueños, luego ponte el mono de trabajo y sal a hacer los sueños realidad. | Fred Van Amburgh
El misterio de la vida no es un problema que hay que resolver; es una realidad que hay que experimentar. | Aart van der Leenw
Sólo hay un rincón del universo que puedes estar seguro de mejorar, y es tu propio yo. | Aldous Huxley
La buena vida es un proceso, no un estado del ser. Es una dirección, no un destino. | Carl Rogers
Somos lo que hacemos repetidamente. La excelencia, pues, no es un acto, sino un hábito. | Aristóteles
Lee no para contradecir y confutar, no para creer y dar por sentado, no para encontrar charla y discurso, sino para sopesar y considerar. | Francis Bacon
Una de las mejores maneras de persuadir a los demás es con los oídos, escuchándolos. | Dean Rusk
Si tienes sólo uno o dos amigos con los que puedes compartir tus más altas aspiraciones, deberías considerarte ricamente bendecido. | J. Donald Waters
En lugar de desear el cambio, primero hay que estar preparado para cambiar. | Catherine Pulsifer
Todo el mundo piensa en cambiar el mundo, pero nadie piensa en cambiarse a sí mismo. | León Tolstoi
El cambio es tan inexorable como el tiempo, pero nada encuentra más resistencia. | Benjamin Disraeli
Sólo los hombres más sabios y estúpidos no cambian nunca. | Confucio
Nunca dejes de aprender, como nunca dejes de cambiar y crecer en tu vida - el aprendizaje te ayuda a adaptarte al cambio más fácilmente. | Citas de aprendizaje
Lo que pensamos determina lo que nos sucede, así que si queremos cambiar nuestras vidas, necesitamos estirar nuestras mentes. | Wayne Dyer
No puedes cambiar tu destino de la noche a la mañana, pero puedes cambiar tu dirección de la noche a la mañana. | Jim Rohn
A menudo nos decepcionamos debido a nuestras expectativas. Sólo cuando aprendes a ver las circunstancias tal y como son realmente, puedes convertirte en el artífice de la mejora. | Greg Henry Quinn
El único hombre que conozco que se comporta con sensatez es mi sastre; me toma las medidas de nuevo cada vez que me ve. El resto sigue con sus viejas medidas y espera que yo me adapte a ellas. | George Bernard Shaw
Sin acción, no hay cambio. Acción limitada, cambio limitado. Mucha acción, el cambio se produce. | Catherine Pulsifer
Siempre eres libre de cambiar de opinión y elegir un futuro diferente, o un pasado diferente. | Richard Bach
No dejes que otros cambien tu vida, sé tu propio agente de cambio y pon en práctica los cambios que deseas. Y si se produce un cambio inesperado en tu vida, encuentra lo positivo en él. | Catherine Pulsifer
El cambio es inevitable. El cambio es constante. | Benjamin Disraeli
Si te sientes decaído, no desesperes. El sol se hunde cada noche, pero vuelve a salir cada mañana. A mi modo de ver, si quieres el arco iris, tienes que aguantar la lluvia. | Dolly Parton
Ponerse a prueba es bueno. La vida desafiada puede ser el mejor terapeuta. | Gail Sheehy
No son las montañas que hay que escalar las que te agotan; es la piedra en el zapato. | Mahummad Ali
Fluye con lo que está sucediendo y deja que tu mente sea libre. Mantente centrado aceptando lo que sea que estés haciendo. Esto es lo máximo. | Chuang Tzu
Puede que no seas responsable de que te derriben, pero sin duda eres responsable de que te levantes. | Wally Amos
Me esfuerzo por ser sabio cuando no puedo ser alegre, fácil cuando no puedo ser feliz, contento con lo que no se puede arreglar y paciente cuando no hay reparación. | Elizabeth Montagu
Lo malo no es lo peor que nos puede pasar. Lo peor que nos puede pasar es "nada". | Richard Bach
La parte nunca puede estar bien si el todo no está bien. | Platón
Las montañas no pueden ser superadas si no es por caminos sinuosos. | Johann Wolfgang Von Goethe
Nunca subestimes tu problema ni tu capacidad para afrontarlo. | Robert H. Schuller
Cada mañana tiene dos asas. Podemos agarrarlo con el mango de la ansiedad o con el mango de la fe. | Henry Ward Beecher
Las imposibilidades son simplemente cosas que aún no hemos aprendido. | Charles W. Chesnutt
Cuando el destino nos da un limón, tratemos de hacer limonada. | Dale Carnegie
Puede que no te des cuenta cuando sucede, pero una patada en los dientes puede ser lo mejor del mundo para ti. | Walt Disney
La grandeza no reside en ser fuerte, sino en el uso correcto de la fuerza. | Henry Ward Beecher
No tengas miedo de la grandeza: algunos nacen grandes, algunos logran la grandeza, y algunos tienen la grandeza impuesta. | William Shakespeare
Los grandes logros suelen nacer de un gran sacrificio, y nunca son el resultado del egoísmo. | Napoleon Hill
Para llegar a ser verdaderamente grande, uno tiene que estar con la gente, no por encima de ella. | Marleen Charles de Montesquieu
Una gran fotografía es aquella que expresa plenamente lo que uno siente, en el sentido más profundo, sobre lo que se está fotografiando. | Ansel Adams
Las alturas alcanzadas y conservadas por los grandes hombres no se obtuvieron por medio de una huida repentina, sino que, mientras sus compañeros dormían, ellos se esforzaban por subir en la noche. | Henry Wadsworth Longfellow
Es bajo la mayor adversidad donde existe el mayor potencial para hacer el bien, tanto para uno mismo como para los demás. | Dalai Lama
Uno de los mayores descubrimientos que hace un hombre, una de sus grandes sorpresas, es descubrir que puede hacer lo que temía no poder hacer. | Henry Ford
La responsabilidad es el precio de la grandeza. | Winston Churchill
La mayoría de las grandes personas han alcanzado su mayor éxito justo un paso más allá de su mayor fracaso. | Napoleón Hill
Ningún gran hombre se queja de la falta de oportunidades. | Ralph Waldo Emerson
Cultiva tu mente con grandes pensamientos; creer en lo heroico hace héroes. | Benjamin Disraeli
Un gran esfuerzo surge naturalmente de una gran actitud. | Pat Riley
Arriesga más de lo que otros creen que es seguro. Preocúpate más de lo que otros piensan que es sabio. Sueña más de lo que otros creen que es práctico. Espera más de lo que otros creen que es posible. | Máxima del cadete
Haz cada día una cosa que te asuste. | Eleanor Roosevelt
Confía en tu propio instinto. Tus errores podrían ser tuyos, en lugar de los de otros. | Billy Wilder
Vivir en riesgo es saltar del acantilado y construir tus alas en el camino hacia abajo. | Ray Bradbury
Uno no descubre nuevas tierras sin consentir en perder de vista la orilla durante mucho tiempo. | André Gide
Cuidado con perder las oportunidades; de lo contrario, algún día puede ser demasiado tarde. | Franz Liszt
Los que confían en el azar deben atenerse a los resultados del azar. | Calvin Coolidge
Nunca te tropezarás con un dedo del pie si te quedas quieto. Cuanto más rápido vayas, más posibilidades hay de que te tropieces, pero más posibilidades tienes de llegar a alguna parte. | Charles F. Kettering
El mejor premio que ofrece la vida es la oportunidad de trabajar duro en un trabajo que vale la pena. | Theodore Roosevelt
En mi época, no teníamos autoestima, sino respeto por nosotros mismos, y no más del que nos habíamos ganado. | Jane Haddam
El que se respeta a sí mismo está a salvo de los demás; lleva una cota de malla que nadie puede atravesar. | Henry Wadsworth Longfellow
La gente que más respeto tiene se comporta como si fuera inmortal y como si la sociedad fuera eterna. | E. M. Forster
Si no tienes respeto por tus propios valores, ¿cómo puedes ser digno del respeto de los demás? | Byron Pulsifer
Un hombre puede soportar muchas cosas mientras pueda soportarse a sí mismo. | Axel Munthe
El respeto no es algo que se pueda pedir, comprar o pedir prestado. El respeto es lo que te ganas de cada persona, sin importar su origen o estatus. | Byron Pulsifer
Prefiero ser fiel a mí mismo, aun a riesgo de incurrir en el ridículo de los demás, antes que ser falso e incurrir en mi propio aborrecimiento. | Frederick Douglass
Si uno se aleja de sí mismo, también se aleja de los demás. Si uno no está en contacto con uno mismo, entonces no puede tocar a los demás. | Anne Morrow Lindbergh
No pueden quitarnos el respeto por nosotros mismos si no se lo damos. | Mahatma Gandhi
Cada individuo tiene un lugar que ocupar en el mundo y es importante en algún aspecto, lo elija o no. | Nathaniel Hawthorne
La tragedia es que mucha gente busca la confianza en sí misma y el respeto por sí misma en todas partes excepto en su propio interior, y así fracasa en su búsqueda. | Nathaniel Branden
El respeto y la confianza nunca pueden darse por sentados. Son atributos que hay que demostrar. También son directamente recíprocos con el comportamiento de los demás. | Elaine Sihera
Mira todo como si lo vieras por primera o última vez. Entonces tu tiempo en la tierra estará lleno de gloria. | Betty Smith
Los sabios hablan porque tienen algo que decir; los tontos, porque tienen que decir algo. | Platón
Cuando veas a un hombre valioso, piensa en cómo puedes emularlo. Cuando veas a uno indigno, examínate a ti mismo. | Confucio
Hay una llamada dentro de cada uno de nosotros, una llamada a hacer algo, aunque sea impopular o desapercibido, para hacer del mundo un lugar mejor. | Robert K. Cooper
Nada está predestinado: Los obstáculos del pasado pueden convertirse en las puertas que conducen a nuevos comienzos. | Ralph Blum
Ser capaz de regalar riquezas es obligatorio si quieres poseerlas. Sólo así serás verdaderamente rico. | Mahummad Ali
Las personas toman diferentes caminos en busca de la plenitud y la felicidad. Que no estén en tu camino no significa que se hayan perdido. | Dalai Lama
Tengo mucho más respeto por la persona con una sola idea que llega a la meta que por la persona con mil ideas que no hace nada. | Thomas Edison
El trabajo y el juego son palabras que se utilizan para describir la misma cosa en condiciones diferentes. | Mark Twain
Es más rico el hombre cuyos placeres son más baratos. | Henry David Thoreau
No se puede dar la mano con el puño cerrado. | Gandhi
Hay que tener cariño a la gente y confiar en ella si no se quiere hacer un desastre de la vida. | E.M. Forster
No se puede confiar sin riesgo, pero tampoco se puede vivir en un capullo. | Byron Pulsifer
Puedes ser engañado si confías demasiado, pero vivirás atormentado si no confías lo suficiente. | Frank Crane
Todos nacemos valientes, confiados y codiciosos, y la mayoría seguimos siendo codiciosos. | Mignon McLaughlin
¿Qué pasa con la política que parece ignorar la confianza a menos que sea en época de elecciones? | Byron Pulsifer
Debo seguir al pueblo. ¿No soy su líder? | Benjamin Disraeli
El que no puede obedecer, no puede mandar. | Benjamin Franklin
Un buen líder no puede adelantarse demasiado a sus seguidores. | Theodore Roosevelt
El liderazgo es el arte de conseguir que otra persona haga algo que tú quieres que se haga porque él quiere hacerlo. | Dwight Eisenhower
La clave del éxito del liderazgo actual es la influencia, no la autoridad. | Kenneth Blanchard
Hay un enorme número de directivos que se han jubilado en el trabajo. | Peter F. Drucker
Un buen líder asume un poco más que su parte de culpa, un poco menos que su parte de crédito. | Arnold H. Glasgow
La gestión es hacer las cosas bien; el liderazgo es hacer las cosas bien. | Peter F. Drucker
No es justo pedir a los demás lo que no estás dispuesto a hacer tú mismo. | Eleanor Roosevelt
Los líderes no crean seguidores, crean más líderes. | Tom Peters
El mayor bien que puedes hacer a otro es no sólo compartir tus riquezas, sino revelarle las suyas. | Benjamin Disraeli
No se lidera golpeando a la gente en la cabeza - eso es asalto, no liderazgo. | Dwight Eisenhower
Un buen objetivo del liderazgo es ayudar a los que lo hacen mal a hacerlo bien y ayudar a los que lo hacen bien a hacerlo aún mejor. | Jim Rohn
Los líderes destacados se esfuerzan por aumentar la autoestima de su personal. Si la gente cree en sí misma, es increíble lo que puede lograr. | Sam Walton
Demasiados líderes actúan como si las ovejas... su gente... estuvieran ahí para el beneficio del pastor, y no como si el pastor fuera responsable de las ovejas. | Kenneth Blanchard
El profesor mediocre cuenta. El buen profesor explica. El profesor superior demuestra. El gran maestro inspira. | William Arthur Ward
En el pasado, un líder era un jefe. Los líderes de hoy deben ser socios de su gente... ya no pueden liderar únicamente en base al poder posicional. | Kenneth Blanchard
La bondad es el lenguaje que los sordos pueden oír y los ciegos ver. | Mark Twain
No se puede hacer una bondad demasiado pronto, porque nunca se sabe cuándo será demasiado tarde. | Ralph Waldo Emerson
Mi religión es muy simple. Mi religión es la bondad. | Dalai Lama
Si hay alguna bondad que pueda mostrar, o cualquier cosa buena que pueda hacer a cualquier semejante, déjame hacerlo ahora, y no lo disuada o descuide, ya que no volveré a pasar por este camino. | William Penn
No has vivido un día perfecto, a menos que hayas hecho algo por alguien que nunca podrá pagarte. | Ruth Smeltzer
¿Qué sabiduría puedes encontrar que sea más grande que la bondad? | Jean Jacques Rousseau
Así brilla una buena acción en un mundo cansado. | William Shakespeare
Nuestros actos nos determinan, tanto como nosotros determinamos nuestros actos. | George Eliot
Sé amable, porque todos los que conoces están librando una dura batalla. | Platón
El que espera hacer mucho bien de una vez, nunca hará nada. | Samuel Johnson
La bondad es el sol en el que crece la virtud. | Robert Green Ingersoll
Busca siempre la completa armonía de pensamiento, palabra y acción. Siempre apunta a purificar tus pensamientos y todo estará bien. | Mohandas Gandhi
Aquel que te ha hecho un favor estará más dispuesto a hacerte otro, que aquel a quien tú mismo has obligado. | Benjamin Franklin
La bondad no tiene incidencias. No brilla, sino que resplandece. | David Grayson
Recordemos que, como se nos ha dado mucho, se espera mucho de nosotros, y que el verdadero homenaje viene del corazón así como de los labios, y se muestra en hechos. | Theodore Roosevelt
Una bondad ofrecida espontáneamente a quien la necesita, es doblemente gratificante. | Jonathan Swift
Cuando das de ti mismo es cuando realmente das. | Kahil Gibran
Haz algo más que pertenecer: participa. Haz algo más que preocuparte: ayuda. Haz más que creer: practica. Más que ser justo: sé amable. Más que perdonar: olvidar. Más que soñar: trabajar. | William Arthur Ward
La bondad es la cadena de oro que une a la sociedad. | Johann Wolfgang Von Goethe
La más pequeña buena acción es mejor que la más grande buena intención. | Proverbio japonés
No hay mejor ejercicio para el corazón que agacharse y ayudar a levantar a alguien. | Bernard Meltzer
La bondad puede convertirse en su propio motivo. Nos hacemos amables siendo amables. | Eric Hoffer
La bondad engendra bondad. | Proverbio griego
Un corazón bondadoso es una fuente de alegría, que hace que todo lo que está cerca se convierta en sonrisas. | Washington Irving
Sé amable con los que te encuentras al levantarte, puede que te los vuelvas a encontrar al caer. | Proverbio irlandés
La posesión completa sólo se demuestra dando. Todo lo que eres incapaz de dar te posee. | André Gide
Una palabra amable puede calentar tres meses de invierno. | Proverbio japonés
Cada vez que vayas a hacer una cosa, aunque no pueda ser conocida más que por ti mismo, pregúntate cómo actuarías si todo el mundo te mirara y actúa en consecuencia. | Thomas Jefferson
La pregunta más persistente y urgente de la vida es: ¿Qué estás haciendo por los demás? | Martin Luther King, Jr.
Dondequiera que haya un ser humano hay una oportunidad para la bondad. | Séneca
Las palabras amables pueden ser cortas y fáciles de pronunciar, pero sus ecos son realmente interminables. | Madre Teresa
Ser capaz, en cualquier circunstancia, de practicar cinco cosas constituye la virtud perfecta; estas cinco cosas son la gravedad, la generosidad de alma, la sinceridad, la seriedad y la bondad. | Confucio
Hagamos una nueva regla de vida a partir de esta noche: tratemos de ser siempre un poco más amables de lo necesario. | Sir James M. Barrie
Las buenas acciones nos ennoblecen, somos hijos de nuestros propios actos. | Jean Paul Richter
Si no tienes caridad en tu corazón, tienes la peor clase de problemas de corazón. | Bob Hope
Las palabras amables abren una puerta de hierro. | Proverbio turco
Cultivar la bondad es una parte valiosa del negocio de la vida. | Samuel Johnson
Podemos estar resentidos por nuestra edad, o podemos estar agradecidos por haberla alcanzado. | William Arthur Ward
Si no se conforman con nada menos que lo mejor de sí mismos, se sorprenderán de lo que pueden lograr en sus vidas. | Vince Lombardi
Las grandes mentes tienen propósitos; las mentes pequeñas tienen deseos. Las mentes pequeñas son sometidas por las desgracias; las mentes grandes se elevan por encima de ellas. | Washington Irving
Ningún hombre puede evitar nacer promedio, pero no tiene que ser común. | Satchel Paige
Cree en lo más profundo de tu corazón que estás destinado a hacer grandes cosas. | Joe Paterno
No debemos mirar hacia atrás a menos que sea para obtener lecciones útiles de los errores del pasado, y con el propósito de sacar provecho de la experiencia adquirida. | George Washington
La Tierra está repleta de Cielo. | Elizabeth Barrett Browning
Recuerda que la inspiración sigue a la acción y no al revés. | Aronson, Eric, Dash.
Recuerda que no conseguir lo que quieres es a veces un maravilloso golpe de suerte. | Dalai Lama
Todas las cosas llegan a aquel que no hace más que esperar. | Henry Wadsworth Longfellow
En la vida, mucha gente sabe lo que tiene que hacer, pero poca gente hace realmente lo que sabe. Saber no es suficiente. Hay que pasar a la acción. | Anthony Robbins
Siempre me gusta mirar el lado optimista de la vida, pero soy lo suficientemente realista como para saber que la vida es un asunto complejo. | Walt Disney
Todos nos encontramos en situaciones que a veces parecen desesperadas. Y todos tenemos la opción de no hacer nada o pasar a la acción. | Catherine Pulsifer
La honestidad es la riqueza más rara que se puede poseer, y sin embargo, toda la honestidad del mundo no es moneda de cambio por una barra de pan. | Josh Billings
¡Oh, qué red tan enmarañada tejemos, cuando primero practicamos el engaño! | Sir Walter Scott
Casi toda la verdad honesta que hay en el mundo la dicen los niños. | Oliver Wendell Holmes, Jr.
Es difícil creer que un hombre dice la verdad cuando sabes que tú mentirías si estuvieras en su lugar. | Henry Louis Mencken
Nuestras vidas sólo mejoran cuando nos arriesgamos, y el primer y más difícil riesgo que podemos tomar es ser honestos con nosotros mismos. | Walter Anderson
Levantemos una norma a la que los sabios y honestos puedan atenerse; el resto está en manos de Dios. | George Washington
Ningún legado es tan rico como la honestidad. | William Shakespeare
La mejor medida de la honestidad de un hombre no es su declaración de la renta. Es el ajuste del cero en su balanza de baño. | Arthur C. Clarke
Uno de los valores más básicos es la honestidad. | Catherine Pulsifer
Las piedras fundamentales para un éxito equilibrado son la honestidad, el carácter, la integridad, la fe, el amor y la lealtad. | Zig Ziglar
La deshonestidad despreciará a la honestidad cualquier día de la semana, si hay algo que conseguir con ella. | Charles Dickens
La honestidad es el primer capítulo del libro de la sabiduría. | Thomas Jefferson
La integridad es decirme a mí mismo la verdad. Y la honestidad es decir la verdad a los demás. | Spencer Johnson
Prepárate y sé honesto. | John Wooden
No hay una zona de penumbra de honestidad en los negocios. Una cosa está bien o está mal. Es negro o es blanco. | John F. Dodge
Ningún hombre tiene suficiente memoria para ser un mentiroso exitoso. | Abraham Lincoln
Sea honesto con su hijo. Nadie detecta una farsa más rápido que un niño. | Mary MacCracken
Sé tonto. Sé honesto. Sé amable. | Ralph Waldo Emerson
Como he dicho, lo primero es ser honesto con uno mismo. | Nelson Mandela
La honestidad es temer una respuesta negativa y decir la verdad de todos modos. | Michelle C. Ustaszeski
La concentración es mi lema: primero la honestidad, luego la industria y después la concentración. | Andrew Carnegie
El desacuerdo honesto es a menudo una buena señal de progreso. | Gandhi
La duda, consentida y acariciada, corre el peligro de convertirse en negación; pero si es honesta, y se empeña en una investigación minuciosa, pronto puede conducir al pleno establecimiento de la verdad. | Ambrose Bierce
